### PR TITLE
feat(games): banana fuel

### PR DESCRIPTION
**Pull request by NeonGamerBot-QK**
# Your checklist for this pull request

## Author name

**Author:** Neon

## About your game

**What is your game about?**
 You eat bananas which change your sprite and with a couple levels.

**How do you play your game?**

use just wasd for now.
## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file.

### CODE REVIEW

**Review by Cosmin-Mare — CHANGES_REQUESTED** [review]
Hey there! I love the concept for your game, but unfortunately it is too simple and doesn't meet the 1 minute playtime requirement. I would love to see more levels and mechanics added to the game and then we'll re-review it! Thank you for your submission!

**Comment by NeonGamerBot-QK** [comment]
> Hey there! I love the concept for your game, but unfortunately it is too simple and doesn't meet the 1 minute playtime requirement. I would love to see more levels and mechanics added to the game and then we'll re-review it! Thank you for your submission!

@Cosmin-Mare sorry about that, updated the game!

**Review by Cosmin-Mare — CHANGES_REQUESTED** [review]
Hey! I like the things you added, but it's still not 1m of gameplay and it's super easy to beat. pls try to make it more complicated and a bit longer. Thank you for your efforts!

**Review by Cosmin-Mare — APPROVED** [review]
Great! I've played through it and I like it more than the first time. Thank you for your efforts!

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev/) and join our [online Slack community](https://hackclub.com/slack) to chat with other people making Sprig games.

**Pull request merged**
