### PR TITLE
restocking simulater

### PR DESCRIPTION
**Pull request by omegakitty**
# Your checklist for this pull request

## About your game

What is your game about? 
restocking shelves

How to play your game?
wasd for player movement, ijkl for player2 movement, a+l for level reset

sprig sim

### CODE REVIEW

**Comment by LucasHT22** [comment]
which of the two is the final version?

**Comment by omegakitty** [comment]
[3134d1a](https://github.com/hackclub/sprig/pull/579/commits/3134d1a843a5e40b3fed98fc4977b92db7e2aedb)

**Review by omegakitty — COMMENTED** [review]
fixed version

**Comment by LucasHT22** [comment]
how to solve level 4?

**Comment by omegakitty** [comment]
I Need to upload commented version

**Comment by omegakitty** [comment]
> how to solve level 4?

new version uploaded

**Comment by LucasHT22** [comment]
but how do you solve level 4? I'm not getting past this level

**Comment by omegakitty** [comment]
> but how do you solve level 4? I'm not getting past this level

What's your issue, can you not move the second character?

**Comment by LucasHT22** [comment]
I just can't put all the boxes on the goals in this level:
image

**Comment by omegakitty** [comment]
> I just can't put all the boxes on the goals in this level: image

[](https://www.kapwing.com/videos/637e809a1ec3f200243bd10b)

**Comment by omegakitty** [comment]
https://www.kapwing.com/videos/637e809a1ec3f200243bd10b

**Comment by LucasHT22** [comment]
oh, ok, thanks!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
