### PR TITLE
Desine Mini

### PR DESCRIPTION
**Pull request by GuySandler**
**Author:**
Guy Sandler

**What is your game about?**
Defeating and dodging enemies 

**How do you play your game?**
on menu: a to go left, d to go right, j to select.
in game: a and d to move left/right (if you are facing the opposite way you just turn), j to attack, w to jump

## Code
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [there are sprite out of bounds errors at the end and the optional boss fight might have some errors I have not found] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [X] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [X] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
This is great! Where did you hear about Sprig? Also, please delete the duplicated img:)

**Comment by GuySandler** [comment]
how do I add changes

**Comment by GuySandler** [comment]
oh I think I got it

**Comment by GuySandler** [comment]
I heard about the sprig after one of my friends at my school went to the makerfair and got some flyers about the sprig.

**Review by LucasHT22 — APPROVED** [review]
Nice! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
