### PR TITLE
Catch the Apples

### PR DESCRIPTION
**Pull request by Kaj795**
# Your checklist for this pull request

## Author name 

**Author: Jack**

## About your game

**What is your game about?**

Catching the apples falling from the sky while avoiding the bugs in order to increase your score. 

**How do you play your game?**

Press A/D to move left/right

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by Kaj795** [comment]
Hi @LucasHT22, I heard about Sprig the other day from a friend in school and thought I'd give it a go

**Comment by LucasHT22** [comment]
> Hi @LucasHT22, I heard about Sprig the other day from a friend in school and thought I'd give it a go

Nice, where are you from?

**Comment by Kaj795** [comment]
> > Hi @LucasHT22, I heard about Sprig the other day from a friend in school and thought I'd give it a go
> 
> Nice, where are you from?

I'm from the UK

**Review by LucasHT22 — APPROVED** [review]
Right:) Nice game, Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by Kaj795** [comment]
> Right:) Nice game, Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> 
> Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Thanks for your help Lucas!

**Pull request merged**
