### PR TITLE
Rico Rodriguez (Inspired by JC3)

### PR DESCRIPTION
**Pull request by DefinitelyInconspicous**
# Your checklist for this pull request

## Author name

**Author:**

Amspy

## About your game

**What is your game about?**

Dodging bullets from the black hand with hacked controls

**How do you play your game?**

WASD to move, but reversed. J to restart. I to start the game, K to remove obstacle
## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by DefinitelyInconspicous** [comment]
What's the problem?

**Comment by recursiveforte** [comment]
Unfortunately this game doesn't meet the bar for being merged into the gallery- it's not clear enough to me how to play, and it's not complex enough. You could improve it by adding instructions and another game mechanic.

**Comment by DefinitelyInconspicous** [comment]
Hi - I added instructions as well as some more features. Hope it's nice!

**Comment by DefinitelyInconspicous** [comment]
Hello! It's been a while. Are the improvements I made good enough or should I iterate on it further?

**Comment by recursiveforte** [comment]
Thanks for making these changes- this looks good to me! One more thing- right now, the game reset button refreshes the page, which isn't supported by Sprig or the Sprig device. Could you instead have it reset the level inside of Sprig, instead of using location.reload()?

**Comment by DefinitelyInconspicous** [comment]
Alr I also added some soundtrack :)

**Comment by DefinitelyInconspicous** [comment]
Are the changes good enough?

**Comment by grymmy** [comment]
Okay - it took me a few moments to get an idea of actually how to play this game, but once I did I was able to successfully play for > 1 min.  Great job!  If you're a teen, and if you haven't already received one, please fill out [this form](https://sprig-order.hackclub.dev/) to receive a Sprig of your very own!

**Comment by DefinitelyInconspicous** [comment]
Thanks!

**Pull request merged**
