### PR TITLE
Civilization_Builder

### PR DESCRIPTION
**Pull request by RussianDraco**
# Your checklist for this pull request

## Author name

**Author:**

Ivan S

## About your game

Civilization Builder is a game about being the greatest civilization and destroying the neighboring nation by improving your economy and training soldiers.

**How do you play your game?**

WASD to move white selection square.
IJKL is used differently across the game and the game shows what each button will do in each case.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by RussianDraco** [comment]
I had to create 3 commits as I accidently uploaded my game with a space instead of an underscore, so I uploaded that file, deleted it and then re-uploaded with the correct name. Thanks.

**Comment by LucasHT22** [comment]
> I had to create 3 commits as I accidently uploaded my game with a space instead of an underscore, so I uploaded that file, deleted it and then re-uploaded with the correct name. Thanks.

No worries!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game!! Just one thing: when appear "You starved", L not looks work

**Comment by RussianDraco** [comment]
> Great game!! Just one thing: when appear "You starved", L not looks work

After you starved (food < 0) or bankrupted (gold < 0), you lost the game so you're supposed to restart the game as you lost

**Comment by RussianDraco** [comment]
I changed it so that the next turn option does not show up now, thanks!

**Review by LucasHT22 — APPROVED** [review]
Great changes and great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
