### PR TITLE
Let_Them_Eat_Cake

### PR DESCRIPTION
**Pull request by XanderOnGithub**
# Your checklist for this pull request

## About your game

What is your game about? 
> Pushing the cake to the sad person, then going back to the door at the beginning of the level. The game is a puzzle game that feels like a speed-running game, with no timer.

How to play your game?
> Press WASD to move, J to restart. All you need to know is that the cake is pushable, the crate later on is pushable, and you can go as fast or slow as you want.

Code Experience 
>I am a high school student that has learned python within the last few months, I also have learned the basics of HTML and CSS from a class at my school. I've been teaching myself programming principles and Unreal Engine throughout middle school into high school. I have had no experience with JavaScript, but with the documentation and knowledge of programming principles, I understood it enough to make a game.

## Code
Check off the items that are true.
- [✓ ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [✓ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ✓] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [✓ ] The game runs without errors. 
- [✓ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [✓ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [✓ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [✓ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
Great game! what is this 2:26pm?
image

**Comment by XanderOnGithub** [comment]
That is the finishing time of development. It is about 4 minutes from the
end of school and I wanted to show that I worked on it for about 4 hours.

**Comment by LucasHT22** [comment]
oh, ok!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
