### PR TITLE
Rickroll

### PR DESCRIPTION
**Pull request by Tiger-The-Cat**
# Your checklist for this pull request

## Author name

**Author:** Tiger-The-Cat

## About your game

**What is your game about?**
This is an animated rickroll, created for the Sprig

**How do you play your game?**
Simply running the program will start the rickroll.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Tiger-The-Cat** [comment]
I wrote this Python program to convert the rickroll video to a series of Sprig maps (see attached).
[video2sprig.zip](https://github.com/hackclub/sprig/files/11046986/video2sprig.zip)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
WOW so cool! Just a detail: Is the thumbnail from this code?

**Comment by LucasHT22** [comment]
> I can change it to this (see below) if you'd like!

I think it's better:)

**Comment by Tiger-The-Cat** [comment]
Thank you! I fixed it!

**Review by LucasHT22 — COMMENTED** [review]
everything is alright! I'm just seeing if there is a line limit for sprig just in case:)

**Review by LucasHT22 — APPROVED** [review]
everything is ok! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by Tiger-The-Cat** [comment]
Great! Thank you, @LucasHT22!

**Pull request merged**
