### PR TITLE
Custom_Tic_Tac_Toe

### PR DESCRIPTION
**Pull request by CaelGanem**
**Author: Cael Ganem**

**What is your game about?**
Play tic tac toe games on any size map you want! The game uses algorithms to generate tic tac toe maps of any size and with any in-a-row requirement to win (ex 6x6 grid and you need 4 in a row to win). This also features "crazy mode," inspired from [Tic-Tac-No.js](https://github.com/hackclub/sprig/blob/main/games/Tic-Tac-No.js), where x's and o's don't matter and a x-in-a-row of any type means you lose!

**How do you play your game?**

-WASD to move your selector
-K to place a mark (x or o) on the screen
-J to start/stop/restart game
-Onscreen controls when applicable

Change the following variables to change the default values for the board size, in-a-row, and crazy mode.
--gridSize = default size of the board (normally 6)
--inaRow = default for how many marks (x's or 0's) you need in a row (normally 4)
--crazyMode = true/false to enable/disable by default
--skipSelection = skip the opening screen to edit the map size and in-a-row each time it should appear (true=skip every time; false=show every time)

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Where did you hear about Sprig?

**Comment by CaelGanem** [comment]
> Great game! Where did you hear about Sprig?
 I heard about it through my computer programming club at school :)

**Comment by CaelGanem** [comment]
Hi, was just hoping you could follow up on this :)

**Review by LucasHT22 — APPROVED** [review]
Oh sorry! I thought I already answered! Anyway, congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
