### PR TITLE
Add Froggo's Dungeon Adventures

### PR DESCRIPTION
**Pull request by amuseee**
# Your checklist for this pull request

## Author name

**Author: Vikshar Rajesh (vik on slack)**

## About your game

**What is your game about?**
The game follows Froggo, the last in his world, going through various stages of the dungeon and avoiding all his enemies to find a rumored savior at the end of the dungeon, who can turn back time and save him and his friends in exchange for some chocolate.

**How do you play your game?**
Press WASD to move, J to attack or interact with the infoboxes, and K to restart the level. The red boxes are teleport markers (but beware, some of them might be false)

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by amuseee** [comment]
there might be some errors when moving (something relating to `getFirst()`'s behavior), but I have verified that It does not affect play-ability and winability.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Awesome game! Loved the sprites and all mechanics:) Where did you hear about Sprig?

**Comment by amuseee** [comment]
Heard about sprig originally through the OnBoard promo. Wanted to "get all the hackclub" achievements in a sense, so started off with the Sprig

**Review by LucasHT22 — APPROVED** [review]
Nice! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our #ship channel:)

**Comment by grymmy** [comment]
Cool!

**Pull request merged**
