### PR TITLE
submitting my game thumb

### PR DESCRIPTION
**Pull request by ktauchathuranga**
update for my game, i added a thumb for my game

### CODE REVIEW

**Comment by ktauchathuranga** [comment]
why this one have red cross 🤔🤧

image

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! Was it made in Sprig?

**Comment by ktauchathuranga** [comment]
yeah yeah

**Comment by LucasHT22** [comment]
> yeah yeah

Sorry for the delay! Out of curiosity, the text too?

**Comment by ktauchathuranga** [comment]
um sorry i didnt understand what you mean by "next"
everything is according to site recommendations.
game made in sprig web editor and thub file made in ps 🖤

**Comment by LucasHT22** [comment]
> um sorry i didnt understand what you mean by "next" everything is according to site recommendations. game made in sprig web editor and thub file made in ps 🖤

I meant in the sense of how did you created the thumb, so you use ps? Could you use as thumb a real image from your game? You can edit on ps but need to be a real image from the game:)


> when i click on the red cross it says this,
> 
> image


Don't worry :) It's just a weird deploy

**Comment by ktauchathuranga** [comment]
okiiii, so what should i do now? should close this pr and request again or ....

**Comment by ktauchathuranga** [comment]
closing my pr for fixing thumb

**Pull request closed without merging**
