### PR TITLE
The Legend of Zelda: Link's Escape

### PR DESCRIPTION
**Pull request by Itz-Hex**
# Your checklist for this pull request

## Author name

**Author:** ItzHex

## About your game

**What is your game about?**

A simple 2d side scrolling infinite runner game heavily inspired by the Zelda games.

**How do you play your game?**

Press K to start the game, also press K to jump, and press J to restart after dying.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
That's awesome! Out of curiosity, where did you heard about sprig?

**Comment by Itz-Hex** [comment]
I was referenced to the Putting the You in CPU page and went into a rabbithole looking through all the Hack Club stuff untill I eventually stumbled upon sprig and thought I'd give it a go.

**Comment by LucasHT22** [comment]
> Thanks! I was referenced from a YT video to the Putting the You in CPU page and went into a rabbithole looking through all the Hack Club stuff untill I eventually stumbled upon sprig and thought I'd give it a go.

WOW Fireship video?

**Comment by Itz-Hex** [comment]
Yeah, that one.

**Comment by Itz-Hex** [comment]
How long does it normally take for games to appear in the gallery and to be contacted about getting a sprig shipped?

**Review by LucasHT22 — APPROVED** [review]
after approval, it usually takes 1-2 weeks for USA and 1-3 months for other countries, but you will receive an email with a tracking link after filling out the form and being approved:)

If you want to make more changes, please make another PR! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by Itz-Hex** [comment]
> Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Definitely will, just waiting on the invite.

**Pull request merged**
