### PR TITLE
Boxxod.js

### PR DESCRIPTION
**Pull request by Kokonico**
# Your checklist for this pull request

## Author name

**Author: Kokonico**

## About your game

**Boxxod is a box-based gravity game where you push boxes around using the power of gravity (different from gravity-box)**

**To play, you can use WASD to shift all the movable boxes in any direction, you start the game by pressing "I" and reset there current level by pressing "K". you must get the RED cube to the GREEN goal.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

<i>N/A<i>

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay! Nice game:) How to solve this level?

**Comment by Kokonico** [comment]
> Sorry for the delay! Nice game:) How to solve this level?

what level? I have made 100% sure everything is possible. the game IS beatable. (it takes me some spamming and thinking to figure out my own levels too 🥴)

**Comment by LucasHT22** [comment]
> > Sorry for the delay! Nice game:) How to solve this level?
> 
> what level? I have made 100% sure everything is possible. the game IS beatable. (it takes me some spamming and thinking to figure out my own levels too 🥴)

oh sorry haha forget to add image, but here is:
image

**Comment by Kokonico** [comment]
> > > Sorry for the delay! Nice game:) How to solve this level?
> > 
> > 
> > what level? I have made 100% sure everything is possible. the game IS beatable. (it takes me some spamming and thinking to figure out my own levels too 🥴)
> 
> oh sorry haha forget to add image, but here is: image

ah yes, that level.

just keep pressing W-A-S-D a couple times. it's whacky. (when in doubt, spam buttons. it works. mostly)

**Comment by LucasHT22** [comment]
nice technique haha tried to spam on this level but couldn't win:
image

**Comment by Kokonico** [comment]
> nice technique haha tried to spam on this level but couldn't win: image

this one is quite tricky. I'm 
not exactly sure how to beat it. but I recorded myself doing it for 3 minutes, I don't know the exact steps needed to take, but I do end up solving it.

https://github.com/hackclub/sprig/assets/96935064/dcc5c604-6b38-4f53-befd-1e862380a65d

**Review by LucasHT22 — APPROVED** [review]
Right, congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
