### PR TITLE
snakey_snitch

### PR DESCRIPTION
**Pull request by Mrshushiknight**
## Shubh Singh

**Shubh**

aka snitch

this is a simple snake game where you have to eat that red pixel and protect yourself from touching the walls else game will restart
Screenshot (81)

### CODE REVIEW

**Comment by GalaxyGamingBoy** [comment]
Hey! Unfortunately we require that games use the sprig engine and not direct canvas interface. Furthermore to meet the quality criteria to get a grant/publish your game in the gallery it would be great to see more novel game mechanics.

**Review by GalaxyGamingBoy — CHANGES_REQUESTED** [review]
Hey! Cool work but unfortunately we require that games use the sprig engine and not direct canvas interface. Furthermore to meet the quality criteria to get a grant/publish your game in the gallery it would be great to see more novel game mechanics.

**Comment by grymmy** [comment]
Looked at this today, still awaiting changes from the author.

**Comment by grymmy** [comment]
Closing this due to inactivity.  Feel free to re-open this PR if you want to advocate for its merge.

**Pull request closed without merging**
