### PR TITLE
Filler

### PR DESCRIPTION
**Pull request by jwjet**
# Your checklist for this pull request

## About your game

What is your game about? 
> Filling up the entire screen with yellow and reaching the goal.

How to play your game?
Press WASD to move and J to restart. Each tile can only be used once, and the goal must be reached after each tile is filled.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by Omay238** [comment]
It does look good, but I feel like it is pretty similar to other games. Maybe add some sore of feature. I feel like that would make it a lot better. Maybe find a way to make it so you have to go over them twice? The levels are very fun though. I like them a lot!

**Comment by LucasHT22** [comment]
Very good game! I agree with Omay:)

**Comment by jwjet** [comment]
> It does look good, but I feel like it is pretty similar to other games. Maybe add some sore of feature. I feel like that would make it a lot better. Maybe find a way to make it so you have to go over them twice? The levels are very fun though. I like them a lot!

That's a really cool idea! I'll definitely try something like that!

**Comment by SamDev-7** [comment]
@jwjet It's been a while. Let us know if you need help with anything!

**Comment by karamassie** [comment]
hi ! @jwjet don't abandon your game, it has potential! if you need more help, come on over to the hack club slack. we're all in the #sprig channel making games together.

**Comment by leomcelroy** [comment]
It's been a little while so I'm going to close this PR for now. 

Feel free to reopen if you want to continue working on your game!

**Pull request closed without merging**
