### PR TITLE
Catch Doggo

### PR DESCRIPTION
**Pull request by JacksonFlanders**
Catch doggo is a relatively simple puzzle game where you're a police car trying to catch the doggo by pushing a cage into him, trapping doggo in the cage. My experience with coding is very little, I'm a rookie at the moment trying to get better at coding.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR!

**Review by LucasHT22 — COMMENTED** [review]
Very good sprites! I loved the dog

**Review by LucasHT22 — COMMENTED** [review]
just one thing, add an all white sprite and place it where there are no sprites to not have this bug: 
image

**Comment by JacksonFlanders** [comment]
Is that a recurring issue? Or is it just a one time thing? I'll look into
it.

**Comment by LucasHT22** [comment]
yeah, it's recurring issue

**Comment by JacksonFlanders** [comment]
Ok, I got an updated one where I replaced the empty areas with plain white
sprites. One question though, how do I replace my current game in my
request with the new & updated one?

**Comment by LucasHT22** [comment]
ok! see:

image
image
image
and that's it Hope this helps :)

**Comment by karamassie** [comment]
congrats on your first PR @JacksonFlanders  !! btw, if you want to meet other people making sprig games (and the devs), and get feedback / help any time we're in Slack in the #sprig channel https://hackclub.com/slack/
would be cool to see you there. say hi when you drop in :p

**Comment by SamDev-7** [comment]
@JacksonFlanders Did you solve the issue? We would love to add your game to the gallery. Let us know if you need any help!

**Comment by JacksonFlanders** [comment]
I'm so sorry for the wait, I just forgot about the project until I opened
my gmail about an hour ago. I'm not sure if the problem was fixed as it's
working fine for me, but I had to remake my game as the game file was lost.
I've got the new file downloaded. How do I replace the old game file and
replace it with the new one?

**Comment by LucasHT22** [comment]
Right, but wait, what do you mean with "game file was lost"?

**Comment by JacksonFlanders** [comment]
I deleted everything in my downloads folder, and at the time I stored the
game in my downloads folder so the game got deleted with it.

**Comment by LucasHT22** [comment]
Check https://github.com/hackclub/sprig/pull/498/files for all files:)

**Comment by JacksonFlanders** [comment]
Thanks

**Pull request closed without merging**
