### PR TITLE
Shataranj

### PR DESCRIPTION
**Pull request by Nikhil8557**
Author name: Nikhil kumar
### SatChitAnand

**About your game**
### What is your game about?

I'm very enthusiastic for New games, but chess is a classic favorite of many. That's why I choose to create it. There was already a chess on Sprig and it motivated me and also inspired me to write those long codes. No wonder it is a silent game, but indeed all the pieces speak up when it's a checkmate. And since I got the fundamentals, I can make a chess website in future with my fellow hack clubbers. Our own chess.com 😅
### How do you play your game?

Use WASD to move your cursor, J to pick up a piece, and K to place it.
You can use L(left) to drop a piece (or deselect), if some mistake happened (oops). Music will play if choose illegal move, to make you dance on your crime 😄

### Code
Check off the items that are true.

[x ] The game was made using the Sprig editor.
[x ] The game is placed in the in the /games directory.
[ x] The code is significantly different from all other games in the Sprig gallery (except for games labeled "demo").
[x ] The game runs without errors.
[x ] The name of the file/game contains only alphanumeric characters, -s, or _s.
[ x] The game name is not the same as the others from gallery
Image (If an image is used)
[ x] The image is in the /games/img directory.
[ x] The name of the image matches the name of your file.

> Thanks for your PR!
Hope we can Play it together

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Man, you know what I'm speaking. It's not the first time. Copying is not the solution, make your own game, you learn and have a console :) You can do remixes, but changing color and text are not big changes to consider your game. I'm here if you need any help:)

**Comment by Nikhil8557** [comment]
> Man, you know what I'm speaking. It's not the first time. Copying is not the solution, make your own game, you learn and have a console :) You can do remixes, but changing color and text are not big changes to consider your game. I'm here if you need any help:)


I developed my own code but yet struggling with graphic and public api

**Comment by LucasHT22** [comment]
what sounds confusing in Sprig?

**Comment by Nikhil8557** [comment]
> what sounds confusing in Sprig?

Can we chat somewhere else slack?

**Comment by LucasHT22** [comment]
sure, are you on Hack Club Slack?

**Comment by Nikhil8557** [comment]
Yes

**Comment by grymmy** [comment]
Closing due to inactivity. Please re-open if you'd like to continue forward landing this game!

**Pull request closed without merging**
