### PR TITLE
Operation_Ocean

### PR DESCRIPTION
**Pull request by ari-tistic**
# Your checklist for this pull request

## Author name

**Author:**

ari-tistic

## About your game

**What is your game about?**

Reducing CO2 emissions to alleviate ocean acidification.

**How do you play your game?**

AD to move, K to begin/move to next text slide, I to shoot

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! There are 2 js files, they are the same?

**Comment by ari-tistic** [comment]
Hi! Yes, I think both files are the same. I may have added one by accident.

**Comment by LucasHT22** [comment]
I'll remove one of them

**Review by LucasHT22 — APPROVED** [review]
Great game!

**Pull request merged**
