### PR TITLE
TheSpaceGuardian

### PR DESCRIPTION
**Pull request by Space1415**
# Your checklist for this pull request

## Author name

**Adrian DeGendt:**

## About your game

**The Game is about shoting ufos with lazers.**

**How do you play your game?**

 Press WASD to move, J to restart and K to toggle trails. Press I to shot with the lazers and move with WASD.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
I do like the fast paced action of this game - however I cannot excuse a game that you can defeat in perpetuity by simply pressing one button (i.e., don't move the ship, and just fire constantly).

Please add a mechanic that defeats this tactic (at least) to reach the bar re: a Sprig device grant.

**Comment by Space1415** [comment]
Thanks for pointing out! I will make it much better. Best regards Adrian DeGendt
________________________________

**Comment by Space1415** [comment]
I updated the code and added new features to make it more challenging. Additionally, I implemented a high score system.

**Comment by grymmy** [comment]
This still doesn't feel playable.  It seems like I randomly die after a couple of ticks, even though it didn't seem like anything hit me.  Can you take another pass at this and try to ensure it doesn't gameover unnecessarily?

**Comment by Space1415** [comment]
Thanks for your comment. I should have included an introduction to the rules and how the game works. I added some new rules to make it very challenging. Your goal is to shoot as many UFOs as possible without dying. You die if the UFOs shoot you or if they get to the other side.

**Comment by Space1415** [comment]
Thank you so much! I am a teenager and would wery like to receive one! Where and how do I receive it?

Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
