### PR TITLE
Swapper

### PR DESCRIPTION
**Pull request by RaidTheWeb**
# Your checklist for this pull request

## Author name

**Author:** RaidTheWeb

## About your game

**What is your game about?** A simple puzzle game involving a swapping mechanic, can be played alone or with a friend.

**How do you play your game?** The How to Play menu can be found on the main menu screen. In singleplayer: WASD to move the selected player, I, J, K, or L to swap players between Blue and Red. In multiplayer: WASD to move Blue and IJKL to move Red. Standing on buttons will activate them and will open one or more door(s), boxes can be pushed onto buttons to keep them activated. Portals are linked Blue<->Orange, boxes and players may enter and exit them. The redo button may be used to reset the level if a mistake is made (a box is pushed into a corner it cannot be pushed out of). Red or Blue must reach the goal to complete the level!

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [X] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [X] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! Wdym with swap? 
> In singleplayer: WASD to move the selected player, I, J, K, or L to swap

**Comment by RaidTheWeb** [comment]
> Nice game! Wdym with swap?
> 
> > In singleplayer: WASD to move the selected player, I, J, K, or L to swap

Swap the selected player, I felt that was sufficiently obvious based on the context. The How to Play menu in-game is more specific in that it's to swap between the colours.

**Comment by LucasHT22** [comment]
Sorry for the delay! Right, did you manage to win the game?

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right! Where did you hear about Sprig?

**Comment by RaidTheWeb** [comment]
> Right! Where did you hear about Sprig?

Sprig specifically? Kognise's website actually, but I've known about hackclub for a while.
Saw it and had to give it a try :D

**Pull request merged**
