### PR TITLE
Cops and Criminals

### PR DESCRIPTION
**Pull request by Ssmidge**
# Checklist

## Author name

**Author:** Adrian T

## About your game

**What is your game about?**
Escaping from jail, each level you get put in a higher security prison, you have to play against your friends to see who's a better criminal!

**How do you play your game?**

To enter the first level, use I.
Criminal's movement: WASD
Cop's movement: IJKL

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

### CODE REVIEW

**Review by GalaxyGamingBoy — CHANGES_REQUESTED** [review]
Good game with the twist on escaping prizon! I'd love an update with movables enemies andor a shop kind of system so you can use your points

**Comment by Ssmidge** [comment]
Hey,

Thanks for the feedback! I'm interested in what you mean by moveable enemies though, as in a singleplayer mode with pathfinding? Also, I'm definitely looking into adding a shop!

**Review by GalaxyGamingBoy — APPROVED** [review]
The pathfinding is seriously so cool! It makes the game so much more harder trying to outrun the actual officers

**Comment by GalaxyGamingBoy** [comment]
If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev/) and join our [Slack community](https://hackclub.com/sprig) to chat with other people making Sprig games and tell people about your game in #sprig!.

**Pull request merged**
