### PR TITLE
cat_and_mouse_with_a_twist

### PR DESCRIPTION
**Pull request by ViviKai06**
# Your checklist for this pull request

## Author name

**Author:** Vincent Villarreal

## About your game

**What is your game about?** In my game, you play as a cat and have to make your way through the levels to get to the mouse.

**How do you play your game?** WASD to move. Level 1: Get to the "purpledude". Level 2: Get to the spaceship. Level 3: Get to the mouse by moving the cheese surrounding him.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Comment by ViviKai06** [comment]
Hello, I heard about Sprig through my computer science teacher. She encouraged her students to try and make a game.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! What about more levels?

**Comment by grymmy** [comment]
> Nice! What about more levels?

I agree with Lucas on this one.  I think it needs some more content (especially on the code side) to be eligible for a Sprig grant.

**Comment by grymmy** [comment]
Closing this PR due to inactivity.  Please reopen it if you'd like to move forward w/ this by adding more content.

**Pull request closed without merging**
