### PR TITLE
Create game Delige

### PR DESCRIPTION
**Pull request by HeritageOlayinka**
I have written a game in JavaScript called Delige and added a thumbnail to the pics sub-folder in the games folder. Basically, you have to push a box into a hole and nothing can pass through the walls. I've been doing web development with HTML, CSS and JavaScript. I also do back-end with Python (Django). Currently learning Node.js and React.js. I also know data manipulation and data visualization using NumPy, Pandas, Matplotlib and Seaborn.

### CODE REVIEW

**Comment by LucasHT22** [comment]
At first I thought it was a compilation of games haha, one question, is it possible to pass phase 4?

**Comment by SamDev-7** [comment]
Thanks for the PR! Some minor issues with the music, it seems to be playing multiple times past the first level.
I also am not sure if it's a problem on my side, but the whole screen is covered with the goal tile. 
image

**Comment by HeritageOlayinka** [comment]
> Thanks for the PR! Some minor issues with the music, it seems to be playing multiple times past the first level. I also am not sure if it's a problem on my side, but the whole screen is covered with the goal tile. image


The music is what it is. I might optimize that very soon. But as always keep things simple, and I will keep iterating on it. Thanks for your feedback. As for the the whole screen is covered with the goal tile, try reloading the page because it is not showing on my device. What level did you experience this? Thanks for your feedback.

**Comment by HeritageOlayinka** [comment]
> At first I thought it was a compilation of games haha, one question, is it possible to pass level 4?

Actually, I've have not completed playing it. I will try to. If you think they can't be solved, then tell me so I can go back to my drawing board and get something better. Thanks for your feedback

**Comment by HeritageOlayinka** [comment]
Wait a second. I am still testing the game from my sprig editor, is there any testable link of the game you could share with me? Thanks

**Comment by LucasHT22** [comment]
In the Sprig editor there is no way to share a link. To resolve fullscreen goal failure:
const background = "k"

in setLegend create an all white bitmap.

on the map fill all the empty space with it.

Attention: Do not add it to solid because others need to pass over it.

Hope this helps :)

**Review by SamDev-7 — CHANGES_REQUESTED** [review]
>  As for the the whole screen is covered with the goal tile, try reloading the page because it is not showing on my device. What level did you experience this? Thanks for your feedback.

I experienced it on all levels. I just tried it again, and the issue disappeared, seems like it was something with the sprig editor. 

This also looks very similar to [purge](https://github.com/hackclub/sprig/blob/main/games/purge.js), try adding more things of your own.
Some ideas could be... A timer countdown, more blocks (an interesting idea could be portals that teleport you), be creative!

**Comment by LucasHT22** [comment]
@SamDev-7 For me it's different from Purge, the levels are similar but different

**Comment by LucasHT22** [comment]
> In the Sprig editor there is no way to share a link. To resolve fullscreen goal failure: const background = "k"
> 
> in setLegend create an all white bitmap.
> 
> on the map fill all the empty space with it.
> 
> Attention: Do not add it to solid because others need to pass over it.
> 
> Hope this helps :)

@HeritageOlayinka Did it help?

**Comment by leomcelroy** [comment]
Is the last level beatable? You can't move the blocks off the wall to get them to the goals.

Screen Shot 2022-09-19 at 5 08 33 PM

**Comment by leomcelroy** [comment]
I do like these sokoban games and am happy to have more but try to add more original levels. Thanks for joining in on Sprig!

**Comment by LucasHT22** [comment]
Hey @HeritageOlayinka !
I see you're gone, need help?

**Comment by LucasHT22** [comment]
@karamassie If there are 2 files with the same name, there isn't conflict?

**Comment by LucasHT22** [comment]
Hey @HeritageOlayinka !
I see you're gone, need help?
We look forward to having your game in the gallery :)

**Comment by leomcelroy** [comment]
I'm going to close this for now to keep the PRs neat and tidy but feel free to reopen when your game is ready.

**Pull request closed without merging**
