### PR TITLE
Apple Skedaddle

### PR DESCRIPTION
**Pull request by DieselFalcon**
You are an apple who wants to be reunited with his Watermelon friend. However, there are dangerous bombs stopping you from reaching him! Touching the bombs will result in an explosion and the reset of your level. Outwit the bombs by working through the maze to reach your friend. Make your way through the 3 levels and rescue your friend!

I have very little experience in coding and decided to create this game to test my knowledge. I had a lot of fun creating it and I learned a lot.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR!

**Review by LucasHT22 — COMMENTED** [review]
Very good game! could you add another two levels? with 3 levels is very fast

**Comment by DieselFalcon** [comment]
Sure! I'll resubmit it as soon as I add another level.
Thanks

**Comment by DieselFalcon** [comment]
Should I submit another PR?

**Comment by LucasHT22** [comment]
no, just change in your Diesel Falcon/spring directory or in this PR itself in `Files changed` > `...` > `edit`

**Comment by DieselFalcon** [comment]
I added my new changes. Thank you

**Review by LucasHT22 — APPROVED** [review]
Congrats!
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by LucasHT22** [comment]
out of curiosity, how did you meet sprig?

**Pull request merged**
