### PR TITLE
inconsequential leveldungeon

### PR DESCRIPTION
**Pull request by LtPeriwinkle**
Collect keys to unlock the portal and escape the randomly-generated dungeon. Don't fall into a trap. The cake is not a lie.

WASD to move, J to start game (or to reset if you end up in an impossible dungeon, which could theoretically happen).

If it's too hard I can nerf it.
The death sound and item-get sound are mario and zelda, respectively, but I wrote them by hand (and they aren't exactly identical) so it should be fine.

I'm a pretty experienced programmer, but this is the most JavaScript I have written probably ever (and the most spritework I've ever done as well).

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR!

**Review by LucasHT22 — COMMENTED** [review]
Great game!

**Review by LucasHT22 — APPROVED** [review]
Congrats!
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by LtPeriwinkle** [comment]
Thanks!

**Pull request merged**
