### PR TITLE
Sound Memory

### PR DESCRIPTION
**Pull request by meronemo**
## Author name

**Author:** meronemo

## About your game

**What is your game about?**
Listen and memorize the order of the sound playing. After the tunes are all played, press the keys to repeat them in the same order.

**How do you play your game?**
Press W for the red box, A for yellow, S for green, and D for blue. Wait and listen for the tunes to play, and press the keys to repeat those tunes in the same order.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by GalaxyGamingBoy** [comment]
Really cool mechanic that makees gameplay enjoyable! If you're a teenager, and you haven't already received a Sprig device, feel free to fill out [this form](https://sprig-order.hackclub.dev/) to receive one! Also, feel free to join Hack Club's Slack in the #sprig channel to share your creation w/ others!

**Review by GalaxyGamingBoy — CHANGES_REQUESTED** [review]
Hey! This has a lot of similarities with the maze starter gallery game. It is okay to remix games however to meet the criteria you must add a new game mechanic or two in order to make it more original

**Comment by meronemo** [comment]
@GalaxyGamingBoy Do you mean by the maze_game_starter game? I don't see any similarities with it and my sound memory game. Could you please have a look at this again?

**Comment by GalaxyGamingBoy** [comment]
I'm really sorry about that! I meant to approve this game. Cool game and I really love the music style puzzle you have. If you're a teenager, and you haven't already received a Sprig device, feel free to fill out [this form](https://sprig-order.hackclub.dev/) to receive one! Also, feel free to join Hack Club's Slack in the #sprig channel to share your creation w/ others!

**Pull request merged**
