### PR TITLE
DoNotConsumeEmptyBowls

### PR DESCRIPTION
**Pull request by se1yu**
# Your checklist for this pull request

## Jeslyn Chang

**Author:**

se1yu

## About your game

This cute minigame features two thing I love most, cats and sushi! You play as a very hungry cat that is at an all you can eat sushi-buffet! Avoid any empty bowls or you lose.

**How do you play your game?**

Press A or D to move. Press J to retry.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [] The name of the image matches the name of your file. 
cant take out spaces in image name

> Thanks for your PR!

### CODE REVIEW

**Review by se1yu — COMMENTED** [review]
took out spaces on file name

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey @se1yu ! Thanks for your PR:) where did you hear about Sprig?

**Review by LucasHT22 — APPROVED** [review]
BTW -- your sprites are so cute! Nice game too:)

**Comment by se1yu** [comment]
> Hey @se1yu ! Thanks for your PR:) where did you hear about Sprig?

Thank you! I heard about Sprig while randomly scrolling through Hack Club's Slack

**Comment by se1yu** [comment]
Also, does this mean I was approved to get a sprig?

**Review by LucasHT22 — APPROVED** [review]
Yes! I just wanted to know where you discovered Sprig. Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
You can also get a case for your Sprig here: https://airtable.com/appN9cSnDgORAM2bp/shrUfm6TWoA1VFKik

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by se1yu** [comment]
Thank you!

**Pull request merged**
