### PR TITLE
Game submission: untitled taiko game

### PR DESCRIPTION
**Pull request by Supercolbat**
# Your checklist for this pull request

## Author name

**Author:** Joey Lent

## About your game

**What is your game about?**

Untitled Taiko Game is a rhythm game that is based on other taiko games (e.g. [Taiko no Tatsujin](https://en.wikipedia.org/wiki/Taiko_no_Tatsujin), [osu!taiko](https://osu.ppy.sh/wiki/en/Game_mode/osu!taiko)).

**How do you play your game?**

The title screen shows you the keys you press and their corresponding colors. These are important in-game. Press the four keys to continue.

On the beatmap selection screen, use the up (<kbd>W</kbd> or <kbd>I</kbd>) and down (<kbd>S</kbd> or <kbd>K</kbd>) keys to select a beatmap. Hit right (<kbd>D</kbd> or <kbd>L</kbd>) to continue. (Currently only 1 beatmap)

Now you need to select a difficulty. Use the same keys as above to select a difficulty.

Notes will appear from the right of the screen in either red or blue. You can hit either <kbd>D</kbd> or <kbd>J</kbd> to hit red notes and either <kbd>A</kbd> or <kbd>L</kbd> to hit blue notes. These are the same keys from the title screen. Use the indicator on the left of the screen and the music to guide when you should click.

Once you finish the beatmap, you'll be sent to a results screen where you can see your final score alongside other statistics. Hit up to return to the selection menu.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] * The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] ** The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

\* There is another Sprig game called [taikoMania](https://sprig.hackclub.com/gallery/taikoMania), but our games are very different.
\*\* The game is a little intensive and **happens to lag on Firefox browsers**. It works fine on Chromium browsers.

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by Supercolbat** [comment]
Hi! I heard about Sprig from a friend who is also in Hack Club. Truthfully, I had known about it for a while now but only now had the inspiration to finish and submit a game.

**Comment by LucasHT22** [comment]
Right:) What about Sprig taiko instaed of untitled taiko game?

**Comment by Supercolbat** [comment]
In retrospect, "Untitled Taiko Game" is not the most intuitive name. I think I'll rename it to "Taiko Fever".

**Review by LucasHT22 — APPROVED** [review]
Perfect! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
