### PR TITLE
Chase

### PR DESCRIPTION
**Pull request by Goldenpig12345**
# Your checklist for this pull request

## Author name
Nathaneal
**Author:**Nathaneal

NathanytheGreat
## About your game

**What is your game about?**
A potatoe Escaping the knives

**How do you play your game?**
You move around and try to survive as long as possible and I still might have some work to do.
Oh I guess its WASD to move.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Goldenpig12345** [comment]
Hey I would really like it if you gave me the sprig , thank you

**Comment by Goldenpig12345** [comment]
I did update it on sprig and I don’t know how to update it here so I just wanted you to know that

**Comment by Goldenpig12345** [comment]
wut??? who are you whats going on this is hared

**Comment by LucasHT22** [comment]
What do you mean with who are you? I'm Lucas, I'm a volunteer reviewing PRs and I'm here to help you:)

**Comment by Sheepy3** [comment]
Closing this PR due to inactivity. If you want it reopened, ping me here.

**Pull request closed without merging**
