### PR TITLE
calculator

### PR DESCRIPTION
**Pull request by SameeraMurthy**
# Your checklist for this pull request

#### What is your game about? 
It is a calculator for the Sprig.

#### How to play your game?
WASD to Move Cursor
K to Select
L to Solve
I for Backspace
J to Clear Screen

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
This is amazing! a small detail: it seems that the operations with Radical isn't working

**Comment by SameeraMurthy** [comment]
It does work with a second input like the other operations.  I'm assuming you thought the radical button was square root? It is supposed to be the nth root. For example, you can input 512 and click the "√" (Radical Button), and then select 3, it will return 8, because the cube root of 512 is 8. You can also do square roots, 4th roots and so on. I also tried to draw an x above the root symbol to show that the user could input any number.

**Comment by LucasHT22** [comment]
> It does work with a second input like the other operations. I'm assuming you thought the radical button was square root? It is supposed to be the nth root. For example, you can input 512 and click the "√" (Radical Button), and then select 3, it will return 8, because the cube root of 512 is 8. You can also do square roots, 4th roots and so on. I also tried to draw an x above the root symbol to show that the user could input any number.

ooohhh right!

**Review by LucasHT22 — APPROVED** [review]
LGTM!

**Comment by LucasHT22** [comment]
https://github.com/hackclub/sprig/commit/0f27e075a77e2b74bc7660b07f0bc354af2e91c6

**Pull request merged**
