### PR TITLE
New game upload for a Personal Sprig Kit.

### PR DESCRIPTION
**Pull request by DuanBoomer**
# Your checklist for this pull request

## Author name
Chirag

## About your game

Dodging bullets falling at you.

**How do you play your game?**
Press A to move left and D to move right.

## Code
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! only 1 bullet falls, was this supposed to happen?

**Comment by DuanBoomer** [comment]
Oo sorry, maybe I missed something in it.
I will take a look.

**Comment by LucasHT22** [comment]
no problem! take your time:)

**Comment by DuanBoomer** [comment]
@LucasHT22 Updates the game to a whole new level.
Please take a look 😊

**Review by LucasHT22 — APPROVED** [review]
Good updates! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
