### PR TITLE
Add Game Chase Escape

### PR DESCRIPTION
**Pull request by EdwardLab**
# Your checklist for this pull request

## Author name

**Author: Edward Hsing**

## About your game

**In a chase game, 'Orange Face' will consume you. You must avoid getting close to 'Orange Face' because touching it results in a game over.**

**Press J to enter Easy Mode, press I for Medium difficulty mode, and press K for Hard Mode. Once chosen, use W to move forward, S to move backward, A to move left, and D to move right to control the Player and avoid being eaten by Orange Face. The game ends when you get caught by Orange Face.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Sorry for the delay! Out of curiosity, did you use any game for inspiration?

**Comment by LucasHT22** [comment]
Sorry for the delay again!! Nice! Could you re-check this?
- [ ]  The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by EdwardLab** [comment]
I'm so sorry for delay. I edited the file name, thank you so much!

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
