### PR TITLE
2D life

### PR DESCRIPTION
**Pull request by Omay238**
If you want better information on how to change the rules, comment on the PR.

### CODE REVIEW

**Comment by Omay238** [comment]
I didn't really have to do this, but I wanted feedback before I merge it.

**Review by LucasHT22 — COMMENTED** [review]
hey @Omay238 !
Your game looks good but I don't understand your game, could you explain it to me?

**Comment by Omay238** [comment]
Conway's game of life. "I" to toggle a cell, "K" to step the simulation, and "WASD" to move the cursor.

**Comment by LucasHT22** [comment]
have any goals? Or is it just an experience?

**Comment by Omay238** [comment]
Just an experience. Not really any goal to it. You can try and make fun rules, and look at patterns, but not much else.

**Comment by LucasHT22** [comment]
Ok!

**Pull request merged**
