### PR TITLE
Add goaled.js

### PR DESCRIPTION
**Pull request by UnstoppableBlob**
Hello, this is my Sprig game. I'm pretty new to programming, so please tell me if there is anything I can do to make it better.

It's a game where you need to push the ball into a teleporting goal. I hope you like it!

### CODE REVIEW

**Comment by SamDev-7** [comment]
Cool game! Really tricky and is fun to play! Thanks for the PR.

One minor issue. One line 194, it will error when there is no goal on the screen, like the game over screen for example. 
To prevent that, I suggest you add a check to see if there is a goal on screen. Let us know if you run into any issues!

**Review by LucasHT22 — COMMENTED** [review]
Good game! The goal moving randomly is fun :)
but for me this error appears:

`Uncaught TypeError: Cannot set properties of undefined (setting 'x') on line 194 in column 20. Open the browser console for more information.`

**Comment by UnstoppableBlob** [comment]
> This is a nice straightforward game. Could you add a background to make it more visually interesting?
> 
> I also get the error Lucas mentioned.
@leomcelroy 

Okay I added a background, made it look better, and fixed that error.

**Comment by LucasHT22** [comment]
I had a lot of fun with your game! 
Good game, good background
congrats :)

If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
