### PR TITLE
The Combine

### PR DESCRIPTION
**Pull request by SidharthBhatt**
# Your checklist for this pull request

## Author name

**Author:** Sidharth Bhatt

## About your game

**What is your game about?**
An adaptain of  Kesey's world famous "One Flew Over the Cooko's Nest", _The Combine_ is a game where players can escape the ward and go fishing! 

**How do you play your game?**
Use the WASD keys to move around
- Based of One Flew Over the Cooko's Nest
- First Module: 
  - you are McMurphy and must escape the ward 
  - use your strength to push the grey pushblocks
  - break into the nurses glass and steal a key 
  - bring the key to the check point
- Second Module:
  - Congrats your free to go fishing!
  - Use WASD to move your pole around
  - Click J to start fishing (afterward you can't move the pole around)
  - You have 60 seconds to collect 3 out the 4 fish 

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x ] The name of the image matches the name of your file. 

> Thanks for your PR! yay!

### CODE REVIEW

**Comment by SidharthBhatt** [comment]
I'm confused as to why it failed the plagiarism check. It seems like there may be an error.

**Review by grymmy — CHANGES_REQUESTED** [review]
Please remove spaces from the filename of your game and the image.  The checklist requests that you ensure only alphanumeric and underscores.

**Comment by SidharthBhatt** [comment]
I think I fixed it, can you run the tests?

**Review by SidharthBhatt — COMMENTED** [review]
this doesnt have a space

**Comment by grymmy** [comment]
Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
