### PR TITLE
Bullet Dodge

### PR DESCRIPTION
**Pull request by Vishram1123**
# Your checklist for this pull request

## About your game

What is your game about? 
My game is a fast-paced bullet-hell style game in which the player tries to avoid bullets from all edges of the screen from hitting them. It has two interesting mechanics - the ability to warp time, and the ability to heal.

How to play your game?
W/A/S/D to move up/left/down/right
J to activate time warp powerup. Using the time warp powerup will slow down the rate at which bullets spawn for 5 seconds. There is an 8 second cooldown to use another powerup after using this one.
I to activate heal powerup. Using the heal powerup will regenerate 3 HP. There is a 5 second cooldown to use another powerup after using this one.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by Vishram1123** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Comments	Updated
> **sprig**	✅ Ready ([Inspect](https://vercel.com/hackclub/sprig/3hxnPhao8YbxAgg7SJrLNCQB9EWg))	[Visit Preview](https://sprig-lu0dyyu4m.hackclub.dev)	💬 [**Add your feedback**](https://vercel.live/open-feedback/sprig-lu0dyyu4m.hackclub.dev)	Jan 13, 2023 at 4:45AM (UTC)

Why does the preview use the demo? Just curious, is that just a config thing, or was there something wrong on my part?

**Comment by LucasHT22** [comment]
> > **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> > Name	Status	Preview	Comments	Updated
> > **sprig**	✅ Ready ([Inspect](https://vercel.com/hackclub/sprig/3hxnPhao8YbxAgg7SJrLNCQB9EWg))	[Visit Preview](https://sprig-lu0dyyu4m.hackclub.dev)	💬 [**Add your feedback**](https://vercel.live/open-feedback/sprig-lu0dyyu4m.hackclub.dev)	Jan 13, 2023 at 4:45AM (UTC)
> 
> Why does the preview use the demo? Just curious, is that just a config thing, or was there something wrong on my part?

it's just a config thing haha

**Comment by LucasHT22** [comment]
We are working to resolve the bug!:)

**Comment by Vishram1123** [comment]
Hello, I seem to have named the js and the png differently (as you can see from my last commit in this pr). Could you please change the name of the js to bullet_dodge.js instead of bullet-dodge.js? Or should I submit another pr?

**Comment by LucasHT22** [comment]
Ok!

**Pull request merged**
