### PR TITLE
Mirror Mirror

### PR DESCRIPTION
**Pull request by Anonymous4045**
## About your game
You must try to escape a large maze that you are trapped in, but you have a clone that is following your every move. You must both make it out at exactly the same time, or risk losing it all.

WASD to move, j to reset. Both entities must reach the green box and go onto it at the same time.

## Code
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Good game! How about adding a background?

**Comment by Anonymous4045** [comment]
> Good game! How about adding a background?

I knew something was missing, thanks!

**Comment by Anonymous4045** [comment]
Just realized I originally uploaded the wrong file! That was an older version, the one I just uploaded has levels 4 & 5 and better sprites/sounds.

**Comment by Anonymous4045** [comment]
All levels are possible, although some are pretty hard/unintuitive. This is mostly by design since this is meant to be a puzzle game, but if it's too difficult to the point of not being fun, let me know and I'll add a few more blocks.

**Comment by LucasHT22** [comment]
Ok! yes it's fun:)

**Review by LucasHT22 — APPROVED** [review]
Good game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
