### PR TITLE
silly little guy game

### PR DESCRIPTION
**Pull request by danilani12**
# Your checklist for this pull request

## Author name

**Author:** Danica 

## About your game

**What is your game about?** Just a silly little guy pushing boxes into goals

**How do you play your game?**Press WASD to move, J to restart and K to toggle trails, Get boxes (pink) to goals (green) while avoiding running into walls (blue). 

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Did you use any game for inspiration?

**Comment by danilani12** [comment]
Hey there!

 Yes, I did. I used the tutorial introduction game as inspiration for my game. The game is titled getting started, and was created by @leo. The game has the same objective, and similar character designs (boxes and goal) but I did create the game entirely by myself. Sorry if I happened to miss a certain check box lol!

**Comment by LucasHT22** [comment]
Nice! 
> Sorry if I happened to miss a certain check box lol!

no worries!

**Comment by danilani12** [comment]
It’s possible that I might add more sprites and levels, but I’m currently not in the position where I have that kind of time.

**Comment by LucasHT22** [comment]
Alright... where did you hear about Sprig?

**Comment by danilani12** [comment]
I heard about it from my Computer Science teacher and classmates! Some of them were doing projects on Sprig and it encouraged me to try it out.Sent from my iPhoneOn Mar 8, 2024, at 7:47 PM, Lucas Honda ***@***.***> wrote:﻿
Alright... where did you hear about Sprig?

**Comment by LucasHT22** [comment]
Nice! I'm thinking here and you won't spend too much time making a new level and polishing the sprites:) Is pretty easy, I'm sure that with 30 minutes you do all this:)

**Comment by leomcelroy** [comment]
Thanks for sharing! I'm going to close this for housekeeping but feel free to resubmit when you are ready.

**Pull request closed without merging**
