### PR TITLE
Minigame Mania

### PR DESCRIPTION
**Pull request by FlubbedAlpaca**
# Your checklist for this pull request

## Author name

**Author:**

## About your game
AngelHacks Toronto
**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by FlubbedAlpaca** [comment]
@ManushPatell
@AiyuuGames
@MatiasSharofi

**Comment by MatiasSharofi** [comment]
We are a team.

**Comment by ManushPatell** [comment]
confirmed!

**Comment by AiyuuGames** [comment]
We are a team

**Review by SamDev-7 — APPROVED** [review]
Note: Made in AngelHacks Toronto (Team of 4)
@FlubbedAlpaca @ManushPatell @MatiasSharofi GOT SPRIGS IN PERSON

@AiyuuGames needs a sprig. https://sprig-order.hackclub.dev/

**Pull request merged**
