### PR TITLE
Add Game "Hidden Maze"

### PR DESCRIPTION
**Pull request by Dark-Sniper101**
Author
Rylan Berry
(Note, if you want I'm on slack as "Rylan Berry")

About
In this game so cleverly named "Hidden Maze" you have to traverse a maze, but the thing is you can't see the walls of the maze, only the end goal and your current location, the game has a total of 3 mazes, getting progressively larger and harder the more you complete. The game is only meant to be played through once because it's not a challenge if you already know the path.

How to Play
You use the WASD keys to move the player character. When you first start you'll see a banana man, which is the playable character, a colorful flooring, and a trophy which is your end goal. You will know if you hit a wall when you can't move in that direction. You'll know when you complete the game when you see the screen covered with a trophy and text saying "You've won," and like in a real maze, you can't go back to the start, Happy travels!

Code
Check off the items that are true. 
- [ X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ X] The game runs without errors. 
- [X ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

I did not include a custom thumbnail

### CODE REVIEW

**Review by reesericci — APPROVED** [review]

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! What about more 2 levels?

**Comment by Dark-Sniper101** [comment]
> Good game! What about more 2 levels?

Can do!

**Comment by Dark-Sniper101** [comment]
> Good game! What about more 2 levels?
 @LucasHT22 I have added 2 more levels in a new commit, hopefully that takes care of your request.

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
