### PR TITLE
spider_home

### PR DESCRIPTION
**Pull request by usermaatresetepenre**
# Your checklist for this pull request

## Author name

Usermaatre Setepenre

## About your game

this game is about a spider that wanna go to his home but he have obstacles along the way and the gravity is a issue, so you have to be patience and wait for the right time and take him home!

**How do you play your game?**

press WASD for move and press J for restart the level. and avoid the bombs otherwise level will restart

## Code
- [YES] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [YES] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [YES] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [YES] The game runs without errors. 
- [YES] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [YES] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [YES] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [YES] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! How about reducing the gravity a little? I think it will be very hard on the console

**Comment by usermaatresetepenre** [comment]
i increased the delay to 1 sec. so player have more time 🖤

**Review by LucasHT22 — APPROVED** [review]
Where did you heard about Sprig?

Anyway, Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by usermaatresetepenre** [comment]
i saw in Arduino forums about you guys 🖤
and thank you 🖤

**Comment by LucasHT22** [comment]
Oh nice! Just out of curiosity, do you have the link?

**Comment by usermaatresetepenre** [comment]
yeaah,
i dont have a link but i can show you snap of the post that i took when i saw that 🖤

image

**Comment by LucasHT22** [comment]
Nice! Thanks for sharing:)

**Pull request merged**
