### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by notmalakahmed**
# Your checklist for this pull request

## Author name

**Author:**

Malak

## About your game

**What is your game about?**

This game is a classic fun flappy bird game that gives a kind of nostalgia.

**How to play?**
The goal of the game is to pass the bird(represented by a red square) through the pipes (represented by a green rectangle) without colliding. This game is super easy as it only utilizes the space bar, as I have tested it on my little brother with two different ways to start, restart and play and i have figured that the space bar was easiest for all. You press the space bar to start  (as instructed by the text on the screen before playing) and press  the space bar to jump to avoid the obstacles and if you lose you restart by pressing the space bar.
 
## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! What is your game about?

**Comment by notmalakahmed** [comment]
> Hey! What is your game about?

> I changed, I realized I left the arrows and example again. I apologize for the inconvenience!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
No worries! Did you use the Sprig editor for this game?

**Comment by notmalakahmed** [comment]
> No worries! Did you use the Sprig editor for this game?

yes! I will share here : https://sprig.hackclub.com/share/lpvkF4O87WYCRInekIN1

**Comment by LucasHT22** [comment]
I think you are sharing the wrong version or is incomplete, there is no bitmaps and maps...

**Comment by LucasHT22** [comment]
Anwer the message above!! Let's get this merged:)

**Comment by Sheepy3** [comment]
Closing this PR due to inactivity. If you want it reopened, ping me here.

**Pull request closed without merging**
