### PR TITLE
Add Boba Maze

### PR DESCRIPTION
**Pull request by audreyolafz**
# Your checklist for this pull request

## Author name

**Author:**
Audrey Wang @audreyolafz

## About your game

**What is your game about?**
The Boba Maze is a game where the user can traverse through a series of mazes, similar to the process of making your own boba.

**How do you play your game?**
Press WASD to move up, left, down, or right respectively. Pressing I will open the instruction manual, J will reset the level, and K and L have secret functionalities for the user to discover. The goal is to move the cup to the globe to move on to the next level.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Comment by audreyolafz** [comment]
> Thanks for the PR! Where did you hear about Sprig?

I first heard about Sprig while organizing Horizon last year, but I never got the time to make one of my own until now!

**Comment by LucasHT22** [comment]
> > Thanks for the PR! Where did you hear about Sprig?
> 
> I first heard about Sprig while organizing Horizon last year, but I never got the time to make one of my own until now!

Oh nice! Horizon was the New York's one, right?

**Comment by audreyolafz** [comment]
> > > Thanks for the PR! Where did you hear about Sprig?
> > 
> > 
> > I first heard about Sprig while organizing Horizon last year, but I never got the time to make one of my own until now!
> 
> Oh nice! Horizon was the New York's one, right?

Yep! Also I realized I had a space in the title of the js file, so I just renamed it.

**Pull request merged**
