### PR TITLE
Add BigButton Game

### PR DESCRIPTION
**Pull request by LinusSkucas**
# Big Button

## About your game

What is your game about? 
> It's really simple: press the specified button when it says to do so. Easy, right? Not so fast: This _will_ help you waste your precious time™, and even after an hour of playing you still won't be able to beat it.

How to play your game?
> Press `w` to start, press the specified button when the screen turns red, then press `w` angrily again to restart the game once it insults you.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

### CODE REVIEW

**Comment by LinusSkucas** [comment]
Alright, I thought I fixed an issue but the check is still failing. I don't see anything in the console when I run it.

**Comment by LucasHT22** [comment]
I fixed it for you:)

**Review by LucasHT22 — APPROVED** [review]
Great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

out of curiosity, how did you meet sprig?

**Comment by LinusSkucas** [comment]
Thanks!
I've been part of hack club and finally got around to making a game.

**Pull request merged**
