### PR TITLE
Escape Arcade Prison

### PR DESCRIPTION
**Pull request by API-Troubles**
# Your checklist for this pull request

## Author name

**Author:** Felix Gao

## About your game

**What is your game about?**

This game is a timed prison game where you need to escape in 5 minutes. With some funny lore for the comedy points! The lore is as follows. You were caught committing ticket fraud. Instead of banning you, the hack club staff felt experimental. You are now locked up in arcade prison for LIFE. Is this legal? Idk. But you need to escape. Lucky for you, the arcade staff are busy waking up the 3 children responsible for Hakkuun up, so you have, lets say, 5 minutes. Hurry.

**How do you play your game?**

WASD = Movement
L = Restart/Start game as prompted on screen
I = Set pin on lockpick minigame

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by API-Troubles** [comment]
Hi! Thanks for fixing the image, just realized that the `!` isn't alphanumeric, oops. Could you also please edit the metadata to fix the typo in prison? I don't know how to fix it now that its a pr.

Thanks!

**Review by grymmy — CHANGES_REQUESTED** [review]
Please contact me in Hack Club's slack to move this PR forward towards merge and a Sprig device grant.

**Comment by grymmy** [comment]
Congratz!  If you're a teenager, and you haven't already received one, this submission has earned you a brand new Sprig device!  Please fill out [this form](https://sprig-order.hackclub.dev/)!****

**Comment by API-Troubles** [comment]
Thanks!

**Pull request merged**
