### PR TITLE
My game for the Penny's Big Breakaway Sprig Jam

### PR DESCRIPTION
**Pull request by OHIO-MAN**
Making the game was fun

# Your checklist for this pull request

## Author name

**Author:**
OHIO-Man

## About your game

**What is your game about?**
My game is a roguelike game where you explore randomly generated levels, fight enemies and eventually fight the final boss

**How do you play your game?**

Controls:
WASD to move
IJKL to attack

The Game:
Explore a randomly generated world where you have to use
your yoyo to fight penguins and eventually fight the
emperor at the end.

Every 3 levels you'll either get a shop where you can buy
items or a prize room that gives you a free item.

To buy an item at the shop, just step on it and it'll be
bought.
Here are the items, their prices, and their effect:

    Item    |    Effect    |    Price    
------------+--------------+-------------
    Appel   |  Heals by 1  |      2
   Borgor   |  Heals by 2  |      5
    Spool   |  Str Len +1  |      10
  Cool Yoyo |    ATK +1    |      15

There are also spikes that you have to dodge.
You also die when you run out of hearts.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR! Nice! Is it possible to win?

**Comment by OHIO-MAN** [comment]
I hope so.

**Review by LucasHT22 — COMMENTED** [review]
Out of curiosity, did you use any game for inspiration? Of course, except Penny's Big Breakway

**Comment by OHIO-MAN** [comment]
Mainly "The Binding of Isaac".

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by faisalsayed10** [comment]
Hi @OHIO-MAN what's your slack id, will send over the game code in DMs :))

**Comment by OHIO-MAN** [comment]
Heres my slack id 
U04LNE9HEFK

**Comment by faisalsayed10** [comment]
Check your DMs :))

**Pull request merged**
