### PR TITLE
Add Game: Hidden Maze Escape

### PR DESCRIPTION
**Pull request by Dark-Sniper101**
## Author name

**Author: Rylan Berry**

## About your game

**What is your game about?**
This game is the final game in my hidden maze trilogy, this game uses the same starting maps as the original, but you can see the walls, but if you complete those five only, you'll get the first ending. For the second ending, you have to find the secret in each map and complete each of their puzzles, then you get the second ending.
The puzzles are hidden in each maze (putting a new meaning to "hidden maze" unlike the original two) you'll have to find them then you'll be taken to the puzzle room. 
The puzzles work as follows: Cover all the targets with blocks, then you're done, do the puzzle for each maze then you get the second ending. 

**How do you play your game?**

WASD: Moving up, left, down, and right, respectively.
J: Restarts the entire game.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for viewing my PR!

### CODE REVIEW

**Comment by Dark-Sniper101** [comment]
Hopefully, the previous commits from this fork don't mess with the main branch, but I'm still new to GitHub so be wary.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! no worries about previous commits!! But how exactly the hidden mazes are unlocked?

**Comment by Spllit1** [comment]
> Hey! no worries about previous commits!! But how exactly the hidden mazes are unlocked?

hii :) i have played the game and searched for the hidden mazes, you have to go places, where you shouldn't normally go to finish the game...

btw @Dark-Sniper101, i like this game!

**Review by LucasHT22 — APPROVED** [review]
Thanks @Spllit1! @Dark-Sniper101 congrats on your 3rd game!!

**Pull request merged**
