### PR TITLE
Tag

### PR DESCRIPTION
**Pull request by ThomasJPrice**
# Your checklist for this pull request

## Author name

**Thomas Price**

## About your game

**It's a two-player game based on tag, so the blue guy has to "tag" or touch the red guy, then  it swaps.**

**Red - WASD, Blue - IJKL. The tagger cannot collide with boxes, but the character being tagged can, for an easier escape.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add one or two more unique mechanics to this game to meet the bar re: a Sprig device reward.

**Comment by ThomasJPrice** [comment]
I added a new feature so there are boxes with red dots which randomly appear and disappear which the tagger can not pass through, thus making it harder for them to tag the other player.

**Comment by PSJahn** [comment]
Hey, it appears that your game has a bug where the disappearing boxes can make the players disappear too, resulting in lots of errors

**Comment by grymmy** [comment]
I looked at this today.  I would echo the previous commenter:

https://github.com/hackclub/sprig/pull/1858#issuecomment-2203387934

**Comment by GalaxyGamingBoy** [comment]
Hey! I’ll be closing the PR because of inactivity. Feel free to reopen the PR and ping me if you still want to move forward into acquiring a sprig device grant and publishing your game.

**Comment by ThomasJPrice** [comment]
Sorry @GalaxyGamingBoy  I didn't realise that was a thing. I'm on holiday at the moment but am definitely keen to acquire the Sprig so I'll fix that bug when I get back 🙂

**Comment by GalaxyGamingBoy** [comment]
Sure, that isn't a problem!

**Comment by ThomasJPrice** [comment]
The bug has now been fixed!

**Comment by grymmy** [comment]
Congratz!  If you're a teen, and you haven't already received one, please fill out [this form](https://sprig-order.hackclub.dev/) to receive a Sprig of your own!  Additionally, feel free to join Hack Club's Slack and share your creation in the #sprig channel!

**Pull request merged**
