### PR TITLE
Mazerunner

### PR DESCRIPTION
**Pull request by AyoubChafiq**
# Your checklist for this pull request

Ayoub Chafiq

## About your game
This is a simple maze game with 10 levels. In the starting menu screen, there are 3 themes to choose from.
**What is your game about?**
In this game, the objective is to reach the Crown. Sometimes this crown will be split into two and both players will have to reach the crown. In this game you will have to avoid obstacles and solve (extremely simple) puzzles. 

**How do you play your game?**
Player One - WASD
Player Two - IJKL

## Code 
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. *To my knowledge
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR! I see a lot of files here, could you say what file is your latest version?

**Comment by AyoubChafiq** [comment]
@LucasHT22 
The file with the name Maze_runner is my latest version

**Comment by LucasHT22** [comment]
> @LucasHT22 The file with the name Maze_runner is my latest version

Could you delete the other files? If you need help, please ask:)

**Comment by AyoubChafiq** [comment]
I believe I deleted them now, but they still appear, so I am unsure. Thanks for the help

**Comment by AyoubChafiq** [comment]
@LucasHT22 I believe I deleted them now, but they still appear, so I am unsure. Thanks for the help.

**Comment by LucasHT22** [comment]
> @LucasHT22 I believe I deleted them now, but they still appear, so I am unsure. Thanks for the help.

I think you forget the other file:) try doing it one more time

**Comment by AyoubChafiq** [comment]
image_2024-05-20_215830230
In the attached image I showed the image I was trying to delete. The delete button is grayed out and I cannot delete it
@LucasHT22

**Comment by leomcelroy** [comment]
This file needs to be in the games folder.

**Comment by grymmy** [comment]
Congratulations on making a great game!  If you're a teenager, and haven't already received one, please fill out [this form](https://sprig-order.hackclub.dev/) to receive a Sprig device of your own!  Also, feel free to check out Hack Club's Slack, and chime in on the #sprig channel to share your game w/ others in our community!

**Comment by AyoubChafiq** [comment]
@grymmy I really appreciate all your help on this. I just had one last question, I was wondering if I could order this in August instead of now, since I won't be home this summer

**Pull request merged**
