### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AndrewCromar**
# Your checklist for this pull request

## Author name

**Author:**
Andrew Cromar

## About your game

**What is your game about?**
You are a dog who is trying to collect all of his bones. When you collect all of them you move onto the next level.

**How do you play your game?**
Move with WASD.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by AndrewCromar** [comment]
I attended hackoc awhile back and when trying to find more hack club
hackathons  I found the sprig site on the hack club website. I saw you
could get a sprig for making a project and thought I would try it out.
Although after reading the requirements I saw it had to be 5 minutes long
so I am working on another project for if this one does not qualify.

**Comment by LucasHT22** [comment]
> I attended hackoc awhile back and when trying to find more hack club hackathons I found the sprig site on the hack club website. I saw you could get a sprig for making a project and thought I would try it out. Although after reading the requirements I saw it had to be 5 minutes long so I am working on another project for if this one does not qualify.

Dont worry about 5 minutes! We consider effort:)

**Comment by LucasHT22** [comment]
Could you add 2 more levels? :)

**Comment by AndrewCromar** [comment]
> Could you add 2 more levels? :)

Yes I will!

**Comment by AndrewCromar** [comment]
> Could you add 2 more levels? :)

I added a few more levels. hopefully the file uploaded correctly github was being a bit weird.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great! Please just re-check this:
The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by AndrewCromar** [comment]
> Great! Please just re-check this: The name of the file/game contains only alphanumeric characters, -s, or _s.

Yes it is only those alphanumeric characters, -s, or _s.

**Comment by LucasHT22** [comment]
replace the space with _ :)

**Comment by AndrewCromar** [comment]
Shoot my bad lol. :) fixed.

**Comment by LucasHT22** [comment]
Could you remove the duplicated file? :)

**Comment by AndrewCromar** [comment]
Alright I fixed it. lol

**Review by LucasHT22 — APPROVED** [review]
Sorry for my delay! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
