### PR TITLE
Add Morph Madness

### PR DESCRIPTION
**Pull request by SimonDMC**
# Your checklist for this pull request

## Author name

**Author:**

SimonDMC

## About your game

**What is your game about?**

Morph Madness is about solving puzzles by switching between a player and a bat. Inspired by Sokoban, the goal is to push boxes onto goals - but with a twist! The player can push blocks, but cannot pass through walls, while the bat can pass through anything, but cannot push blocks.

**How do you play your game?**

You play as a player who can morph into a bat.
 
Black blocks can be pushed. 
Yellow blocks morph you between a player and a bat.
Green blocks are the goals.

You move onto the next level by covering all goals with pushable blocks.

Controls:

WASD - Movement
K - Select Level
J - Restart Level

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Loved the sprites:) Where did you hear about Sprig?

**Comment by SimonDMC** [comment]
glad you liked the sprites! :D i found sinerider on twitter a few days ago (great game btw), from there found hack club, and saw sprig on the [github profile](https://github.com/hackclub/)!

**Comment by LucasHT22** [comment]
oh Sinerider, nice! How to solve this level? 
image

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
