### PR TITLE
Catch the star

### PR DESCRIPTION
**Pull request by grymmy**
# Your checklist for this pull request

## Author name

Mizuki (Saumya)

## About your game

It's about a reindeer catching the star while having a side quest of collecting the gifts.

It can be played by using WASD to move, J to restart, Move towards the star, and gifts.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
Sorry but who is the author?

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! What about more levels?

**Review by LucasHT22 — APPROVED** [review]
Great game! Congrats:) I really encourage you to add more levels:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by grymmy** [comment]
Congratz @mesaumya!  Your Sprig game has been approved and now merged into the gallery for others to see, learn from, and share.  If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/)

**Pull request merged**
