### PR TITLE
Nickels

### PR DESCRIPTION
**Pull request by AdamCodes2023**
# Your checklist for this pull request

## Author name

**Author:**

<-- Adam Miller -->

## About your game

**What is your game about?**

<-- Nickels is a fun die game that has players compete to be the first one to fill a board. Players roll two dice and cover up the matching sum on their board with a nickel. If a player already has already covered the number that he or she rolls, the next player has a chance to steal that value for his or her own board. Play continues to the next player after the stealer. If a player rolls the same number on both dice and does not get stolen from, he or she gets to roll again. If a player rolls a 7, a random nickel is removed from his or her own board. The first player to fill all ten spaces on the board is the winner! In this digital version, all decisions are handled randomly and immediately. The goal is to beat the computer opponent. -->

**How do you play your game?**

<-- Press "L" to roll the Player's dice. All decisions and board functions are handled appropriately and immediately. The Computer's turn follows. Continue pressing "L" to progress the game until somebody is victorious. Press "K" to reset the game and play again. -->

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Really sorry for delay! Thanks for PR:) Where did you hear about Sprig?

**Comment by AdamCodes2023** [comment]
I did the PCB program through HackClub earlier this year. I got an email about Sprig because of my prior activity and decided to check it out.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Oh Onboard! Did you use any game for inspiration?

**Comment by AdamCodes2023** [comment]
I used a board game called Nickels as my inspiration for this project. The rules and controls are very similar to the real game.

**Review by LucasHT22 — APPROVED** [review]
Oh Onboard! Did you use any game for inspiration?
Right! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by AdamCodes2023** [comment]
I ordered my Sprig console and received it on Monday. However, I did not
receive the special winter Sprig case that was advertised on the official
website. Who am I supposed to contact to receive it?

**Comment by LucasHT22** [comment]
> I ordered my Sprig console and received it on Monday. However, I did not receive the special winter Sprig case that was advertised on the official website. Who am I supposed to contact to receive it?

Will be sent soon:) sorry about it

**Pull request merged**
