### PR TITLE
Add a reset button in the tune editor

### PR DESCRIPTION
**Pull request by duck123acb**
I added a button to reset all the notes in the tune editor, with a confirmation prompt.
This could fix [this issue](https://github.com/hackclub/sprig/issues/905).
<br>
<br>
sprig-ui-full
<br>
sprig-ui-changed
sprig-ui-changed-confermation

### CODE REVIEW

**Review by grymmy — APPROVED** [review]
LGTM

**Review by grymmy — CHANGES_REQUESTED** [review]
This PR needs rebasing (seemingly due to the recent merge that occurred late last week).  Sorry for the inconvenience.

**Comment by duck123acb** [comment]
Alright

**Comment by duck123acb** [comment]
I have decided to close this, as it will take some time to learn how this new system works, so I might stop working on this for now

**Pull request closed without merging**
