### PR TITLE
Add LabyrinthRedux.js

### PR DESCRIPTION
**Pull request by itsimpeccable**
# Your checklist for this pull request

## Author name

**Author:** DorukSarpAlwaysStrikesBack

## About your game

**What is your game about?**
Classic Labyrinth game series made by me but with a new obstacle, fake goals.

**How do you play your game?**
WASD to walk, J to restart.

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [X] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [X] The name of the image matches the name of your file. 

> Thanks for your PR!
no problem lucas, you just gave me the motivation to make sprig games <3

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! What about more complex levels?

**Comment by itsimpeccable** [comment]
Sequel is coming soonTM

**Comment by LucasHT22** [comment]
hmmm what about increase the size of the levels a little?

**Comment by grymmy** [comment]
@LucasHT22 what is the gameplay length here?  is the game unique?  if it's unique and just a little small I say we move this one forward...

@itsimpeccable do you want to push for this being landed?  Chime in here please...

**Comment by LucasHT22** [comment]
@grymmy , it's too similar with their other games, that's why isn't merged:)

**Comment by LucasHT22** [comment]
@grymmy per my comment above closing this due to being too similar of another game

**Pull request closed without merging**
