### PR TITLE
Women in War

### PR DESCRIPTION
**Pull request by revaga**
# Your checklist for this pull request

## Author name

**Author:**
cupcakes

## About your game

**What is your game about?**
My game is about women's roles during the world wars. They were able to gain some rights and open new doors by entering the workforce while the men had gone to fight int he war. But when the soldiers returned, women were usually forced to give up their jobs or settle for low-paying ones. My game aims to depict their story. A player moves the crown (symbolizes the metamorphosis of women from fragile princesses to queens running a kingdom) around to pick up rights and opportunities. The player must pick up all items available in order to advance to the next part of the story.

**How do you play your game?**

Press WAD to move, W captures items, A & D move the crown left and right.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

### CODE REVIEW

**Comment by revaga** [comment]
I can do that!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice changes! One detail: the code looks duplicated

**Comment by revaga** [comment]
Oopsie ;) I'll fix that! Thank you so much for helping me

**Review by LucasHT22 — APPROVED** [review]
Thanks YOU! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
