### PR TITLE
Added Frog_Maze

### PR DESCRIPTION
**Pull request by venny-dev**
# Your checklist for this pull request

## Author name

**Jeremiah Kellison:**

Jay 

## About your game

**What is your game about?**

 Navigating progressively harder mazes.

**How do you play your game?**

Press WASD to move, navigate the frog sprite to the lily-pad. Using the help menu you can manually select a level you want to play. 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Did you use any games as inspiration?

**Comment by venny-dev** [comment]
Not really, just wanted to create a super long maze and decided to make it themed around frogs!

**Comment by LucasHT22** [comment]
Sorry for the delay! Nice! Did you manage to reach the end of the game?

**Comment by venny-dev** [comment]
I did, It is possible if you are wondering. Were you not able too?

**Comment by LucasHT22** [comment]
> I did, It is possible if you are wondering. Were you not able too?

I won once but was hard haha I think would be too hard on console, what about reduce the last levels?

**Comment by venny-dev** [comment]
Just uploaded a new file, switched the last level and added the big base as a bonus level. Let me know if that works. I can remove it fully if necessary or do anything other changes!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! What about "j" to restart?

**Comment by venny-dev** [comment]
Just added that!

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by LucasHT22** [comment]
@venny-dev did you use win sound from another game?

**Comment by venny-dev** [comment]
I found the idea for one but changed it a bit. Does it need to be redone?

**Comment by venny-dev** [comment]
I believe it was called "Amazing Maze" or something along those lines

**Comment by LucasHT22** [comment]
ok, will merge your PR

**Pull request merged**
