### PR TITLE
LittleSpringGeme

### PR DESCRIPTION
**Pull request by JonasHeilig**
The Player must go Home and can move Boxes

# Your checklist for this pull request

## Author name

**Author: Jonas Heilig**

## About your game

**What is your game about?**

The Player must go Home and can move Boxes

**How do you play your game?**
Press WASD to move, Press J to reset. You must move to the House
You must destroy the rocks with k to finish the level.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add more content to this game (especially code) to meet the bar for a Sprig device grant.

**Comment by JonasHeilig** [comment]
Add tow new Mechanics.
Destroiable Rocks and Boxes that only can moved by Cats

**Comment by JonasHeilig** [comment]
Should I add something else?

**Comment by grymmy** [comment]
> Should I add something else?

Looking at it now, sec...

**Comment by grymmy** [comment]
Gratz!  If you're a teenager, and you haven't already received one, please feel free to fill out [this form](https://sprig-order.hackclub.dev/) to receive a Sprig device grant of your very own!  Additionally, feel free to join Hack Club's Slack and share your creation in the #sprig channel!

**Pull request merged**
