### PR TITLE
the RUN

### PR DESCRIPTION
**Pull request by arielTROY**
Hello, my name is Ariel and I am 15 years old. My knowledge of programming comes from my father who is a programmer and he taught me. The game is basically like the crossy road mobile game and I worked for several hours to create a collision system! I really liked the project and waited a long time for something like this. Hopefully the game will make it to the gallery and I'll get the device so I can try it out

### CODE REVIEW

**Comment by LucasHT22** [comment]
Nice Ariel! could you complete this?

# Your checklist for this pull request

## About your game

What is your game about? 
> Example: Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
How to play your game?
> Example  : Press WASD to move, J to restart and K to toggle trails, Get A boxes (cyan) to A goals (green), Get B boxes (magenta) to B goals (red), Get normal boxes (gray) to either goal. (from [Sokoban plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
## Code
Check off the items that are true.
- [ ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

**Comment by LucasHT22** [comment]
I saw that it has some bugs... is there a victory screen?

**Comment by arielTROY** [comment]
Your checklist for this pull request
About your game
What is your game about?

its a game when you a bug that tries to cross the road without touching the cars
How to play your game?
w forward s backward
Code
Check off the items that are true.

 The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/). yes
 The game is placed in the in the [/games directory](https://github.com/hackclub/sprig/tree/main/games). yes
 The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo"). yes
 The game runs without errors. error that doesnt influence the gameplay
 The name of the file/game contains only alphanumeric characters, -s, or _s. yes
 The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
Image (If an image is used) the name is original
 The image is in the [/games/img directory](https://github.com/hackclub/sprig/tree/main/games/img). yes
 The name of the image matches the name of your file. Example: sokoban_plus.js -> sokoban_plus.png. yes
Thanks for PR!

**Comment by LucasHT22** [comment]
the error disappeared for me

**Comment by arielTROY** [comment]
great! what now?

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
