### PR TITLE
Eminent's Gateway

### PR DESCRIPTION
**Pull request by eminentquasar34**
# Your checklist for this pull request

## Author name

**Author:** EminentQuasar34

## About your game

**What is your game about?**
It's a maze game involving numerous levels, with a caveat that includes gateways. Gateways act like portals, instantly teleporting the main character from one location in the maze to another.

**How do you play your game?**

WASD to move.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

### CODE REVIEW

**Review by Cosmin-Mare — CHANGES_REQUESTED** [review]
Hey there! I like the concept behind your game, but I would love to see more levels and maybe some more mechanics, for example a death condition. Once you add these, please mention me and I'll re-review your game. Thank you for your submission!

**Comment by eminentquasar34** [comment]
Hi @Cosmin-Mare!
Thanks for the quick response. I have added more levels and a death option! Please take a look as soon as you can!

**Review by Cosmin-Mare — CHANGES_REQUESTED** [review]
Hey! I like the things you added, but it's still not 1m of gameplay and it's super easy to beat. pls try to make it more complicated and a bit longer. Thank you for your efforts!

**Comment by eminentquasar34** [comment]
@Cosmin-Mare Sorry, when testing the code I let the level start at 11. Now, that is fixed and the game begins at the first level. It should take longer than 1 minute to complete!

**Review by Cosmin-Mare — APPROVED** [review]
Thank you so much for taking the time to improve the game! It's awesome and you put in the effort to create and revise it!

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev/) and join our [online Slack community](https://hackclub.com/slack) to chat with other people making Sprig games.

**Pull request merged**
