### PR TITLE
Balloon(2)

### PR DESCRIPTION
**Pull request by LucasHT22**
my game is very simple, it's a balloon that goes through a maze. I did it with the intention of testing and understanding the sprig platform. The choice to be a balloon was due to being a "brand" of mine, whenever I'm learning a new language or tool I do something with balloons

### CODE REVIEW

**Comment by leomcelroy** [comment]
Thanks for the PR! Love that you have a signature test motif. 

Do you think you could make the levels a little more challenging? Right now the game is definitely in demo territory.  You could try just making the mazes more complicated or perhaps add some movable walls or something. It's often good if mechanics have trade-offs to them.

**Comment by LucasHT22** [comment]
@leomcelroy Includes other balloons as moving obstacles

**Comment by LucasHT22** [comment]
@leomcelroy I look forward to your feedback! :)

**Comment by leomcelroy** [comment]
Thanks for improving the game Lucas and for your other submission. The levels definitely feel more like puzzles now. As I mentioned on your other PR I love the playful feel to your games. Congrats on your Sprig I sent the link in the other PR I approved for the scooter game.

**Pull request merged**
