### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by thinkingjet**
# Your checklist for this pull request

## About your game

What is your game about? 
> Example: Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
Welcome to "Protect The Surfer"! In this exciting and challenging game, you'll take control of a surfer navigating through dangerous waters, trying to reach the safety of the shore without getting attacked by sharks.
How to play your game?
> Example  : Press WASD to move, J to restart and K to toggle trails, Get A boxes (cyan) to A goals (green), Get B boxes (magenta) to B goals (red), Get normal boxes (gray) to either goal. (from [Sokoban plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
Use the WASD keys to control your surfer's movement. As you make your way through the ocean, be on the lookout for sharks lurking in the water. If you get too close to a shark, it will attack and kill you, resulting in a game over.
## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
I thought it was nice of you to add a thank you to Hectic Hockey! people usually don't do that. but could you add a little more, maybe some powerups, to my game? to make little more different

**Review by thinkingjet — COMMENTED** [review]
added powerups but they dont work :\

**Comment by karamassie** [comment]
@thinkingjet if you want, come on over to our #sprig channel in our slack and we can help get this thru the gates and get you a sprig and a game in the gallery!

**Comment by LucasHT22** [comment]
> added powerups but they dont work :\

need help? I can help you:)

**Comment by thinkingjet** [comment]
@LucasHT22 yeah it would be great if you could help

**Comment by LucasHT22** [comment]
@thinkingjet call me on Slack, @ Lucas Honda

**Comment by thinkingjet** [comment]
@LucasHT22 could you check once again?

**Pull request merged**
