### PR TITLE
Super Efficient Bunny by Mihir S.

### PR DESCRIPTION
**Pull request by Mihirsur007**
# Your checklist for this pull request

## About your game

What is your game about? 

Move the Bunny to get the carrot in the least amount of steps. Every Carrot you get advances you to the next level. Try to get as many levels in 400 steps. This is my first time coding in javascript.
How to play your game?

Use WASD to move the Bunny around the field.
## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! Was the bunny supposed to disappear? image

**Comment by Mihirsur007** [comment]
> Good game! Was the bunny supposed to disappear? image

Hm. In all the times I tested the game, that never happened to me

**Review by Mihirsur007 — COMMENTED** [review]
I checked and tested the code, and It did not disappear for me.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Ok, and even after the end, should the rabbit walk?
image

**Comment by Mihirsur007** [comment]
> Ok, and even after the end, should the rabbit walk?
> image

Just Fixed that issue in my code. I also figured out that the bunny would disappear mid game if the carrot spawned on (0,0). So I edited the code to stop that too. Thanks!

**Comment by Mihirsur007** [comment]
> now it's crashing at 1 step
> 
>  Video.sem.titulo.Feito.com.o.Clipchamp.7.mp4

I tested the code a bunch of times right now and I am not sure why it glitched on the first step. I was able to fix the error that you were getting in the later part of the video. Sorry for all the glitches.

**Comment by Mihirsur007** [comment]
> no problem about the "glitchs" is part of learning.
> now it's giving that error:
> image

[https://streamable.com/vdfmkj](url)
I tested the code for the error you had and I wasn't able to get the same error. I attached a video of my test to this comment (I changed the steps to 100 just to make it quicker), and the bunny did not go past its 100 steps.

**Comment by leomcelroy** [comment]
Love the sprites!

I would add a check for the bunny in the movement code so that the error when a player keeps pressing buttons after the game is over doesn't come up. Maybe add an option to restart?

We have an automated test that button mashes thousands of times so it uncovers lots of bugs which can be hard to find otherwise. Fixing them helps make sure the game can run on your Sprig.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
hmm weird
image
Is the carrot weird for you too?

**Comment by Mihirsur007** [comment]
> hmm weird
> image
> Is the carrot weird for you too?

After a few tests I noticed that the carrots would duplicate sometimes if the whole screen wasn't cleared after the Bunny was in the same tile as the carrot. I edited the code to clear the whole screen. I also was able to fix the errors given by hitting the keys after game over by moving the Bunny to 0,0 and not moving the Bunny or advancing any steps if the steps left is less than or equal to 0. Hopefully these should be the last of the bugs. Thanks!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
