### PR TITLE
Add really_really_bad_music_maker

### PR DESCRIPTION
**Pull request by secondary-smiles**
## RRBMM

**Shav (secondary-smiles)**

## About

**Explore Sprig's sonic capabilities by influencing a simple generative music algorithm.**

## How to play

**start/stop music playback**: `k`
**cycle sound (sine, sawtooth, etc.):** `l`
**shift octave up**: `i`
**shift octave down**: `j`
**choose note scale (each key is a different scale)**: `w` `a` `s` `d`

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by secondary-smiles** [comment]
@LucasHT22 Nope, frequencies themselves can't damage speakers, the only thing that can is the actual physical voltage provided to the speakers (i.e. volume) which Sprig doesn't provide an interface for.

The only thing this can damage is my ears :]

**Comment by LucasHT22** [comment]
Right haha 

where did you hear about sprig?

**Comment by secondary-smiles** [comment]
Well I first read about Hack Club in a GitHub newsletter, and that lead to a really enjoyable spiral of checking out all the cool things they offer to people like me.

It was a bit intimidating starting out trying to introduce myself to this big community/network, so I figured that after joining the Slack, this would be a good project to work on since I do love game/interactive programming.

**Review by LucasHT22 — APPROVED** [review]
I also heard about HackClub in a GitHub Newsletter

Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
