### PR TITLE
Something

### PR DESCRIPTION
**Pull request by kaptainkoala**
This was my first time coding and I enjoyed learning about some of the functions and logic of it. The game is very basic, to the point where it might not be considered a game. I learned a lot from coding it, and my favorite part was making the sprites.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for the PR! Glad to hear you liked the Sprig :)

**Comment by LucasHT22** [comment]
How about adding more functions? If you need help, you can call me :)

**Comment by LucasHT22** [comment]
you mentioned that you liked making the sprites, you will probably like pixel art, it's the principle of sprites, see: https://www.pixilart.com/

**Comment by SamDev-7** [comment]
@kaptainkoala You're really close to getting the game merged, don't give up! 
Let us know if you need any help!

**Comment by leomcelroy** [comment]
It seems you need to make more changes before you're ready to get your Sprig. I'm going to close this PR for now. Feel free to reopen if you want to continue working on your game.

**Pull request closed without merging**
