### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Roizor**
# Your checklist for this pull request

## About your game

What is your game about? 
> This game is a platformer with interesting mechanics. There's movable boxes to help you complete a level. You collect coins until meeting the end (FIN screen)

How to play your game?
> WASD for up left down right (respectively), make it to the green line while collecting all coins in the level. Moving boxes moved by pushing them. Coins collected by moving **from the left, right, or bottom**. You cannot get coins by going on top of them

## Code
Check off the items that are true.
- [X] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
wow! hard game! could you add a background?

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

out of curiosity, how did you meet sprig?

**Comment by Roizor** [comment]
> Looks good to me! Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> 
> out of curiosity, how did you meet sprig?

i volunteered at a youth code jam, and one of the actual employees i spoke to at the end is part of hack club and recommended hack club, from there when i was joining the slack channel, in the active projects was this line: `#sprig: get a free game console by making a fun game`

**Comment by LucasHT22** [comment]
oh, nice!

**Pull request merged**
