### PR TITLE
Half_Untitled_Lost - checklist for pull request

### PR DESCRIPTION
**Pull request by TabDD**
# Your checklist for this pull request
game name:
Half_Untitled_Lost

## Author name

TabDD

## About your game

pushing boxes with a basic combat, encounter, and attack system.

**How do you play your game?**

W A S D to move, and I J K L to attack when in an encounter

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used) (image was not used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Comment by TabDD** [comment]
> Thanks for the PR! Where did you hear about Sprig?

CS Principles AP teacher. A cool platform.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! What about "J" to restart?

**Comment by TabDD** [comment]
> Nice! What about "J" to restart?

I unfortunately did not add a restart function.

**Comment by LucasHT22** [comment]
> > Nice! What about "J" to restart?
> 
> I unfortunately did not add a restart function.

But what about add one? :)

**Comment by TabDD** [comment]
> > > Nice! What about "J" to restart?
> > 
> > 
> > I unfortunately did not add a restart function.
> 
> But what about add one? :)

yes. How do I add recent changes?

**Comment by LucasHT22** [comment]
Go to `Files changed` > `...` > `edit` :)

**Comment by TabDD** [comment]
> Go to `Files changed` > `...` > `edit` :)

changes made

**Comment by LucasHT22** [comment]
Nice! did you beat your game?

**Comment by TabDD** [comment]
> Nice! did you beat your game?

yes

**Comment by Sheepy3** [comment]
closing this pull request as it seems inactive. feel free to ping me to have it re-opened and merged!

**Pull request closed without merging**
