### PR TITLE
Snake Feast

### PR DESCRIPTION
**Pull request by shyakachaste**
# Your checklist for this pull request

## Author name

**Author:**

chaste

## About your game

**What is your game about?**

Snake Feast is about controlling a snake to eat oranges while avoiding obstacles and boundaries.

**How do you play your game?**

Press WASD to move the centipede. Eat oranges (O) to grow longer. Avoid obstacles (X) and boundaries (W). Press I to restart the game after a game over.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by shyakachaste** [comment]
Hye@grymmy ,did i make a good game?

**Comment by grymmy** [comment]
> Hye @grymmy ,did i make a good game?

Reviewing right now!

**Comment by shyakachaste** [comment]
yeah,cool

**Comment by grymmy** [comment]
Neat!  Good job.

If you're a teen, you can submit [this form here](https://sprig-order.hackclub.dev/) and receive a Sprig device if you haven't already gotten one.  Feel free to share your game in the #sprig channel in Hack Club's Slack, too!

**Comment by shyakachaste** [comment]
Thanks

**Pull request merged**
