### PR TITLE
Raincatch

### PR DESCRIPTION
**Pull request by ShutBaton**
# Your checklist for this pull request

## Author name

**Author:**

A Malladi

## About your game

**What is your game about?**

Catch the rain that drips from the sky in your bucket! You need to drink _something_ right?

**How do you play your game?**

A and D to move your bucket and catch the rain! Your goal is to get as high a score as you can. use the I key to reset your score.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for PR! Where did you hear about Sprig?

**Comment by ShutBaton** [comment]
> Thanks for PR! Where did you hear about Sprig?

Hi! I heard about it from a friend and I found it very interesting, so i decided to give it a go since i already had some JS knowledge.

**Comment by LucasHT22** [comment]
Sorry me for slow answer! Is it endless, right?

**Comment by ShutBaton** [comment]
> Sorry me for slow answer! Is it endless, right?

Yes!

**Review by LucasHT22 — APPROVED** [review]
Happy new year! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by ShutBaton** [comment]
Hi Lucas! Can I claim my sprig?

**Comment by ShutBaton** [comment]
> Happy new year! Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> 
> Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Thanks so much! Happy new year!

**Pull request merged**
