### PR TITLE
tag your buddy

### PR DESCRIPTION
**Pull request by abjectbrake**
# Your checklist for this pull request

## Author name

**Author: Aadarsh Jonnalagadda**

 

## About your game 

**The game is about two characters who are separated. The goal is to unite them again by moving the black character towards the red one.**

**Press WASD to move the black character around. You have to go around the blue characters and reach the red character. Press J to reset the current level and press I to reset the entire game.?**

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

Image was not used ^^^

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR! Could you confirm your game's  and author's name?

**Comment by abjectbrake** [comment]
The author’s name is Aadarsh Jonnalagadda and the game’s name is “tag your
buddy”

**Comment by LucasHT22** [comment]
Right, what about reduce a bit this level? 
image

**Comment by abjectbrake** [comment]
I can reduce it but it was supposed to be kind of an Easter egg in the game
where you can go through a shortcut instead of going all the way around.

**Comment by abjectbrake** [comment]
Hey, I reduced the level a bit like you said. Here is the link: [https://sprig.hackclub.com/share/h2nJ2aCGWsORUcMANcfc](url)

**Comment by LucasHT22** [comment]
Great! Could you go to `Files changed` > `...` > `edit` to update the file here?

**Comment by abjectbrake** [comment]
Okay sure

**Comment by abjectbrake** [comment]
Done! I updated the code.

**Comment by leomcelroy** [comment]
There are not too many choices to make in the mazes. I think the game could be improved greatly by adding some puzzle element. I can tell you put effort into it though. Congrats, you can order your Sprig here: https://sprig-order.hackclub.dev/

**Comment by abjectbrake** [comment]
Thank you so much!

**Pull request merged**
