### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by anvayajmera**
Among us game by Anvay

# Your checklist for this pull request

## Author name

**Anvay Ajmera:**

## About your game

**My game takes an among us character, and places it in a world where you have to move to survive fire bombs! If the among us character gets hit, the game restarts.**

**How do you play your game?**

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)
(I do not use an image)
- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by anvayajmera** [comment]
This is my actual pull request, I forgot to fill out the information in the last one so I closed it.

**Comment by anvayajmera** [comment]
Hi, @grymmy I don't understand what happened... did the code not work?

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add one or two novel game mechanics to this game to bring it up to the bar required for a Sprig device grant.

**Comment by anvayajmera** [comment]
@grymmy Thank you I added more game mechanics

**Comment by grymmy** [comment]
Good job!  If you're a teen, and you haven't already received one, please fill out [this form](https://sprig-order.hackclub.dev/) to receive your Sprig device!  Also, feel free to share your creation with others in Hack Club's #sprig Slack channel!

**Pull request merged**
