### PR TITLE
FlyMyKite

### PR DESCRIPTION
**Pull request by TiarkRompf**
## Author name

**Author:** Julius Rompf (8yrs)

## About your game

**What is your game about?**

Fly a kite, collect yellow gems. The wind speed increases with every 10 gems collected, making steering more difficult.

**How do you play your game?**

- J: Take off and fly higher
- D: Fly lower

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

No image used

### CODE REVIEW

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Hiii, 

Congrats on your game, it is super impressive that you made this game at such an early age!

However, the game is somewhat laggy in my browser, and the sprig's hardware isn't powerful enough to run your game as of now. Could you make optimizations so the game runs more smoothly?

**Comment by alx-alexpark** [comment]
It also appears the plagiarism check failed, likely due to the copied pixel library. Could you add more original code or make enough changes to the library so it passes the check?

**Comment by TiarkRompf** [comment]
Certainly! We'll keep revising it. In Safari on an M2 MacBook it runs pretty smoothly, not quite sure about other setups. Does Sprigenstein3D run smoothly on your browser/machine?

**Comment by TiarkRompf** [comment]
Hi @alx-alexpark! 

We made a bunch of changes, including setting a different iteration delay in Chrome (which was the apparent source for sluggishness), and rewriting the pixel engine implementation. Happy to address any other feedback you might have.

Best,
- Julius (and Tiark)

**Review by alx-alexpark — APPROVED** [review]
Congrats on your game :) It's super impressive you made this at such a young age.

If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
