### PR TITLE
Blob Runner

### PR DESCRIPTION
**Pull request by BrightTheBackpack**
# Your checklist for this pull request

## Author name

**Author:**

Bright Li
## About your game

**What is your game about?**
It's a platformer and maze following a little blob.

**How do you play your game?**
WASD to move, j to restart, i to skip a level. Reach the very right side of the screen to progress to the next level. 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
       -There is an error when you beat or lose the game, but it does not affect playability
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!
I triple-dog dare the reviewer to beat the game in under 10 minutes

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Hey! Thanks for the PR! @grymmy , want to review this one too?

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! I'll continue with this review, where did you hear about Sprig?

**Comment by BrightTheBackpack** [comment]
I first heard about it at the Hack OC hackathon, and later me and my friend started planning a hack club for our school, I learned more about it

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
WOW nice! Did you use any game as inspiration?

**Comment by BrightTheBackpack** [comment]
not really, just inspired by other platformers i guess

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right:) What about increasing gravity delay?

**Comment by BrightTheBackpack** [comment]
> Right:) What about increasing gravity delay?

I think some levels might become easier than I would like if I increased the gravity delay...

**Comment by LucasHT22** [comment]
Hmmm I understand but my fear is that it is impossible on the console, but if you really want to keep, lmk

**Comment by BrightTheBackpack** [comment]
lets keep it for now. If it gets to difficult on the console, i can change it

**Comment by LucasHT22** [comment]
Did you manage to win the game?

**Comment by BrightTheBackpack** [comment]
i've won twice, took about 30 minutes each time

**Comment by LucasHT22** [comment]
My apologies for the delay, could you wait until tonight? I'm travelling, but I'm back this night and want to play your game with more time:)

**Comment by BrightTheBackpack** [comment]
sure!

**Comment by BrightTheBackpack** [comment]
just beat it with a new record of 8 minutes and 55 seconds!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay! My flight delayed. But could you send a screenshot of the end of your game?

**Comment by BrightTheBackpack** [comment]
Anyway to play my game on mobile?

**Comment by BrightTheBackpack** [comment]
I'm kinda in new york and don't have my laptop

**Comment by LucasHT22** [comment]
yes, just open this link https://sprig.hackclub.com/share/GQYbBKmcgTue2ZSWNJ2w :)

**Comment by BrightTheBackpack** [comment]
I can't seem to get to the win stage on mobile. It was working on my computer though

**Comment by LucasHT22** [comment]
I can wait until you get your computer:)

**Comment by BrightTheBackpack** [comment]
I think I found the problem. I think I might  have uploaded the wrong version of the game. I added a commit that should fix it

**Comment by BrightTheBackpack** [comment]
Can you send the updated share link? Or is it thr same one

**Comment by LucasHT22** [comment]
Here is: https://sprig.hackclub.com/share/grAWI0fWxvrAKkN3bfzQ! btw - merry christmas!

**Comment by BrightTheBackpack** [comment]
sorry for the late response.  Here are some screenshots of the end.
image
sprig_1

If you think it's still to difficult, I can make some changes to the map to make it easier.

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by BrightTheBackpack** [comment]
Tysm!

**Pull request merged**
