### PR TITLE
dodge the pumpkins!!!

### PR DESCRIPTION
**Pull request by DefNotEv**
I made this at Haunted House TO about 9 months ago and forgot to make a pull request 😭. 

# Your checklist for this pull request

## Author name

**Author:** Ev

## About your game

**What is your game about?** You are a blob and you need to dodge pumpkins. 

**How do you play your game?** A and D to move. Don't get hit by the pumpkins

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add a game mechanic or two to justify a Sprig device grant.

**Comment by grymmy** [comment]
Looked at this today, still waiting on author to respond.

**Comment by DefNotEv** [comment]
Hi sorry, will work on it

*Evelyn Wong*
Grade 11 STEM Student
***@***.*** | (647)-636-4438 | Linktree
<https://linktr.ee/evelynhzswong>

**Comment by grymmy** [comment]
Looked at this today - still awaiting changes from the author.

**Comment by grymmy** [comment]
Looked at this today, still awaiting changes from the author.

**Comment by grymmy** [comment]
Looked at this today, still awaiting changes from the author.

**Comment by grymmy** [comment]
I am closing this PR due to inactivity.  Please feel free to re-open this PR if you want to move it towards merging and a Sprig device grant reward.

**Pull request closed without merging**
