### PR TITLE
CaveGame

### PR DESCRIPTION
**Pull request by Al0102**
# Your checklist for this pull request

## Author name

**Author: AlexL**

## About your game

**A simple puzzle adventure about caving, collecting gold, and fighting monsters**

**How do you play your game?**

**CONTROLS
WASD - Movement
I - Attack/Mine
J - Restart Game
K - Reset Level
L - Buy Item
**

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by Al0102** [comment]
I learned about it from the hack club email newsletter!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
nice! sorry for my delay, I love dungeon games, did you use any game for inspiration?

**Comment by Al0102** [comment]
Haha no worries, as long as I didn't make a mistake lol. I love dungeon games too! Tried to take inspiration from the early Zelda games and things like POWDER.

**Comment by LucasHT22** [comment]
Nice! Did you win your game? It's hard haha

**Comment by Al0102** [comment]
Haha yeah, it took me several tries though. I might edit or add more later if I have the time, this was my first time making a game but it was fun!

**Review by LucasHT22 — APPROVED** [review]
You can update anytime by making another PR! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by Al0102** [comment]
Thanks!

**Pull request merged**
