### PR TITLE
Add Sprig Boy!

### PR DESCRIPTION
**Pull request by KaiDevrim**
## Sprig Boy!

**Author: Kai Devrim**

## About your game

**Play as the lonely sprig boy trying to achieve a trophy to present to his parents but can't seem to reach it easily, maybe his ability to create boxes to the left and right of him! Solve many puzzles using a unique play style inspred by the Nintendo game, BoxBoy!**

## How do you play your game?

**Press WASD to move, W is jump but there is gravity. Use J to create a box to your left and L to create a box to your right. The goal is to get to the trophy at the end of the level. The boxes can move and are affected by gravity.**

## Code

- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! How about making gravity a little weaker?

**Comment by KaiDevrim** [comment]
@LucasHT22 Changed the gravity! Should be easier now!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
good:) how about j for restart?

**Comment by KaiDevrim** [comment]
J is already reserved for creating a box on the right side, I set the restart button to I instead! Anyways hopefully that is all that is needed 🤞 @LucasHT22

**Comment by LucasHT22** [comment]
oh yeah my bad, i meant i:)

**Comment by LucasHT22** [comment]
hmm I think you forgot the bitmaps when making the changes

**Comment by KaiDevrim** [comment]
oh woops idk how that happened lol

**Comment by KaiDevrim** [comment]
oh I probably copied and pasted rather than downloaded

**Comment by KaiDevrim** [comment]
ok added the bitmaps back in, HOPEFULLY it is good

**Review by LucasHT22 — APPROVED** [review]
Perfect! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by KaiDevrim** [comment]
I would love to post it there, if only I wasn't banned :/ ! Don't worry I wil be back soon enough!

**Comment by KaiDevrim** [comment]
Btw the note at the end of the form is incorrect

**Comment by LucasHT22** [comment]
> Btw the note at the end of the form is incorrect

What exactly?

**Comment by KaiDevrim** [comment]
it says mid marchThanks,Kai McCormick

**Comment by LucasHT22** [comment]
Thanks for the report!

**Comment by LucasHT22** [comment]
Could you send a screenshot of it?

**Comment by KaiDevrim** [comment]
I don't think it really matters at this point

**Comment by LucasHT22** [comment]
it's because checked and everything seems to be ok, anyway thanks!

**Pull request merged**
