### PR TITLE
Add 'Mathematical Meteorite' game

### PR DESCRIPTION
**Pull request by arashnrim**
## About your game

**What is your game about?**
The game involves you as the player guiding a falling meteorite to the proper campfire. The game revolves around quick mathematical calculations, with each campfire containing either a right or wrong answer.

**How to play your game?**
A and D are used to guide the meteorite left and right respectively. When the game ends or at any time, I can be pressed to restart the game.

## Code
**Check off the items that are true.**
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
    - I try my best to prevent any direct similarity with other projects. I made this game without referencing the gallery, so there may be close similarities that I haven't known!
- [x] The game runs without errors.
    - To the best of my ability, I've made sure that there are little if not no errors. Let me know if you've encountered one. :) 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

Thank _you_ in advance for the review + hard work into Sprig!

### CODE REVIEW

**Comment by Arpan-206** [comment]
The game is stuck in some kind of loop and seems to be operating without input after 2 rounds.

**Comment by arashnrim** [comment]
🥲 thank you for pointing it out! Will have another look and let you know again.

**Comment by arashnrim** [comment]
Don't ask how buggy the previous version was. What about now? 😛

**Comment by Arpan-206** [comment]
Works like a charm! Also fantastic game!

**Review by LucasHT22 — APPROVED** [review]
Thanks @Arpan-206 for the review! 

@arashnrim Fun! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
