### PR TITLE
Add sprite picker and boolean checkbox editor inline widgets, improve CodeMirror integration

### PR DESCRIPTION
**Pull request by Merlin04**
This PR upgrades the editor to CodeMirror 6, allowing for easier editor plugin development. The biggest change is that the editor bundle is now generated using Rollup through running `yarn generate-cm`.

### CODE REVIEW

**Comment by Merlin04** [comment]
Actually I think there's a better way to do this - hold off on merging for now

**Comment by Merlin04** [comment]
Ok, I improved it and I'm ready for review

**Comment by Merlin04** [comment]
Cleaned up some merge conflicts, I think some stuff will have broken so I'll make fixes tomorrow

**Comment by Merlin04** [comment]
Ok, should be ready to merge!

**Comment by Merlin04** [comment]
Never mind found a bug

**Comment by Merlin04** [comment]
Ok this time it is actually ready to merge

**Comment by Merlin04** [comment]
It's still a bit glitchy sometimes though, I have no idea why

**Comment by Merlin04** [comment]
@leomcelroy sorry to ping you but could you review this PR? I want to make sure it gets merged before things on the main branch get too far away and it becomes really hard to resolve the conflicts/update things

**Comment by leomcelroy** [comment]
@Merlin04 No worries about the ping. This is a really interesting feature but I'd like to test how this changes the UX before pushing to main. I noticed a few little bugs myself like this:

Screen Shot 2022-02-08 at 10 13 05 PM

**Comment by leomcelroy** [comment]
Not relevant after migrating to Sprig but this was useful work because we integrated this sort of functionality into the new editor.

**Pull request closed without merging**
