### PR TITLE
Space Odyssey

### PR DESCRIPTION
**Pull request by CondolentFire10**
# Your checklist for this pull request

## Author name

**Author:**

CondolentFire10 - Devon S.

## About your game

**What is your game about?**

An exciting spaceship flying simulator in which you must avoid crashing into asteroids or the boundary, and survive as long as possible!

**How do you play your game?**

Use J to start the game (or restart after death), and use wasd to move the spaceship around.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! But I get stuck on top:
image

**Comment by CondolentFire10** [comment]
Oh my goodness thank you so much for noticing!  I mistakenly uploaded the incorrect file version.  I will attach the correct one.

**Comment by CondolentFire10** [comment]
I heard about it from a friend at school who is hosting a hack club during lunches.

**Review by LucasHT22 — APPROVED** [review]
Nice! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
