### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AnDevix**
This the which I have made with the help of my friends and we really worked hard on it. This game is about Flipping a Coin like you do in real life but the only difference is that you can flipping either on your Sprig or on your computer. With this you can play game like truth and dare like based on what you get you can play truth or dare with you friends.

## Author name

**Author:** Naresh Kumar

## About your game

**What is your game about?**

So this game is all about flipping a coin like you do in the real life but the twist is that this game will be used to play truth and dare with the help of Sprig and have fun with your friends . If you get heads you have to do a dare and if you get a tail you have to tell a truth

**How do you play your game?**
so basically after you have successfully uploaded this code on you computer or Sprig you have to press 'S' ad after that you will randomly get a result in the form of head or a tail now based on the result you have give each other the dares and altogether have fun with the Sprig console

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by AnDevix** [comment]
you do check out our game we have really worked hard on it

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Out of curiosity, did you use any game for inspiration?

**Comment by AnDevix** [comment]
This just for fun and we can use Sprig in parties and even spread the idea of Sprig among friends and encourage them to join hackclub and enhance their game development skills

**Comment by LucasHT22** [comment]
Nice, but did you use any part of another game?

**Comment by AnDevix** [comment]
No actually When I was in my 9th Standard I learned a Java function i.e. Math.random() so i made use of that function and made a quite simple and fun program

**Comment by LucasHT22** [comment]
Could you add more in your game? :)

**Comment by AnDevix** [comment]
like you want more features and my program to do something more fascinating

**Comment by LucasHT22** [comment]
just add more features:)

**Comment by AnDevix** [comment]
like what kind of features

**Comment by karamassie** [comment]
hi ! @AnDevix , can you DM me in Slack pls? @kara

**Comment by LucasHT22** [comment]
> like what kind of features

Whatever you want:) Also please DM kara:)

**Comment by kara** [comment]
Hi can you please stop @ pinging me  (I'm username kara) - thanks!

**Comment by Sheepy3** [comment]
Closing this PR due to inactivity. Please let me know if you'd like this reopened.

**Pull request closed without merging**
