### PR TITLE
PR template

### PR DESCRIPTION
**Pull request by LucasHT22**
open for suggestions!

thread:
https://hackclub.slack.com/archives/C02UN35M7LG/p1666373256254869

repo:
https://github.com/LucasHT22/pr_template

test this:
https://github.com/LucasHT22/tests_pr

Original idea:
@SamDev-7

### CODE REVIEW

**Comment by Omay238** [comment]
Should there be something that says "the game name is not the same as others"

**Comment by LucasHT22** [comment]
yeah, there was even the "maze" problem

**Comment by LucasHT22** [comment]
and now? What do you think?

**Comment by Omay238** [comment]
I think that's all the problems we've encountered.

**Comment by LucasHT22** [comment]
I agree

**Comment by SamDev-7** [comment]
> Should there be something that says "the game name is not the same as others"

I recall Leo saying (in the Slack) that that's fine, just as long as the code is different. Many people may only be able to make beginner games.

**Comment by LucasHT22** [comment]
@SamDev-7 It's to prevent the same from happening with "Maze" https://github.com/hackclub/sprig/commit/32430f4cc0d6b92124baf69320de62716d12adb7

**Comment by SamDev-7** [comment]
I read it wrong, makes sense now. Looks great!

**Comment by Omay238** [comment]
should this be merged?

**Comment by LucasHT22** [comment]
I'm waiting for Leo's opinion

**Comment by LucasHT22** [comment]
hey @leomcelroy 
 I'd love for you to review this PR :)

**Comment by leomcelroy** [comment]
Looks good to me! Thanks for your patience.

**Comment by LucasHT22** [comment]
ok!

**Pull request merged**
