### PR TITLE
Divine_Tree_Man_Saves_A_Forest

### PR DESCRIPTION
**Pull request by RohanPani**
# Your checklist for this pull request

## Author name

  Author:  Rohan Pani

## About your game

**What is your game about?**

My game is about you, a divine tree man, who's goal is to save his forest form fires and fungus. If you can make it to the end, the Zire absorbs the evil force trying to destroy the forest, the Ezir. Everything is normal after Ezir is eradicated.

**How do you play your game?**

WASD to move, i to reset
Push the fungus into the fire
Push Zire onto suspicious spots(looks like wall but the character can walk over it) to delete parts of wall
Push suspicious walls with the Zire (looks like wall, but can be pushed by the Zire. Only one can be pushed at a time by the Zire)

The last level is super difficult, but if you know the mechanics it is easy. Dot fall for the 3 fake exits, only go through the colorful block to finish the game.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add one or two novel game mechanics to meet the bar for a Sprig device grant.

**Comment by RohanPani** [comment]
👍

**Comment by RohanPani** [comment]
I just realized that I forgot to set the level back to zero, It was set to
level 5. I there anyway you could switch it back or should i resubmit?.
Right under all the map bitmaps, it says setMap(level[5]). could you switch
that to 0? Thank you.

**Comment by RohanPani** [comment]
this is the fixed game https://sprig.hackclub.com/~/b1PNZ7iIxNlfmAA3g6V8

**Pull request closed without merging**
