### PR TITLE
Building a Snake Game

### PR DESCRIPTION
**Pull request by souvikpal2000**
Review & accept my PR

### CODE REVIEW

**Comment by souvikpal2000** [comment]
snake_game

Hello,
I am Souvik Pal, a youngster who has built a game by using sprig game editor. The game is based on our childhood  **CLASSIC SNAKE** game which we used to play in arcades. The controls are very simple, only use **w**, **s**, **a**, **d** keys to move the snake **up**, **down**, **right**, **left** respectively.

I really enjoyed while making this game & most important thing I learnt about the inbuild functions of Sprig Language which is really **_AMAZING_**.

Review & Accept my PR.

**Thank You.**

**Comment by souvikpal2000** [comment]
Review my PR

**Comment by leomcelroy** [comment]
Although we already have Snake in the gallery it looks like this is implemented differently so it's welcome addition. The game looks simple but polished which is an aesthetic I personally like a lot. Thanks for the PR.

If you're a teen congrats on your Sprig which you can get here: https://sprig-order.hackclub.dev/

**Comment by souvikpal2000** [comment]
Thanks, I created new PR where I have added image for my game.

**Comment by souvikpal2000** [comment]
> Although we already have Snake in the gallery it looks like this is implemented differently so it's welcome addition. The game looks simple but polished which is an aesthetic I personally like a lot. Thanks for the PR.
> 
> If you're a teen congrats on your Sprig which you can get here: https://sprig-order.hackclub.dev/

Thanks, I have created a new PR where I have added image for my game.

**Pull request merged**
