### PR TITLE
Dragon Rush

### PR DESCRIPTION
**Pull request by daSeaTurtle**
# Your checklist for this pull request

## Author names

**Authors: Xhaiden, Aaron, and Brenden**

## About your game

**What is your game about?**
Our game is Sokoban-like game with a cute dragon player that pushes a flower to a green spot.

**How do you play your game?**
To play the game, you must use WASD to move a dragon that must push a flower to a green spot. Avoid red at all costs. Make sure to push crates out of the way, open doors by picking up keys, and use portals for difficult situations. The levels get progressively harder. Some other controls are "i" for information, like coordinates and level number, and "j" to restart the level if you get stuck.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
great bitmaps and great game! 3rd map seems to be impossible to solve, could you tell me how to solve it?

**Comment by daSeaTurtle** [comment]
Hi! I just recorded a video that shows how to beat every level. For one of the levels, I messed up, but I used 'j' to restart the level. After that, I succeeded.
[Screen recording 2023-07-14 9.32.18 AM.webm](https://github.com/hackclub/sprig/assets/76405735/3bd466ae-fe1a-4e7f-829b-17f129dc6e1a)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks! Looks like there's an error at line 507 `TypeError: Cannot read properties of undefined (reading 'x')` , do you know how to solve it? If youb need help, lmk:)

**Comment by daSeaTurtle** [comment]
Yeah, we noticed that error. We didn't think much of it because we couldn't find any way that it affected the gameplay. We also did not understand why it was happening. It would be great if you could help us fix it, unless there is no need to.

**Comment by LucasHT22** [comment]
as it is not an error that affects the game itself, what about I add a wip tag to your game and we continue via Slack talking about and how to solve?

**Comment by daSeaTurtle** [comment]
Sure, sounds good to me!

**Review by LucasHT22 — APPROVED** [review]
Post about it on sprig channel, so anyone can help! Anyway, Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by daSeaTurtle** [comment]
I ordered the sprig, and I will ask in slack about the error. Thanks so much!

**Comment by daSeaTurtle** [comment]
We fixed the error, so now the game is completely functional with no errors.

**Comment by LucasHT22** [comment]
> We fixed the error, so now the game is completely functional with no errors.

Could you make another PR with fixed version? Thanks

**Comment by daSeaTurtle** [comment]
Ok

**Comment by daSeaTurtle** [comment]
I created another pull request with the fixed version.

**Pull request merged**
