### PR TITLE
sprig machine

### PR DESCRIPTION
**Pull request by Omay238**
After about a month, 3 programs since the beginning of this project, and probably about 20 hours of work, it is finally done.

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
one of the biggest codes made in Sprig (if not the biggest)!

**Comment by kognise** [comment]
awesome art! so much code! uh... what's the objective? i moved the blue thing to the level of the red thing, ran the simulation, and it ate the red thing and nothing happened.

**Comment by Omay238** [comment]
I spent a long time on it lol.

**Comment by Omay238** [comment]
Just press k again. It brings you to the next level. There are 16 levels for now.

**Comment by Omay238** [comment]
10 more levels done, i have yet to upload them. its on my personal computer, i can only use school computer right now.

**Comment by kognise** [comment]
> Just press k again. It brings you to the next level. There are 16 levels for now.

Awesome, thank you! It would be nice to document this since J doesn't automatically bring you to the next level.

I now can't get past level 4... the green block seems to be creating a wall in front of it and then nothing else happens. At that point I can't move any blocks, and a bit later the game freezes.

**Comment by Omay238** [comment]
Yeah, if you put the green part in front of the yellow block, then it will make more yellow blocks in front of it. I'm probably going to put a link to a walkthrough video or a description on what the blocks do.

**Comment by Omay238** [comment]
Better docs now.

**Comment by Omay238** [comment]
Also, that means the game is running. If it is running, you have to reset it before anything will happen.

**Comment by LucasHT22** [comment]
the name of these commits haha

**Comment by Omay238** [comment]
should i use this image as the thumbnail?
sprig_machine

**Comment by LucasHT22** [comment]
yes!

**Comment by LucasHT22** [comment]
Very good game!

**Comment by LucasHT22** [comment]
did you manage to complete all levels?

**Comment by Omay238** [comment]
I can complete all the levels, but I just noticed a bug that I've seen before, and forgot about.

**Comment by LucasHT22** [comment]
which bug?

**Comment by Omay238** [comment]
Here: it should not generate into a wall.
[Screen recording 2022-10-21 3.03.15 PM.webm](https://user-images.githubusercontent.com/70179858/197288374-6b4ec748-4bce-4cc8-99c9-a5a1d7796801.webm)

**Comment by Omay238** [comment]
I fixed it.

**Comment by LucasHT22** [comment]
deleted the video?

**Comment by Omay238** [comment]
What do you mean?

**Comment by LucasHT22** [comment]
image

**Comment by Omay238** [comment]
Oops. Yeah, I didn't have that in my sprig editor. Only in github.

**Comment by Omay238** [comment]
is fixed

**Comment by LucasHT22** [comment]
the name of this commit haha

**Comment by LucasHT22** [comment]
for me, it's all right. can i merge?

**Comment by Omay238** [comment]
I just wanted feedback. I'll merge it now.

**Pull request merged**
