### PR TITLE
MazeMission

### PR DESCRIPTION
**Pull request by Caitlin925**
## MazeMission

**Author:** CaitlinOchuwa

## About your game

This game is about getting your character, named orange, to the end of all of the mazes. Along the way there are coins orange must collect which increase his score and get him out of the mazes.

## HOW TO PLAY
'WASD' to control your player
'I' to reset the game

The goal is to get to the door to escape the mazes. However, in order to maximize your score and successfully complete the run, you must collect all of the coins. But, the red coins are known as AntiCoins and actually hurt your score. Collect coins, avoid the AntiCoins, and navigate through the mazes to become the ultimate maze master!

## Code

- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by grymmy** [comment]
Please add a new mechanic to this game to differentiate it sufficiently for rewarding a Sprig device grant.

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add a new mechanic to this game to differentiate it sufficiently for rewarding a Sprig device grant.

**Comment by grymmy** [comment]
Looked at this today, still awaiting changes from the author.

**Comment by grymmy** [comment]
Hmmm seems there's activity here!  Checking it out, hi @Caitlin925 !

**Comment by Caitlin925** [comment]
Hi!!

**Comment by grymmy** [comment]
> Hi!!

NOW I am looking :)

**Review by grymmy — CHANGES_REQUESTED** [review]
I remember the graphics on this game from another submission iirc.  Was this remixed from another game, by chance?  How was it differentiated?

It is possible it was submitted but not landed, but I need some sort of understanding on my side here before granting a Sprig reward.

**Comment by Caitlin925** [comment]
Yes, so I originally submitted this game on July 8th, however, upon further review, I received a message from you on July 22nd telling me that I need to add a new mechanic to my game to differentiate it more. So today, I re-uploaded my game, MazeMission, with the new mechanic being the AntiCoins that makes the game a little more complex. I hope this clears up the confusion, thank you!

**Comment by grymmy** [comment]
Congratulations!  If you're a teenager, and if you haven't already received one, please fill out [this form](https://sprig-order.hackclub.dev/) to receive a Sprig device!  Also, free free to join Hack Club's Slack and share your creation in the #sprig channel!

**Pull request merged**
