### PR TITLE
catch the pink star

### PR DESCRIPTION
**Pull request by Raulmontano4**
# Your checklist for this pull request

## Author name

**Author:** Raul montano 4

## About your game

**What is your game about?** my game is abot catching a pink star fish, and to avoid the bombs, and to get a high score.

**How do you play your game?** you press " A " or " D " to move left or right and to try and catch the star.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! What's the name of your game?

**Comment by Raulmontano4** [comment]
Catch the pink star

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Raulmontano4** [comment]
I'm pretty sure, it's something like that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LucasHT22** [comment]
Sorry for the delay! So could you rename the file? You can do it going in `Files changed` > `...` > `edit` :)

**Comment by leomcelroy** [comment]
Thank you for sharing your project! I think this game needs some refinement. It never seems to end and the music can become quite chaotic fairly easily. 

I'm going to close this PR for housekeeping but feel free to resubmit when you are ready.

**Pull request closed without merging**
