### PR TITLE
just added my new game yay

### PR DESCRIPTION
**Pull request by cott3**
# Your checklist for this pull request

## Author name

Efe Özülkü (efeoz)

## About your game

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by cott3** [comment]
just realized some stuff didnt load so:
the game is about delivering packages to the houses
wasd to move and j to restart

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Are the 2 games yours?

**Comment by cott3** [comment]
no, mines: ding dong- delivery!

**Comment by LucasHT22** [comment]
And the other game?

**Comment by cott3** [comment]
im pretty sure that my old attempt-  but dont merge that one

**Comment by cott3** [comment]
also if i dont reply on github just dm me on slack

**Comment by cott3** [comment]
if you need shipping info then its saved to my slack

**Comment by LucasHT22** [comment]
> im pretty sure that my old attempt- but dont merge that one

so could you delete the file? thanks:)

**Comment by LucasHT22** [comment]
> if you need shipping info then its saved to my slack

You'll answer on a form that I'll send after merge:)

**Comment by cott3** [comment]
can i just close this pr and make another one

**Comment by LucasHT22** [comment]
You can just delete the file and will be automatically updated here:)

**Pull request closed without merging**
