### PR TITLE
Gravity is a Thing

### PR DESCRIPTION
**Pull request by whrigney01**
This game is a basic platformer that features the main character as a cow. I have some experience coding but almost none with javaScript so it was fun to learn a new language to make this game.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Great game! Had a lot of fun, reminded me of Geometry Dash :)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by leomcelroy** [comment]
I had a lot of fun playing this. 

I noticed a bug on the later levels which you may want to address. The player gets stuck in the air and has to move over blocks and press down to get more jumps.

Screen Shot 2022-09-30 at 12 29 58 PM

**Comment by LucasHT22** [comment]
@leomcelroy Strange, I played all levels and I didn't have this bug

**Comment by whrigney01** [comment]
Ahh..... I made the gravity activate at a y-level to low. Should be fixed now. How should I go about adding it to the repository?

**Comment by LucasHT22** [comment]
Or send it here and we'll add it or open a new PR

**Pull request merged**
