### PR TITLE
StickMan Plant

### PR DESCRIPTION
**Pull request by Crystal-07**
**Author:**
Crystal Castro

**What is your game about?**

My game is about a stick figure reaching its goal which is a plant by overcoming its obstacles in its way.

**How do you play your game?**

 Press WASD to move

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! What's the real name of your game?

**Comment by Crystal-07** [comment]
> Thanks for the PR! What's the real name of your game?

My game is called Stickman Plant

**Comment by LucasHT22** [comment]
> > Thanks for the PR! What's the real name of your game?
> 
> My game is called Stickman Plant

so could you rename the filename? :)

**Comment by leomcelroy** [comment]
This levels don't really give much choice to the player. Could you add some puzzle or challenge element?  I don't think this can earn a Sprig yet.

**Comment by grymmy** [comment]
Closing this PR due to inactivity.  Please feel free to re-open this PR once you have added more content to your game such that we can potentially award you your Sprig device.

**Pull request closed without merging**
