### PR TITLE
Added Astroid World

### PR DESCRIPTION
**Pull request by madebyshaurya**
# Your checklist for this pull request

## Author name

**Author:**
Shaurya

## About your game

**What is your game about?**
In my game you have to try to survive and shoot as many astroids as you can.

**How do you play your game?**
You use a and d to move. w to shoot and j to start (or restart)!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by recursiveforte** [comment]
Hey, nice work on this game! I noticed that when I was hit by an asteroid, the game wouldn't stop and would look like this screenshot. Could you fix this and add a game over screen before I approve this game?
Screenshot 2024-08-05 at 13 56 22

**Comment by madebyshaurya** [comment]
Sorry, I probably didn't test it enough but now it should be fine.

**Comment by madebyshaurya** [comment]
@recursiveforte

**Comment by recursiveforte** [comment]
Great work! This is fun to play, and works well after you modified it. I'm merging this, and on Wednesday, you should see it in the Sprig gallery. Also, you can head to [this link](https://sprig-order.hackclub.dev) to order a Sprig device.

**Pull request merged**
