### PR TITLE
Forked

### PR DESCRIPTION
**Pull request by SiritheFork**
dodge the forks so they stab tomatoes, w to jump
not much experience, took gateway a bit in 8th

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR! How does the player move? only with W? if yes, for me W is not working

**Review by LucasHT22 — COMMENTED** [review]
Leave only the latest version! It is confusing for us more than one version

**Comment by SamDev-7** [comment]
@SiritheFork Remember to remove the old file! Let us know if you need help with anything!

**Comment by leomcelroy** [comment]
It seems you need to make more changes before you're ready to get your Sprig.

I'm going to close this PR for now. Feel free to reopen if you want to continue working on your game.

Thanks for the submission!

**Pull request closed without merging**
