### PR TITLE
Added MusicalTiles via upload

### PR DESCRIPTION
**Pull request by SHREEYA2007**
# Your checklist for this pull request

## About your game

What is your game about? 

How to play your game?

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Thanks for the PR! 

What is your game about?

How to play your game?

**Comment by SHREEYA2007** [comment]
Hi Lucas,
This game is inspired by the reaction task in the popular game 'Among Us'.
You can play it using the 'w', 'a', 's', 'd' keys on keyboard.

How it works in one of the colors would blink randomly with a short tune and you can use the keys to locate which color blinked, this process continues and if you guess any key wrong then you lose the game.

It's like a short memory game, hope you will like it 😄

**Review by LucasHT22 — APPROVED** [review]
oh, reminds me Simon! 

Good game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by LucasHT22** [comment]
Wait wait wait, this game has many similarities with https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/nomis.js , I will revert this PR and encourage you to make more changes to make it original.

**Comment by SHREEYA2007** [comment]
Hey Lucas,
I have made the necessary changes and tried to makes this as original as possible. 
I have changed the file in 'main' but I am not sure if it's updated or not, please let me know if that works if I should create another pull request.
Thanks!

Regards,
Shreeya Rani

**Comment by LucasHT22** [comment]
Please open a new PR so I can review it better:)

**Pull request merged**
