### PR TITLE
English Checkers

### PR DESCRIPTION
**Pull request by Oakchris1955**
# Your checklist for this pull request

## Author name

**Author:**

Oakchris1955

## About your game

**What is your game about?**

The english variant of checkers (or draughts)

**How do you play your game?**

Press WASD to move the selection on another dark square

Press J on one of your own pieces to select it and show available moves (cyan squares), 
Press J on one of the available moves to move your piece there and let the next player play
Press J on the selected piece to unselect it

Press I when the game is over to play another match

Press K to reset the board an an already-running game (5 seconds timeout). Press L to cancel the timeout

Note: you may see some orange squares. Those indicate mandatory jumps. If multiple are present, the player can select which of them to play. When mandatory jumps are present, only those moves can be played

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by Oakchris1955** [comment]
A friend of mine told me about Hack Club. I decided to check it out and when I visited the website, Sprig drew my attention

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! Out of curiosity, did you use any game for inspiration?

**Comment by Oakchris1955** [comment]
When I went into the game gallery, the first game I searched was chess, which someone else had already ported. I then decided to check if that's also the case with checkers, since that's what came into my mind then. When I saw that nobody had already ported that game, I decided to give it a shot

**Comment by LucasHT22** [comment]
Sorry for delay! Could you send me a gameplay just to have sure if i'm playing right?

**Comment by Oakchris1955** [comment]
Below is a typical gameplay session that is being interrupted by one of the players choosing to reset the board

https://github.com/hackclub/sprig/assets/80592203/639ed669-c25d-4314-a955-6f21f6127ed7

Please take notice of 0:22. This is an example of a mandatory move (jumping). When one or more mandatory moves are found, the player MUST choose between one of them.

In case the game instructions are unclear, I can update them
You might also wanna take a look at this: https://en.wikipedia.org/wiki/English_draughts#Rules

**Comment by LucasHT22** [comment]
Great! Just update the instructions and i'll merge:)

**Comment by GalaxyGamingBoy** [comment]
re metadata, @LucasHT22 can you update them to the new format, I can run the script later today if you want thanksss

**Pull request merged**
