### PR TITLE
Worldcraft

### PR DESCRIPTION
**Pull request by apzzd**
# Your checklist for this pull request

## About your game

What is your game about? 

You control a little blob. There is no objective to this game, just explore the world and build things. You get different items by picking up different things. 

How to play your game?

WASD to move, L to pick up things to your right, J to set things down to your left. Use I to change which item to drop, you will see a star appear next to the name of the item.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
seccond game, right?

**Comment by apzzd** [comment]
yes :)

**Comment by LucasHT22** [comment]
congrats!

**Review by LucasHT22 — APPROVED** [review]
reminded me minecraft. Good job!

**Comment by apzzd** [comment]
Yay, thanks!

**Pull request merged**
