### PR TITLE
Rolling Obstacles

### PR DESCRIPTION
**Pull request by 0rang-3**
Welcome to Rolling Obstacles! The objective of the game is to move the ball and collect the coins! But be careful, as you cannot move through the obstacles! Collect 15 coins to win the game!

# Code
Check off the items that are true.

- [x]  The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [/games directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors.
- [x] The name of the file/game contains only alphanumeric characters, -s, or _s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

# Image (If an image is used)

- [x] The image is in the [/games/img directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! was supposed to appear "Game Over!" when scoring more than 14?

**Comment by 0rang-3** [comment]
Yes, once the user collects 15 coins (more than 14), the user has won the game and the game is over.

**Review by LucasHT22 — APPROVED** [review]
Right! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by 0rang-3** [comment]
Thanks!

**Comment by sonicx180** [comment]
do you have to be a teen? what if you are younger?

**Comment by yazidears** [comment]
Np! You can upload Sprig games with whatever age!

But the Sprig console is only for underage (-18) people!

**Pull request merged**
