### PR TITLE
Added maise game

### PR DESCRIPTION
**Pull request by Umurmiria**
# Your checklist for this pull request

## Author name

**Author:** Urvi Murmuria

## About your game

**What is your game about?**
The game is to solve the maze and reach the end without running into the dangerous fire.

**How do you play your game?**
Press WASD to move the character to the pr pad to got to the next level. Press i to reset

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)
Not used
- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
good game! I would suggest reducing level 3, it can be too small on console

**Comment by LucasHT22** [comment]
Nice! How about more levels?

**Comment by LucasHT22** [comment]
Great changes! Did you use any game for inspiration?

**Comment by Umurmiria** [comment]
I didn't use any specific game as an inspiration, I just had a book of small puzzles, from there I got an idea to make this game.

**Comment by LucasHT22** [comment]
> I didn't use any specific game as an inspiration, I just had a book of small puzzles, from there I got an idea to make this game. @LucasHT22

interesting! which book?

**Comment by Umurmiria** [comment]
hello @LucasHT22 
The book is "Amazing Brain Games for Clever Kids'

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! Now please just keep the latest version:)

**Comment by Umurmiria** [comment]
Done

**Review by LucasHT22 — APPROVED** [review]
Nice! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
