### PR TITLE
SpaceFlight

### PR DESCRIPTION
**Pull request by Isaak3**
# Your checklist for this pull request

## Author name

**Author:Isaak**

## About your game

**My game is about flying in space and dodging meteorites**

**Press A and D to move, I to pause, K to start, L to restart**

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! what does the name of the game mean? haha

**Comment by LucasHT22** [comment]
Sorry if you didn't understand! You just need to change the name:)

**Comment by LucasHT22** [comment]
Let's get this merged! Just change the file name:)

**Comment by grymmy** [comment]
Closing due to inactivity. Please re-open if you'd like to continue forward landing this game!

**Pull request closed without merging**
