### PR TITLE
mini maze and puzzle game

### PR DESCRIPTION
**Pull request by mukhayyar**

### CODE REVIEW

**Comment by SamDev-7** [comment]
Thanks for the PR! Interesting game! I do think polishing it up a bit would be beneficial, though. When you move, sometimes empty white squares appear. Are those intended? I also think that you should potentially lower the gravity a bit, it currently is difficult to move while jumping. Try adding more levels, be creative! Let us know if you need any help with those.

**Comment by LucasHT22** [comment]
@mukhayyar Do the white blocks that appear when you move have a purpose?

**Comment by mukhayyar** [comment]
hello guys, thx for the review. The white blocks are not intended, i'll fix it soon and for first release maybe i'll change the background to white again.

**Comment by mukhayyar** [comment]
hey @SamDev-7 & @LucasHT22 i've updated the game, kindly check it out

**Review by SamDev-7 — APPROVED** [review]
I like it! It is easier to control now, the traps require you to be careful while moving. Great game!

**Comment by LucasHT22** [comment]
Good job! Great game :)

**Comment by leomcelroy** [comment]
Nice work! Welcome to the Gallery. If you're a teen you can order your Sprig here: https://sprig-order.hackclub.dev/

**Pull request merged**
