### PR TITLE
ninja game

### PR DESCRIPTION
**Pull request by GANESH-46**
# Your checklist for this pull request

## About your game

What is your game about? 
> Example: Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))

How to play your game?
> Example  : Press WASD to move, J to restart and K to toggle trails, Get A boxes (cyan) to A goals (green), Get B boxes (magenta) to B goals (red), Get normal boxes (gray) to either goal. (from [Sokoban plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by GANESH-46** [comment]
game

**Comment by GANESH-46** [comment]
good

**Comment by GANESH-46** [comment]
it's interesting....

**Comment by LucasHT22** [comment]
Thanks for PR! which of the two versions is the current one?

**Comment by SamDev-7** [comment]
Is [`UNTITLED (3).js`](https://github.com/hackclub/sprig/pull/687/files#diff-d15a9e9b03dda1bfd0cd3465b8622bf8dd5f9272cf9f14ab2a1c0f8881f3ab84) supposed to be there?

**Comment by LucasHT22** [comment]
@SamDev-7 we comment at the same time haha

**Review by ni5arga — APPROVED** [review]

**Comment by grymmy** [comment]
@GANESH-46  I am closing this PR.  **You are free to reopen this PR yourself** (or reach out to me directly!) and continue advocating for this code landing, but it seems that it hasn't been acted upon for 3 months.

**Pull request closed without merging**
