### PR TITLE
Stupid Maze

### PR DESCRIPTION
**Pull request by yashsethu**
**Author: Yash Sethuraman **

## About your game
My game is a simple maze-solving game with 3 increasingly difficult levels

**How do you play your game?**
WASD controls to move the character, and find the trophy!

## Code
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)
- [ N/A] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ N/A] The name of the image matches the name of your file.

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add one or two new game mechanics to differentiate this from other games.  This as it stands is too low-effort - I want to see code-driven mechanics (not just bitmap changes) for this to meet the grant bar.

**Comment by yashsethu** [comment]
I added running physics, better more detailed maps and bitmaps, and a chest-key-lock mechanism to differentiate it

**Comment by yashsethu** [comment]
@grymmy lmk what you think

**Comment by recursiveforte** [comment]
Nice work on improving this game- I really enjoyed the walking animation. You should see it in the Sprig gallery tomorrow!

If you're in high school, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev/) and join our [online community](https://hackclub.com/slack) to talk to other teenagers making Sprig games.

**Pull request merged**
