### PR TITLE
Fix #839, added "Hack on a game by opening it in the Sprig editor!"

### LINKED ISSUE #839: Gallery Modification
in gallery add a line saying somethign like “click on a game to see its code / hack on it in the sprig editor

### PR DESCRIPTION
**Pull request by agentblack6000**
Implement #839, added "Hack on a game by opening it in the Sprig editor!"

### CODE REVIEW

**Review by grymmy — APPROVED** [review]
LGTM thank for for this.

**Comment by agentblack6000** [comment]
np! I'll help out more when my finals are over

**Review by grymmy — CHANGES_REQUESTED** [review]
Hmm so - it seems as though [this work](https://github.com/hackclub/sprig/issues/862) was already performed by @kognise.  This results in a merge conflict.

In the future, please send PR's that address one issue only so that we can keep review simple and avoid conflating two pieces of work into one.  That being said, I would say we had a bit of a process failure here on our side - we need to get better about allowing external contributors like you to gain ownership of issues in an official way so we don't accidently step on each others' toes like we've done here - and I would have merged the code here if not for the conflict.

Can you please resubmit the PR so that it only addresses #839, which I have now official assigned to you?

**Comment by agentblack6000** [comment]
@grymmy updated the PR and reverted the commit, thanks for the feedback, in future I'll separate out the issues in different branches :)

**Review by grymmy — APPROVED** [review]
Ship it

**Pull request merged**
