### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by andrewchen11**
# Your checklist for this pull request

## About your game
Flappy Bird game. The file is currently named Untitied because I forgot to change the name

What is your game about? 
move the bird across the obstacles 

How to play your game?
Press W or S to move up or down

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Review by SamDev-7 — CHANGES_REQUESTED** [review]
Thanks for the PR! A few more things need to be done before we can merge.

This game is VERY similar to [`flappy_bird_but_no_gravity_and_worse`](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/flappy_bird_but_no_gravity_and_worse.js), you're welcome to remix games, but please make sure to state the original author and modify it moderately.
Additionally, you can always rename files by editing your fork of the sprig repository.
Let us know if you need any help.

**Comment by andrewchen11** [comment]
Now I had added the official title of my game

**Review by SamDev-7 — CHANGES_REQUESTED** [review]
There are still more things needed, check my above comment.

**Comment by grymmy** [comment]
@andrewchen11 I am closing this PR.  **You are free to reopen this PR yourself** (or reach out to me directly!) and continue advocating for this code landing, but it seems that it hasn't been acted upon for about 3 months.

**Pull request closed without merging**
