### PR TITLE
monster battle

### PR DESCRIPTION
**Pull request by BShadee**
Win the game when you kill the monster blob

### CODE REVIEW

**Comment by leomcelroy** [comment]
Thanks for the PR shadee! I think you've got the start of a game here but not quite a full one. There needs to be some sort of way to lose or mechanism to motivate the player to destroy the blobs. I think also having an indication of how much life each blob has (perhaps by changing the sprite color) would be a nice piece of feedback to provide the player. 

One version of this game I could imagine is the player trying to smash blobs before a monster catches them. Or perhaps as you smash different blobs you can destroy other types or attach things with more power. Then the game becomes figuring out the right order to hit blobs. 

It's a nice start! We need a bit more work before we add it to the gallery though.

**Comment by BShadee** [comment]
> Thanks for the PR shadee! I think you've got the start of a game here but not quite a full one. There needs to be some sort of way to lose or mechanism to motivate the player to destroy the blobs. I think also having an indication of how much life each blob has (perhaps by changing the sprite color) would be a nice piece of feedback to provide the player.
> 
> One version of this game I could imagine is the player trying to smash blobs before a monster catches them. Or perhaps as you smash different blobs you can destroy other types or attach things with more power. Then the game becomes figuring out the right order to hit blobs.
> 
> It's a nice start! We need a bit more work before we add it to the gallery though.

Hi leom. It is my first programming assignment i have had since I took robotics in middle school. I have tried to add some more functionalities and health bar for the boss. It is a slight puzzle in the sense that the powerup will dissapear if you dont get it first. And if you get it then you will take big damage over the spikes and lose the fight. If you do not you will barely win the fight. Added slight animations Let me know what you think

**Comment by BShadee** [comment]
> Thanks for the PR shadee! I think you've got the start of a game here but not quite a full one. There needs to be some sort of way to lose or mechanism to motivate the player to destroy the blobs. I think also having an indication of how much life each blob has (perhaps by changing the sprite color) would be a nice piece of feedback to provide the player.
> 
> One version of this game I could imagine is the player trying to smash blobs before a monster catches them. Or perhaps as you smash different blobs you can destroy other types or attach things with more power. Then the game becomes figuring out the right order to hit blobs.
> 
> It's a nice start! We need a bit more work before we add it to the gallery though.

Hi waiting on an update on this

**Comment by leomcelroy** [comment]
Nice improvements. The mechanics are starting to get there but you still need more levels. Try to make a level where you have to get power-ups and kill monsters in a certain order. If you want to get some help and feedback while you build you could go to the #sprig channel in the [Hack Club Slack](https://hackclub.com/slack/?continent=North%20America). 

Keep at it!

**Comment by BShadee** [comment]
By the time I figure out how to create even more levels the event will be
over. I wasn't aware there is a minimum type of game. I added what you
asked powerup, a fail condition, and damage animation

**Comment by BShadee** [comment]
Yes please point me in the right direction. Would be much appreciated!

**Comment by leomcelroy** [comment]
Alright here's my interpretation at generalizing things a bit, let me know if you want help understanding why it is the way it is. One key change I made is defining the legend only once. It's a little tricky to figure out where to store the monster health when you want to have multiple monsters. I ordered the sprite types in an array and use that to derive their health number value from the index.

Try to add some new levels. I think the objective of this game is to figure out the order to fight monsters and get power ups. 

```
/*
@title: moded: monster battle
@author: shadee & leo
*/


const player = "p";
const monster5 = "5";
const monster4 = "4";
const monster3 = "3";
const monster2 = "2";
const monster1 = "1";
const spikes = "s";
const armor = "a";
const powerup = "u";
const dead = "d";

setLegend(
  [ player, bitmap`
................
.....8888...7...
....88...8..7...
....88...8..7...
.....8888...7...
......888...7...
......8...77777.
.....88888..7...
.....88..8887...
....888.....7...
...88.8....7....
..8...88........
.....8.8........
....8...88......
....8....8......
...8............`],
  [ monster5, bitmap`
............777.
............7...
............777.
....444444....7.
...44....44.777.
...4.0...04.....
...4.00..0.4....
...4.00..004....
...400....000...
...44......40...
....4......4....
....44....44....
.....444444.....
................
................
................`],
  [ monster4, bitmap`
............7.7.
............7.7.
............777.
....444444....7.
...44....44...7.
...4.0...04.....
...4.00..0.4....
...4.00..004....
...400....000...
...44......40...
....4......4....
....44....44....
.....444444.....
................
................
................`],
  [ monster3, bitmap`
............777.
..............7.
.............77.
....444444....7.
...44....44.777.
...4.0...04.....
...4.00..0.4....
...4.00..004....
...400....000...
...44......40...
....4......4....
....44....44....
.....444444.....
................
................
................`],
  [ monster2, bitmap`
............777.
..............7.
............777.
....444444..7...
...44....44.777.
...4.0...04.....
...4.00..0.4....
...4.00..004....
...400....000...
...44......40...
....4......4....
....44....44....
.....444444.....
................
................
................`],
  [ monster1, bitmap`
.............7..
............77..
.............7..
....444444...7..
...44....44.777.
...4.0...04.....
...4.00..0.4....
...4.00..004....
...400....000...
...44......40...
....4......4....
....44....44....
.....444444.....
................
................
................`],
  [ spikes, bitmap`
................
................
................
................
................
................
................
................
................
................
...3...3.....3..
...3..33....33..
..33..3.3..333..
..33..3.3..3.33.
.3..33...33...3.
33..33...3....33`],
  [ powerup, bitmap`
................
................
................
.......LL.......
......L66L......
.....L6666L.....
....L666666L....
...L66666666L...
....LLL66LLL....
......L66L......
......L66L......
......L66L......
......L66L......
.......LL.......
................
................`],
  [ dead, bitmap`
................
................
................
................
................
................
................
......7.........
......7.........
...7777777777...
88...87.........
.88..87888......
..888888.88.....
.88..8.8.88.....
.8...8..88......
.....8..........`]
);

let level = 0;

let playerHealth = 8;
let attackPower = 1;

const levels = [
  map`
us.p.5`,
  map`
.5su..
us.p.5
...2..`,  
];


const setLevel = (level) => {
  playerHealth = 8;
  attackPower = 1;
  clearText();
  const currentLevel = levels[level];
  setMap(currentLevel);
  addText(`Health: ${playerHealth}`, { x: 0, y: 0, color: [255, 0, 0]})
  addText(`Power: ${attackPower}`, { x: 0, y: 1, color: [255, 56, 0]})
}

setLevel(level);

setSolids([player, monster5, monster4, monster3, monster2, monster1]);

const monsters = [monster1, monster2, monster3, monster4, monster5];

const tileHasMonster = (x, y) => getTile(x, y)
  .some(s => monsters.includes(s.type));

const getMonster = (x, y) => getTile(x, y)
  .find(s => monsters.includes(s.type));

const encounterMonster = (x, y) => {
    playerHealth -= 1;
    const m = getMonster(x, y);
    const monsterHealth = monsters.indexOf(m.type) + 1;
    const newMonsterHealth = monsterHealth - attackPower;
    if (newMonsterHealth > 0) m.type = monsters[newMonsterHealth-1];
    else m.remove();
}

onInput("d", () => {
  const p = getFirst(player);
  if (!p) return;
  
  if (tileHasMonster(p.x+1, p.y)) {
    encounterMonster(p.x+1, p.y);
  }
  
  p.x += 1;
});

onInput("a", () => {
  const p = getFirst(player);
  if (!p) return;

  if (tileHasMonster(p.x-1, p.y)) {
    encounterMonster(p.x-1, p.y);
  }
  
  p.x -= 1;
});

onInput("w", () => {
  const p = getFirst(player);
  if (!p) return;

  if (tileHasMonster(p.x, p.y-1)) {
    encounterMonster(p.x, p.y-1);
  }
  
  p.y -= 1;
})

onInput("s", () => {
  const p = getFirst(player);
  if (!p) return;

  if (tileHasMonster(p.x, p.y+1)) {
    encounterMonster(p.x, p.y+1);
  }
  
  p.y += 1;
})

afterInput(() => {
  if (tilesWith(player, spikes).length > 0) {
    playerHealth -= 3;
  }


  tilesWith(player, powerup).forEach(tile => {
    attackPower += 1;
    tile.forEach(sprite => {
      if (sprite.type === powerup) sprite.remove();
    })
  })

  if (monsters.every(monster => tilesWith(monster).length === 0)) {
    level += 1;
    console.log(level, levels.length);
    if (level < levels.length) setLevel(level);
    else {
      clearText();
      addText(`You Win!`, { y: 5, color: [255, 0, 0]});
      return;
    }
  }
  
  
  clearText();
  addText(`Health: ${playerHealth}`, { x: 0, y: 0, color: [255, 0, 0]})
  addText(`Power: ${attackPower}`, { x: 0, y: 1, color: [255, 56, 0]})

  if (playerHealth <= 0) {
    addText(`You Lose!`, { y: 5, color: [255, 0, 0]});
    const p = getFirst(player);
    if (!p) return;
    addSprite(p.x, p.y, dead);
    p.remove();
  }

});
```

**Comment by LucasHT22** [comment]
Hey @BShadee !
I see you're gone, don't give up your game!
We hope to see you here again :)

**Comment by BShadee** [comment]
Hey Lucas,

Yes I have not given up. I had to go on vacation. Will start back up Monday!

Can't let your help go in vain

Thank you

**Comment by LucasHT22** [comment]
Hey @BShadee !
time is flying! Don't forget the Sprig!

**Comment by leomcelroy** [comment]
I'm going to close this PR for now. Feel free to reopen if you want to continue working on your game.

**Pull request closed without merging**
