### PR TITLE
24hrs-of-LeStoopid

### PR DESCRIPTION
**Pull request by Idonotknowhowtoprogram**
This game is an artistic vision, one which only few can truly grasp. 24hrs of LeStoopid places you directly into the drivers seat of a Le Mans driver, for a truly staggering 24hrs straight. Now some may question the authenticity of this experience, and let me put the to rest. I am both a veteran Le Mans driver, and decorated artist, and let me tell you, this game is the REAL DEAL!

# Your checklist for this pull request

## Liam O'Keeffe

**Liam"LeMans"O'Keeffe**

## This is a fully realistic, high octane, LeMans simulation 

**Fast, ENDURANCE, racing**

**Just WASD**

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay! Thanks for the PR!
Where did you hear about Sprig?

**Comment by Idonotknowhowtoprogram** [comment]
Dont worry about the delay, I am a student at [Sonoma Academy](https://www.sonomaacademy.org) and this is the first project in our Advanced Computer Programming class.

**Comment by Idonotknowhowtoprogram** [comment]
I have had a great time using sprig, my only suggestion is more fleshed out documentation, but besides that everything has worked well. If you have any specific questions i suggest getting in contact with the teacher of the class (Changa Imara-changa.imara@sonomaacademy.org). Are there any things to do with my game that I can improve so that I can push it to the main branch 🥺

**Comment by LucasHT22** [comment]
> I have had a great time using sprig, my only suggestion is more fleshed out documentation, but besides that everything has worked well. If you have any specific questions i suggest getting in contact with the teacher of the class (Changa [Imara-changa.imara@sonomaacademy.org](mailto:Imara-changa.imara@sonomaacademy.org)).

We're working on this:) Check sprig.hackclub.com/sprikipedia, not released yet but shows a bit of what will be
> Are there any things to do with my game that I can improve so that I can push it to the main branch 🥺

Nope haha I was just holding to collect feedback haha

**Comment by Idonotknowhowtoprogram** [comment]
Hi lucas, sprikepedia looks like a great resource for us, thank you so much. I just fixed the naming issue, I think, I renamed it from "24hrs of Le Stoopid" to "24hrs-of-LeStoopid"

**Comment by LucasHT22** [comment]
> Hi lucas, sprikepedia looks like a great resource for us, thank you so much. I just fixed the naming issue, I think, I renamed it from "24hrs of Le Stoopid" to "24hrs-of-LeStoopid"

Please rename your file too:)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Out of curiosity, did you use any game for inspiration?

**Comment by LucasHT22** [comment]
Nice:) Just re-check this:
- [ ] The game is placed in the in the [/games directory](https://github.com/hackclub/sprig/tree/main/games).

**Comment by Idonotknowhowtoprogram** [comment]
Lucas I am making a new pull request because I messed up a couple of things, this next one should be correct.

**Comment by Sheepy3** [comment]
closing this PR due to inactivity. feel free to ping me and ask for this to be reopened and hopefully merged!

**Pull request closed without merging**
