### PR TITLE
Galactic

### PR DESCRIPTION
**Pull request by polypixeldev**
# Your checklist for this pull request

## Author name

**Author:**
polypixeldev

## About your game

**What is your game about?**
Building a new city on another planet and keeping your citizens alive.

**How do you play your game?**
WASD for directional controls (moving the green select box, or the rocket during resource collection). I to select. J to go back. K to skip the story when you begin.
Select the play button on the main menu, then start collecting wood and stone by selecting either the wood+ or stone+ sprites with the select box. Collect wood or stone by moving your rocket to it. When you have materials, select any blue tile to enter select mode, then navigate to the add option with A and D and select with I. Choose the building you would like to place it using the same controls. If you do not have enough materials, you will hear an error sound. Exit the menu by navigating and selecting the cancel option. You can also upgrade or remove buildings with the same menu. The status of your city is shown in the bottom left tile, ranging from DINOBBQ (very good) to THREAT (about to die). If your city becomes too crowded, the game will end.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game!
> Choose the building you would like to place it.

What button?

**Comment by polypixeldev** [comment]
You can navigate the select menus with A and D, and I to select

**Comment by LucasHT22** [comment]
oh right, could you add a way to exit this menu when you don't have the necessary wood or stone and maybe add on start how much stone and wood is necessary for each thing? The quantities would help the player a lot:)

**Comment by polypixeldev** [comment]
You can already exit the menu by navigating to the cancel option - I'll add the quantities now!

**Review by LucasHT22 — APPROVED** [review]
Sorry for the delay, I thought I had already approved. Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
