### PR TITLE
Updated game killer_training

### PR DESCRIPTION
**Pull request by jakjakob**
How to play etc.. https://github.com/hackclub/sprig/pull/1141

Tutorial is also in the game itself

Now in version 1.1.0

1.1.0
Practice mode (not time limit and no restart if enemy touched)
Complete menu redesign:
  - main menu has a button interface, with various options
  - main menu shows highscore
  - tutorial rewritten
  - pages are controlled by key input
  - shows version number

Highscore counter 
New finish screen with highscore, score and option to go to main menu
Go on menu instead button on restarts
Failing tutorial brings you back to main menu
2 slight level updates (mazes)

### CODE REVIEW

**Comment by jakjakob** [comment]
It's funny how doing the menu was waaaay easier than the game itself

**Comment by jakjakob** [comment]
and btw the preview by Vercel is wrong

**Comment by LucasHT22** [comment]
> and btw the preview by Vercel is wrong

Just ignore it:)

**Review by LucasHT22 — APPROVED** [review]
Awesome changes!! Just a note - Idk if you know but these version numbers there are specifications for this: https://semver.org but it's just a curiosity :)

**Comment by jakjakob** [comment]
> Awesome changes!! Just a note - Idk if you know but these version numbers there are specifications for this: https://semver.org but it's just a curiosity :)

wow cool didn't know that! Thanks for the advice

**Comment by LucasHT22** [comment]
> wow cool didn't know that! Thanks for the advice

Fun fact: SemVer was created by Tom Preston-Werner, the creator of GitHub:)

**Pull request merged**
