### PR TITLE
Random block game

### PR DESCRIPTION
**Pull request by nicholasyoannou**
A random block game, based off the getting_started by Leo code.
Though this time it has more mechanics, sounds, more maps + other stuff.

This is the first release but planning to add more mechanics when I have the chance (I've added a fire sprite but need to make maps to add the fire in, and make stuff happen when objects touch the fire).
Though for now this is version 1 of the game haha.

### CODE REVIEW

**Comment by leomcelroy** [comment]
This is a great start Nicholas. I think you should definitely finish up the new fire mechanics. With those I think Random Block Game would differentiate itself enough from Sokoban enough to be added to the gallery.

**Comment by LucasHT22** [comment]
Hey @nicholasyoannou !
I see you're gone, don't give up your game!
Complete your game!
We look forward to having your game in the gallery :)

**Comment by LucasHT22** [comment]
Hey @nicholasyoannou !
1month from your PR!
Don't give up on the Sprig

**Comment by leomcelroy** [comment]
I'm going to close this to keep the PRs tidy but feel free to reopen if you'd like to continue working.

**Pull request closed without merging**
