### PR TITLE
Added new Sprig game

### PR DESCRIPTION
**Pull request by fireblooded**
# Your checklist for this pull request

## About your game

What is your game about? 

Navigating through an abandoned laboratory to kill enemies.

How to play your game?

"w" is up, "s" is down, "a" is left, "d" is right".

Move to the sword, and press "i" to grab it. You can only do this once.

Without the sword, you're immune to monsters and can push stumps,
but that on its own won't get you far.

With the sword, you're able to kill monsters and walk through walls,
but you're able to be killed.

Swap between having a sword and not having a sword by hitting "i". While
having the sword in your hand, you also hit anything within a one-block
radius.

Beat all enemies in the red room to win the game.

INTENDED ORDER
The intended order is to do: yellow => green => purple => orange => red,
but I've given it a more non-linear layout for player freedom purposes.

Hit "run" to execute the code and
start the game (you can also press shift+enter).

## Code
Check off the items that are true. <-- Put a `x` in the  `[ ]`. Example: `[x] The game was made...` -->
- [ x ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ x ] The game is placed in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x ] The game runs without errors. 
- [ x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Was it supposed to end the game by pressing "i"?

**Comment by fireblooded** [comment]
It depends. You hit "i" to arm and disarm your sword, but you only attack when disarming your sword. The game ends when you're hit by an enemy, and enemies move whenever you make a move (WASD or "i"), so my guess is that you got hit by an enemy while arming the sword.

**Comment by fireblooded** [comment]
Also, found a TypeError if you do something in the wrong place. Minor issue with a minor change. Can I reupload the game?

**Comment by LucasHT22** [comment]
> Also, found a TypeError if you do something in the wrong place. Minor issue with a minor change. Can I reupload the game?

Yep! `Files` > `...` > `edit`

**Comment by fireblooded** [comment]
The file has been updated.

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
