### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by KidPrograms**
# Your checklist for this pull request

## Author name 

**Author:Pavel Bohačík**

KIDPROGRAMS

## About your game
Its just my second game.

**What is your game about?
U catch or run**

**How do you play your game?
WASD is run and IJKL is enemy **

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [I dont know ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [I dont know ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Could you please add a bit more to your game?

**Comment by KidPrograms** [comment]
I dont know what to add but i think im going to make a new game entirely.
But still isnt going to be for five minutes.

**Comment by LucasHT22** [comment]
> I dont know what to add but i think im going to make a new game entirely. But still isnt going to be for five minutes.

It doesn't necessarily need to be 5 minutes :) It just needs to be "more complex"
Try our tutorials:
https://sprig.hackclub.com/gallery/getting_started
https://sprig.hackclub.com/gallery/sprig_dodge

**Comment by KidPrograms** [comment]
Now i think maybe i could win the sprigkit.

**Comment by LucasHT22** [comment]
Sorry for the delay! Which of the 2 files it's the version that you will follow?

> Now i think maybe i could win the sprigkit.

You definitely will!

**Comment by KidPrograms** [comment]
Catch me multiplayer Is my good game.
So i Will go with that

**Comment by LucasHT22** [comment]
Looks like nothing happen when I catch:( Need help?

**Comment by KidPrograms** [comment]
Ok

**Comment by KidPrograms** [comment]
Can u help me?

**Comment by LucasHT22** [comment]
> Can u help me?

Sure! What do you expect when catch?

**Comment by KidPrograms** [comment]
When catch print u got cought.
I have it there somehow doesnt work i tried it to and no text.
Thanks.

**Comment by LucasHT22** [comment]
It's just a typo:) it's `length` not `lenght`

**Comment by KidPrograms** [comment]
Oh thanks.

**Comment by KidPrograms** [comment]
I just have a question. Where to put my addres.

**Comment by LucasHT22** [comment]
> I just have a question. Where to put my addres.
> 

Calm:) After merge I'll send a form

**Comment by LucasHT22** [comment]
> Oh thanks.

You can make the change following these steps:
Click on `Files changed`, then `...` and `edit`

**Comment by LucasHT22** [comment]
Make the updates! Let's get this merged!

**Comment by Sheepy3** [comment]
Closing this PR due to inactivity. If you want it reopened, ping me here.

**Pull request closed without merging**
