### PR TITLE
sPaint first release!

### PR DESCRIPTION
**Pull request by yazidears**
sPaint is a JS game for sprig, is a paint game, so you can unleash your creativity when you are bored! Expect updates :)

## About sPaint

Unleash your creativity with sPaint! Make pixel art with it and share it on slack! Very simple game!
Paint whatever you want and share it with us on the "#spaint" channel on slack!

## How to play sPaint?

When you first enter the game, you will be prompted to press "w" to play.
Now you are in your paint! Use WASD to move within the canvas, use J to switch between cursor and eraser, use K to place pixels or to erase pixels, and L to reset the map!

Have fun!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Comment by LucasHT22** [comment]
Ok! it's `test-game` , see: 
image

**Comment by yazidears** [comment]
> Ok! it's `test-game` , see: image

Hi again, I don't really know where's that error coming from, and ```
tileInputs[key]. forEach(fn
fn());
``` is not even on my JS code, what should I do? I've tried putting the code onto the Sprig editor and it would work without any kind of problem :c,

**Comment by LucasHT22** [comment]
oh ok, this test is more to know if the game runs on the console, here is an example of how to fix: https://github.com/hackclub/sprig/commit/ba7e8b67ee47a12312c49ac6a5dee8573b61eeb3

**Comment by yazidears** [comment]
I think I have the code that works, how can I upload it?

**Comment by LucasHT22** [comment]
> I think I have the code that works, how can I upload it?

`Files changed`  >  `...`  >  `edit`

**Comment by yazidears** [comment]
Done! Seems to work now :p

**Review by LucasHT22 — APPROVED** [review]
perfect! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
