### PR TITLE
bug: Add other missing games.

### PR DESCRIPTION
**Pull request by shanecelis**
There were a few other missing games I found. I wrote a little tool for that. Other pull request incoming.

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
@shanecelis I apologize but I believe this PR was effected by the recent merge and needs rebasing/etc.  Can you please reissue so we can move forward (if you believe it's still needed?)

**Comment by sampoder** [comment]
@shanecelis & @grymmy: I think I've fixed the conflicts!

**Comment by shanecelis** [comment]
I made a new PR that restores the changes the old PR did. 

https://github.com/hackclub/sprig/pull/971

I am seeing weird messages in this PR of `shanecelis force-pushed main branch 8c97c0f... 8 minutes ago.` that don't look right to me. Is this more vercel weirdness?

**Comment by grymmy** [comment]
> I made a new PR that restores the changes the old PR did. 
> 
> https://github.com/hackclub/sprig/pull/971
> 
> I am seeing weird messages in this PR of `shanecelis force-pushed main branch 8c97c0f... 8 minutes ago.` that don't look right to me. Is this more vercel weirdness?

This is git warning about a push to a remote that overwrites history and may be an unavoidable consequence of how the merge last week was performed.

**Pull request closed without merging**
