### PR TITLE
JB's Pushy Blocky Portal Game

### PR DESCRIPTION
**Pull request by Pho3nixCoding**
## Justin Burns II

**Author: JB**

## About your game

**My game is about pushing a brown box into a portal with a character that seems sus.**

**How do you play your game?**

Press WASD to move, J to restart and push the brown box into the orange and yellow swirly thing that looks like a portal.

### CODE REVIEW

**Comment by Pho3nixCoding** [comment]
My first game :)

**Comment by Pho3nixCoding** [comment]
my first game

**Comment by Cosmin-Mare** [comment]
Hey! Thank you for your submission, and congrats on your first game! some of the levels really are challenging and require strategy to solve and also I like the amongus refference:). Your submission is approved!

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev/) and join our [online Slack community](https://hackclub.com/slack) to chat with other people making Sprig games.

**Review by Cosmin-Mare — APPROVED** [review]
Hey! Thank you for your submission, and congrats on your first game! some of the levels really are challenging and require strategy to solve and also I like the amongus refference:). Your submission is approved!

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev/) and join our [online Slack community](https://hackclub.com/slack) to chat with other people making Sprig games.

**Pull request merged**
