### PR TITLE
QuadraPedal

### PR DESCRIPTION
**Pull request by MarkAwesomeness**
Its similar to the "Getting Started" level, but you control four characters at once. It was definitely enjoyable to code and make the music for.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR!

**Review by LucasHT22 — COMMENTED** [review]
how to solve this level?
image

**Comment by MarkAwesomeness** [comment]
For example, the green player would push the green box onto the red goal, and so on

**Comment by MarkAwesomeness** [comment]
I realized that one is a little more complicated than intended, so I could create a walkthrough of the sprig if needed

**Comment by LucasHT22** [comment]
Very good game! there are no errors, it has many levels and it's a lot of fun! the function of restarting the phase is very good, only in the last level I restarted many times haha

**Comment by LucasHT22** [comment]
> You would use the different characters to Push the certain boxes into their respective spots

ok but I can't solve it, I'll record the screen

**Comment by MarkAwesomeness** [comment]
2022-11-04 22-00-26_Trim


Hopefully the gif works

**Comment by MarkAwesomeness** [comment]
Glad you enjoyed the game though! I might plan on adding to it some time in the future

**Comment by LucasHT22** [comment]
> 2022-11-04 22-00-26_Trim [ 2022-11-04 22-00-26_Trim ](https://user-images.githubusercontent.com/94931561/200096324-187aefb9-0aa8-4dab-9dc4-84cf311ba630.gif) [ ](https://user-images.githubusercontent.com/94931561/200096324-187aefb9-0aa8-4dab-9dc4-84cf311ba630.gif)
> 
> Hopefully the gif works

oh, ok!

**Comment by LucasHT22** [comment]
Very good game! Congrats!
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by MarkAwesomeness** [comment]
I am, I'll set that up now!

**Pull request merged**
