### PR TITLE
Battery-Tracker

### PR DESCRIPTION
**Pull request by St305094**
# Your checklist for this pull request

## Author name

Trevor Smith

## About your game

**What is your game about?**

Moving through a maze and removing enemies in order to reach a goal. 

**How do you play your game?**

WASD to move, J to restart the level. Move to box with a person crossed out to remove an enemy, press multiple times to remove more. Once a path is clear, move to battery to complete the current level. 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add more content (especially logic/code) to this game to bring it up to the quality we expect to award a grant.  It is pretty bare-bones right now.

**Comment by grymmy** [comment]
Ping on this - do you intend on moving forward with landing this PR?

**Comment by grymmy** [comment]
Closing this PR due to inactivity.  Please feel free to re-open this PR once you add more content to it.

**Pull request closed without merging**
