### PR TITLE
dino-game

### PR DESCRIPTION
**Pull request by TheOtherTridentGuy**
# Your checklist for this pull request
[ x] complete the game
## Author name
Aiden Bohlander aka @TheTridentGuy
**Author:**
Aiden Bohlander aka @TheTridentGuy

## About your game
It's a remake of the classic Chrome dino game.
**What is your game about?**
Basically, you are a dinosaur (Orpheus??) and you have to jump over cacti and avoid raptors.

**How do you play your game?**
W to jump, and start the game.

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)
dino-game.png
- [ x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Comment by TheOtherTridentGuy** [comment]
> Thanks for the PR! Where did you hear about Sprig?

I heard about it in the HC Slack.

**Comment by TheOtherTridentGuy** [comment]
@LucasHT22 Do I have to change anything if it says "changes requested"?

**Comment by LucasHT22** [comment]
> @LucasHT22 Do I have to change anything if it says "changes requested"?

Nope, it's just so you see the comment with more emphasis:)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
What about "J" to restart?

**Review by LucasHT22 — COMMENTED** [review]
Sorry for the delay! Just one last question, did you use any game for inspiration?

**Comment by TheOtherTridentGuy** [comment]
Does the original Chrome dino game count?

**Review by LucasHT22 — APPROVED** [review]
Alright, sorry! Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
