### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by KhushalKD**
Khushal Davesar
builind this for my campus Club as I am presedent of CodeX

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Could you please answer this? Thanks:)
## Author name

**Author:**



## About your game

**What is your game about?**



**How do you play your game?**



## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

**Comment by KhushalKD** [comment]
Hello,
I currently hold the position of President at CodeX
<https://codex-hc.web.app/>, and we are in the process of organizing a
Hackathon. As an incentive, we plan to offer a Sprig as a prize to the
Hackathon winner, while all participants will receive exclusive Hack Club
stickers.So I request you to send me a Sprig so I can make my
hackathon Exiting..
Regards
Khushal Davesar <https://khushaldavesar-studio.web.app/>

**Comment by LucasHT22** [comment]
Hey! Please contact via Slack (@ lht), but answer the message above too

**Comment by grymmy** [comment]
@KhushalKD This seems to be your first and only PR and it seems to be for promotional purposes more than anything.  I am closing this PR as not in alignment with the sprig project - the rules for receiving a Sprig device are fairly clearly laid out on Hack Club's website...

Please re-open this issue if you feel I have closed it unfairly or prematurely.

**Pull request closed without merging**
