### PR TITLE
Watermellonman_BluebarryMan

### PR DESCRIPTION
**Pull request by Joel11940**
# Your checklist for this pull request

## Author name

**Joel Robbins**

## About your game

**What is your game about?**

In my game you have 2 players that you have to move to the 2 different portals when both of the players are standing on both portals at the same time you will advance to the next level.

**How do you play your game?**

To play my game you have to move Watermellon man to his portal using keys W,A,S,D.
For Bluebarry man you have to use keys J,K,L,I.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! did you use any game for inspiration?

**Comment by Joel11940** [comment]
I had inspiration from My friend who loves the game fire boy and lava girl so my robotics teacher gave me and the rest of the programers the fliers to the sprig game so I made my friend this game and I was hoping to get a sprig so I could give it to him.

**Comment by Joel11940** [comment]
So I guess my inspiration came from water boy and lava girl

**Review by LucasHT22 — APPROVED** [review]
oh, nice!! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
