### PR TITLE
Tic-Tac-Toe-YZ

### PR DESCRIPTION
**Pull request by bochk0**
# Your checklist for this pull request

## Author name

**Author: bochk0**

## About your game

**What is your game about?**
Tic-Tac-Toe is a unique variation of the classic game, where the objective is to be the first to get three of your own marks in a row, either horizontally, vertically, or diagonally, against an AI opponent represented by Z, while you play as Y.

**How do you play your game?**
W - Up, S - Down, A - left, D - Right, I - place Y, K - reset game

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [X] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [X] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by GalaxyGamingBoy** [comment]
Cool iteration on a tictactoe game but the AI could use some work and/or there could be more game mechanics to make the game more interesting and unique.

**Comment by bochk0** [comment]
> Cool iteration on a tictactoe game but the AI could use some work and/or there could be more game mechanics to make the game more interesting and unique.


@GalaxyGamingBoy, could you give me some ideas? I have no idea what I could add more on tic-tac-toe. Should I make the AI more advanced so it almost doesn't give chance to the player to win?```

**Comment by GalaxyGamingBoy** [comment]
That certainly is a possibility, in the case you can also introduce a twist like power ups for the player to "freeze" the AI, or even trip it

**Comment by bochk0** [comment]
> That certainly is a possibility, in the case you can also introduce a twist like power ups for the player to "freeze" the AI, or even trap it

@GalaxyGamingBoy 
I added two power-ups: 
- Freezing 1 AI move
- Double move for player (AI skip 2 moves)
also made the AI harder to beat

**Comment by GalaxyGamingBoy** [comment]
Cool! I really like the twist you added!

**Comment by bochk0** [comment]
> Cool! I really like the twist you added!

@GalaxyGamingBoy 
Thank you! Could you link me the form for sprig in airtable?

**Comment by GalaxyGamingBoy** [comment]
Ah yes my bad, the message didn't send. If you are a teenager and haven't received a sprig device you are welcome to out fill out this form to receive one! Also, feel free to join Hack Club's Slack in the #sprig channel to share your creation with others!

**Comment by bochk0** [comment]
Thank you!

**Pull request merged**
