### PR TITLE
Maze Chase

### PR DESCRIPTION
**Pull request by 4n0nym0u5-3y3**
# Your checklist for this pull request

## Author name

**Author: Armaanpreet Singh**

## About your game

**What is your game about?**
Maze Chase is an exciting two-player game where each player navigates through intricate mazes to capture the flag before their opponent. Players control their characters, represented by distinct icons on the maze, and must maneuver through walls and obstacles strategically placed throughout each level. The objective is simple yet challenging: be the first to reach and capture the flag located at different points in each maze.

**How do you play your game?**
To play "Maze Chase," follow these steps:

Each player controls a character represented by an icon (player1 and player2).

Controls:

Player 1 controls:

1. Move up: Press W
2. Move down: Press S
3. Move left: Press A
4. Move right: Press D

Player 2 controls:

1. Move up: Press I
2. Move down: Press K
3. Move left: Press J
4. Move right: Press L

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by 4n0nym0u5-3y3** [comment]
How long it takes to approv my project

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add a game mechanic (something w/ some code, specifically) or two to differentiate this game from others in the gallery and to meet the bar for a sprig device grant.

**Comment by 4n0nym0u5-3y3** [comment]
> Please add a game mechanic (something w/ some code, specifically) or two to differentiate this game from others in the gallery and to meet the bar for a sprig device grant.

Hi, i updated my code i added this Teleporte and Timer in this game.

**Comment by grymmy** [comment]
I was not able to utilize the teleporter mechanic.  I saw it appear on the playing field but it didn't seem to do anything.  Can you fix that such that it works as designed, or explain what it is actually supposed to do?

**Comment by grymmy** [comment]
Looked at this today, still awaiting changes from the author.

**Comment by 4n0nym0u5-3y3** [comment]
> Looked at this today, still awaiting changes from the author.

yes i am changing my ocde

**Comment by 4n0nym0u5-3y3** [comment]
> Looked at this today, still awaiting changes from the author.

know teleport works

**Comment by 4n0nym0u5-3y3** [comment]
So it's approved my project

**Comment by 4n0nym0u5-3y3** [comment]
I updated my work

**Comment by 4n0nym0u5-3y3** [comment]
when can i have my spring console

**Comment by grymmy** [comment]
Congratulations!  If you're a teen, and you haven't already gotten one, you are eligible for a Sprig device grant!  Please fill out [this form](https://sprig-order.hackclub.dev/).  Additionally, feel free to join Hack Club's Slack and share your creation with others in the #sprig channel!

**Comment by 4n0nym0u5-3y3** [comment]
> Congratulations! If you're a teen, and you haven't already gotten one, you are eligible for a Sprig device grant! Please fill out [this form](https://sprig-order.hackclub.dev/). Additionally, feel free to join Hack Club's Slack and share your creation with others in the #sprig channel!

thank you

**Pull request merged**
