### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by DefinetlyNotAI**
# Your checklist for this pull request

## Author name

**Author:** Shahm Najeeb

## About your game

**What is your game about?**

Fun rock paper scissor game

**How do you play your game?**

Press A or S or D to play against my ai, super simple game of rock (A) paper (S) scissors (D)
A message appears if you won or lost

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. PROBLEM : The game is functional, but due to a weird problem it keeps giving .y errors in blanck lines, it operational tho
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by recursiveforte** [comment]
Hi- there has already been a rock-paper-scissors game submitted to the gallery, and one requirement for submissions is that they must be original. You could differentiate this game by adding another unique game mechanic.

**Comment by DefinetlyNotAI** [comment]
Can i add music? Can you give me a simple idea, sorry its my first time programming is js

**Comment by DefinetlyNotAI** [comment]
Umm, can you please answer my question?

**Comment by recursiveforte** [comment]
Sorry, I should have approved this- I didn't have a clear enough understanding of the submission criteria. I'm merging this, and you'll see it in the gallery this week!

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev) and join our [online Slack community](https://hackclub.com/slack) to chat with other people making Sprig games.

**Comment by DefinetlyNotAI** [comment]
thx :)

**Pull request merged**
