### PR TITLE
5-in-1 Carnival Game Pack

### PR DESCRIPTION
**Pull request by apzzd**
# Your checklist for this pull request

## About your game

What is your game about? 
My game is basically a compilation of other smaller games. It takes place in a carnival.

See if you can find the easter egg! (Hint: It's in the maze)

How to play your game?
WASD to move, J to exit any game.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
good game! there is only one bug, the map crashes

**Comment by apzzd** [comment]
hmm. where do you find this bug?

**Comment by LucasHT22** [comment]
I will record my screen

**Comment by LucasHT22** [comment]
actually it's a little delay when you walk, is that intentional?

**Comment by apzzd** [comment]
It's not meant to have any delays - but for some reason that tends to happen when I have the Web Inspector open to look for errors. Maybe you had it open? Other than that, I don't get any delays.

**Comment by LucasHT22** [comment]
No, it's weird, check: https://user-images.githubusercontent.com/88567622/210660067-c2c232f2-10fd-4d88-99e5-0200eaed3f02.mp4

**Comment by apzzd** [comment]
That's so weird. I can't seem to replicate that error 😕

**Comment by SamDev-7** [comment]
@LucasHT22 It doesn't seem to be happening to me, odd.

**Comment by LucasHT22** [comment]
I will consider it as a problem in my notebook and I will merge

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
