### PR TITLE
Add Catch Orpheus game!

### PR DESCRIPTION
**Pull request by sampoder**
in this game, use WASD to try and 
catch Orpheus as she moves in all sorts
of directions! good luck!

made this small game as a demo at Sego Lily Hacks!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
simple but good game, could you add a background to make it more interesting?

**Comment by sampoder** [comment]
sure! (my goal isn't to get a sprig here, just made a small demo for the workshop I'm running)

**Comment by sampoder** [comment]
any recommendations for what would make a cool background?

**Comment by LucasHT22** [comment]
> sure! (my goal isn't to get a sprig here, just made a small demo for the workshop I'm running)

yes I know, I've seen you many times here and on Slack haha

**Comment by LucasHT22** [comment]
> any recommendations for what would make a cool background?

how about a green to represent grass?

**Comment by sampoder** [comment]
ooo! i like that idea

**Comment by LucasHT22** [comment]
very good Sam, congrats!

**Pull request merged**
