### PR TITLE
connectTheDots

### PR DESCRIPTION
**Pull request by ahowden27**
# Your checklist for this pull request

## About your game

What is your game about? 
Connecting all of the dots on each level.

How to play your game?
Press WASD to move the cursor, K to reset the level,  J on a dot to clear all tiles of that color, and I on a dot to toggle drag, which will enable you to draw a path to the corresponding dot.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Comment by Arpan-206** [comment]
Fantastic game, I love flow free! Although, if you can add a little text indicating the current level/total levels, that'd be lovely.

**Comment by ahowden27** [comment]
> Fantastic game, I love flow free! Although, if you can add a little text indicating the current level/total levels, that'd be lovely.

I have made this change, thank you for the suggestion!

**Comment by Arpan-206** [comment]
Looks fantastic!

**Comment by ahowden27** [comment]
> @Arpan-206 thanks! @ahowden27 great game! how to solve level 27?

here is a picture of level 27:

**Comment by ahowden27** [comment]
> @Arpan-206 thanks! @ahowden27 great game! how to solve level 27?

Here is the solution to lvl 27:
image

**Review by LucasHT22 — APPROVED** [review]
Sorry for the delay! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
