### PR TITLE
Street Fighter

### PR DESCRIPTION
**Pull request by akshatsinghania**
# Your checklist for this pull request

## Author name

**Author:** Akshat Singhania

## About your game

**What is your game about?**

A two player brutal battle with fists until one of the player loses.

**How do you play your game?**

Player 1 presses A,D to move, W to attack. Player 2 presses J,L to move and I to attack. Attack, move, push till one player loses all HP and the other player wins. Games reset automatically.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Thanks for the PR:) Please re-check this:
- [ ] The name of the file/game contains only alphanumeric characters, -s, or _s.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Not sure if I really understand how to play it, could you send a gameplay? Thanks:)

**Comment by aramshiva** [comment]
@LucasHT22 He sent a [video](https://hackclub.slack.com/archives/C02UN35M7LG/p1702758808694539) in slack!

**Comment by LucasHT22** [comment]
My apologies for the delay! Right, could you wait until tonight? I want to take a more careful review, and I'm back to my house this night:)

**Comment by akshatsinghania** [comment]
Not particularly but I remembered seeing multiplayer fighting games, and so got the idea to make a intense fist fighting game with a twist by being able to also push the opponent.

**Comment by LucasHT22** [comment]
Right, I think Street Fighter is copyrighted, what about Sprig Fighter?

**Comment by akshatsinghania** [comment]
I love that actually. Sounds perfect!

**Comment by LucasHT22** [comment]
Please rename it:)

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
