### PR TITLE
@shaileshsaravanan's better dino game

### PR DESCRIPTION
**Pull request by Shaileshsaravanan**
# Your checklist for this pull request

## Author name

**Author:**

## About your game

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Shaileshsaravanan** [comment]
my email: shaileshsaravanan385@gmail.com
I am a highschooler, grade: 11

**Comment by recursiveforte** [comment]
Hi- I can't approve this because it is too similar to another game: [color dino](https://github.com/hackclub/sprig/pull/2202). You could differentiate this game by changing the art and further differentiating the game mechanics.

**Comment by grymmy** [comment]
Looked at this today - awaiting response from author.

**Comment by grymmy** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
