### PR TITLE
FOOD-CATCH

### PR DESCRIPTION
**Pull request by jakob07ffm**
# For the record: PR #1119 

# Your checklist for this pull request

## Author name

**Author: Jakob**

## About your game

**What is your game about?**
Catch all the food falling from the sky. If you miss 3 the game is over!

**How do you play your game?**
Controll the player with a and d

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! There's 2 img files, also - is it foot or food? just a small typo :)

**Comment by jakob07ffm** [comment]
I am sorry for the many typos. I am not the best a english

**Comment by jakob07ffm** [comment]
There is again the problen that i dont know how to delete a Image. Do you know? I dont know if i asked you that before?

**Comment by LucasHT22** [comment]
> I am sorry for the many typos. I am not the best a english

Same here! Nw, I'm brazilian, my native language is portuguese, so I have the same problems haha

**Comment by LucasHT22** [comment]
> There is again the problen that i dont know how to delete a Image. Do you know? I dont know if i asked you that before?

I think it's a GitHub bug, I can't delete too, but nw! I can delete after merge

**Comment by LucasHT22** [comment]
> I am trying it again with a new pull request. I am sorry :(

No worries!

**Pull request closed without merging**
