### PR TITLE
Maze game

### PR DESCRIPTION
**Pull request by darshanC07**
# Maze Game

# Your checklist for this pull request

## Author name

**Author: Darshan Choudhary**

## About your game

**What is your game about?**
My Game is about a Simple Maze...A maze is a complex network of paths or passages, typically designed as a puzzle or challenge, where the goal is to find a route from the entrance to the exit. Mazes vary widely in complexity and size, often found in games, puzzles, or architectural designs. Also to make the game interesting, I have provided a feature to collect coins. Players can collect coins and at the end, the total coins collected by the player will be displayed

**How do you play your game?**
The game is very easy to play..Players can start the game by pressing 'k' at starting frame and then pressing WASD to move.
press J to reset the level. At the top, there's a coin counter, and at the bottom, there's the current level number.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by darshanC07** [comment]
Helloo  GalaxyGamingBoy, I am not able to understand some things on this page....
Is my game rejected?? Or should I make some changes and then reapply?

**Comment by GalaxyGamingBoy** [comment]
Cool maze game so far but it would be great to add more novel game mechanics in order to make your game unique, to stand out, and of course to meet the necessary quality standard in order to receive a sprig hardware grant

**Review by GalaxyGamingBoy — CHANGES_REQUESTED** [review]
Cool maze game so far but it would be great to add more novel game mechanics in order to make your game unique, to stand out, and of course to meet the necessary quality standard in order to receive a sprig hardware grant

**Comment by darshanC07** [comment]
hello reviewer, i added a new feature in my of shop where player can earn coins while coming out of maze and then use those coins to buy new backgrounds for maze...everything is working perfectly...without any errors...
can please you re-review game....

**Review by GalaxyGamingBoy — APPROVED** [review]

**Comment by GalaxyGamingBoy** [comment]
Amazing! I really like the background switch and shop feature, makes coin collection fun. FYI, if you're a teen and haven't already received one, please feel free to fill out [this form](https://sprig-order.hackclub.dev/) to get it! Additionally, feel free to join Hack Club's Slack and share your creation in the #sprig channel!

**Comment by darshanC07** [comment]
Thank you so much @GalaxyGamingBoy for approving the game, yes I am filling the form.. 
Just one question... In india, the customs on sprig is very high, one of my relative lives in USA, so will it be fine if I mention his address in sprig order form??

**Comment by GalaxyGamingBoy** [comment]
Make sure to put the address you want the sprig to be shipped at! If your relatives forward it to you I still think that you will need to pay customs but I'm not sure

**Pull request merged**
