### PR TITLE
Maze runner

### PR DESCRIPTION
**Pull request by wetf**
You spawn in a maze and try to get to the little box at the end

### CODE REVIEW

**Comment by SamDev-7** [comment]
Thanks for the PR! Cool game, however, it would be awesome if you added more to it.
Consider adding more levels, mechanics, or even sounds to make it special and unique. 
Things like keys and doors could be a potential addition.

Great start! Try to add something more unique before it gets added to the gallery though.
Let us know if you run into any issues, happy hacking!

**Review by LucasHT22 — COMMENTED** [review]
The game's intent is cool, but there's no way to lose or compete (via a timer analysis for example), just be persistent and go from level to level.
Consider changing the default sprite, add obstacles and complicating levels.

Be creative! It takes a while, but you can do it :)

Also, I'm getting a strange error:
`Uncaught TypeError: b.trim is not a function on line 1672 in column 1807. Open the browser console for more information.
`

**Comment by wetf** [comment]
I updated it, but how do I give you the update?

**Comment by leomcelroy** [comment]
You can just push to your branch again!

**Comment by LucasHT22** [comment]
Great update! The game is much more interesting :)

If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
