### PR TITLE
Push_The_Box

### PR DESCRIPTION
**Pull request by NetanelGuber**
# Your checklist for this pull request

## Author name

**Author:**

Sandy Burger

## About your game

**What is your game about?**

You are a player that can move
Your goal is to push the box to the button
Once the box has been pushed to the button, you will advance to the next level
There are different game mechanics such as spikes and togglable walls that can be toggled by pushing the box on a toggle button
If you or your box touches a spike it will restart the level
There are 15 levels that I think are kind of puzzling

**How do you play your game?**

Press WASD to move, J to restart the level if you are stuck, and i (only in the beginning where there is text)

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo"). (hopefully)
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Hey! Thanks for your PR! I'll review it:)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Where did you hear about Sprig?

**Comment by NetanelGuber** [comment]
I heard about sprig from engineering club that I have at school, they said it was their sponsor so I decided to make this game

**Comment by SamDev-7** [comment]
Fill out the form at https://hack.af/slack and  check your email! Let us know if you encounter any issues along the way.

**Pull request merged**
