### PR TITLE
It_Is_Coming_Out!

### PR DESCRIPTION
**Pull request by Onovez**
## About your game

What is your game about? 
The player has to eat food and find the way to the toilet to poop then go through the door to progress to the next level.

How to play your game?
To move the player its 'w','a','s','d' since its common to use these, 'j' is to reset the map, 'k' is to restart the entire game. 
the main goal for the game is to eat food then go to toilet to poop.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Just one thing, `'` are not allowed in the title

**Comment by Onovez** [comment]
How do I change the File? I have a new name for it and I want to use that

**Comment by LucasHT22** [comment]
the image just deleting and adding again

**Review by LucasHT22 — APPROVED** [review]
No problem! I will merge and change the name. Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by Onovez** [comment]
Can a school transcript work? I have lost my School ID card and everyone throws the schedule away after a week

**Comment by LucasHT22** [comment]
> Can a school transcript work? I have lost my School ID card and everyone throws the schedule away after a week

Yep!

**Comment by Onovez** [comment]
Thank you!

**Pull request merged**
