### PR TITLE
ConnectX

### PR DESCRIPTION
**Pull request by siddhp1**
# Your checklist for this pull request

## Author name

Siddh Patel

## About your game

Connect 4 with a twist! Two players duke it out over 10 rounds from Connect 3 to Connect 12. Winner is the one that takes the most rounds by the end!

Press A and D to move the cursor (which is red if you are the red player and vice versa) and K to place a chip in that column. Get a Connect X (which is stated at the start of the round) to win the round. Players get 1 point for a round win and 0.5 each for a draw. 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for PR! Where did you hear about Sprig?

**Comment by siddhp1** [comment]
As the co-president of my school's Hack Club chapter, I first heard about Sprig during our onboarding meeting with Holly. Throughout the past two months, our chapter members all made their own Sprig games.

**Comment by LucasHT22** [comment]
> As the co-president of my school's Hack Club chapter, I first heard about Sprig during our onboarding meeting with Holly. Throughout the past two months, our chapter members all made their own Sprig games.

Nice! Do you know some games from your club?

**Comment by siddhp1** [comment]
I do not know their names off the top of my head, but a few students made some puzzle games (similar to bloxorz) and we also had a few platformers.

**Comment by LucasHT22** [comment]
> I do not know their names off the top of my head, but a few students made some puzzle games (similar to bloxorz) and we also had a few platformers.

Not even 1? Or your school name? If you prefer you can send me for DM at Slack (`@lucas`)

**Comment by siddhp1** [comment]
I go to Heart Lake Secondary School in Brampton, Ontario, Canada. At the end of 2023, our club ran workshops where we used the Sprig editor to make different games. Since we haven't had a club meeting in a few weeks (due to the exam season), I am unaware of whether my club members completed and submitted their Sprig games. I can get a list of the submitted games, or the number of students that are going to submit their games in the future at our next meeting.

**Review by LucasHT22 — APPROVED** [review]
Oh, right! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
