### PR TITLE
Monkey Catch Food

### PR DESCRIPTION
**Pull request by Ahmet-Dedeler**
# Your checklist for this pull request

## Author name

**Author: Ahmet Dedeler**

## About your game

**What is your game about?**

You're playing as a monkey trying to catch the falling fruits! There are power ups (like the lifrefruit and speed booster), dangerous objects (like TNTs!) and more! The goal is to catch as many fruits as possible without running out of lives.

**How do you play your game?**

You can use 'A' to move left, 'D' to move right, and 'J' to jump. 

Pretty simple and easy to play.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Ahmet-Dedeler** [comment]
Here is a demo of the game! You are able to jump, and move around the area to catch all the fruits and power-ups!

Monkey Catch Food

**Comment by grymmy** [comment]
oh Ahmet this is so cool, I can't wait to play, thanks for your submission!!!

**Comment by Ahmet-Dedeler** [comment]
> oh Ahmet this is so cool, I can't wait to play, thanks for your submission!!!

I'm glad to hear that you liked the game!

**Comment by Ahmet-Dedeler** [comment]
@grymmy Hey there, I'm wondering is there anything else I have to do?

**Comment by Ahmet-Dedeler** [comment]
@grymmy  Hey there, I'm wondering is there anything else I have to do?

btw I think the workflows started over again by mistake although they were finished before 😅

**Comment by LucasHT22** [comment]
Hey @Ahmet-Dedeler ! I'll follow with thisa review:) Graham is on vacation. Don't worry about workflows:)

**Comment by LucasHT22** [comment]
Where did you hear about Sprig?

**Comment by Ahmet-Dedeler** [comment]
Hey @LucasHT22! Thanks for looking into it!

I heard about sprig from the hackclub slack, found it fun and decided to make a game! You can check out the gameplay I shared with Graham!

**Review by LucasHT22 — APPROVED** [review]
I played and it's really good game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
