### PR TITLE
Starjump

### PR DESCRIPTION
**Pull request by skifli**
# Your checklist for this pull request

## Author name

**Author:** @skifli

## About your game

It is a maze where you have to get to the star to finish each level, and sometimes there are keys you must first access for the star to work and teleport you to the next level.

**How do you play your game?**

- WASD to move.
- K to reset the level.
- L to go the next level (if at a star and keys have been obtained).

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

> [!NOTE]\
> Not used.

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR!! Where did you hear about Sprig?

**Comment by skifli** [comment]
> Thanks for your PR!! Where did you hear about Sprig?

Someone recommended it to me in the Hackclub slack, which I found from a GitHub Eduation newsletter.

**Comment by skifli** [comment]
Sorry, not sure what changes you requested so would you mind sending them here?

**Comment by skifli** [comment]
Oh wait I just realised it was the question, oops 😄.

**Comment by LucasHT22** [comment]
> > Thanks for your PR!! Where did you hear about Sprig?
> 
> Someone recommended it to me in the Hackclub slack, which I found from a GitHub Eduation newsletter.

This month newsletter?

**Comment by skifli** [comment]
> > > Thanks for your PR!! Where did you hear about Sprig?
> > 
> > 
> > Someone recommended it to me in the Hackclub slack, which I found from a GitHub Eduation newsletter.
> 
> This month newsletter?

Yep.
image

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay! Out of curiosity, did you use any game for inspiration?

**Comment by skifli** [comment]
> Sorry for the delay! Out of curiosity, did you use any game for inspiration?

No, but the idea for stars was from Terraria because I've been playing a lot of it recently.

**Comment by LucasHT22** [comment]
Right but did you use any code from other game?

**Comment by skifli** [comment]
> Right but did you use any code from other game?

Nope.

**Comment by LucasHT22** [comment]
Wasn't misunderstanding was 2 different questions:) I'm asking bc i noticed some similarities in the timer mechanism

**Comment by skifli** [comment]
> Wasn't misunderstanding was 2 different questions:) I'm asking bc i noticed some similarities in the timer mechanism

Ah ok 👍 .

**Comment by LucasHT22** [comment]
again, did you use any code from other game?

**Comment by LucasHT22** [comment]
(This won't stop you from get the console)

**Comment by skifli** [comment]
> again, did you use any code from other game?

No, however I did use the code supplied in the getting started tutorial so maybe that is why it is similar?

> Wasn't misunderstanding was 2 different questions:) I'm asking bc i noticed some similarities in the timer mechanism

Also which part do you mean by timer mechanism, I'm not sure what that is referring to.

**Comment by LucasHT22** [comment]
oh wait, really sorry!! I noted the wrong PR number, this is to merge:)

**Review by LucasHT22 — APPROVED** [review]
Great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by skifli** [comment]
> oh wait, really sorry!! I noted the wrong PR number, this is to merge:)

Haha, it's fine, happens to the best of us.

**Pull request merged**
