### PR TITLE
Lava the Impossible maze Sprig submission 

### PR DESCRIPTION
**Pull request by EZCODEAZGOD**
## Lava the Impossible maze

What is your game about? 
> Example: getting to the goal

How to play your game?
> Example  : Press WASD to move, J to restart

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
good game! Could you slow down the last few levels? can get too small on the console

**Comment by EZCODEAZGOD** [comment]
> 

How do I do that? What do you mean by “slow down”? Thx

**Comment by LucasHT22** [comment]
> > 
> 
> How do I do that? What do you mean by “slow down”? Thx

Sorry, I mean reducing the size

**Comment by EZCODEAZGOD** [comment]
> 

So do I have to repost the code?

**Comment by LucasHT22** [comment]
just a update, `Files changed` > `...` > `Edit file`

**Comment by LucasHT22** [comment]
I think it's better to reduce it a little more... sorry, but how do you solve levels 5,6,7,8?

**Comment by EZCODEAZGOD** [comment]
> I think it's better to reduce it a little more... sorry, but how do you solve levels 5,6,7,8?

Go into the slack, I’ll dm a speedrun

**Comment by EZCODEAZGOD** [comment]
I’ll do it when I get the chance

**Comment by LucasHT22** [comment]
I'm on Slack @ Lucas Honda

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats :)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
