### PR TITLE
Mirror_Snake

### PR DESCRIPTION
**Pull request by funnoodle11**
# Your checklist for this pull request

## Author name

**Author:** 
funnoodle11

## About your game

**What is your game about?** 
Eat apples, increase your score, but don't hit a wall or your mirrored snake.

**How do you play your game?**
Use WASD to move. You control the blue snake, while the orange snake mirrors your movements. Have your snake or the mirrored snake eat apples to increase your length. Don't run into walls, or the other snake.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
great game! did you use any game for inspiration?

**Comment by funnoodle11** [comment]
> great game! did you use any game for inspiration?

thanks! my main inspiration was the google snake game, where there is a very similar gamemode to the one i made.

**Review by LucasHT22 — APPROVED** [review]
Ok! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Where did you hear about Sprig?

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by funnoodle11** [comment]
Thank you! I heard about sprig through hackclub's website. i filled out the form, so when can i expect the sprig to arrive?

**Comment by LucasHT22** [comment]
it depends on the country where you live, where are you from?

**Comment by funnoodle11** [comment]
i live in the US

**Comment by LucasHT22** [comment]
Probably in 15 days it will be with you!

**Comment by funnoodle11** [comment]
ok, thank you!

**Pull request merged**
