### PR TITLE
Nerds_Shall_Perish

### PR DESCRIPTION
**Pull request by ABSolute-L00ser**
# Your checklist for this pull request

## Author name
NoneOYoConcern
**Author:**
Gideon M. Hannsz

TrueCaedmonman
## About your game
it is very game-like
**What is your game about?**
pushing boxes and 

**How do you play your game?**
wasd to move, j to restart, and k to change the music

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Comment by ABSolute-L00ser** [comment]
At school

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LucasHT22** [comment]
> what is this change request 

Just for control purpose
> This whole thing seems pretty sketchy

What would you do to make my work better?

**Comment by Sheepy3** [comment]
Closing this PR due to inactivity. Please feel free to ping me and have this reopened / hopefully merged!

**Pull request closed without merging**
