### PR TITLE
Eat the cake

### PR DESCRIPTION
**Pull request by klyap**
A mini game about choices...

### CODE REVIEW

**Comment by sampoder** [comment]
sorry misclicked!

**Comment by sampoder** [comment]
@klyap could you create a new PR? this sounds like a wonderful game, I just misclicked!

**Comment by leomcelroy** [comment]
Hey @klyap sorry about the mix-up! Just wanted to follow-up to see if you can refile this PR.

**Comment by klyap** [comment]
Ahh just saw this, @leomcelroy ! I will re-file!

**Pull request merged**
