### PR TITLE
Sprigorous Vigor

### PR DESCRIPTION
**Pull request by boston2029**
# Your checklist for this pull request

## Author name

**Author:**
Bost

## About your game

**What is your game about?**
A mysterious maze that you need to get to the end of.

**How do you play your game?**
WASD to move, L to restart. Get to the portals to progress. Move pushables to get to the portals

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used) (N/A)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by GalaxyGamingBoy** [comment]
Hey I really love how this game is going but to make it even better (and to match the sprig grant criteria) it would be amazing to add some more game mechanics, like enemies on the "run" level.

**Review by GalaxyGamingBoy — CHANGES_REQUESTED** [review]
Hey I really love how this game is going but to make it even better (and to match the sprig grant criteria) it would be amazing to add some more game mechanics, like enemies on the "run" level.

**Comment by boston2029** [comment]
@GalaxyGamingBoy I added some more levels and made the portal move around where you have to time it right. Also, I added a title screen.

**Comment by GalaxyGamingBoy** [comment]
Looks great now, love the timing level! If you're a teenager, and you haven't already received a Sprig device, feel free to fill out [this form](https://sprig-order.hackclub.dev/) to receive one! Also, feel free to join Hack Club's Slack in the #sprig channel to share your creation w/ others!

**Pull request merged**
