### PR TITLE
IMG Tag

### PR DESCRIPTION
**Pull request by GalaxyGamingBoy**

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
And what happen with people's images?

**Comment by GalaxyGamingBoy** [comment]
per the bug report, the img tag is not used anymore. The image gets dynamically fetched on load

**Comment by Sheepy3** [comment]
this is marked as changes requested, are there actually any changes to be made here @LucasHT22 ?

**Review by Cosmin-Mare — APPROVED** [review]
Changes look good to me! On a side note, can't we just remove the img tags altogether and also remove them from the starting code?

**Comment by GalaxyGamingBoy** [comment]
PR is already out for that, pending reviews

**Pull request merged**
