### PR TITLE
Tic-Tac-No

### PR DESCRIPTION
**Pull request by 0jas0jas**
# Your checklist for this pull request

## About your game

What is your game about? 
Tic-Tac-No is a modded version of the classic Tic-Tac-Toe which attempts to make the classic game more interesting. In here, you AVOID placing three crosses consecutively.

Both players play with Xs.
Players take turns to place their X trying to PREVENT a triple X from being formed
The player who completes a triple X LOSES :(

How to play your game?
    w, a, s, d to control the pointer
    j to place a cross

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Apologies for the delay! Looks like the win criteria are kinda weird

**Comment by 0jas0jas** [comment]
Hi! I'll try to fix it right away.

**Comment by 0jas0jas** [comment]
Fixed, yay!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
hmm was it for when you reach 4 x the game decide who wins?

**Comment by 0jas0jas** [comment]
The player who makes the 3Xes in a row LOSES. It's bending the rules of the original game. The problem was that when the game ends, any movement buttons you press would cause an error because, well, there IS no player after the game ends.

**Review by LucasHT22 — APPROVED** [review]
oh, right! Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by 0jas0jas** [comment]
Thank you so much, @LucasHT22 !

**Pull request merged**
