### PR TITLE
Asteroid Field

### PR DESCRIPTION
**Pull request by haileyhapi**
## About your game

What is your game about? 
Lost in space and floating through an asteroid field, on an endless journey to try and find any semblance of a home.

How to play your game?
Press WASD to move, and go for the goal in the asteroid field.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Comment by LucasHT22** [comment]
great game! however we have several similar to this one in the gallery, add some other mechanism in the game such as power-ups, in short there are countless possibilities:)

**Comment by haileyhapi** [comment]
actually that's a great idea!
i have some ideas of how i could polish it, I'll get on those today!
thanks for the feedback! :D

**Comment by SamDev-7** [comment]
@haileyhapi How's it going? Let us know if you need any help!

**Comment by haileyhapi** [comment]
honestly I've been a bit busy with school and general life stuff, but i might have time to put some work into it today or tomorrow!

**Comment by LucasHT22** [comment]
no problem!

**Comment by LucasHT22** [comment]
Great changes!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
