### PR TITLE
Add `squarey_runs_away_from_the_fireball`

### PR DESCRIPTION
**Pull request by sampoder**
###### I'm submitting on behalf of Jack Mole (my cousin who is too young to have a GitHub account). We visited over the CNY break and built this game together.

# Your checklist for this pull request

## About your game

This game is a two-player game where the fire needs to catch "Squarey" (a character in my cousin's cinematic universe). WASD controls Squarey and IJKL controls the fire.

After 30 seconds, press any key to restart. You win if you survive 30 seconds.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
how old is your cousin? 👀

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! Should the timer continue after Squarey's death?

**Comment by sampoder** [comment]
> how old is your cousin? 👀

he's in Year 5 (Grade 5) at school!

**Comment by sampoder** [comment]
> Good game! Should the timer continue after Squarey's death?

Done!

**Comment by LucasHT22** [comment]
> > how old is your cousin? 👀
> 
> he's in Year 5 (Grade 5) at school!

WOW!

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
you can get his sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
