### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tigerflame777**
This game is a fun, simple music maker game. You just move the character to the different coloured blocks and play some music! The multi coloured blocks are pre-written songs made by me. You can use the I, J, K, L keys for extra notes. 

This is my 4th game for the sprig.

### CODE REVIEW

**Comment by LucasHT22** [comment]
I already lost the amount of games you have haha

**Review by LucasHT22 — APPROVED** [review]
In this case it's not a game, it's an experience! anyway, very good!
You're using it for hacktoberfest, right?

**Comment by tigerflame777** [comment]
> In this case it's not a game, it's an experience! anyway, very good! You're using it for hacktoberfest, right?

What's the hacktoberfest?

**Comment by LucasHT22** [comment]
" HACKTOBERFEST IS FOR EVERYONE. WHETHER IT’S YOUR FIRST TIME—OR YOUR NINTH—IT’S ALMOST TIME TO HACK OUT FOUR PRISTINE PULL/MERGE REQUESTS AND COMPLETE YOUR MISSION FOR OPEN SOURCE." https://hacktoberfest.com/

**Comment by LucasHT22** [comment]
you have a good profile for hacktoberfest

**Comment by LucasHT22** [comment]
do you have slack? join the hack club community! https://hackclub.com/slack/

**Pull request merged**
