### PR TITLE
Basketball Game

### PR DESCRIPTION
**Pull request by De-y**
# Your checklist for this pull request

## Author name

**Author: Dheeraj**

@de-y
## About your game

**What is your game about?**
My game is about a person who is sentenced to shoot hoops, the game is a simple top-down basketball game with enemies and spikes (stationary) and make your way to the hoop & score.

image

**How do you play your game?**
Using WASD to move and J to reset the game if you die (also in general)

You also have some unknown levels.

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game:) Whats the name of the game? The file says one and the code another

**Comment by De-y** [comment]
I would call it basketball game but it could also be called inception

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right, Where did you hear about Sprig?

**Comment by De-y** [comment]
> Right, Where did you hear about Sprig?

I heard about Sprig from the website, which I was then fascinated by and wanted to make my own game.

**Comment by LucasHT22** [comment]
Hack Club website or ?

**Comment by De-y** [comment]
Hack Club website when I just scrolled down

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right, Did you win the game? It's hard haha

**Comment by De-y** [comment]
> Right, Did you win the game? It's hard haha

I did, but I had to restart a lot

**Pull request closed without merging**
