### PR TITLE
I added a file for a game I made for sprig.

### PR DESCRIPTION
**Pull request by PerrinPerson**
My dad showed me sprig, and I was wanting to get a game done and up on your gallery. I had a lot of fun making this, and this is an awesome project!

### CODE REVIEW

**Comment by LucasHT22** [comment]
I'm happy to hear you liked the Sprig!

**Comment by LucasHT22** [comment]
Thanks for PR :)

**Review by LucasHT22 — COMMENTED** [review]
good game!

**Comment by PerrinPerson** [comment]
> good game!

Thanks!

**Comment by LucasHT22** [comment]
we usually use j to restart the game

**Comment by PerrinPerson** [comment]
want me to change that real quick?

**Comment by LucasHT22** [comment]
please :)

**Comment by LucasHT22** [comment]
Is this your first programming experience?

**Comment by PerrinPerson** [comment]
yes it is, so I got my dad to help me

**Comment by LucasHT22** [comment]
oh, nice!

**Comment by PerrinPerson** [comment]
Fixed it!

**Review by LucasHT22 — APPROVED** [review]
Congrats!
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by PerrinPerson** [comment]
thanks!

**Comment by LucasHT22** [comment]
make more games on Sprig :)

**Comment by LucasHT22** [comment]
Check https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/Zooter.js

**Comment by PerrinPerson** [comment]
This is really awesome that you guys are doing this, and thank you for the sprig!

**Comment by LucasHT22** [comment]
I'm glad to hear this! Keep making games on Sprig :)

**Comment by LucasHT22** [comment]
join our Slack for more! https://hackclub.com/slack/

**Comment by PerrinPerson** [comment]
got ya :)

**Pull request merged**
