### PR TITLE
4_Colour_Drawing

### PR DESCRIPTION
**Pull request by Speedlet1**
# Your checklist for this pull request

## Author name

Dexter Speed

## About your game

A 4 colour drawing game using a similar colour palette to the original gameboy except shades of grey rather than green. It has a resolution of 20x18, but this can easily be adjusted in the Sprig editor if a higher or lower resolution is wanted!

**How do you play your game?**

WASD moves the cursor, I places black, K places dark grey, L places light grey and J places white

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! Have you already done a PR/contributed here on Sprig? GitHub says yes but I don't remember you around here

**Comment by Speedlet1** [comment]
Yeah, I developed the Amazing_Mazes simple game as my first experiment, and thought I'd try to develop some more tools similar to those that I've used for some of my projects at school!

**Comment by LucasHT22** [comment]
Right! Just saw that your author name in the other game is DLSFG, would you prefer use the same name or use the name of this PR or rename your another name to this or?

**Comment by Speedlet1** [comment]
Please could I use use the PR name for it please? As long as it's not too
much of a hassle in which case I'll happily use DLSFG for this one as well

**Comment by Speedlet1** [comment]
And rename the old one as well if that's not a problem. If it's too much
trouble then don't worry about it

**Comment by Speedlet1** [comment]
Sorry I completely forgot I used a different name for the other game 😅

**Comment by LucasHT22** [comment]
No worries! I can change simply changing a json file:)

**Comment by LucasHT22** [comment]
Congrats for your 2nd PR here!

**Pull request merged**
