### PR TITLE
pr again

### PR DESCRIPTION
**Pull request by cott3**
# Your checklist for this pull request

## Author name

Efe Özülkü

## About your game

You are an amazon delivery person and you need to deliver all the packages to the adresses.

**How do you play your game?**

 Press WASD to move, J to restart 

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! How to solve this level? 
image

**Comment by cott3** [comment]
so the player can go thru potholes but boxes cant

**Comment by LucasHT22** [comment]
oh right, my bad! Please make sure of this: The name of the file/game contains only alphanumeric characters, -s, or _s. , you can change going to `Files changed` > `...` > `edit`

**Comment by cott3** [comment]
done!

**Review by LucasHT22 — APPROVED** [review]
Alright, Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
