### PR TITLE
Pluffy_The_Cage_Bird

### PR DESCRIPTION
**Pull request by ioNihal**
# Your checklist for this pull request

## Author name

**Author: Nihal K**

## About your game

**What is your game about? : It is about a bird that want to reach its home (cage) and throughout the way to home the bird faces many challenges!**

**How do you play your game? : Move Using W ,S, D, A and Press J to restart the current level, Press I to restart game(To level zero), Move the Bird to the Cage**

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Don't worry about Vercel and workflows:) where did you hear about Sprig?

**Comment by ioNihal** [comment]
I was scrolling through my email

**Comment by ioNihal** [comment]
I learnt sprig overnight 🫠 till 3am

**Comment by ioNihal** [comment]
> Hey! Don't worry about Vercel and workflows:) where did you hear about Sprig?

I was scrolling through my email and i found an invite so I learnt sprig overnight 🫠 till 3am

**Comment by ioNihal** [comment]
@LucasHT22

**Comment by ioNihal** [comment]
@LucasHT22 if you want me to change anything in that game, just ask me here, thanks

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay! Out of curiosity, did you use any game for inspiration?

**Comment by ioNihal** [comment]
> Sorry for the delay! Out of curiosity, did you use any game for inspiration?

Sure i was trying to make a fluffy bird game, then i thought about making a new story so turned in to maze game. Also there is a lack of resource support with me🥲, i am coding in a half display broken 13yr old laptop

**Comment by LucasHT22** [comment]
13y... Wow... did you use code from any other game in the gallery?

**Comment by ioNihal** [comment]
> 13y... Wow... did you use code from any other game in the gallery?

Not really but i just referred to the first sprig tutorial

**Comment by LucasHT22** [comment]
Did you use any code from other game?

**Comment by ioNihal** [comment]
> Did you use any code from other game?

No

**Comment by LucasHT22** [comment]
This will not take away your opportunity to win a console, are you sure?

**Comment by ioNihal** [comment]
Yeah i am sure! There is nothing complex in there just movement and timout function to countdown time and some statements to check to the position of character and the goal

**Comment by ioNihal** [comment]
> This will not take away your opportunity to win a console, are you sure?

Yeah i am sure! There is nothing complex in there just movement and timout function to countdown time and some statements to check to the position of character and the goal

**Comment by LucasHT22** [comment]
I noticed some similarities:
https://cloud-dnil6o7wo-hack-club-bot.vercel.app/020231223-1734-49.9695611.mp4

**Comment by ioNihal** [comment]
> I noticed some similarities:
> https://cloud-dnil6o7wo-hack-club-bot.vercel.app/020231223-1734-49.9695611.mp4

Technically if that is what you think, thats not like that i didnt start from clicking new game, first i saw fluffy bird game, that game is not working, so i tried fixing and it didn't work, in the same canvas i re write an new code entirely changing old one like in the same canvas redrawing something by erasing old one, you can see that i deleted all sprite added new only kept the bird and bg,

So its basically new code new idea

**Comment by ioNihal** [comment]
And the timeout function is also a complete re build not copied if you think so

**Comment by ioNihal** [comment]
Thats what i said i first tried making a fluffy bird game than i made another game

**Comment by ioNihal** [comment]
It was 2 pillers first not a maze, fyi
(ig if you can see changes of that game then you see the difference is big too)

**Comment by ioNihal** [comment]
> I noticed some similarities:
> https://cloud-dnil6o7wo-hack-club-bot.vercel.app/020231223-1734-49.9695611.mp4

Btw this is not the game i opened,
This author name different and that game didn't work also

**Comment by LucasHT22** [comment]
That's what I was expecting to hear! Please add in header that you inspired in Flurffy game:)

**Comment by ioNihal** [comment]
> That's what I was expecting to hear! Please add in header that you inspired in Flurffy game:)

Ohh, <3

**Pull request merged**
