### PR TITLE
King of the hill

### PR DESCRIPTION
**Pull request by Sybrx**
# Your checklist for this pull request

## Author name
Sol Y
**Author:**

Sybrx
## About your game

**What is your game about?**
Push the other player into the pits to get a point

**How do you play your game?**
press WASD to move for player 1, press IJKL for player 2

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR!

**Comment by Sybrx** [comment]
how do i know if it's accepted

**Comment by UserJHansen** [comment]
This game is very fun, perhaps some way to tell the score without having a player die would be good too?

**Comment by savinajabbo** [comment]
Your game is so creative!! I love the idea, and a two-player game is always fun. What about adding a time limit for the game to add more of a challenge? Also, what about leaving the score up throughout the game so the players can see it as they play? :D

**Comment by leomcelroy** [comment]
Thanks for sharing your project! This game needs more work before it can earn a Sprig. I'm going to close this for housekeeping but please resubmit in the future when you are ready.

**Pull request closed without merging**
