### PR TITLE
Chrome Dino Game

### PR DESCRIPTION
**Pull request by blazecoding2009**
# Your checklist for this pull request

**Author: Arnnav Kudale**

## About your game

**What is your game about?**
My game is a almost 1 to 1 replica of the offline chrome dino game with a few addons (mainly just colors)

**How do you play your game?**
There's only one button which you need to press to do everything, W. W to start, W to jump, W to restart.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

### CODE REVIEW

**Comment by OtterCodes101** [comment]
isn't this already on the sprig website?

**Comment by blazecoding2009** [comment]
> isn't this already on the sprig website?

I did see one but this is imo pretty different from that one

**Comment by OtterCodes101** [comment]
thats just my 2 cents, you should probably wait till an actual HackClub reviewer comes by to check this PR out.

**Review by GalaxyGamingBoy — CHANGES_REQUESTED** [review]
Really cool game with quality but it would be great to add some more novel game mechanics like power-ups as to difference it from the other [chrome dino game ](https://sprig.hackclub.com/gallery/dino-game)in the gallery. Even tho the sprites are quite different, the logic and gameplay loop feels really similar!

**Comment by blazecoding2009** [comment]
> Really cool game with quality but it would be great to add some more novel game mechanics like power-ups as to difference it from the other [chrome dino game ](https://sprig.hackclub.com/gallery/dino-game)in the gallery. Even tho the sprites are quite different, the logic and gameplay loop feels really similar!

Hey @GalaxyGamingBoy 
Thanks for reviewing my PR!
I'm going for a retro-style for this game, trying to make it as close as the actual game.
If this is preventing me from getting a Sprig, I'll add some more mechanics such as power-ups like you said but I'd like to keep it as "retro" as possible.

**Comment by blazecoding2009** [comment]
@GalaxyGamingBoy I've added an invincibility powerup to the game, please let me know if I need to add anything else.

**Review by grymmy — CHANGES_REQUESTED** [review]
You don't need to jump to gain score.  Plz this fix.

**Review by grymmy — APPROVED** [review]
Nevermind.  I misunderstood actually, there may not be a bug.

**Comment by grymmy** [comment]
Congratulations!  If you're a teenager, and you haven't already received one, plz fill out this form to receive a Sprig device of your own!  Also please feel free to join Hack Club's Slack and share your creation in the #sprig channel!

**Pull request merged**
