### PR TITLE
The Sky Is Falling For Real This Time

### PR DESCRIPTION
**Pull request by leTable**
# Your checklist for this pull request

## About The Game

What is your game about? 
The "Sky," or group of clouds, is falling. You, the player, must dodge the sky and get a new highscore!

How to play your game?
Use A and D to move left and right. That's it. It's that simple.

## Code
Check off the items that are true. 
- [X ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [X ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X (Used a tutorial, not sure if others used the same) ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ X] The game runs without errors. 
- [ X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Remember me Stumble Guys (idk why haha), just one thing, () is not allowed in the title

**Comment by leTable** [comment]
> Great game! Remember me Stumble Guys (idk why haha), just one thing, () is not allowed in the title

What do you mean Stumble Guys? I fixed the title, am I eligible for a Sprig?

**Comment by LucasHT22** [comment]
> What do you mean Stumble Guys? 
image

> I fixed the title, am I eligible for a Sprig?
If you're a teen, yes

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
