### PR TITLE
Update CSS to add PCB background and improve contrast

### PR DESCRIPTION
**Pull request by jzaleta**

### CODE REVIEW

**Comment by jzaleta** [comment]
@LucasHT22 I merged the main branch into my patch branch to solve the conflicts and to trigger the Vercel Preview:

Captura de pantalla 2023-05-20 a la(s) 13 39 38

**Comment by jzaleta** [comment]
I also updated the color of the text on the editor to have more contrast:

Captura de pantalla 2023-05-20 a la(s) 14 40 07

**Review by kognise — CHANGES_REQUESTED** [review]
Thank you for the contribution! And sorry for taking so long to review, this slipped by me.

I like this in theory but I think the new PCB background is a little dark. It feels distracting and also makes it hard to read the text in front. Do you want to perhaps try lightening it a lot to be closer to the background color and have less contrast?

**Comment by jzaleta** [comment]
Sure! I'll try to make it more similar to the background.

**Comment by jzaleta** [comment]
@kognise , should I edit the color directly on the current PCB svg with css or upload a new svg element with the new color?

**Comment by kognise** [comment]
Alright, as long as `pcb.svg` isn't used anywhere else?

**Comment by jzaleta** [comment]
Huh the deployment is still using the old color but this is how the svg element looks now:

Captura de pantalla 2023-06-01 a la(s) 17 55 46

**Comment by jzaleta** [comment]
Hi! Sorry for the merge issues, I'll try to fix this locally and after that the PR would be ready to check, meanwhile is going to be a draft.

**Pull request closed without merging**
