### PR TITLE
AirHockey

### PR DESCRIPTION
**Pull request by BLADE9078**
# Your checklist for this pull request

## Author name

**Author:**

## About your game

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for the PR! please answer this:

## Author name

**Author:**



## About your game

**What is your game about?**



**How do you play your game?**

**Comment by BLADE9078** [comment]
AUTHOR - SOUMAY MANDERNA
my game is about the air hockey in which a puck and two paddles are there
It's a two player game
I play my game in real life too and i thought i should build one for sprig
too

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
ok, You are from the Thread in Slack, right?

**Comment by BLADE9078** [comment]
Yes i am that only

**Comment by BLADE9078** [comment]
So is my game approved for sprig?

**Comment by LucasHT22** [comment]
So add this to code header

**Comment by BLADE9078** [comment]
> So add this to code header

done!!!

**Comment by LucasHT22** [comment]
Great! please re-check this:
- [ ] The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by BLADE9078** [comment]
> Great! please re-check this:
> 
> * [ ]  The name of the file/game contains only alphanumeric characters, -s, or _s.

i didn't get that
can you explain a bit

**Comment by LucasHT22** [comment]
your game file name must not contain spaces

**Comment by BLADE9078** [comment]
How can i edit that?

**Comment by BLADE9078** [comment]
> your game file name must not contain spaces

umm.......i think now it's okay

**Comment by Tiger-The-Cat** [comment]
I think Lucas is saying that the actual game file at `/games/Air Hockey (1).js`, but it should be at `/games/AirHockey.js`.

**Comment by BLADE9078** [comment]
> ## Merge state

so please help me how to change it?

**Comment by LucasHT22** [comment]
@Tiger-The-Cat  it's right, @BLADE9078 where is  "Merge state" appearing?

**Comment by Tiger-The-Cat** [comment]
@BLADE9078 In your own sprig fork, go to the /games directory. Then, click on your game file within the games directory. Click the little pencil icon like so:
image
Then, the name of your file that once looked like this:
image
will now look like this:
image
Now, all you have to do is delete the spaces in "Air Hockey (1).js", so it looks like this:
image
Make sure to commit your changes:
image

**Comment by Tiger-The-Cat** [comment]
This was all done through my own Sprig fork.

**Comment by BLADE9078** [comment]
How to fix this problem?

**Comment by LucasHT22** [comment]
@Tiger-The-Cat great tutorial! @BLADE9078 you can follow this tutorial too: https://scribehow.com/embed/How_to_Edit_a_File_on_GitHub_Pull_Request__sdayIETHQ_uIbGVN187mwQ
(I could solve this problem for you but it's a good opportunity for you to learn)

**Comment by BLADE9078** [comment]
Thank you So much lucas, i love learning

**Comment by BLADE9078** [comment]
Hey lucas 
i'm quite confused with this tutorial 
please can you help me out as i am quite excited for submiting my game

**Comment by LucasHT22** [comment]
what's your doubt?

**Comment by BLADE9078** [comment]
Can you please get me familiar with this tutorial site?

**Comment by LucasHT22** [comment]
Sorry! Check now: https://scribehow.com/shared/Github_Labels__Kqxm1xw8Qo2aRaSCjdGPOg

**Comment by LucasHT22** [comment]
Sorry! re-check now

**Comment by BLADE9078** [comment]
hey lucas, now it's done yea

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
