### PR TITLE
Added MagicalTiles by Shreeya Rani

### PR DESCRIPTION
**Pull request by Shreeya-Rani**
# Your checklist for this pull request

## Author name

Shreeya Rani

## About your game

This is a small music player. Every note has it's own tune to it and it plays the sound when the dedicated key is pressed (WASD keys)

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
good changes, how about adding jkl as music too?

sorry for the question, do you know @Shrey-Mehra?

**Comment by Shreeya-Rani** [comment]
Okay Lucas, I'll add jkl keys as music too, shouldn't be a big task!

And yeah, I know Shrey, he is a good friend of mine and he inspired me in the first place to start building my sprig gane.

**Comment by Shreeya-Rani** [comment]
Hey Lucas,
I have updated the file, you can go through it once :D

**Comment by LucasHT22** [comment]
> And yeah, I know Shrey, he is a good friend of mine and he inspired me in the first place to start building my sprig game.
By the way, may I know why you asked?

Your PRs were one after the other and the general structure very similar. sorry for the question

**Comment by Shrey-Mehra** [comment]
Hey Lucas,
Why you mentioned me in this PR

**Comment by Shreeya-Rani** [comment]
> > Hey Lucas, I have updated the file, you can go through it once :D
> 
> Great changes! one detail: the playback function seems to have an error

Yeah Lucas, I looked into that, I added the playback.end(); from the help box, but it doesn't seem to work

**Comment by LucasHT22** [comment]
> Yeah Lucas, I looked into that, I added the playback.end(); from the help box, but it doesn't seem to work

you have to add the name of the sound in the `()` :)

**Comment by LucasHT22** [comment]
> Hey Lucas, Why you mentioned me in this PR

don't worry, I just asked if she knew you

**Comment by Shrey-Mehra** [comment]
> > Hey Lucas, Why you mentioned me in this PR
> 
> don't worry, I just asked if she knew you

ohh ok actually it just making spam in my mail

**Review by LucasHT22 — APPROVED** [review]
Ok @Shreeya-Rani ! Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
