### PR TITLE
Sprigressbar

### PR DESCRIPTION
**Pull request by theMathR**
# Your checklist for this pull request

## Author name

**Author:** MathR

## About your game

**What is your game about?**
Sprigressbar is based on the game Progressbar95. The goal is to fill your progress bar with blue or orange segments while avoiding red segments and closing the annoying mascots with your cursor.

**How do you play your game?**

Move your progress bar using WASD and your cursor using IJKL.
Catch the blue and orange segments in the empty space of your bar. Once the bar is filled you move to the next level. Orange segments don't give points at the end of the level. Red segments must not be touched at all cost, pink segments take away your progress, gray segments do nothing.
Close the mascots by moving your cursor into them. Some mascots can cause a game over and some rare ones can give you bonus points.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by theMathR** [comment]
I might update the game, will I need to make another pull request?

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Loved the sprites but it's a hard game haha did you make it to the end?

**Comment by theMathR** [comment]
No, that's why I want to update it later. I hate adjusting difficulty...

**Comment by theMathR** [comment]
It's done, I decided to add easier levels at the beginning of the game.

**Comment by LucasHT22** [comment]
nice updates! now did you make it to the end?

**Comment by theMathR** [comment]
Yes, I just needed to try more

**Comment by LucasHT22** [comment]
ok, out of curiosity, where did you heard about sprig?

**Comment by theMathR** [comment]
My friend told me about it, but he doesn't have access to a computer so he can't make a game yet.

**Review by LucasHT22 — APPROVED** [review]
Alright, so congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
