### PR TITLE
Super_Platformer

### PR DESCRIPTION
**Pull request by KinjalPriya000**
# Your checklist for this pull request

## Author name

Author: Kinjal Priyadarshini

## About your game

What is your game about? Super_Platformer is a a fun game which involves the player moving through the map and over obstacles, with the end goal being to get to the flag!

How do you play your game? Press WASD to move. W is to jump, A is to move left and D is to move right. Get to the red flag to win the level. Some levels require clever movement of boxes in order to reach the flag and proceed!

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by KinjalPriya000** [comment]
> Thanks for your PR! Where did you hear about Sprig?

We have a Hack Club in my high school, of which I am a part of! The leaders of the club introduced us to Sprig.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! What about increase the gravity delay? Sorry for my delay btw

**Comment by Sheepy3** [comment]
closing this PR due to inactivity. feel free to ping me and ask for this to be reopened and hopefully merged!

**Comment by KinjalPriya000** [comment]
> closing this PR due to inactivity. feel free to ping me and ask for this to be reopened and hopefully merged!

Hi, could you please reopen this PR? Also, I am immensely sorry for my very late reply to the increase gravity delay comment. I tried to change it but I am not too familiar with this platform and couldn't find the option to reopen and edit my sprig game. I can try again though. Again, sorry for the late reply.

**Comment by Sheepy3** [comment]
@KinjalPriya000 Reopened!

**Review by KinjalPriya000 — COMMENTED** [review]
Ok, I updated the gravity jump delays. It is a lot easier to play now!

**Review by LucasHT22 — APPROVED** [review]
You could ask us:) Great! Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
