### PR TITLE
added game

### PR DESCRIPTION
**Pull request by zKxra**
# Your checklist for this pull request

## Author name

**Author:**

Deniz Melik Aktın

## About your game

**What is your game about?**

Destroying the hearts with the swords

**How do you play your game?**

WASD for moving, J to reset

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! How to solve this level? 
image

**Comment by zKxra** [comment]
Some maps was unbeatable so i'm working on them right now

**Comment by zKxra** [comment]
I'm trying to figure out how to upload the new code

**Comment by zKxra** [comment]
can you close this pr pls

**Comment by LucasHT22** [comment]
> I'm trying to figure out how to upload the new code

Go to `Files changed` > `...` > `edit` :)

**Pull request closed without merging**
