### PR TITLE
dungenrun

### PR DESCRIPTION
**Pull request by s-saanvi**
# Your checklist for this pull request

## Author name

**Author: Sau**

## About your game

**What is your game about?**
**Collecting the keys & rushing towards the Exit. Game has 7 lvls & then it restarts from begining , soon more lvls will be added**

**How do you play your game?**
**Press WASD to move, I to restart **

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by s-saanvi** [comment]
**hey I'm 16 yr old & i would like to have a sprig console **

**Comment by s-saanvi** [comment]
submission

**Comment by recursiveforte** [comment]
I love the art for this game, but the points & keys system doesn't work- when I go over a key, sometimes it collects a key from another part of the screen. Could you fix that before I merge this game?

**Comment by s-saanvi** [comment]
> I love the art for this game, but the points & keys system doesn't work- when I go over a key, sometimes it collects a key from another part of the screen. Could you fix that before I merge this game?

hey it was meant to be like that ,so player would not travel all the maze and collect key . And i have tried some ways to resolve it but i'm not getting correct output, so let it be as it is..
AND i wanna a have a sprig console how to get it please share the procedure please..!!

**Comment by recursiveforte** [comment]
You could join the [Hack Club Slack](https://hackclub.com/slack) and head to the #sprig channel to get support with your game!

**Comment by s-saanvi** [comment]
> You could join the [Hack Club Slack](https://hackclub.com/slack) and head to the #sprig channel to get support with your game!

hey if i edit the game should i close this PR and open a new request !! or else do changes in existing one ...???

**Comment by recursiveforte** [comment]
You can make changes in this PR

**Comment by s-saanvi** [comment]
@recursiveforte made some changes the pr ,changed  the levels and key collection after levl 7 it restarts again from the begining..

**Comment by recursiveforte** [comment]
Nice job with this. Approved, and you'll see it in the gallery soon.

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev) and join our [online Slack community](https://hackclub.com/slack) to chat with other people making Sprig games.

**Pull request merged**
