### PR TITLE
Wham Game Submission

### PR DESCRIPTION
**Pull request by LittleNooblet**
Author: Aaman Patnaik

**About my game:**

It's a simple game called "Wham!". The objective is to hit the "monster" in a green pipe as many times as you can.

**How do you play your game?**

Press WASD to move up, to the left, down, and to the right to move. Press J to whack the monster!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used - **it isn't used**)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! Did you use any game as inspiration?

**Comment by LittleNooblet** [comment]
> Nice! Did you use any game as inspiration?

I had the arcade game "Whac-A-Mole" in mind while making it. It was a very fun experience!

**Comment by LucasHT22** [comment]
> I had the arcade game "Whac-A-Mole" in mind while making it.

Nice!
>  It was a very fun experience!

Glad to hear:)

What are the three numbers on game?

**Comment by LittleNooblet** [comment]
> > I had the arcade game "Whac-A-Mole" in mind while making it.
> 
> Nice!
> 
> > It was a very fun experience!
> 
> Glad to hear:)
> 
> What are the three numbers on game?

The three numbers? I'm confused (this is my first time doing something like this - I'm sorry).

**Comment by LucasHT22** [comment]
sorry, my bad, I meant these numbers: 
image

**Comment by LittleNooblet** [comment]
> sorry, my bad, I meant these numbers: image

Sorry for the late reply - it's supposed to be the score and position of the cursor. It's very sloppy, I know haha.

**Review by LucasHT22 — APPROVED** [review]
No worries haha Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by LittleNooblet** [comment]
> No worries haha Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> 
> Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Thank you so much!

**Pull request merged**
