### PR TITLE
Cat in the rain game!

### PR DESCRIPTION
**Pull request by alxndriab**
# Checklist
## Author name

**Author:** alxndriab

## About your game
**What is your game about?**
Cat avoiding the rain with umbrellas.

**How do you play your game?**
Cat is played by you, "A" is left and "D" is right, "I" pulls out the umbrella. "K" stops the game.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by alxndriab** [comment]
like a game over screen?

**Comment by LucasHT22** [comment]
yep! the game over screen, sorry

**Comment by alxndriab** [comment]
oh ok! anything else I should add then before it's merged?

**Comment by LucasHT22** [comment]
> oh ok! anything else I should add then before it's merged?

If you want ¯\_(ツ)_/¯

**Comment by alxndriab** [comment]
if you think it's good, i'm good!

**Comment by LucasHT22** [comment]
Hey! I think I misunderstood, do you want to continue with the version of this PR? Sorry for the delay

**Comment by alxndriab** [comment]
lol it's okay, i still would like to submit!

**Review by LucasHT22 — APPROVED** [review]
Right! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by alxndriab** [comment]
Oh no :( unfortunately I just graduated after I began working on sprig. I'm still a teen, so would I still be eligible?

**Comment by LucasHT22** [comment]
Peobably yes, lmk when you submit your order for me let the team about it:)

**Pull request merged**
