### PR TITLE
Tennis game

### PR DESCRIPTION
**Pull request by shyakachaste**
# Your checklist for this pull request

## shyaka chaste

**chaste:**

## About your game

**What is your game about?**

**How do you play your game?**

## Experience
I used javascript and sprig inorder to make that game .

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! **What is your game about?**



**How do you play your game?**



Please check this:

- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file.

**Comment by LucasHT22** [comment]
Answer the questions ahead:) Let's get this merged

**Comment by grymmy** [comment]
@shyakachaste do you wish to move forward with this PR?  If you don't respond in a month or so I will be closing this PR due to inactivity...

**Comment by shyakachaste** [comment]
yes

**Comment by LucasHT22** [comment]
So please answer the questions above!:)

**Comment by shyakachaste** [comment]
my game is called tennis game , i created this game by using spring editor, to play this game you can use on "w" and "s". "w" is to move to top and "s" is to move to bottom in order to catch the ball, if the player catch the ball , the ball is directly turn to another stick player. and when you win the score will be written above and when another stick player win the score is also written on the right side. Thank you that is all about my game

**Comment by shyakachaste** [comment]
> my game is called tennis game , i created this game by using spring editor, to play this game you can use on "w" and "s". "w" is to move to top and "s" is to move to bottom in order to catch the ball, if the player catch the ball , the ball is directly turn to another stick player. and when you win the score will be written above and when another stick player win the score is also written on the right side. Thank you that is all about my game

https://sprig.hackclub.com/share/L2c4NUbEJFQkLxWzwkPO

**Comment by LucasHT22** [comment]
Which of the versions in this PR is the most recent?

**Comment by shyakachaste** [comment]
> Right, which of the versions in this PR is the most recent?

the most thing to know about the game is that , the player use "W" and "S" to play with another stick player in form of horizontal line

**Comment by LucasHT22** [comment]
Hmmm could you say which one of the files (in `Files changed`) is that version? To avoid my mistakes:)

**Comment by shyakachaste** [comment]
is called Tennis game.js                     https://github.com/shyakachaste/sprig/blob/main/games/Tennis%20game.js

**Comment by shyakachaste** [comment]
or i can start and create another file called tennis 1 game.js, ?

**Comment by LucasHT22** [comment]
Whatever you prefer, but please delete other files:) Also - Is it endless on purpose?

**Comment by Sheepy3** [comment]
Closing due to inactivity. if you want to reopen it, ping me here.

**Pull request closed without merging**
