### PR TITLE
s2k.js

### PR DESCRIPTION
**Pull request by Spectrepro**
# Your checklist for this pull request

## s2k

**Author:**

## A platformer 

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Spectrepro** [comment]
The player must navigate through the maze, collect the key (k), and reach the door (d) to advance to the next level.
The game ends with a "You Win!" message after completing all levels.

**Comment by Spectrepro** [comment]
Please tell me what has failed as i dont seem to understand the email.
Thanks,

________________________________

**Comment by recursiveforte** [comment]
I'm rejecting this game- it doesn't work and appears AI-generated.

**Comment by Spectrepro** [comment]
Is it possible for me to re do it
________________________________

**Pull request closed without merging**
