### PR TITLE
Squilium_Escape

### PR DESCRIPTION
**Pull request by alimyust**
# Your checklist for this pull request

## Author name

**Author:**

Ali Mustafa

## About your game

**What is your game about?**

 It is a puzzle game where you navigate each player to an X 
 
**How do you play your game?**

Press WASD to move and J to restart each level. Each player moves in the same direction per input. If there is 1 crate (brown) in front of any player, it can push it forward. If there is a block (gray) or more than 1 crate in front of any player, it won't be able to move in that direction, but all other players will.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by alimyust** [comment]
> Thanks for your PR! Where did you hear about Sprig?

I got an email talking about the 3D-printed winter Sprig cases and that piqued my interest, so I went and learned about what Sprig was in the first place.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right:) How to solve this level:
image

**Comment by alimyust** [comment]
> Right:) How to solve this level: image

For this one, the strategy is to get 3 of the eyeball guys on the left and use the border to align them so that they are in a line centred in the middle. Then you can move right and get them all in position. 

The exact moves are d l d l l l d u u u d r r.

**Comment by LucasHT22** [comment]
> d l d l l l d u u u d r r.

Could you send in WASD? Thanks:)

**Comment by alimyust** [comment]
> > d l d l l l d u u u d r r.
> 
> Could you send in WASD? Thanks:)

Sure. It would be SASAAASWWWSDD

**Comment by LucasHT22** [comment]
Thanks:) and this one?
image

**Comment by alimyust** [comment]
> Thanks:) and this one? image

This one should be ASAAWDSSWWDSASDAWWAAA

**Comment by LucasHT22** [comment]
Sorry but how to solve this one too: 
image

**Comment by alimyust** [comment]
> Sorry but how to solve this one too: image

Yea, no problem. For this one it's SAAWAWWWSSSDWAW

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
