### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by NidheeshP28**
# Catch Me if you can!

## About my game

What is the game about? 

Catch Me if you can is a pattern identifying fun game where you need to find out a way how to catch the goal and has 5 different levels, each level increases the complexity. 

How to play your game?

Use WASD (W is up, A is left, S is down, D is right) and shift+enter to restart

## Code
Check off the items that are true.

- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

image

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by SamDev-7** [comment]
Thanks for the PR, before we continue, can you move the game to the `games` directory? Thanks!

**Comment by NidheeshP28** [comment]
Thank you for your email, placed the game in the game file and the image in
the image file.

**Comment by NidheeshP28** [comment]
Hello, can anyone approve? Thanks!

**Review by SamDev-7 — CHANGES_REQUESTED** [review]
Cool concept! Thanks for the PR. Before we merge, I would like to mention a few things.

- The game is too short, are you able to add more levels? Try to reach 5 minutes of playtime.
- The concept is great but I feel that there can me more, maybe a potential idea could be to make walls or barriers that make it harder to the player to catch the goal.

Let us know if you need help with anything, happy hacking!

**Comment by NidheeshP28** [comment]
Thank you for the suggestions! I'll be working on that over the weekend

**Comment by NidheeshP28** [comment]
I extended my game to 15 levels and added barriers from level 6 and I increased the complexity and added the file. Thank you!

**Review by SamDev-7 — APPROVED** [review]

**Comment by SamDev-7** [comment]
🥳 Congrats on your submission!
You can order your Sprig here if you are a teen: https://sprig-order.hackclub.dev/
If you have any questions, don't hesitate to ask them here or message us in `#sprig` on [the Slack](https://hackclub.com/slack)!

**Comment by NidheeshP28** [comment]
Thank you!

**Comment by NidheeshP28** [comment]
I have a question, how can I know when the console is coming? Thanks!

**Comment by LucasHT22** [comment]
You will receive an email :)

**Comment by NidheeshP28** [comment]
Thanks!

**Pull request merged**
