### PR TITLE
Added Games by Radhesh Goel

### PR DESCRIPTION
**Pull request by radhesh1**
## Author name

**Author:** Radhesh Goel

## About your game

**What is your game about?**
My Games are about Fractal patterns because who doesnt love infinite patterns

**How do you play your game?**
  w - Pan up
  s - Pan down
  a - Pan left
  d - Pan right
  i - Zoom in
  j - Zoom out
  k - Reset to defaults
  
## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Nice! Are the 3 games yours?

**Comment by radhesh1** [comment]
yeah
i love math art!

**Comment by radhesh1** [comment]
sorry, i forgot to check out my github inbox

**Comment by LucasHT22** [comment]
Sorry for the delay! So could you split in 3 different PRs? Thanks:)

**Comment by radhesh1** [comment]
> Sorry for the delay! So could you split in 3 different PRs? Thanks:)

Sure why not?

**Comment by radhesh1** [comment]
So do I get a sprig?

**Comment by radhesh1** [comment]
I am closing this PR to divide my games into 3 PR

**Pull request closed without merging**
