### PR TITLE
DontGetBurnt

### PR DESCRIPTION
**Pull request by alexrosemiller**
# Your checklist for this pull request

## Authors name

Alexandra Miller, Mariia Tymoshenko, Elaine Liu, Shenelle Jayakody, Ariane Clarke

@fox-tech17
@ChemistryNarwhal 

## About your game

**What is your game about?**

Our game is about a toaster who hated all types of bread. You are a slice of bread that is trying to escape from the evil toaster and all of its toaster friends! Dodge toasters and collect jams and see how far you can go :)

**How do you play your game?**

The game will start with a storyline introduction. After the intro, press J and you will be put directly into the game. Use WASD keys to dodge the toasters. Go as far as you can and collect jam to earn extra points.

## Code
Check off the items that are true. 
- [ x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x ] The game runs without errors. 
- [ x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ x ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ x ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by fox-tech17** [comment]
Check out our game and help Crummington the Ninth escape! We had a lot of fun making the game and hope you will have just as much playing it!

**Comment by ChemistryNarwhal** [comment]
Great game to play

**Comment by SamDev-7** [comment]
Note: AngelHacks Toronto Game (Team of 5)

**Comment by LucasHT22** [comment]
I like that you used the case function, it's definitely not your first time with js haha, how did you learn this language?

**Comment by SamDev-7** [comment]
Hello again! I remember that this was a team of 5, do the other 2 team members have github? If not, we can figure something out to contact them about their sprig.

**Comment by alexrosemiller** [comment]
Thank you @LucasHT22 but it actually was our first time using js! We had background knowledge in python and java which we used for some of the code. For complex parts, we referenced numerous games from the hack club gallery and had awesome help from our hackathon organizers :)

**Comment by LucasHT22** [comment]
Wow that's awesome! Congrats!

**Review by SamDev-7 — APPROVED** [review]
The game is amazing! Thanks for the submission.

Get your sprigs here! https://sprig-order.hackclub.dev/

**Pull request merged**
