### PR TITLE
Robot Party

### PR DESCRIPTION
**Pull request by Gam3rrXD**
# Your checklist for this pull request

## About your game

What is your game about? 
>  Moving the Robot to push boxes and get coins, also finding the secret level

How to play your game?
> Move John [the robot] using keys WASD, J resets the level incase you messed up. The secret level is a one in 5 chance of finding it, if you do there is some special music and a different style end!
## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

### CODE REVIEW

**Comment by SamDev-7** [comment]
Cool game and great art! However, the code is quite similar to [sokoban](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban.js), are you able to add more levels or add another feature (for example a timer)? Another thing, can you remove the spaces in the filenames, thanks for the PR!

**Comment by Gam3rrXD** [comment]
sure id be happy to add a couple levels, im also going to be trying to implement a timer. i will remove the issues once i finish the edit. Thanks!

**Comment by Gam3rrXD** [comment]
@SamDev-7 I finished implementing the suggestions, I am unsure how to rename the JPG but I did go ahead and rename the js file. Thanks!

**Comment by LucasHT22** [comment]
Great changes! the movement counter and the timer make it more competitive, I'll just change the .jpg name

**Comment by LucasHT22** [comment]
Robot_Party_Basic_Buildv1
I don't have permission to add the file, so download this and upload it to your directory (https://github.com/Gam3rrXD/sprig)

**Comment by Gam3rrXD** [comment]
Sure i will do that now

**Comment by Gam3rrXD** [comment]
@LucasHT22 all changes are complete! let me know if I need to do anything else, Thanks!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me. Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
