### PR TITLE
add sprigish

### PR DESCRIPTION
**Pull request by mrhappyma**
# Your checklist for this pull request

## Author name

**Author:** dom

## About your game

**What is your game about?** finding your little radish kids. sprig recreation (of sorts) of [Dadish](https://store.steampowered.com/app/1522950/Dadish/)

**How do you play your game?** WASD. a to move left, d to move right, w to jump.

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! I think I already saw you here, second game, right?

**Comment by mrhappyma** [comment]
Nope, I've been in the slack for a little while but this is my first sprig game.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
oh right:) How about increasing the gravity delay? I think it can be too hard on the console

**Comment by mrhappyma** [comment]
Sure, sounds like a fine idea. I just upped it to 550ms if you think that's enough, it's hard for me to get a good idea of what this should be.

**Review by LucasHT22 — APPROVED** [review]
LGTM! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
