### PR TITLE
FRC CHARGED UP

### PR DESCRIPTION
**Pull request by Wyatt459**
# Your checklist for this pull request

Wyatt Adolph
**Wyatt459:**

## About your game

**What is your game about?**

Use the robots to move the cones and cubes to your alliance grid trying to score as many as possible
in the fastest amount of time.

**How do you play your game?**

Each grid can hold 10 game pieces. Game pieces can not be used to
move other game pieces. The first one to fill their grid wins. Game pieces can be moved over the
charging station. To restart the game turn the console off and back on again. Game pieces can NOT be 
moved away from walls so be careful. Robots can make contact so you can play some defense.

Blue controls: W = up
               S = down
               A = left
               D = right

Red controls: I = up
              K = down
              J = left
              L = right        
## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR!

**Comment by savinajabbo** [comment]
Your game is super creative and fun to play! What about adding more levels, or an ending screen announcing the winner of the game?

**Comment by Wyatt459** [comment]
> Your game is super creative and fun to play! What about adding more levels, or an ending screen announcing the winner of the game?

This isn't meant to be a multi-level game as it's based on the 2023 FRC game.

**Comment by savinajabbo** [comment]
Are you sure you don't want to expand and develop your game? It's so good that players won't just be satisfied with that haha

**Comment by Wyatt459** [comment]
> Are you sure you don't want to expand and develop your game? It's so good that players won't just be satisfied with that haha

I am sure. This game is a strategy game almost like tic tac toe. As you play the game with your friends, family, and possibly even teammates, each time you play it will be slightly different. If there's anything else you might want to see, feel free to let me know.

**Comment by leomcelroy** [comment]
I think it earns a Sprig. Congrats you can order it here: https://sprig-order.hackclub.dev/

**Pull request merged**
