### PR TITLE
PushBattle

### PR DESCRIPTION
**Pull request by MatrixMongoose**
PushBattle:

This game is a two player pushing game. Players have to push each other into hazard blocks to win the round. The game can be played for an unlimited amount of rounds since it will keep track of rounds and wins for each player. My next step in this game's development is to create a random map each time the game resets. For my first game I ever created it was a good experience overall. Once I learn all the capabilities of this software I will be able to make great games.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR!

**Comment by LucasHT22** [comment]
It's already a great game!

**Comment by LucasHT22** [comment]
are you from a hack club?

**Comment by MatrixMongoose** [comment]
No, I found out about sprig from my dad.

**Comment by LucasHT22** [comment]
oh, nice! welcome to Sprig!

**Comment by LucasHT22** [comment]
do you want me to merge or are you going to make changes? (merging won't stop you from making changes!)

**Comment by MatrixMongoose** [comment]
I would like it if you merged this version of the game now!

**Review by LucasHT22 — APPROVED** [review]
You can make updates with a new PR! Congrats!
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
