### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Aradhya-Shaswat**
# Your checklist for this pull request

## Author name

**Author: Aradhya Shaswat**

## About your game

**What is your game about?**

You are a hammer and you have to hit the button to win the game! (but there are mazes!!)

**How do you play your game?**

WASD to move, navigate through the maze and collide your player with the button to advance to the next level.

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ n] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [n ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Hey there!  Please add a new game mechanic or two to differentiate your game from others and make you eligible for a sprig device award!

**Comment by grymmy** [comment]
Specifically, we're looking for new unique code that adds to the fun of your game's play!

**Comment by grymmy** [comment]
Please feel free to re-open this PR once you have made significant updates to it per my commentary above.

**Comment by Aradhya-Shaswat** [comment]
ok@

**Pull request closed without merging**
