### PR TITLE
osu! mania

### PR DESCRIPTION
**Pull request by alx-alexpark**
# Your checklist for this pull request

## Author name

**Author:** Alex Park

## About your game

**What is your game about?**

It is like osu! mania, or piano tiles. You hit 4 keys based on the beat of a song. 

**How do you play your game?**

You play the game by using the keys a,d,j,l which correspond to the keys from left to right.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by alx-alexpark** [comment]
Some other notes I would like to add:
- The musical notes are actually represented by bitmaps which are translated into sprites on the fly
- The song is [Lagtrain](https://www.youtube.com/watch?v=UnIhRpIT7nc), which I took a piano version from MuseScore and converted it to sprig using this [very nice tool](https://the.lastgimbus.com/midi-to-sprig)
- There is a semi-rare chance of an Amogus replacing the normal note sprite

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! What about adding your answer to "How do you play your game?" in header? Also - what was your highest score?

**Comment by alx-alexpark** [comment]
@LucasHT22 Done! My highest score is 158.

**Review by LucasHT22 — APPROVED** [review]
Happy new year! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by alx-alexpark** [comment]
Happy new year!

**Pull request merged**
