### PR TITLE
L0st (Game for sprig)

### PR DESCRIPTION
**Pull request by Teal-Cat-35**
My game is a puzzle game where you are finding your way through a maze, and trying to get out.
Creating this was hard but really fun, and also my first original game.
I looked at other code for how to do things, (but mostly asked my Dad to help). However, some things I did myself.
Also, Instructions in case:
WASD to move, I to restart level, K to talk to NPCs/continue NPC text, get to the green and black thing(that now looks like a cabbage), push orange and blue things.

### CODE REVIEW

**Comment by Teal-Cat-35** [comment]
I hope you like my game!!

**Comment by Omay238** [comment]
I really like how there's a story. I don't think I've seen that in a Sprig game before! Some feedback I have though is that the levels are kind of repetitive, and the larger ones are hard to see where you're going. Also, making the walls into more of a block shape could make it a lot easier to see things.

**Comment by Teal-Cat-35** [comment]
Oh, TYSM!! That was pretty quick, I shared this just a few moments ago!
Anyway, I was going to make the walls bigger. I could try making it easier to see things on big levels, too!!

**Review by LucasHT22 — COMMENTED** [review]
Very good game! the function "talk to npcs" it's so nice :)
I agree with Omay about the changes

**Comment by LucasHT22** [comment]
just Out of curiosity, how did you meet Sprig?

**Comment by Teal-Cat-35** [comment]
My Dad had told me about it, because I wanted to learn to hack and code.
I also do a lot of coding on scratch.mit.edu.

**Comment by LucasHT22** [comment]
oh nice! do you know where he saw the sprig?
scratch is a classic, I've coded a lot with it too because of the [CS50 Scratch](https://cs50.harvard.edu/scratch/2021/)

**Review by LucasHT22 — COMMENTED** [review]
add this in games/img

**Comment by Teal-Cat-35** [comment]
No, I don't know how he found it, but, well, I'm glad he did!!

**Comment by LucasHT22** [comment]
just one thing, add image L0ST.png in games/img

**Comment by Teal-Cat-35** [comment]
I have done that now!! :D

**Review by LucasHT22 — APPROVED** [review]
Congrats!
 you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by Teal-Cat-35** [comment]
Thank you for all the support on my game!! I've made parts 2 and 3 already, I might create a pull request for those 2.

**Pull request merged**
