### PR TITLE
Added MicroBot Adventure

### PR DESCRIPTION
**Pull request by cskartikey**
# Your checklist for this pull request

## Author name

**Author:** Kartikey Singh Chauhan 

## About your game

**What is your game about?**

In this game, players take on the role of a robot navigating through maze-like maps fraught with peril. The primary objective is to outmaneuver enemies, strategically use boxes to block enemy attacks, and eliminate hostile turrets with a  lasers and reach the portal (goal) which progresses to the next level.
 
**How do you play your game?**

WASD keys handle movement. Laser firing is executed with 'K' (westward) and 'L' (eastward) keys, and J is used to reset to the game.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

### CODE REVIEW

**Comment by cskartikey** [comment]
Oh and I first heard about Sprig back in June from a friend who attended Code Day and later joined Hack Club. I've been putting off finishing this game for a while, but I finally got it done!

**Comment by LucasHT22** [comment]
> Oh and I first heard about Sprig back in June from a friend who attended Code Day and later joined Hack Club. I've been putting off finishing this game for a while, but I finally got it done!

WOW you read my thoughts haha sorry for the delay tho

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
What about add the instructions to the header? :)

**Comment by cskartikey** [comment]
> What about add the instructions to the header? :)

Done!

**Comment by LucasHT22** [comment]
Right :) I don't know if i understood right, why laser doesnt work in level 1?

**Comment by cskartikey** [comment]
> Right :) I don't know if i understood right, why laser doesnt work in level 1?

It doesnt works for the first two level and that is intentional. It is mostly to make the game not soo easy and add some sort of progression.

**Comment by LucasHT22** [comment]
Could you send a gameplay completing the first level just so i can understand better:)

**Comment by LucasHT22** [comment]
No worries! And this? How to solve?
image

**Review by LucasHT22 — APPROVED** [review]
Thanks! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
