### PR TITLE
Puzzle_Game

### PR DESCRIPTION
**Pull request by MLKoo**

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for PR! How should this level be resolved?
image

**Comment by LucasHT22** [comment]
yeah, I realized that it is solvable, my bad

for information: this is one of @bellesea 's club games is being directed by Slack too

**Review by LucasHT22 — COMMENTED** [review]
good changes! could increase the timer? oh, thanks for the credits :)

**Comment by MLKoo** [comment]
Thank you for the help :)

**Pull request merged**
