### PR TITLE
Invisible Maze

### PR DESCRIPTION
**Pull request by PulcaDot**
The player goes through a series of levels where the path is invisible. In a certain level, there even is a EASTER EGG. Will the player be tricked by the multiple winding paths set up, or will they prevail to beat the game?

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for PR! Very good game! please, add more levels:)

**Comment by SamDev-7** [comment]
@PulcaDot It's been 15 days, how's your game going? It's a really cool concept, but we just need a few more levels.

**Comment by PulcaDot** [comment]
Sorry it took so long I was down with Covid-19 and I was down with a cold directly after that. I finished the game up and changed it :3.

**Comment by LucasHT22** [comment]
we are glad you came back! covid is hard

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
