### PR TITLE
pb & j maze!

### PR DESCRIPTION
**Pull request by alxthe**
Alexander Mathew --> i prefer Alex

**Description**

a lonely splotch of jelly/jam is finding its way to a splotch of peanut butter in a maze of toast! find keys to unlock secret places and travel through portals to find the peanut butter.

**How do you play your game?**

press WASD to move around, run over keys to unlock locks, step on portals to travel through them. 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Loved the sprites! What about a checkered background?

**Comment by alxthe** [comment]
Thanks for the idea!! I tried it out here:
￼

I’m not sure if it looks the best it is a bit crowded. I want to try changing the background because it is pretty basic. Do you have any other ideas?

Thanks!
Alex

**Comment by LucasHT22** [comment]
for record - talked in Slack!

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
