### PR TITLE
Tried to submit Flappy Sprig to 

### PR DESCRIPTION
**Pull request by Spectralo**
# Your checklist for this pull request

## Author name

**Spectral**

## About your game

** It's a Flappy Bird but with a Sprig. The sprig is the same that on SprigressBar, MathR is a friend and autorised me to pick it. Go check his game!!!!
I've just seen that there is already an Flappy Bird but ... I've passed so much time on it to stop it. I don't think i will get a sprig but, i hope it.
Enjoy my Game !
(And sorry for my english that is like ... The pipes on this game ;-))**

**Use W and Z to move up and down.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Spectralo** [comment]
I need to add content or this is suffisant ? I

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
No worries about your english, I'm not a native speaker either haha, What was your highest score on this game?

**Comment by LucasHT22** [comment]
> I need to add content or this is suffisant ? I

Let's see... What do you think? :)

**Comment by Spectralo** [comment]
> No worries about your english, I'm not a native speaker either haha, What was your highest score on this game?

25

**Comment by Spectralo** [comment]
> > I need to add content or this is suffisant ? I
> 
> Let's see... What do you think? :)

mmmh i dont really now what i can add. In Flappy Bird there is not a ton of gameplay

**Comment by LucasHT22** [comment]
Make sure about this: The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by Spectralo** [comment]
> Make sure about this: The name of the file/game contains only alphanumeric characters, -s, or _s.

Done

**Comment by LucasHT22** [comment]
> I don't think i will get a sprig but

Why do you think it? 👀

**Comment by Spectralo** [comment]
Because Flappy Bird game is already do

**Review by LucasHT22 — APPROVED** [review]
But this is you that created! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
