### PR TITLE
Add "Infinite Shooter.js"

### PR DESCRIPTION
**Pull request by not-a-robot69**
First time writing JavaScript, and first time writing a game too.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
it seems that the controls aren't working, the has_lost variable isn't declared

**Comment by not-a-robot69** [comment]
What do you mean? `var has_lost = false;` is on line 12, and copying the code into the online editor works... could you send a video/screenshot? Controls are WASD for movement, K to shoot.

**Review by LucasHT22 — APPROVED** [review]
@not-a-robot69 My bad, sorry! Very good game :) Congrats :)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by LucasHT22** [comment]
I was having trouble with the keyboard

**Comment by not-a-robot69** [comment]
No problem. Thanks a lot!

**Pull request merged**
