### PR TITLE
Snake Boxes

### PR DESCRIPTION
**Pull request by AV-01**
# My checklist for this pull request

## Aryavrat Mishra

**Author: Aryavrat Mishra**

## About your game
This game is a variation of a classic snake game. It's a different mode, where you need to push boxes to goals instead of eating apples. This version exists in the classic "Google Snake" game, with its own speedrun category. I really enjoy playing Google Snake, and even have 2 records in the game(they're not very good, but at least I have them!) Basically, it's a port of a Google Snake mode.

Here is one of my google snake speedruns if you're interested(username AryavratMishra): (https://www.speedrun.com/snake_game/leaderboards?h=Light_Mode_Fast-25_Apples-Dice-Standard&x=l_5d7mnl5d-mke9xe9d-0nwovxdl.qoxx6dxq-p854j77l.z19gp0jl) 

**What is your game about?**
Your snake needs to push boxes to goals instead of eating apples. However, the snake never stops moving, can't crash into walls, and can't crash into itself. You need to move yourself carefully to get the box to the goal(alternatively, you can push the goal to the box!).

**How do you play your game?**
Press WASD to move/start the game, move the box adjacent to the goal, you can push either the goal or the box, press L to restart when you die.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Congrats on your speedrun. Where did you hear about Sprig?

**Comment by AV-01** [comment]
I'm a member of hack club, so I heard about it from Holly during my leaders orientation when she was still working at Hack Club!

**Comment by LucasHT22** [comment]
oh right:) What is your highest score in your game?

**Comment by AV-01** [comment]
6, but I could probably get better if I tried harder

**Review by LucasHT22 — APPROVED** [review]
Nice! Sorry for the delay! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
