### PR TITLE
The Maze-trixs

### PR DESCRIPTION
**Pull request by Lightshayan**
# Your checklist for this pull request

## Author

**Author: Shayan**

## About your game

**A maze game with boxes that can be pushed and key and locks**

**WASD Controls, J to restart. Get to the green circle. Push boxes away from your path and get the key to unlock the gates to proceed.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Lightshayan** [comment]
https://sprig.hackclub.com/share/Xf1EHN60xpwgdnyTLx7B
(latest share link)

**Comment by grymmy** [comment]
Please add one or two additional game mechanics to differentiate this game sufficiently from the rest of the gallery, and to meet the bar for receiving a Sprig device grant.

**Comment by grymmy** [comment]
Looked at this today, still awaiting changes from the author.

**Comment by grymmy** [comment]
Looked at this today, still awaiting changes from the author.

**Comment by Lightshayan** [comment]
Hey - I'll push a commit as soon as I get back.

**Comment by grymmy** [comment]
Looked at this today and I see the author is actively working on new changes based on feedback.  Can't wait to see what you come up with!

**Comment by recursiveforte** [comment]
Looked at this today- still awaiting changes!

**Comment by grymmy** [comment]
Closing this as it seems inactive.  Please feel free to re-open this PR if you want to advocate for it its being merged.

**Pull request closed without merging**
