### PR TITLE
Connect Four

### PR DESCRIPTION
**Pull request by SamDev-7**
The typical Connect Four game.

### CODE REVIEW

**Comment by leomcelroy** [comment]
Another nice game Sam! I like how your code is nice and simple to understand. This is a good addition to the game library.

For your next one I would challenge you to make an original game with a novel mechanic! Try doing something with multiple levels. Really appreciate the two you've contributed so far. Any feedback on the system?

**Comment by SamDev-7** [comment]
My next goal is an original game :D

Different text sizes would be awesome.
There were times when errors in the console which didn't show up in the editor.
A built-in way to add timed loops/delays would be amazing, we seem to have to resort to setTimeOut. 
More colors/declare custom colors similar to sprites?

I'll be looking at the sprig code to see if I can contribute.

**Comment by leomcelroy** [comment]
Definitely let us know as you find bugs. 

We just use setInterval and setTimeout. What do you find lacking about them?

I actually still haven't totally settled on the color palette. We want to keep it small but I just evenly distributed the colors as a temp option originally. I've come to like the style myself.

**Comment by leomcelroy** [comment]
Also here's the form to get on the Sprig waitlist!

https://airtable.com/appN9cSnDgORAM2bp/tblYLyzi8RySfkONg/viwMrglQ6x9pBSE0O?blocks=hide

**Pull request merged**
