### PR TITLE
Bad Apple port on Sprig

### PR DESCRIPTION
**Pull request by Sychamis**
# Your checklist for this pull request

## Author name

**Author:**

Sychamis

## About your game

**What is your game about?**

Watching the Sprig port of the Bad Apple video (https://www.youtube.com/watch?v=FtutLA63Cp8)

Context: people try to play the video on everything they can so I thought It'd be cool to add a Sprig port to the list (https://www.youtube.com/playlist?list=PLajlU5EKJVdonUGTEc7B-0YqElDlz9Sf9)

**How do you play your game?**

Select the playback frame-rate with J (15 fps) or L (30 fps, but it can lag and desync the music), and enjoy.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Out of curiosity, did you use any game for inspiration?

**Comment by Sychamis** [comment]
The game [ROOM](https://sprig.hackclub.com/gallery/ROOM) by davnotdev gave me the idea to use a tilemap as a framebuffer and the setInterval() function to refresh graphics and prevent music from slowing down.

**Comment by LucasHT22** [comment]
> The game [ROOM](https://sprig.hackclub.com/gallery/ROOM) by davnotdev gave me the idea to use a tilemap as a framebuffer and the setInterval() function to refresh graphics and prevent music from slowing down.

hmm did you use any code from another person?

**Comment by Sychamis** [comment]
I planned to use davnotdev's code (and credit him) if my own code wouldn't work: I first tried to make the framebuffer myself and it happened to work properly with some tweaks. So in the end I didn't use code from anyone except myself (because I made the python music scripts and JS player for a previous project.)
However, as mentionned in my code, I got video data from [ 52525rr ]( https://github.com/52525rr ) and she made the encoding and ffmpeg video scanning so I find it fair to credit her even if it's not code.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right:) Where did you hear about Sprig?

**Comment by Sychamis** [comment]
I discovered sprig when people in a discord server were talking about hackclub, I took a look at what the organization was then  checked its repos and I clicked on the first one out of curiosity :eyes:

**Comment by LucasHT22** [comment]
hmmmm out of curiosity, are you on hackclub slack?

**Comment by Sychamis** [comment]
No I'm not on it.

**Comment by LucasHT22** [comment]
> No I'm not on it.

Right:) out of curiosity why bad apple?

**Comment by Sychamis** [comment]
Because on the list of "port it on everything" projects it's by far the most popular and easy one, the other ones being [ STNICCC 2000 ]( https://youtube.com/playlist?list=PLHDxrzOvt6kQF1OHLNnfLGGdOdYA_vFRl&feature=shared ) (rendering a polygon stream animation) and of course DOOM.

**Comment by Sychamis** [comment]
Sure !

**Review by LucasHT22 — APPROVED** [review]
Looks legit to me! Nice method:) 
Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by LucasHT22** [comment]
I'll merge later because i need to update your metadata but my github isn't loading the file 
image

**Comment by Sychamis** [comment]
Thanks! I'll try to join the sprig slack and apply for the console but I'm a bit worried about having to give my personal infomation.

**Comment by LucasHT22** [comment]
> Thanks! I'll try to join the sprig slack and apply for the console but I'm a bit worried about having to give my personal infomation.

We don't share your info, the airtable that stores the data is extremely controlled and only trusted people have access. but if you prefer to not fill, it's your choice and we respect:)

**Pull request merged**
