### PR TITLE
offline_t-rex_game

### PR DESCRIPTION
**Pull request by zoya-hussain**
# Your checklist for this pull request

## About your game

What is your game about? 
> This game is a simplified version of Chrome's offline dinosaur game! The player is the dinosaur, running endlessly while avoiding cacti.

How to play your game?
> Press "W" to hop over the cacti in your path. The objective is to attain a high score as the speed increases. 

## Code
Check off the items that are true.
- [✓] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [✓] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [✓] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [✓] The game runs without errors. 
- [✓] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [✓] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [✓] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [✓] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
Great game! just a detail, the image must be in `games/img` :)

**Comment by zoya-hussain** [comment]
Sorry about that, I'll fix that now! Also,, should I go ahead and move close the pull request?

**Comment by LucasHT22** [comment]
> Sorry about that, I'll fix that now! Also, should I go ahead and move close the pull request?

No need to be sorry! no, continue in this PR:)

**Comment by LucasHT22** [comment]
delete image outside `img`

**Comment by zoya-hussain** [comment]
i'm not sure why but i can't delete the image outside of img

**Comment by zoya-hussain** [comment]
I can't seem to delete the file outside of the img folder.

**Comment by LucasHT22** [comment]
Ok! So I merge and delete the image :) I'm without my notebook right now, I'll merge in a few hours, ok?

**Comment by zoya-hussain** [comment]
Thank you so much! Sorry again, I couldn't quite figure out how to delete it.

**Comment by the456gamer** [comment]
Ok if your still here, this should now work
https://github.com/zoya-hussain/sprig/blob/main/games/offline_t-rex_game.png
This is the file you added on the branch you are trying to get merged in, so it's almost like your copy of the repository.
Therefore, in desktop, there should be a delete button on the top right of the file, and it should allow you to directly commit it so your branch

GitHub doesn't make this the easiest process, since I think it expect people to use got locally for commit manipulation

**Comment by SamDev-7** [comment]
Let us know if you still need help!
You can also message us in `#sprig` on [the Slack](https://hackclub.com/slack).

**Comment by LucasHT22** [comment]
the game is good and we can do this after the merge, I don't see why not merge, so If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/  :)

**Comment by zoya-hussain** [comment]
Thank you :))

**Pull request merged**
