### PR TITLE
Endless zombie shooter game

### PR DESCRIPTION
**Pull request by edmundlzen**
A zombie shooter game that's endless and progressively gets harder. Also has a bullet management aspect to it with the reload time. Goal is simple, get the highest score.

Controls:
- w, s | Movement
- i | Shooting
- j | Restart

### CODE REVIEW

**Comment by edmundlzen** [comment]
https://user-images.githubusercontent.com/12859874/190695259-3e6abca1-afea-412a-9eda-c8f32387f79f.mp4

Video of the game

**Comment by Omay238** [comment]
Heya. The game is pretty good, and fun. Something that would make the game more enjoyable in my opinion is if the roads had some sort of indication to help you shoot zombies that are far away. Other than that, it is a good game, good art, and good sfx. Also, a manual reload could be nice if there are no zombies at that moment.

**Comment by LucasHT22** [comment]
I thought the game was really good! but I think it can make it a little more difficult by increasing the speed at which the zombies approach
(this is just my opinion :))

**Comment by edmundlzen** [comment]
> I thought the game was really good! but I think it can make it a little more difficult by increasing the speed at which the zombies approach
> (this is just my opinion :))

That's fine, I have the same thought too! Thankfully It can be easily done.

**Comment by edmundlzen** [comment]
> Heya. The game is pretty good, and fun. Something that would make the game more enjoyable in my opinion is if the roads had some sort of indication to help you shoot zombies that are far away. Other than that, it is a good game, good art, and good sfx. Also, a manual reload could be nice if there are no zombies at that moment. 

I think I can those stripes in the center of the road.

**Comment by edmundlzen** [comment]
Added some new stuff:
- Stripes on road
- Manual reloading
- SFX on bullet empty
- Minor bug fixes
- Reload! text
- Tweaked initial zombie walk speed to be faster
- Capped zombie walk speed and zombie spawn rate increase
- Reduced zombie walk speed decrease rate
- Increased zombie spawn rate increase rate
- Changed reload button to j

**Comment by LucasHT22** [comment]
Wow good job! Game very good!

**Comment by leomcelroy** [comment]
I got quite into playing this 😄 . The reload mechanic really forces you to strategize. Nice work and welcome to the Gallery.

If you're a teenager congrats on your Sprig!

https://sprig-order.hackclub.dev/

**Comment by karamassie** [comment]
LOVE this @edmundlzen

**Pull request merged**
