### PR TITLE
Revert 1 artism30 patch 1

### PR DESCRIPTION
**Pull request by ARTISM30**
# Your checklist for this pull request

## ARTISM

**Author:**

 Creator

## About your game

**What is your game about?**

My game is about pushing the blob into the portal and figuring out how to get it through each level

**How do you play your game?**

Press WASD to move, J to restart Get blob to portal

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by alx-alexpark** [comment]
What is the purpose of this PR? Did you mean to submit a game?

**Comment by ARTISM30** [comment]
Yes I was trying to submit a game

**Comment by alx-alexpark** [comment]
You didn't upload your game file. I suggest that you use the publish to github button in the sprig editor, that should do most of it for you automatically. If you need any help, feel free to send a message in #sprig!

**Comment by ARTISM30** [comment]
I’m trying to but it’s saying there’s something wrong

**Comment by ARTISM30** [comment]
Never mind I got it to work

**Pull request closed without merging**
