### PR TITLE
Labyrinth

### PR DESCRIPTION
**Pull request by itsimpeccable**
# Your checklist for this pull request

## About your game
What is your game about? 
A simple labyrinth game where you would find the exit.

How to play your game?
Simply, you would use W to move up, A to move left, S to down, D to right and J to restart.
## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for PR! How to solve the labyrinth? seems to have no solution

**Comment by itsimpeccable** [comment]
alright, I added a solution and a level too. it will say you win if you get through the levels.

**Comment by itsimpeccable** [comment]
now this version has 3 levels, j to restart, ready for the gallery.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great changes! How about 2 more levels?

**Comment by itsimpeccable** [comment]
I did, I added 2 more levels, now it is really ready for the galery!

**Comment by itsimpeccable** [comment]
final version of labyrinth, fixed the last level.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
image
there seems to be no solution

**Comment by itsimpeccable** [comment]
It's the old version, look on the new one I changed.

**Review by LucasHT22 — APPROVED** [review]
Sorry! Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
