### PR TITLE
fire boom

### PR DESCRIPTION
**Pull request by Samarpan1122**
# Your checklist for this pull request

## Author name

Samarpan

## About your game
Fire escaping game

**How do you play your game?**

Press AD to move to escape and W to shoot water
it all about how long you survive
## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Thanks for the PR:) Which file is the correct?

**Comment by LucasHT22** [comment]
Answer the question ahead! Would love to see this merged:)

**Comment by Samarpan1122** [comment]
games/gorgeous_venonat.js

**Comment by LucasHT22** [comment]
Nice:) What about add more in your game? Maybe a life system?

**Comment by Samarpan1122** [comment]
I had an idea to add water blaster to negate fire blasts and bad 3 lives too but anyways can I get a sprig

**Comment by Samarpan1122** [comment]
please email me on samarpanmohanty3347@gmail.com

**Comment by LucasHT22** [comment]
Great changes! One last question, where did you heard about sprig?

**Comment by Samarpan1122** [comment]
Went to attend codeday hackathon,there were guest who were telling about sprigs and js

**Comment by Samarpan1122** [comment]
Will I get a sprig?

**Comment by LucasHT22** [comment]
Sure you'll get, just add .js on file name:)

**Comment by Samarpan1122** [comment]
Anything else and ???

**Comment by LucasHT22** [comment]
Delete the file outside of /games :)

**Comment by Samarpan1122** [comment]
done

**Comment by Samarpan1122** [comment]
hi i have ordered from my side 3 days ago but still i didnt get any mail yet

**Comment by LucasHT22** [comment]
Hey! I'll check, sorry in advance

**Comment by Samarpan1122** [comment]
ok

**Comment by LucasHT22** [comment]
Just checked, we are waiting a Sprig shipment arrive in India to be distributed, I don't know the current status of this shipment but I think in 1 month the console is with you:) Sorry about it

**Comment by Samarpan1122** [comment]
hi any updates?

**Comment by Samarpan1122** [comment]
ok

**Comment by LucasHT22** [comment]
Hey @Samarpan1122 ! I checked and there are people working on this, sorry about it

**Comment by Samarpan1122** [comment]
its been 12 days for me i havent received any email
Screenshot 2023-10-07 200517

**Comment by Samarpan1122** [comment]
they got it in 2-3 days

**Comment by Samarpan1122** [comment]
i just need an email confirming that my sprig is coming, if possible please send one email

**Comment by LucasHT22** [comment]
Oof, Monday I'll ask again to see what is happening to India shippings. Sorry about it again

**Pull request merged**
