### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hippo1308**
# Your checklist for this pull request

## Author name

Tushi.T

## About your game

Hippos adventure to complete boxes

PRESS: "A" to move left, "W" to jump up,  "D" to move right and "S" to move down. Boxes are pink and goals are green. 

## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Please complete this:
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

**Comment by hippo1308** [comment]
- ✔️  The game was made using the Sprig editor
   <https://sprig.hackclub.com/editor>.
   - ✔️  The game is placed in the in the /games directory
   <https://github.com/hackclub/sprig/tree/main/games>.
   - ✔️  The code is significantly different from all other games in the Sprig
   gallery <https://sprig.hackclub.com/gallery> (except for games labeled
   "demo").
   - ✔️  The game runs without errors.
   - ✔️   The name of the file/game contains only alphanumeric characters, -s,
   or _s.
   - ✔️   The game name is not the same as the others from gallery
   <https://sprig.hackclub.com/gallery>

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great! Where did you hear about Sprig?

**Comment by Sheepy3** [comment]
closing this PR due to inactivity. feel free to ping me and ask for this to be reopened and hopefully merged!

**Pull request closed without merging**
