### PR TITLE
ocean maze escape

### PR DESCRIPTION
**Pull request by imadinosaur1**
# Your checklist for this pull request

## Author name
michael barrera
**Author:ima_dinosaur**

## About your game

**What is your game about?**
get squid(player1) to submarine and get shark(player2) to boat

**How do you play your game?**
 WASD=player 1 movement IJKL= player 2 movement

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Just one thing, you need a name:)

**Comment by LucasHT22** [comment]
Want to see this merged:) you just need to choose a name for the game

**Comment by imadinosaur1** [comment]
what issues do i have

**Comment by LucasHT22** [comment]
Just change the name:) `Files changed` > `...` > `edit`

**Comment by imadinosaur1** [comment]
is that what i needed to change?

**Comment by LucasHT22** [comment]
> is that what i needed to change?

Yep! If I can ask, What made you not answer for so long? just to improve our work:)

**Comment by imadinosaur1** [comment]
I was out for summer break and forgot about it for a bit

**Review by LucasHT22 — APPROVED** [review]
Right, Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
