### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Deadly0009**
# Your checklist for this pull request

## Author name ezekiel

**Author:**

## About your game move all chests to the keys 

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Deadly0009** [comment]
h

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR!

**Comment by savinajabbo** [comment]
I love the last level of your game! What about adding more elements?

**Comment by grymmy** [comment]
Closing this PR due to inactivity.  Please feel free to re-open this once you've resolved the feedback and we can take another look!

**Pull request closed without merging**
