### PR TITLE
Sprig Alarm

### PR DESCRIPTION
**Pull request by techpixel**
# Your checklist for this pull request

## Author name

**Author:**

Manitej Boorgu

## About your game

**What is your game about?**

It's a utility to make me wake up in the morning. Because I can't. Allows the user to keep track of time and sounds an alarm if configured.

**How do you play your game?**

WASD to interact with the menus & set the alarm. Otherwise, sit back and relax as you watch the minutes tick away from your life. 

When the alarm sounds, a memorization test is displayed - you will need to memorize a code & re-enter it to stop the alarm.

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [X] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [X] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by techpixel** [comment]
Saw it on the GitHub homepage but was motivated by the Slack to do it!

**Comment by LucasHT22** [comment]
> Saw it on the GitHub homepage but was motivated by the Slack to do it!

Nice! Trending repositories?

**Comment by techpixel** [comment]
The Hack Club GitHub organization page

**Comment by techpixel** [comment]
Updates?

**Comment by LucasHT22** [comment]
Sorry for the delay! I lost you in notifications!

**Comment by LucasHT22** [comment]
Out of curiosity, why a alarm?

**Comment by techpixel** [comment]
I made an alarm because I can't wake up in the morning! 😭
I thought combining an alarm with a wake mechanism (a way to prevent me from falling asleep again) might help.

**Comment by LucasHT22** [comment]
haha I don't know if I understood correctly, could you send a screen record of this working?

**Comment by techpixel** [comment]
https://github.com/hackclub/sprig/assets/68567672/433e5b13-8e39-4f23-aa4d-c6e0c7acf9de

**Comment by techpixel** [comment]
Updates? (Sorry if you're busy)

**Comment by LucasHT22** [comment]
I'm having problems with GitHub notifications, sorry for the delay! Great! What about add instructions to header? Also how do you synchronize with real time?

**Comment by techpixel** [comment]
Instructions to header?

I forgot to put in time synchronization🤦. I swear I did that! I'll fix that!

**Comment by LucasHT22** [comment]
> Instructions to header?

In the comments:)

> I forgot to put in time synchronization🤦. I swear I did that! I'll fix that!

It's actually synchronized, I'm asking how? haha

**Comment by techpixel** [comment]
Ah I see.

I thought you meant you couldn't configure time synchronization - I used JerryScript's provided Date functionality.

**Comment by LucasHT22** [comment]
> Ah I see.
> 
> I thought you meant you couldn't configure time synchronization - I used JerryScript's provided Date functionality.

That's nice! Out of curiosity, Where did you learn JavaScript?

**Comment by techpixel** [comment]
I actually don't remember - I think it was through W3Schools originally but then I started using MDN & Node documentation after mastering syntax.

**Comment by LucasHT22** [comment]
> I actually don't remember (It's been a while) - I think it was through W3Schools originally but then I started using MDN & Node documentation after mastering syntax.

Nice, is there anything that you would change in Sprig?

**Comment by techpixel** [comment]
I think sprig should be more moddable (but I here things are in motion for that 👀) so not really! Sprig's been amazing so far!

**Comment by techpixel** [comment]
Hooray! Thank you!!!

**Pull request merged**
