### PR TITLE
UFO Attack

### PR DESCRIPTION
**Pull request by troy7615**
# Your checklist for this pull request

## About your game

What is your game about? 
> You are a cow trying to eat hay without being abducted by aliens!

How to play your game?
> Press WASD to move and press J to restart

I've done some coding before (HTML) but never javascript. When I saw the article about this on hackaday (https://hackaday.com/2022/11/10/sprig-is-an-open-source-handheld-game-console/) I was genuinely interested and decided to try it out. 

If I get a sprig console one of the things I'm looking forward to (besides coding) is to design and 3d print a case for it, which I think could really make it look more polished.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

### CODE REVIEW

**Comment by LucasHT22** [comment]
wow, do you have a 3d printer? what model?

**Comment by troy7615** [comment]
nothing crazy, just an ender 3 pro, but I have made some upgrades to it, like adding a raspberry pi 3 for an octoprint server

**Review by LucasHT22 — COMMENTED** [review]
one question, what's the function of the sprite block?

**Comment by troy7615** [comment]
That's Just the sprite I use for making the game over screen, I could just use the text function though

**Comment by Omay238** [comment]
Lol. I was actually also hoping to try to 3d print a case for it. We also have the same exact printer!

**Comment by troy7615** [comment]
Ya, I think I'd make button caps that have wasd and ijkl printed on them so you know what button is what

**Comment by LucasHT22** [comment]
It's my dream to have a 3d printer, is the ender 3 pro really good?

**Comment by LucasHT22** [comment]
> That's Just the sprite I use for making the game over screen, I could just use the text function though

right!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by troy7615** [comment]
> It's my dream to have a 3d printer, is the ender 3 pro really good?

I would genuinely recommend the ender 3 pro, its the all round budge at beginner king, and with such a large community there are so many upgrades you can get and you wont have a problem looking for a solution to an issue you have.

**Comment by troy7615** [comment]
> Looks good to me! Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Thanks!

**Comment by troy7615** [comment]
How longs do they usually take to ship?

**Comment by LucasHT22** [comment]
> How longs do they usually take to ship?

we aren't shipping, we had delays in delivering ALLPCB

**Comment by troy7615** [comment]
> > How longs do they usually take to ship?
> 
> we aren't shipping, we had delays in delivering ALLPCB

When do you plan on starting shipping again?

**Comment by LucasHT22** [comment]
> > > How longs do they usually take to ship?
> > 
> > 
> > we aren't shipping, we had delays in delivering ALLPCB
> 
> When do you plan on starting shipping again?

the shipments haven't even started... I think that by the beginning of December, the shipments will start

**Comment by troy7615** [comment]
> > > > How longs do they usually take to ship?
> > > 
> > > 
> > > we aren't shipping, we had delays in delivering ALLPCB
> > 
> > 
> > When do you plan on starting shipping again?
> 
> the shipments haven't even started... I think that by the beginning of December, the shipments will start

Oh I understand. Sounds good! And good luck with supply shortages...

**Pull request merged**
