### PR TITLE
Add `Dynamic_Adventure.js`

### PR DESCRIPTION
**Pull request by alexis-martel**
# Your checklist for this pull request

## Author name

**Author:**

Alexis Martel

## About your game

**What is your game about?**

Get the rabbit to the flag!

**How do you play your game?**

`WASD`: moves the player (most of the time)

## Code
Check off the items that are true. 
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game!! did you make it to the end of the game?

**Comment by alexis-martel** [comment]
Not for a few tries! I've always had trouble finishing my own games though 🙃

**Comment by alexis-martel** [comment]
By the way I really enjoyed programming it! I've used PyGame before and the ability to have multiple concurrent timers in JavaScript really made coding for Sprig easier. I loved how simple everything was!

**Comment by LucasHT22** [comment]
> By the way I really enjoyed programming it! I've used PyGame before and the ability to have multiple concurrent timers in JavaScript really made coding for Sprig easier. I loved how simple everything was!

Glad to hear that you liked! Where did you hear about Sprig?

**Comment by alexis-martel** [comment]
> > By the way I really enjoyed programming it! I've used PyGame before and the ability to have multiple concurrent timers in JavaScript really made coding for Sprig easier. I loved how simple everything was!
> 
> Glad to hear that you liked! Where did you hear about Sprig?

I actually first heard about Sprig on [this Hacker News post](https://news.ycombinator.com/item?id=33451148)

**Comment by LucasHT22** [comment]
> I actually first heard about Sprig on [this Hacker News post](https://news.ycombinator.com/item?id=33451148)

WOW out of curiosity, why didn't you make a game before?

**Comment by alexis-martel** [comment]
> WOW out of curiosity, why didn't you make a game before?

I'd been using up my spare time working on my main programming project and I just wanted to finish up a change before moving my focus to Sprig. It was a nice, fun break!

**Comment by LucasHT22** [comment]
Ok! My last question, are you on Hack Club Slack?

**Comment by alexis-martel** [comment]
> Ok! My last question, are you on Hack Club Slack?

No! I'd love to join though!

**Comment by LucasHT22** [comment]
> No! I'd love to join though!

You can join https://hackclub.com/slack/!

**Comment by alexis-martel** [comment]
Thanks!

**Review by LucasHT22 — APPROVED** [review]
As we talked on Slack, 

Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
