### PR TITLE
Countdown Golf

### PR DESCRIPTION
**Pull request by schoblaska**
**Author:** @schoblaska

## Countdown Golf
Countdown Golf is based on [Herugolf](https://www.nikoli.co.jp/en/puzzles/herugolf/) by NIKOLI.

Hit each ball into a hole without crossing any other ball's path. Each ball is labeled with a number; that number indicates how far the ball will travel, and decreases by one each time the ball is hit. Balls can cross blue water hazard tiles but not land on them. You can hit a ball backwards to undo but a stroke will be added to your score.

Use WASD to move the cursor and J to select. Once a ball is selected, choose a direction to hit it in with WASD.

Countdown Golf has 360 original courses. Each course has only one solution. In higher-numbered courses you can score under par with perfect play.

## Code
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image
- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

https://github.com/hackclub/sprig/assets/29129/9504768a-fe03-4880-9229-0b33c6277d39

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR!

**Comment by savinajabbo** [comment]
I love how creative this game is! The amount of maps is amazing, and the music makes the gaming experience fun :)

**Comment by Sheepy3** [comment]
hi, what's blocking this game from being merged?

**Review by LucasHT22 — COMMENTED** [review]
Hey @schoblaska ! I saw that you are still making changes to the game, would you prefer to merge and then open other prs for changes or remain open and let me know when you finish the changes?
(Thanks for the ping @Sheepy3 !)

**Comment by schoblaska** [comment]
Thanks for asking - I'm done fussing with it, feel free to merge whenever :)

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
