### PR TITLE
Jumper

### PR DESCRIPTION
**Pull request by F-14-Tomcat**
# Your checklist for this pull request

## About your game

What is your game about? 
Jump over the obstacles. This is a fun, endless game that allows player to train their reaction time and try to get a new highscore.

How to play your game?
Press W and S to move around the menu. Press any other button to make your selection. Once you start a game, you can move your character with the left D-pad and jump using the right D-pad. Jump over and avoid the obstacles as they move across the screen. If you hit an obstacle you lose a life. You have 3 lives, so be careful!

## Code
Check off the items that are true.
- [X] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [X] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
wow! a fighter plane making games haha

**Comment by LucasHT22** [comment]
great game!
reminded me of Subway Surf
the sprite player is very beautiful

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

out of curiosity, how did you meet sprig?

**Comment by F-14-Tomcat** [comment]
I first learned about sprig from the Hackaday article about it. I based the sprite off of the original Mario just because I liked the way the jumping animation from the first Mario game looked. Unfortunately, I'm in college and am not eligible for a sprig, but I would love to buy one if you make them available to the public.

**Comment by LucasHT22** [comment]
We're not selling, thank you for your interest

**Pull request merged**
