### PR TITLE
SquidsInTheStars

### PR DESCRIPTION
**Pull request by Lucas4680**
# Your checklist for this pull request

## Author name

**Author: Lucas**

## About your game

**What is your game about? Defeating evil squids in a galaxy setting**

**How do you play your game? Use WASD to move and I to shoot. It is an endless game that progressively gets harder, and the score is kept by how many squids you've defeated.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
What's your author name? :)

**Comment by LucasHT22** [comment]
For future reference: #1368

**Comment by Lucas4680** [comment]
Lucas

**Comment by LucasHT22** [comment]
couldn't be Lucas4680? we already have other Lucas:)

**Comment by Lucas4680** [comment]
Yeah sure, Lucas4680 works!

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
