### PR TITLE
Ultra mega  Soap 

### PR DESCRIPTION
**Pull request by joser1109**
# Your checklist for this pull request

## Author name

**Author:** Joser1109

## About your game

Stickman scared of dingle. Use soap dingle, Be careful the soap is omnipotent and can destroy you too!!!!!!! 

**How do you play your game?**
Press WASD to move, and IJKL to place your soap. place soaps on dingles to delete them. Only one soap bar at a time!!!! You cant get hit by a dingle and your soap can hurt you too. There cant be more then 35 dingles or you die. To reset reboot the machine

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR! How do you win your game?

**Comment by joser1109** [comment]
> Thanks for the PR! How do you win your game?

It's endless and the objective is just to survive!

**Comment by LucasHT22** [comment]
Hmm looks like these never disappear 
image

**Comment by joser1109** [comment]
> Hmm looks like these never disappear 
> image
> 

You gotta use the soap bar to clear your path!

**Comment by leomcelroy** [comment]
I like the cleaning premise but I do think this game need more clear parameters for playing. If it's survival at least give a score for how well you survived and indicate when you lost.

Right now you can stand still and spam soap above your head.

**Comment by leomcelroy** [comment]
I'm going to close this for housekeeping but feel free to reopen a submission when you are ready.

**Pull request closed without merging**
