### PR TITLE
Add Hack Craft

### PR DESCRIPTION
**Pull request by khrj**
## About Hack Craft

**What is your game about?**

Hack Craft is a voxel game in which you can build and mine structures

**How to play your game?**

See [controls](https://github.com/khrj/hackcraft#controls)

[Try Hack Craft](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/khrj/sprig/add-hackcraft/games/hackcraft.js&run=true&hide=true)
[Try Hack Craft (with editor)](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/khrj/sprig/add-hackcraft/games/hackcraft.js&run=true)

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

### CODE REVIEW

**Comment by khrj** [comment]
[Try Hack Craft](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/8522ca0cc57673fe1e7caaa0948e3147f7e196e5/games/hackcraft.js&run=true&hide=true)
[Try Hack Craft (with editor)](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/8522ca0cc57673fe1e7caaa0948e3147f7e196e5/games/hackcraft.js&run=true)

**Comment by khrj** [comment]
(I'm not sure why CI is broken, the game seems to work fine)

**Comment by LucasHT22** [comment]
Great game! maybe a pre made structure, background and bigger map can make it even better:)

**Comment by khrj** [comment]
@LucasHT22 I've made the following changes:

- Added a tree, a house and some stone as dirt as ground
- Added a control: Hold s to clear the map (including prebuilt structures, so you can get a fresh slate)
- The map is now larger and has nearly the same aspect ratio as the sprig

[Test changes](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/khrj/sprig/add-hackcraft/games/hackcraft.js&run=true&hide=true)

**Comment by LucasHT22** [comment]
Great changes! for me a background would make it even better:)

**Comment by khrj** [comment]
I don't really like the idea of a background, since it's just a Sprite tiled over and over.

I've tried implementing one, and it didn't really look good, so I decided to leave it out.

**Comment by LucasHT22** [comment]
oh, ok!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by khrj** [comment]
@LucasHT22 btw the author seems wrong, I think you mixed PRs up

**Comment by LucasHT22** [comment]
Sorry! Fixed.

**Pull request merged**
