### PR TITLE
Fake chrome dino game

### PR DESCRIPTION
**Pull request by beanbeah**
Think chrome dino game, but instead of a dino, its now a red cube. 

Interesting experience creating this on the web editor. Will be interesting to see how it plays on the actual hardware

### CODE REVIEW

**Comment by leomcelroy** [comment]
Thanks for the PR! It's a nice tight implementation. I think it needs a little polish before we merge it in though. Could you add a high score and maybe spruce up the art a bit. Perhaps a different background? One of our community members made a help function for layering tiles for backgrounds:

```
function addMap(mapa){
  mapa = mapa.split("\n");
  for(var i = 0; i < mapa.length; i++){
    for(var j = 0; j < mapa[i].length; j++){
      if(mapa[i].charAt(j) !== "."){
        addSprite(j, i-1, mapa[i].charAt(j));
      }
    }
  }
}
```

**Comment by leomcelroy** [comment]
Tested it a bit more and found some other behavior which seems off.

https://user-images.githubusercontent.com/27078897/191111494-dadc8f79-dab6-4ca8-85c3-390d0ad8f075.mov

**Comment by beanbeah** [comment]
Will look into it.

**Comment by ungarmichael** [comment]
we were creating something similar called bert blaster, check it out in the gallery

**Comment by SamDev-7** [comment]
@beanbeah How's it going? It's been a while. Let us know if you need help with anything!

**Comment by leomcelroy** [comment]
I'm going to close this PR for now. Feel free to reopen if you want to continue working on your game.

**Pull request closed without merging**
