### PR TITLE
International morse code trainer

### PR DESCRIPTION
**Pull request by yutarour**
# Your checklist for this pull request

## Author name

**Author:** Yuuta

## About your game

**What is your game about?**
- This game is about learning international morse code. Morse code used to be used for communication, and is still today via the Ham radio service. However, learning it is a pain. Therefore, I tried making it a flashcard/game-like system using sprig.

**How do you play your game?**
- This game has two modes. A text to morse and a morse to text mode. The text to morse code has a interface that allows the user to go through the characters of the alphabet, select the letter and type out a message. The morse to text mode has a interface that allows the user to input morse code and convert it to the alphabet which can be used to learn morse code, and test to see which sequence of dots and dashes is equal to which character. All of the relavant playing instructions i.e. button presses are present in the game.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Comment by yutarour** [comment]
I was looking through things to do over winter break and was reading e-mails and saw it being mentioned in one of the newsletters.

**Review by yutarour — COMMENTED** [review]
Don't know what you want me to change, but sure. I'll review the code.

**Comment by aramshiva** [comment]
Hey! Just wait, Lucas is out on vacation. @grymmy might be able to help.

**Comment by LucasHT22** [comment]
Sorry for the delay @yutarour ! Thanks @aramshiva :)
What should I do after this screen?

**Comment by yutarour** [comment]
You can decode the morse code you entered by pressing the a button which will run the decoding code, turning the morse code (one character at a time) text, and adding it to the buffer characters which is displayed. Or, you can go try the text to morse part of the code which involves selecting a character, by scrolling through the character list and writing a message.

**Comment by LucasHT22** [comment]
Could you wait until tomorrow night? I want to take a more careful review and I'm currently traveling, I'm back to my "office" tomorrow night:)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay! My flight delayed. Could you explain the "toggle sound"?

**Comment by yutarour** [comment]
No problem! Flight delays are a very common thing to happen during the winter traveling season.
That is a currently unimplemented feature that plans to be implemented in the near future. This is because the tone feature of the Sprig editor is a little finicky and making it produce a short tone, delay, produce a long tone makes all of the tones happen at once causing a jumble of notes.

**Comment by LucasHT22** [comment]
True, so could you remove the option? if isn't implemented i think it's better remove:)

**Comment by yutarour** [comment]
Ok, done

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
