### PR TITLE
for_Squiggly_myLost_worm.js

### PR DESCRIPTION
**Pull request by Jerrymiah0220**
# Your checklist for this pull request

## Author name

**Author: Jeremiah Sung**

## About your game

**What is your game about?**
Getting the blue worm to the golden crown

**How do you play your game?**
Press WASD to move, however, the keys are inverted (Example: W goes down) and you have to press J to restart the certain level. The goal? Get the blue worm to the golden crown(infinitely)

Also, I'm not sure if I'm supposed to do this but to describe my coding experience, it is pretty low. This was my first time creating using JS, I believe, and I think it was a very fun experience. I usually do java but doing JS was fun. I am a current 11th grade in Sunny Hills high school. Please, if this was not needed, I am sorry for putting this here.

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Jerrymiah0220** [comment]
Ok no problem

**Comment by LucasHT22** [comment]
What about reduce the width too? I can't see the start and end of this level
 image

**Comment by Jerrymiah0220** [comment]
Fixed!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
image
Sorry for this again! but I would reduce this level too

**Comment by Jerrymiah0220** [comment]
No problem, if there are any more problems please let me know. Thank you.

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
