### PR TITLE
Maise

### PR DESCRIPTION
**Pull request by Umurmiria**
# Your checklist for this pull request

## Author name
Urvi Murmuria
**Author:**

UrMMa

## About your game

**What is your game about?**

To touch the PR pad to reach the next level

**How do you play your game?**

Press WASD to move around to navigate the maze
Dont crash into the fire otherwise your level start restart
press i to reset

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! How about adding an obstacle that if the player crashes the game restarts?

**Comment by Umurmiria** [comment]
Thanks for the idea, but I like my game this way only.

**Comment by LucasHT22** [comment]
hey @Umurmiria ! I would like to see your game approved, but let's get away from the sokoban style a little? maybe adding obstacles...

If you need help, lmk:)

**Comment by Umurmiria** [comment]
Hello @LucasHT22 
I have made the changes you asked for and uploaded my modified game.
I have deleted my old game.

**Comment by LucasHT22** [comment]
Hey! I saw you closed your PR:( Is itv on purpose?

**Pull request closed without merging**
