### PR TITLE
DonkeyKong

### PR DESCRIPTION
**Pull request by Pattuv**
# Your checklist for this pull request

## Author name

**Pratyush Verma**

## About your game

**The game I have created is the original DonkeyKong game from 1981. It has some major differences from the original considering the limitations of the Sprig Console, but I tried to capture the same feel of the game. In the game you look like you have come out of a pipe (absolutely iconic Mario reference) and you have to avoid barrels which move very fast back and forth. You climb ladders until you get to the top level where the princess is captured. When you save her you win! :D**

**The controls for the game are similar to the arcade version of Donkey Kong, A and D to move left and right, W to climb ladders and to go down them. K to jump and I for starting and restarting, which is said in the game.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by alx-alexpark — COMMENTED** [review]
Hii,

I know I sound pretty stupid saying this, but the game is a bit too hard in my opinion (I couldn't get up the first ladder). However, if you think it's playable, I would be fine with accepting it because I can see you put a lot of effort into this game.

**Comment by Pattuv** [comment]
No you are absolutely fine! I understand the game is hard, and it is; it took me 10+ tries to beat it the first time. Of course, that was intentional. The original Donkey Kong, for me at least, is pretty difficult as well, so I tried my best to acheive the same level of difficulty. If you would really like me to decrease the difficulty, all I would have to do is decrease the barrel speed (changing 1 constant lol).

**Comment by Pattuv** [comment]
But if it is okay with you, I would like it to be accepted. Thanks!

**Comment by Pattuv** [comment]
If you would like to see the win screen of my game, here is a screencast of me beating it.
*The video is sped up slightly because of the file size limits on these pull request comments. Thanks!

https://github.com/user-attachments/assets/0ee45ac1-8178-4d95-8635-3bb865e9c740

**Comment by Pattuv** [comment]
One more thing....I am a student going to a verified high school. What are the next steps I need to take to get a Sprig? Thanks again!

**Review by alx-alexpark — APPROVED** [review]
You're all good, thanks for the video! I think your game is really cool and well-made.

You can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/) :)

**Pull request merged**
