### PR TITLE
It's Raining Tacos !

### PR DESCRIPTION
**Pull request by omarko-dev**
# Your checklist for this pull request

## Author name

**Author: omarko**

## About your game

**Welcome to "It's Raining Tacos!", a playful and exciting game where tacos , avocados and chilly fall from the sky, dodge the tacos and shoot the other obstacles to help saving the taco family !**

**How do you play your game?**

Use A and D to move the player, Use J to shoot

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by yednapg** [comment]
Hey @omarko-dev! A couple of changes/modifications are required before I begin reviewing the game.

1.	Please complete the metadata in your game file. It should be like:
```
/*
@title: game titile
@author: name
@tags: [""]
@addedOn: 2024-00-00
*/
```
2.	Rename the game file to avoid any spaces. For example, myGame.js
3.	Please update the GitHub comment in the “How do you play your game?” section.

**Comment by omarko-dev** [comment]
I think everything is ready now

**Comment by yednapg** [comment]
Hey! Thanks for the update!

This needs a bit more to qualify for a Sprig device grant. Please add new mechanics and features to make it more interactive and fun to play.

**Review by grymmy — CHANGES_REQUESTED** [review]
I observed that this game is impossible to succeed at given taco and taco-related objects do not get destroyed after they fall.  This makes subsequent objects unavoidable.

At the very least fix this mechanic such that the game is enjoyable for 60 seconds or more.  Perhaps think of a fun dimension of play such as certain objects that fall (tacos specifically, not avocados perhaps) that radiate pepper-caused heat horizontally that one must avoid - or some such silliness to make it fun and laughable - and again, playable for 60s or more.

**Comment by yednapg** [comment]
Waiting for the author to modify this to meet the bar for a Sprig device grant.

**Comment by omarko-dev** [comment]
@yednapg working on new obstacles and fixing the old issues to make the game more fun and enjoyable for more than 2 minutes the changes should be done in the next few hours

**Comment by omarko-dev** [comment]
@yednapg @grymmy the whole game logic changed now you have to shoot the other obstacles to save the tacos !
i made the game more challenging to be fun for more than 2 minutes
Hope you like it !

**Comment by grymmy** [comment]
This meets the bar now.  Congratz!  If you're a teen, you're eligible for a Sprig device if you fill out this [lil' form for us](https://sprig-order.hackclub.dev/)...  Also, feel free to join Hack Club's slack and share you creation in the #sprig channel!

**Pull request merged**
