### PR TITLE
Save-The-Flower

### PR DESCRIPTION
**Pull request by mhr-isham**
# Your checklist for this pull request

## Author name

**Author:**

Mahir Ishum

## About your game

**What is your game about?**

This game is about saving a fire. There is a flower in the middle. Fires will come towards the flower from two corners. You are driving a firetruck. Your mission should you choose to accept it is to save the flower from the fires. Do you have the speed and courage to complete this mission? (Actually you cannot because it is a game with no end but let's see how much can you withstand?) 

It took me more than 2 weeks to come up with the idea of the game but only about a week to do the code. It was quite a nice experience. 

**How do you play your game?**

Press I to start the game. The fires will come from the upper left and bottom right. As time goes by, the speed of the fires will increase. You need to run over a fire to extinguish it. Use the keys WASD to move. After certain amount of time walls will start to block your way. I also wrote functions for the fires to come from other two corners also but there seems to be a problem with those two function, so I'm keeping them as a comment in the code for now.
## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
- 
## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by mhr-isham** [comment]
> Sorry for the delay! Thanks for your PR! Where did you hear about Sprig?

No problem. I heard about hackclub maybe from a discord server a year ago.Then I got to know about sprig from the newsletter

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! GitHub Education newsletter? Please re-check this:
- [ ] The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by mhr-isham** [comment]
> Nice! GitHub Education newsletter? Please re-check this:
> 
> * [ ]  The name of the file/game contains only alphanumeric characters, -s, or _s.

No hackclub newsletter. I rechecked.

**Comment by LucasHT22** [comment]
Nice! Do you have any suggestions for Sprig?

**Comment by mhr-isham** [comment]
> Nice! Do you have any suggestions for Sprig?

It should have a clear documentation.

**Comment by LucasHT22** [comment]
Right:) Have you already won in your game? it's hard haha

**Comment by mhr-isham** [comment]
> Right:) Have you already won in your game? it's hard haha

Nah. When the fire speed increases drastically, it's impossible to win

**Comment by LucasHT22** [comment]
Haha. What about add instructions to the header?

**Comment by mhr-isham** [comment]
> Haha. What about add instructions to the header?

I have added them already

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
