### PR TITLE
Super Hard Puzzle challenges

### PR DESCRIPTION
**Pull request by RuihanCao**
Super Hard Puzzle challenges
By Ruihan Cao

Instructions:
Hit "run" to execute the code and
The goal is to push the brown boxes onto the green goals. Press j to reset the current level.
Press WASD for movements.
You are a genius if you can pass all ten levels.

I'm a High School student in MA, and I would like to get a Sprig, if my game was approved, you can contact me through my gmail: Ruihan20080129@gmail.com

### CODE REVIEW

**Comment by LucasHT22** [comment]
Hey! Thanks for the PR:)

Please check this:
## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file.

**Comment by RuihanCao** [comment]
I did it based on the tutorial so The code isn't significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery), and everything else is checked off, is that ok or I need to make a different game other than box pushing

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
ok:) how to solve level 4?

**Comment by RuihanCao** [comment]
Yeah, level 4 is tricky many of my friends stuck on it, I can give you a tip, don't move the box straight into the goal. Do you want to try it again or I can tell you the answer.

**Comment by RuihanCao** [comment]
also I changed the graphic a bit, do I need to upload it again or it automatically do that?

**Comment by LucasHT22** [comment]
just update in your fork :)

**Comment by RuihanCao** [comment]
I added music, hints, score, and changed graphic, do I submit another one or what do I do? I think my code is very different then others now.

**Comment by LucasHT22** [comment]
step by step here: https://scribehow.com/shared/How_to_Edit_a_File_on_GitHub_Pull_Request__sdayIETHQ_uIbGVN187mwQ

**Comment by LucasHT22** [comment]
hint number 6 doesn't seem to work, could you explain?

**Comment by RuihanCao** [comment]
what do you mean?

**Comment by RuihanCao** [comment]
like what didn't work? I didn't see anything wrong

**Comment by RuihanCao** [comment]
btw you can go on top of the boxes, I changed the box to gold and goal to box

**Comment by LucasHT22** [comment]
> like what didn't work? I didn't see anything wrong

How to solve level 6?

**Comment by RuihanCao** [comment]
I just made the hints better, you can try again now

**Comment by RuihanCao** [comment]
![image](https://user-images.githubusercontent.com/116044324/232906187-3a6557e3-2456-4e9b-bcb0-9c7d5c4807be.png
All levels are possible to pass.

**Comment by LucasHT22** [comment]
sure, but how to solve level 6?

**Comment by RuihanCao** [comment]
for 7 you go right 1, up 2, left 1, right1, up2, left 1, right 1, down 2, left 1, up 1, left 1, up 1, down 1, right 2, down 3, left 1, up 2,  right 1, up1, left 1, right 1, up1, left 1.

**Comment by RuihanCao** [comment]
for 8 you go up 1, left 1, right 1, up 2, left 1, down 1, left 2, up 1, right 2, down 1, right 1, down 2, left 1, up 1,  right 1, up 1, left 1, up 1, left 2,  down 1, right 2, left 2, down 1, right 2.

**Comment by RuihanCao** [comment]
for 9 you go down 2, up 2, right 1, down 2, left 2, down 2, right 1, up 2, right 1, up 2, left 2,  down 1, up 1, right 2, down 2, left 1, down 2, right 1, up 1.

**Comment by RuihanCao** [comment]
then you pass the game

**Review by LucasHT22 — APPROVED** [review]
Thanks! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Where did you hear about sprig?

**Pull request merged**
