### PR TITLE
Added The Adventures of SprigBot: The Shifting Labyrinth

### PR DESCRIPTION
**Pull request by studentkrisk**
## Author name

**Author:**
Krisk

## About your game

**What is your game about?**

An endless rouge like where you battle evil clones of yourself.

**How do you play your game?**

WASD to move, IJKL to spray acid in the respective direction. There is currently no end; I'm waiting for inspiration to figure out how to end it lol.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors.
^ while there are some errors, they do not affect the playability of the game. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!
Thanks for the repo!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game!! Did you maneged to win some level? I don't haha

**Comment by studentkrisk** [comment]
Yeah, I'm still creating proper levels lol, I want about 10 before I update the PR. Sorry!

**Comment by LucasHT22** [comment]
> Yeah, I'm still creating proper levels lol, I want about 10 before I update the PR. After that I'm going to add a boss fight. Sorry!

No worries, so would you prefer keep this PR til you complete the updates or merge and you make another PR for updates?

**Comment by studentkrisk** [comment]
I have no preference, so I'll just stick with this one for now. Thanks!

**Comment by LucasHT22** [comment]
Alright!

**Comment by LucasHT22** [comment]
Hey! I think I misunderstood, do you want to continue with the version of this PR? Sorry for the delay

**Comment by Sheepy3** [comment]
Closing this PR due to inactivity. If you want it reopened, ping me here.

**Pull request closed without merging**
