### PR TITLE
Maze Game

### PR DESCRIPTION
**Pull request by madison-shaw0**
# Your checklist for this pull request

## Author name
Madison Shaw

## About your game

A character needs to find their way through 5 levels of mazes before they can escape!

**How do you play your game?**
Press WASD to move, get to the green flag.

## Code
Check off the items that are true. 
- [X ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X ] The game runs without errors. 
- [X ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! Did you use any game for inspiration?

**Comment by madison-shaw0** [comment]
Thank you! My inspiration wasn't a specific game, but an escape room my friends and I recently did.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! What about more levels?

**Comment by madison-shaw0** [comment]
I added 5 more levels with longer mazes!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
level 7 seems impossible to solve, could you tell me how to solve it?

**Comment by madison-shaw0** [comment]
It was impossible to solve, my bad! I updated the code to fix it.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
No worries! How about decreasing the size of the last level? I think it will be too small on the console

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Last thing, could you change the name? We already have a game with that name, sorry

**Comment by madison-shaw0** [comment]
Of course! No problem

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
