### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by TvoozMagnificent**
# Your checklist for this pull request

## Author name

**Author:**

NumberBasher

## About your game

**What is your game about?**

Sliding Puzzle Game Without Friction

**How do you play your game?**

WASD.

### CODE REVIEW

**Review by GalaxyGamingBoy — CHANGES_REQUESTED** [review]
Cool game so far, I love the art but unfortunately to publish it in the gallery it would be to add at least one more novel game mechanic to make it unique. It's okay to remix other games but we expect to see some more game mechanic differences :)

**Comment by TvoozMagnificent** [comment]
How do I resubmit?

**Comment by TvoozMagnificent** [comment]
@GalaxyGamingBoy also, while we're here, how much should i worry about in terms of optimization (will sprig require optimization)

my current code is not worrying about optimization at all (a lot of redundant checks, etc.)

**Comment by GalaxyGamingBoy** [comment]
> How do I resubmit? 

Hi! Just commit the updated file and I'll rereview it! No need to close this PR, GitHub will automatically update it based on your repo

**Comment by GalaxyGamingBoy** [comment]
> @GalaxyGamingBoy also, while we're here, how much should i worry about in terms of optimization (will sprig require optimization)
> 
> my current code is not worrying about optimization at all (a lot of redundant checks, etc.)

You don't have to worry about that for now. You can always do further optimizations after getting your sprig so you can test it on device

**Comment by TvoozMagnificent** [comment]
@GalaxyGamingBoy Updated!

**Comment by TvoozMagnificent** [comment]
hello?

**Comment by grymmy** [comment]
Unfortunately, this game is too similar to others in the gallery (i.e. much of the code is identical).  Closing this PR as it hasn't moved in some time.

**Pull request closed without merging**
