### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Oasx**
# Your checklist for this pull request

## Author name

**Author: Akko**

## About your game

**You are a mailman, deliver these packages, or the world will sink into despair!!!**

**Normal WSAD, J if stuck, avoid badboxes: they are bad, get to the conveyor belt**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! Some questions:) What's the game name? How to solve this level? 
image

**Comment by Oasx** [comment]
The game is called mailman. The level is supposed to be a puzzle, you can move the first box to the left and the other box down so they are parallel, and move the upper box to the upper goal and the other one to the one in the lower goal

**Comment by LucasHT22** [comment]
> The game is called mailman. 

So please rename the file to this:) 

> The level is supposed to be a puzzle, you can move the first box to the left and the other box down so they are parallel, and move the upper box to the upper goal and the other one to the one in the lower goal

Could you send a screen record? thanks:)

Also - did you use some game as inspiration?

**Comment by Oasx** [comment]
https://github.com/hackclub/sprig/assets/126536553/0f10f309-983f-4f07-b8a6-3d29e943d10e

Done

**Comment by Oasx** [comment]
What is the "inspect" link from vercel? It redirects me to a site where I have to log-in as username:gamer? even though my git hub username is Oasx. It might be broken

**Comment by LucasHT22** [comment]
> Untitled.videoasd.mp4 
> Done

Thanks!!

**Comment by LucasHT22** [comment]
> What is the "inspect" link from vercel? It redirects me to a site where I have to log-in as username:gamer? even though my git hub username is Oasx. It might be broken

oh just ignore this haha, this is for development, i also don't have access to this

**Comment by Oasx** [comment]
No, I just used the tutorial as a kind of base so there might be a similarity in the first or second level, but no.

**Comment by Oasx** [comment]
@LucasHT22

**Comment by LucasHT22** [comment]
Sorry for the late! Alright, could you please just move your game to /games? You can do it renaming and adding games/ before the game name:)

**Comment by Oasx** [comment]
there!

**Review by LucasHT22 — APPROVED** [review]
Alright! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
