### PR TITLE
type_or_die

### PR DESCRIPTION
**Pull request by jblum-coder**
# Your checklist for this pull request

## Author name
Jesse Blum aka jblum-coder 

## About your game
Type out words before the time runs out! 

**How do you play your game?**
Use WASD to move to the characters and J to select the letter. To remove a letter press K.

## Code
- [x] The game was made using the [Sprig editor]
- [X] The game is placed in the in the [`/games` directory]
- [X] The code is significantly different from all other games in the [Sprig gallery]
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery]

## Image (If an image is used)
- [X] The image is in the [`/games/img` directory]
- [X] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for my delay and thanks for the PR! Where did you hear about Sprig?

**Comment by jblum-coder** [comment]
Hello, I heard about Sprig from my computer science teacher. I am a sophomore and i am in AP computer science principles. He showed me this because he knows I am a good coder and thought I might enjoy it. I thought it would be cool to get a Sprig so i developed the game “type_or_die” in hopes of meeting the requirements and getting sent a Sprig of my own.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! What about increase time?

**Comment by jblum-coder** [comment]
I increased the time, I get what your saying. It was super hard, but it's now 15 seconds. Is it good?

**Review by LucasHT22 — APPROVED** [review]
Great! What was your highest score? Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
