### PR TITLE
Block Stacker

### PR DESCRIPTION
**Pull request by vracton**
# Your checklist for this pull request

## Author name

**Author:** vracto

## About your game

**What is your game about?**

Stack blocks on top of each other! Can you get to the top?!

**How do you play your game?**

It's simple! Just press `s` to place a block and `w` to restart!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR!

**Comment by savinajabbo** [comment]
Your game is superb, and is really entertaining! What about adding more levels to make it a challenge? Also, what about adding a key to restart the game?

**Comment by vracton** [comment]
> Your game is superb, and is really entertaining! What about adding more levels to make it a challenge? Also, what about adding a key to restart the game?

That's a great idea! I'm not really sure about adding more levels, but I could definitely add a restart button.

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
