### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AVSCGREAT**
# Your checklist for this pull request

## Author name

**Author: AVSC**

## About your game

**What is your game about? - Ping pong full**

**How do you play your game?**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
There are graphical glitches obvious when playing the game (the paddles don't re-render properly).  Also, I need you to add a bit of spice to the game (i.e. more mechanics, or a twist) to meet the bar for receiving a Sprig device grant.

**Comment by AVSCGREAT** [comment]
K

**Comment by grymmy** [comment]
Still eagerly awaiting changes from author re: this game.

**Comment by recursiveforte** [comment]
Looked at this today- no change

**Comment by AVSCGREAT** [comment]
Sorry changes are delayed as I am busy for few days

**Comment by grymmy** [comment]
Closing this due to inactivity.  Feel free to re-open this PR if you want to advocate for its merge.

**Pull request closed without merging**
