### PR TITLE
Cross_the_Road game added

### PR DESCRIPTION
**Pull request by Haneesh000**
# Your checklist for this pull request

## About your game

What is your game about? 
> This game is a basic game about crossing the road. The vehicles will spawn randomly in the map and you have to dodge them and reach the finish line.
How to play your game?
> Press WASD to move and don't forget to dodge the vehicles.
## Code
Check off the items that are true.
- [ ✔ ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ ✔ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ✔ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labelled "demo").
- [ ✔ ] The game runs without errors. 
- [ ✔ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ✔ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ✔ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ✔ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by vmss2009** [comment]
please upload the game fast

**Comment by LucasHT22** [comment]
Good game! I saw that it has a second Score counter at the end, was it intentional?

https://user-images.githubusercontent.com/88567622/209687298-4e335301-afd8-48e5-b18e-2a4948c7d604.mp4

**Comment by Haneesh000** [comment]
It's just a bug but I've solved it

**Comment by Haneesh000** [comment]
Can you just review the game and publish it?

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
