### PR TITLE
NEW tags

### PR DESCRIPTION
**Pull request by LucasHT22**

### CODE REVIEW

**Comment by grymmy** [comment]
@LucasHT22 @GalaxyGamingBoy do yall plan on landing this ever?

**Comment by GalaxyGamingBoy** [comment]
what is this pr?

**Comment by LucasHT22** [comment]
Finishing tonight

**Comment by Sheepy3** [comment]
hey, has this PR been abandoned?

**Comment by grymmy** [comment]
@LucasHT22 do you intend on landing this?

**Comment by grymmy** [comment]
I am closing this PR as it seems old and probably not worth landing.  Please reopen this PR if you feel strongly that it should land.

**Pull request closed without merging**
