### PR TITLE
GAME UPDATE!!

### PR DESCRIPTION
**Pull request by ktauchathuranga**
heyyyy,
i added score system, and fixed some bugs in some levels

(my thumb is not showing in the gallery tho, can you check what happened?)

### CODE REVIEW

**Comment by ktauchathuranga** [comment]
i see that "test game" failed for some reason. but i just played and tested it a number of times. it works fine for me tho 🤧

**Review by LucasHT22 — APPROVED** [review]
LGTM! About thumb, it's bc the first map is full white, you can add a thumb in /games/img with the same name of your game:)

**Comment by ktauchathuranga** [comment]
actually i did upload the thumb. you can see here,
https://github.com/hackclub/sprig/pull/1189/commits/69ccc9a2102fa8e9282a8d21fe82550b8a26c3e8
(it have a red cross saying authorization needs to deploy in that commit) 🤧

**Comment by LucasHT22** [comment]
oh it's because is .png.PNG, need to be only [GAMENAME].png

**Comment by ktauchathuranga** [comment]
oooooh nooooooooo, i didnt see that. um sorry.
can you please tell me what should i do?
should open a pr after fixing that?

**Pull request merged**
