### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by puppybro11991**
# Your checklist for this pull request

## Author name

**Author:** Hunter

## About your game

**What is your game about?** About my FRC team 2016 mighty monkey wrenches defeating our enemies nemesis

**How do you play your game?** WASD and use i to shoot and j to reset

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! what does the enemy represent?

**Comment by puppybro11991** [comment]
> Nice game! what does the enemy represent?

Team nemisis I thought it was funny to have our enemy be nemisis

**Comment by LucasHT22** [comment]
oh interesting! I'll check

**Comment by puppybro11991** [comment]
> oh interesting! I'll check

Is it eligible for a sprig?

**Comment by LucasHT22** [comment]
Hey, after an internal discussion, we concluded that the enemy being a real team may sound like an offense, I know it was not your intention but before approving I ask that you change the appearance of the "enemy" sprite to avoid problems :)

Thank you for understanding!

**Comment by puppybro11991** [comment]
> 
> 
> Hey, after an internal discussion, we concluded that the enemy being a real team may sound like an offense, I know it was not your intention but before approving I ask that you change the appearance of the "enemy" sprite to avoid problems :)
> 
> 
> 
> Thank you for understanding!

Ok should I redo it and just edit the code in or create a new pull request

**Comment by LucasHT22** [comment]
just edit:)

**Comment by puppybro11991** [comment]
> just edit:)

K

**Comment by puppybro11991** [comment]
> just edit:)

ok i fixed it its now a banana in a space ship

**Review by LucasHT22 — APPROVED** [review]
Great, thanks for understanding! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by puppybro11991** [comment]
> Great, thanks for understanding! Congrats:)
> 
> If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> 
> 
> 
> Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Ok thank you

**Pull request merged**
