### PR TITLE
botdotpng

### PR DESCRIPTION
**Pull request by mavdotjs**
# Your checklist for this pull request

## Author name

**Author:** Kai

## About your game

**What is your game about?**
Teaching a robot to reach it's flag by placing arrows

**How do you play your game?**
WASD - Move Cursor

I - Spawn in bot
J - Rotate an arrow
K - Cycle though the tutorial text
L - Changes a tile (turns an empty tile into an arrow, and back, or if you have unlocked conditionals, it will cycle between normal, conditional, or empty)

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The game runs without errors. 
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by mavdotjs** [comment]
despite being called 'dotpng' the art isn't very good

**Comment by mavdotjs** [comment]
I also have no reason why I called it that..

**Comment by recursiveforte** [comment]
Great job with this project- this was really interesting to play with. I'm approving it, and you should see it in the gallery next week.

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev) and join our [online Slack community](https://hackclub.com/sprig) to chat with other people making Sprig games.

**Comment by mavdotjs** [comment]
Thank you so much! I updated the branch so it can merge, I'm not sure if sprig maintainers have edit access to my branch.

**Pull request merged**
