### PR TITLE
Remove unused logo file

### PR DESCRIPTION
**Pull request by sampoder**
We don't seem to be using this anymore, might be worthwhile removing.

### CODE REVIEW

**Comment by Omay238** [comment]
Hello, this image is being used: [see here](https://editor.sprig.hackclub.com/assets/index.764eb6b7.js). It is the top left image in the editor.

**Comment by LucasHT22** [comment]
Exact 
image

**Comment by sampoder** [comment]
> Hello, this image is being used: [see here](https://editor.sprig.hackclub.com/assets/index.764eb6b7.js). It is the top left image in the editor.

In here it's being pulled from Hack Club's CDN:

```
 <img src="https://cloud-ah8ey4rmb-hack-club-bot.vercel.app/0spriglogotext-white.png" alt="sprig logo" class="sprig-logo" />
```

**Comment by sampoder** [comment]
> Exact image

This is a separate codebase: https://github.com/hackclub/sprig-gallery/blob/main/static/spriglogotext-white.png

**Pull request merged**
