### PR TITLE
Add eat_the_cake game

### PR DESCRIPTION
**Pull request by klyap**
A mini game about choices...

(A re-submission of: https://github.com/hackclub/sprig/pull/351)

### CODE REVIEW

**Comment by LucasHT22** [comment]
thanks for the collaboration!

**Comment by LucasHT22** [comment]
I'll merge this, looks like Sam and Leo already approve

**Comment by SamDev-7** [comment]
Might be better to keep the "two" games in one file.

**Comment by LucasHT22** [comment]
Before merging, @SamDev-7 , what do you mean 2 games?

**Comment by SamDev-7** [comment]
My bad! I didn't read all comments in the other PR.
Disregard everything I just said.

**Comment by LucasHT22** [comment]
no problems! I was confused too

**Pull request merged**
