### PR TITLE
Destroy The Hearts

### PR DESCRIPTION
**Pull request by zKxra**
I Made a game that you destroy the hearts (its my first game)

Your checklist for this pull request
Author name
Author: Deniz Melik Aktın (zKxra)

About your game
What is your game about?

 Destroying the hearts with swords 

How do you play your game?

Press WASD to move, J to restart.

Code
Check off the items that are true. 
[x ] The game was made using the Sprig editor.
[x ] The game is placed in the in the /games directory.
[x ] The code is significantly different from all other games in the Sprig gallery (except for games labeled "demo").
[x ] The game runs without errors.
[x ] The name of the file/game contains only alphanumeric characters, -s, or _s.
[x ] The game name is not the same as the others from gallery

Image (If an image is used)
[ ] The image is in the /games/img directory.
[ ] The name of the image matches the name of your file. 

Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Were you able to run your game?

**Comment by zKxra** [comment]
Yes i was able to

**Comment by LucasHT22** [comment]
So check if the code you send is the correct, because I wasn't:)

**Comment by cott3** [comment]
so my friend is gonna create a new pr

**Comment by zKxra** [comment]
Can you delete my PR I can't do anything to it

**Comment by LucasHT22** [comment]
> i found out why just trying to make it correct

Sorry, I didn't understand, could you reformulate?

**Comment by LucasHT22** [comment]
> Can you delete my PR I can't do anything to it

don't give up! I'm here to help

**Pull request closed without merging**
