### PR TITLE
Dogs vs Cats

### PR DESCRIPTION
**Pull request by throdeo**
# Your checklist for this pull request

## About your game
i am a beginner coder this is my first game i have ever finished.
What is your game about? 
 my game is about a dog dodging cats.

How to play your game?
S and W to move the dog up and down and dodge the cats!

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Game very good! could you add a background?

**Comment by throdeo** [comment]
> Game very good! could you add a background?

added grass background as requested by @LucasHT22

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

out of curiosity, how did you meet sprig?

**Comment by throdeo** [comment]
my dad found it

**Comment by LucasHT22** [comment]
do you know where he found it?

**Comment by LucasHT22** [comment]
oh, cool!

**Pull request merged**
