### PR TITLE
maze-eye

### PR DESCRIPTION
**Pull request by acornitum**
# Your checklist for this pull request

## Author name

**Acon**

## About your game

Maze-eye is a multi level game where you try escaping a maze - however, there are multiple monsters going from both horizontal and vertical directions that you need to dodge. Through the later levels, there are also blind parts of the map where you can't see your character. 😁 

It's called Maze-eye because 1) maze and 2) the monsters all have a giant eye, so thematic reasons. It used to be called thundering_mewtwo which was the coolest name ever but sadly I felt like changing it to fit 😔 

**How to play** 👁️ 

Press WASD to move! Remember, dodge the monsters, and run keep on running right to the next level. 👟 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR!! Where did you hear about Sprig?

**Comment by acornitum** [comment]
Orignally through the github education(?) newsletter, but I've been in the hack club slack for around a year!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! What about J to restart?

**Comment by acornitum** [comment]
I've added press i to restart!

**Comment by LucasHT22** [comment]
Nice! Did you manage to win the game?

**Comment by acornitum** [comment]
Yup! after quite a few tries :"D

**Review by LucasHT22 — APPROVED** [review]
Right! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
