### PR TITLE
Save the knight

### PR DESCRIPTION
**Pull request by JARVIS-124**
# Your checklist for this pull request

## Author name

**Dibya**

## About your game

**In this game  you have to save the knight from the goblins falling from above by dodging them**

**Press your A key to move left and press your D key to move right  and save the knight**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`games/img/savetheknight.png](https://github.com/JARVIS-124/sprig/blob/main/games/img/savetheknight.png).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by JARVIS-124** [comment]
please check

**Comment by JARVIS-124** [comment]
please check

**Comment by JARVIS-124** [comment]
Please check

**Comment by recursiveforte** [comment]
Hi- unfortunately this game doesn't meet the bar for being merged into the gallery, as it's too similar to other games with falling objects. You could differentiate it by adding another game mechanic or two.

**Comment by JARVIS-124** [comment]
No sir it's not I searched as much as possible didn't find anything like this so I made it

**Comment by grymmy** [comment]
> No sir it's not I searched as much as possible didn't find anything like this so I made it

Please differentiate this game by adding one or two game mechanics per @recursiveforte 's statement.

**Comment by JARVIS-124** [comment]
Which mechanics you want me to add can you suggest

**Comment by recursiveforte** [comment]
I'm not sure which mechanics you'd want to add in your particular case, but here's a [tutorial](https://jams.hackclub.com/batch/sprig/part-3) that walks you through some common mechanics and Sprig features!

**Comment by grymmy** [comment]
Closing this due to inactivity.  Feel free to re-open this PR if you want to advocate for its merge.

**Pull request closed without merging**
