### PR TITLE
author sprig runbook

### PR DESCRIPTION
**Pull request by JosiasAurel**

### CODE REVIEW

**Review by grymmy — APPROVED** [review]
a step in the right direction

**Comment by LucasHT22** [comment]
I know that I shouldn't intrude in this, but Wouldn't it be better to keep this in /wiki?

**Comment by JosiasAurel** [comment]
@LucasHT22 you're not intruding at all. We should probably have it there as well tbh I didn't know that existed :D

**Comment by LucasHT22** [comment]
:) some time ago Graham said that would be better runbooks be in wiki bc it's faster to update

**Comment by grymmy** [comment]
As long as easily accessible via github + added as slacker resource I'm 😊

**Comment by grymmy** [comment]
Can link from wiki add Readme and slacker - all to same source of truth

**Pull request merged**
