### PR TITLE
DoNotTouch

### PR DESCRIPTION
**Pull request by tinkeridea**
## About your game
This game is like offline browser dinosaur game.

What is your game about? 
> You Need to avoid walls and try to move forward to score

How to play your game?
> Press WASD to move.

## Code
Check off the items that are true.
- [ yes ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ yes ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ yes ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ yes ] The game runs without errors. 
- [ yes ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ yes ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ yes ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ yes ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
Good game! how about making sprites with drawings? did you use any other game for inspiration?

**Comment by SamDev-7** [comment]
Your file name should not contain spaces or apostrophes. Let us know if you need any help!

**Comment by tinkeridea** [comment]
> Good game! how about making sprites with drawings? did you use any other game for inspiration?

First I wanted to make a simple dinosaur game of offline browser to make it more interesting I added more opponents. Then I started to explore more games in sprig I found one game in that game you need to touch the finish line so I added this to my game. This is the full process that how made my game. I started working on this game epoch Delhi.

**Comment by tinkeridea** [comment]
> Your file name should not contain spaces or apostrophes. Let us know if you need any help!

What I have to do next to get sprig.

**Comment by SamDev-7** [comment]
Rename your file to not contain spaces or apostrophes and it should be good to go!

**Comment by tinkeridea** [comment]
> Rename your file to not contain spaces or apostrophes and it should be good to go!

I renamed my file. 
You can see it again.

**Comment by LucasHT22** [comment]
Could you add more to your game or add inspiration credits? the code is very similar to another one in the gallery

**Comment by tinkeridea** [comment]
> Could you add more to your game or add inspiration credits? the code is very similar to another one in the gallery

Ok

**Comment by leomcelroy** [comment]
I'm going to close this PR for now but feel free to reopen if you want to continue working.

**Pull request closed without merging**
