### PR TITLE
Health_Bar_Tutorial

### PR DESCRIPTION
**Pull request by KnightOfTheRoundTable**
# Your checklist for this pull request

## About your game

What is your game about? 
> Example: This is a tutorial showing how to put a health bar in your game

How to play your game?
> Example  :  Just read it, comment or uncomment things, and hit run.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by KnightOfTheRoundTable** [comment]
The Fish in the Sea game wasn't supposed to be updated in this pull request, but I can't figure out how to undo it.

**Comment by KnightOfTheRoundTable** [comment]
The fish in the sea game should not be updated, but I can't figure out how to delete that commit

**Comment by LucasHT22** [comment]
> The fish in the sea game should not be updated, but I can't figure out how to delete that commit

To remove just change the file putting a previous version with another commit:)

**Comment by LucasHT22** [comment]
Jet_Box too?

**Comment by KnightOfTheRoundTable** [comment]
I think everything is fixed now. Everything can be updated and if it messes something up, I'll make another pull request to fix it.

**Comment by LucasHT22** [comment]
Very interesting tutorial! Do you have an example of use? Just to make sure I understand:)

**Comment by KnightOfTheRoundTable** [comment]
You could make a game with a health bar at the top or a corner of the screen and have it go down when your character gets hurt. It's just a fancier way to display health than with text on screen.

**Comment by LucasHT22** [comment]
Do you want me to add the tag "tutorial" or "tool"?

**Comment by KnightOfTheRoundTable** [comment]
Either tag works, but I've run into other problems that the code causes. I'll fix them as they come up and then re-open this.

**Pull request closed without merging**
