### PR TITLE
⚡ Add the Reactor game!

### PR DESCRIPTION
**Pull request by sampoder**
_(my not so great game... but it is two player?)_

### CODE REVIEW

**Comment by SamDev-7** [comment]
Great game! I love it!
_Would be cool if it restarted by itself after a while though._

**Comment by sampoder** [comment]
100%! Is there any previous game that's used similar logic?

**Comment by LucasHT22** [comment]
I confess I got lost in this game haha. Good game!

**Comment by blobbybilb** [comment]
> 100%! Is there any previous game that's used similar logic?
@sampoder

Not sure if it's exactly what you're looking for, but I made a restart countdown for my game...

[Seven Ate Nine](https://editor.sprig.hackclub.com/?id=36376f33cb2485c32002521c4b0ea94e)

**Comment by leomcelroy** [comment]
I love the thread on here. Congrats on your Sprig Sam! https://sprig-order.hackclub.dev/

**Pull request merged**
