### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AKTHEPRO47**
# Your checklist for this pull request

## Aryan is the creator of the game

What is your game about? 
> Example: Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))

How to play your game?
> Press WASD to move, , use the cricket bat to move the ball  to the target

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
Please complete the checks!

**Comment by LucasHT22** [comment]
What's the nome of the game? and levels 1, 6 and 7 seem to have no solution

**Comment by AKTHEPRO47** [comment]
The Name isCRICKET FRENZY

**Comment by LucasHT22** [comment]
How solve levels 1,6 and 7?

**Comment by AKTHEPRO47** [comment]
new levels created

**Comment by LucasHT22** [comment]
I didn't receive the updates :(

**Comment by AKTHEPRO47** [comment]
try seeing now sir

**Comment by AKTHEPRO47** [comment]
above is the full code

**Comment by SamDev-7** [comment]
Can you paste the code into the file?
image
image

**Comment by LucasHT22** [comment]
^^^

**Comment by AKTHEPRO47** [comment]
done sir

**Comment by LucasHT22** [comment]
sorry, but how to play your game?

**Comment by AKTHEPRO47** [comment]
use WASD to move bat to hit ball to target

**Comment by LucasHT22** [comment]
oh, sorry, when i did an update i deleted the player by mistake

**Comment by LucasHT22** [comment]
about the music, don't you think it's too shrill?

**Comment by AKTHEPRO47** [comment]
to me the music makes the player tense

**Comment by LucasHT22** [comment]
oh, ok! makes sense.

**Comment by AKTHEPRO47** [comment]
THANK YOU

**Pull request merged**
