### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by avasada**
Santa's Workshop

## About your game

What is your game about? 
Help santa's elves push presents towards the shoots. 

How to play your game?
Push presents to the shoots. Some levels with have obstacles you eed to get around. You might also have more than 1 present, just make sure each shoot has one present to progress to the next level!

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great! what do you think of adding a restart function?

**Comment by avasada** [comment]
> Great! what do you think of adding a restart function?

Great idea! I just added 2 restart functions. Pressing "l" restarts the level and "j" restarts the game :)

**Comment by LucasHT22** [comment]
good changes! just a detail, Levels 7 and 8 are the same, is it on purpose?

**Comment by avasada** [comment]
> 

Oh you're right! I just fixed that

**Comment by LucasHT22** [comment]
Just out of curiosity:) what does the name mean?

**Comment by LucasHT22** [comment]
how about adding a "you win!" at the end?

**Comment by avasada** [comment]
> how about adding a "you win!" at the end?

You read my mind! Just added

**Comment by avasada** [comment]
> 
The player is an elf who is pushing presents down tubes in Santa's workshop

**Comment by LucasHT22** [comment]
sorry for the delay!! I missed your notification in the middle of the issues

 one more detail `(sorry for so many details:))` : in this version, are the levels evolving for you?

**Review by LucasHT22 — APPROVED** [review]
Yeah, progress! Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
