### PR TITLE
Create spriggymon.js

### PR DESCRIPTION
**Pull request by spriglover69**
# Your checklist for this pull request

## About your game

What is your game about? 

Proudly inspired by the genre-defining ludonarrative experience, _Pokemon_, spriggymon is a fully-featured JRPG with ZERO bugs or confusing narratives.

How to play your game?

I'm sure you'll figure it out.

## Code
Check off the items that are true.
- [ ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
WOW great game! I'll take a while to review all the code, ok?

**Comment by LucasHT22** [comment]
do you have a game script? what happens or such

**Comment by LucasHT22** [comment]
is this the final screen?

**Comment by troy7615** [comment]
This game is amazing! it looks like a game boy game!

**Pull request merged**
