### PR TITLE
TICTACGPT

### PR DESCRIPTION
**Pull request by 2008wbbv**
Your checklist for this pull request
Author name
Author: 2008wbbv

About your game
Basic Tic Tac Toe game with a very low level computer player, planning on adding more difficulties, no other tic-tac-toe games have a CP

Control the cursor with WASD and press I to place your x/o Code
Check off the items that are true.

[x ] The game was made using the Sprig editor.
[x ] The game is placed in the in the /games directory. [x ] The code is significantly different from all other games in the Sprig gallery (except for games labeled "demo"). [x ] The game runs without errors.
[x ] The name of the file/game contains only alphanumeric characters, -s, or _s. [x ] The game name is not the same as the others from gallery Image (If an image is used)
[x ] The image is in the /games/img directory.
[x ] The name of the image matches the name of your file.

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! What about J to restart?

**Comment by Ben-Vaccaro** [comment]
im not very good with js and dont know how to, if you could help explain how that would be cool.

**Comment by LucasHT22** [comment]
> im not very good with js and dont know how to, if you could help explain how that would be cool.

Sure, I can help:) you will need the same structure of player movments, but instaed of using getFirst(), you'll use const with the current level variable

**Comment by 2008wbbv** [comment]
im still not sure how to after a week of messsing around with it

**Comment by LucasHT22** [comment]
> im still not sure how to after a week of messsing around with it

Try to find other game in gallery that have this function:) If you don't find, please lmk:)

**Comment by 2008wbbv** [comment]
If im not mistaken the code I modified did not have that function aswell as any simaler code

**Comment by LucasHT22** [comment]
wait, which code did you modify?

**Comment by 2008wbbv** [comment]
It should be in the credits at the top of the file.

**Comment by LucasHT22** [comment]
> It should be in the credits at the top of the file.

would you have a link?

**Comment by 2008wbbv** [comment]
https://sprig.hackclub.com/gallery/Tic_Tac_Toe

**Comment by LucasHT22** [comment]
Could you add it to the header of your game?

**Comment by 2008wbbv** [comment]
Sure I had his name but that's a good idea too, I just saw that he didn't put a link for his source so I assumed it was fine.

**Comment by 2008wbbv** [comment]
> 

done

**Review by LucasHT22 — APPROVED** [review]
Alright! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
