### PR TITLE
Falling_Water

### PR DESCRIPTION
**Pull request by Captainexpo-1**
This is a falling sand style game that simulates water with an amount of accuracy. 

I have made games with unity for a few years, and I made my first website around a week ago. This is my first JavaScript coding experience, and I am pretty happy with the result.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Good game! A game with gravity, interesting

**Review by LucasHT22 — COMMENTED** [review]
Good game! A game with gravity, interesting

**Review by LucasHT22 — COMMENTED** [review]
What is the purpose of the game? 
Just fill with water? 
Is there any way to lose? 
What do you need to level up?

**Comment by Captainexpo-1** [comment]
This is just meant to be a cool little experience. It's not really meant to be played with the mindset that you are going to level up and get better at it, it is just something to mess around with.

**Comment by SamDev-7** [comment]
Thanks for the PR! The code looks very simple for what it does, wow! 
Good work!

If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by LucasHT22** [comment]
> This is just meant to be a cool little experience. It's not really meant to be played with the mindset that you are going to level up and get better at it, it is just something to mess around with.

Ok!

**Comment by Captainexpo-1** [comment]
Thank you!

**Pull request merged**
