### PR TITLE
CaveEscape.js

### PR DESCRIPTION
**Pull request by ThePancake41**
# Your checklist for this pull request

## Author name: Michael

**Author:** aPancake

## About your game

**What is your game about?**

Use your three skills to defeat enemies and escape the cave. Gamble and use you magic or rely on health to damage your enemies.

**How do you play your game?**

WASD to move the cursor around and J to select/execute action you have selected.

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay! Thanks for your PR! Where did you hear about Sprig?

**Comment by ThePancake41** [comment]
I heard about it from my AS Computer Programing teacher.

**Comment by LucasHT22** [comment]
Nice! Could you remove from /img folder and just let in /games? :)

**Comment by ThePancake41** [comment]
Moved it, sorry for the delay!

**Comment by LucasHT22** [comment]
No problem! What about adding instructions in header? :)

**Comment by ThePancake41** [comment]
I believe this is what you wanted?

**Comment by LucasHT22** [comment]
Yep! Have you already won in your game?

**Comment by ThePancake41** [comment]
I have beat the game yes.

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
