### PR TITLE
Cricket Dodge

### PR DESCRIPTION
**Pull request by harshsingh89**
Hi my name is Harsh Singh . The name of my game is cricket dodge . It was made using sprig editor . I used the tutorial for some help in making the game . In this game we have to not let the wicket get hit by the cricket ball or we will loose a life . We have a total of 5 lives . We can move using A and D . 

Thanks

### CODE REVIEW

**Review by SamDev-7 — CHANGES_REQUESTED** [review]
Cool game! Thanks for the PR!
The game is very hard, it might be good to reduce the number of obstacles spawning. One way to achieve this is to make it spawn once per 2, 3 or more game loops.
For the image, it would be preferred if it would be a screenshot of the game itself in the sprig editor. 
Let us know if you need any help. Happy hacking!

**Comment by harshsingh89** [comment]
Hi my name is Harsh Singh . Thank you for your suggestion . I tried to make
it a little easier . Could you please check my game again .

**Comment by harshsingh89** [comment]
Hi . I just ordered the sprig . I mistakenly wrote my number wrong . You
can find my number below

+91 8882251176

Thanks.

**Comment by LucasHT22** [comment]
Ok! I will delete your comment so your number is not public:)

**Comment by harshsingh89** [comment]
Awesome, thank you so much!

**Pull request merged**
