### PR TITLE
Add updated spade uf2

### PR DESCRIPTION
**Pull request by polypixeldev**
Updates the `pico-os.uf2` file to the latest build from the hackclub/spade repo on main. Fixes at least 1 bug where gray text wouldn't show up on black backgrounds.

In the future this might be better automated with an addition to the build workflow on the spade repo that automatically uploads the new UF2 to this repo.

### CODE REVIEW

**Comment by JosiasAurel** [comment]
relevant #1298

**Comment by grymmy** [comment]
Thanks @polypixeldev !

> Updates the `pico-os.uf2` file to the latest build from the hackclub/spade repo on main. Fixes at least 1 bug where gray text wouldn't show up on black backgrounds.
> 
> In the future this might be better automated with an addition to the build workflow on the spade repo that automatically uploads the new UF2 to this repo.

I actually disagree with ^^^ - I want us to internally ensure that we test each new uf2 on a real spade device before shipping new firmware, for now.

**Comment by polypixeldev** [comment]
Would it not work to have UF2 testing on a Sprig as part of the hackclub/spade PR review process?

**Comment by grymmy** [comment]
@Sheepy3 can u plz load this version of the firmware on a sprig and ensure 1/2 common/popular apps look like they're working?

**Review by Sheepy3 — APPROVED** [review]
Tested against the following games:
https://sprig.hackclub.com/gallery/Friendly_Figures
https://sprig.hackclub.com/gallery/infinite_cat
https://sprig.hackclub.com/gallery/crimbletips
https://sprig.hackclub.com/gallery/randomworld
https://sprig.hackclub.com/gallery/chuckman_go
and found no unexpected behavior/issues.

**Pull request merged**
