### PR TITLE
Find the Watermelon Submission

### PR DESCRIPTION
**Pull request by thedev132**
# Your checklist for this pull request

## Author name

**Author: Mohamad**

## About your game

**What is your game about?**

My game is about a character who is trying to get the watermelon across the maze. There are walls and bombs which are preventing him and the character has to work around it.

**How do you play your game?**

Press WASD to move, J to restart, Get the watermelon icon but having your character on it (you will go to another level).

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

no images 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! What about background?

**Comment by thedev132** [comment]
I added a blue background to it :D

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Try use setBackground() function:) avoid these blank spaces: 
image

**Comment by thedev132** [comment]
Fixed it :D

**Comment by LucasHT22** [comment]
Great! I'll just ask to change the name of your game because we already have game called Maze runner

**Comment by thedev132** [comment]
Done! Changed it to Find the Watermelon!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay:) Did you use any game as inspiration?

**Comment by thedev132** [comment]
No I just used the getting started demo as my starting point! It was very helpful

**Comment by LucasHT22** [comment]
I'm asking because there's a game named maze_runner that is already on gallery and is in Files changed

**Comment by thedev132** [comment]
Ohhhhh. Yea no I just got the name for the game because it's a maze and it's similar to like the movie maze runner.

**Comment by LucasHT22** [comment]
Are you wetf? If not, I think it's GitHub because there is a game on our repo called maze_runner

**Comment by thedev132** [comment]
Ohhhhhh I see. Shoot I think I overwrote his file.

**Comment by LucasHT22** [comment]
> Ohhhhhh I see. Shoot I think I overwrote his file. What should I do? Should I just recreate his file in my commit? So sorry!

No worries, I know you are not in bad faith. Close this PR, make a new fork, a new PR and I merge:) I promisse merging before today's midnight

**Comment by thedev132** [comment]
I recreated his file. So I think it's all solved right now

**Pull request closed without merging**
