### PR TITLE
Learn Morse

### PR DESCRIPTION
**Pull request by ktauchathuranga**
# Your checklist for this pull request

## Author name

Ashen Chathuranga

## About your game

this game is for learning morse code. actually i am gonna use this game for me too 😅
the goal is, match the letter for the shown morse code character. and it is randomized. levels are randomized so players have to really play the game.

"wasd" for moving the box and when you found the English letter, move the box to the top of the letter and then press "i" for confirmation.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Out of curiosity, where did you heard about Sprig?

**Comment by ktauchathuranga** [comment]
one of my friend told me, he submitted a game too 😋

**Comment by LucasHT22** [comment]
What his game? 👀

**Comment by ktauchathuranga** [comment]
its called spider home i think

**Review by LucasHT22 — APPROVED** [review]
Right!

Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
