### PR TITLE
lazer guy is out

### PR DESCRIPTION
**Pull request by haywardherlihy**
i did a few things and did stuf and i got this yay

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
I didn't understand your game very well, could you explain it to me?

**Comment by LucasHT22** [comment]
@haywardherlihy Need help?
Anything I'm here, you can call me :)

**Comment by leomcelroy** [comment]
I think this is a really interesting remix Hayward! Nice work. There seem to be some little bugs though which can confuse the game play. Is the objective to hit the target with the laser or to stand on top of it?

Maybe if you wrote out what the different game mechanics are we could help you iron out the code and refactor it to be more clear. The level design seems really good and I love how you made laser tag your own by changing the laser shooter into the player and by moving in increments of two.

**Comment by SamDev-7** [comment]
Interesting game, I love it! The concept is really cool and indeed an awesome remix. 
However, there seems to be errors popping up and one of the levels does not contain the player.

Polish it up, and I'd say it's ready to merge! Maybe also add a few more levels while you're at it. :D

**Comment by LucasHT22** [comment]
Hey @haywardherlihy ! 
Fix bugs, if you need help just call :)
After that we can reevaluate.

**Review by LucasHT22 — COMMENTED** [review]
nice changes :) wow, how many ternary operators! haha. now it's possible to complete the game, the jail function is nice, there are no errors (at least it didn't show any for me), but there are sprites that I don't know how to use, could you explain to me how to use rightLaser, downLaser, ball, horz?

**Pull request closed without merging**
