### PR TITLE
shitpest:3

### PR DESCRIPTION
**Pull request by snoglobe**
# Your checklist for this pull request

## About your game

What is your game about? 
> Shitpest is a shitty Tempest clone

How to play your game?
> A and D to move left and right, and I to shoot. J to use the super, which destroys all enemies on screen.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Comment by LucasHT22** [comment]
Great game! why did you choose that name?

**Comment by snoglobe** [comment]
thank you, and bc it’s a shitty tempest clone

**Comment by LucasHT22** [comment]
I can't find it, could you send a link or a photo?

**Comment by snoglobe** [comment]
Can't find the game? It's in the commit I believe

**Comment by LucasHT22** [comment]
I meant the reference game

**Comment by snoglobe** [comment]
https://en.m.wikipedia.org/wiki/Tempest_(video_game)

**Comment by LucasHT22** [comment]
oh, right

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
Happy holidays!
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
