### PR TITLE
BulletRun

### PR DESCRIPTION
**Pull request by GeoWizard4645**
Author: Vivaan Shahani (use this as nickname for author of game)

**What is your game about?**

My game is about thinking ahead and planning out a route to make it to the goal without getting hit by a bullet.

**How do you play your game?**
Press WASD to move run to the green portal to move on for the next level, avoid the bullets.

- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add one or two mechanics to this game to justify receiving a Sprig device grant.

**Comment by GeoWizard4645** [comment]
@grymmy > Looked at this game today. Still awaiting author to make changes.

Hi there, thanks for the feedback, I've been bust for the last two weeks but finally made changes. I've added a timer feature and the ability to try randomly generated levels once you finish the game, by pressing K once your done. 

Please let me know if this is enough and what I need to do from here

Sincerely,
Vivaan Shahani

**Comment by grymmy** [comment]
Entertaining and challenging game that actually made me stop and think for a second re: how I should proceed at certain points.  Good job!

If you're a teen, and haven't already received a Sprig device, please feel free to fill out [this form](https://sprig-order.hackclub.dev/) to receive one of your own!  Additionally, please join Hack Club's Slack and share your creation in the #sprig channel!

**Comment by GeoWizard4645** [comment]
@grymmy Hi there, Thank you so much. I filled out the form and it said I should receive a confirmation email. However it's been two days and I still haven't received anything, I was just wondering if you could guarantee my form when through or not. The name is Vivaan Shahani. The email id should be vivaan.shahani@gmail.com. Let me know if you need any more info here, though everything should be on the form.

**Pull request merged**
