### PR TITLE
Inverted Paradox

### PR DESCRIPTION
**Pull request by CallingBoar**
# Your checklist for this pull request

## CallingBoar

**Author:**

## Dodge these arrow things and shoot them too. WASD to move, K to shoot; if you are on the left side of the center line, you shoot right and if you are on the right side you shoot left! Survive as long as you can!

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## 
image

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

no, thank you! I qualify to get a sprig too :P

### CODE REVIEW

**Comment by savinajabbo** [comment]
I love the inverse shooting mechanism of your game; it's awesome! What about adding a point system for every arrow the player shoots down, and/or an ending screen notifying the user that they lost when they get hit?

**Comment by CallingBoar** [comment]
Oh, so I am allowed to update it? Ok, I was confused about that, Thank you! How exactly would I upload changes?On Apr 30, 2024, at 10:37 PM, Savina Jabbo ***@***.***> wrote:﻿
I love the inverse shooting mechanism of your game; it's awesome! What about adding a point system for every arrow the player shoots down, and/or an ending screen notifying the user that they lost when they get hit?

**Comment by LucasHT22** [comment]
> Oh, so I am allowed to update it? Ok, I was confused about that, Thank you! How exactly would I upload changes?On Apr 30, 2024, at 10:37 PM, Savina Jabbo ***@***.***> wrote:﻿ I love the inverse shooting mechanism of your game; it's awesome! What about adding a point system for every arrow the player shoots down, and/or an ending screen notifying the user that they lost when they get hit? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Sorry for the delay! You can go to `Files changed` > `...` > `edit` :)

**Comment by grymmy** [comment]
@CallingBoar - I think this game needs slightly more work.  It does not allow for further play after you die due to what appears to be a bug.  Can you please fix that so the game is more playable?

**Comment by grymmy** [comment]
I am closing this PR due to inactivity.  Please do feel free to reopen this PR if you desire landing your game and getting your Sprig reward!

**Pull request closed without merging**
