### PR TITLE
Falling Blocks

### PR DESCRIPTION
**Pull request by thanosan23**
Dodge the falling blocks for as long as you can. Use A and D to move.

I have experience coding in Python, but I do not have as much experience with JavaScript.

### CODE REVIEW

**Comment by SamDev-7** [comment]
Thanks for the PR, interesting game! One minor suggestion I have is that the block don't seem to actually touch the ground, they disappear before reaching the ground. Try tweaking your code, so they reach the ground and then disappear, let us know if you need any help!

**Comment by thanosan23** [comment]
I fixed the game so the obstacles reach the ground before disappearing.

**Comment by SamDev-7** [comment]
That works! There are still some minor issues I just noticed, if you quickly move after being hit by a block, the block stays there. Another very rare issue, if you move into a block just before it gets removed, it removes the player as well. I have an idea how those two could have occurred, let us know if you need any help. Happy hacking!

**Comment by thanosan23** [comment]
Is there a way to remove all tiles in the last row without removing the player?

**Comment by SamDev-7** [comment]
You should be able to check the type with
```javascript
if (sprite.type != "p")
```

**Comment by thanosan23** [comment]
Thank you! I have fixed the bugs.

**Comment by LucasHT22** [comment]
Great game!
I would merge this if I had the permissions :)

**Review by LucasHT22 — COMMENTED** [review]
Game over sound effect reminded me of Chrome Dino haha

**Comment by leomcelroy** [comment]
It's an elegant game. Welcome to the gallery! If you're a teen congrats on your Sprig. You can order it here: https://sprig-order.hackclub.dev/

**Pull request merged**
