### PR TITLE
Goblin Gobbler

### PR DESCRIPTION
**Pull request by TyMeowBlackBelt**
# Your checklist for this pull request

## Author name Tyler P Evans

**Author:**

TyMeowBlackBelt 

## About your game A Puzzle game about stuffing goblins into holes

**What is your game about?** stuffing goblins into holes

**How do you play your game?** wasd to move i to skip level j to reset level k to go back a level L to display a move score

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by TyMeowBlackBelt** [comment]
I heard about from a computer science teacher who mentioned it in passing.

**Review by TyMeowBlackBelt — COMMENTED** [review]
It is a finished product with poorly made ice puzzles

**Comment by TyMeowBlackBelt** [comment]
I am being told changes are requested and the upload is failing, this is my first time doing this, I am confused. what do I do?

**Comment by LucasHT22** [comment]
> I am being told changes are requested and the upload is failing, this is my first time doing this, I am confused. what do I do?

Ignore it:) There's nothing wrong

**Comment by LucasHT22** [comment]
Could you re-check this? :)
- [ ] The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by TyMeowBlackBelt** [comment]
Re-checked  the thing you told me to

**Comment by LucasHT22** [comment]
So could you make the changes to check again? :)

**Comment by TyMeowBlackBelt** [comment]
I am confused, is that what you wanted?

**Comment by LucasHT22** [comment]
> I am confused, is that what you wanted?

I can't see your changes, could you please try again?

**Comment by TyMeowBlackBelt** [comment]
I fixed problems I had while filling out the form for the pull request at the top of this pull request page.

**Comment by LucasHT22** [comment]
> I fixed problems I had while filling out the form for the pull request at the top of this pull request page.

Right:) Could you rename the file removing the space and using _ instaed?

**Comment by TyMeowBlackBelt** [comment]
Oh that makes sense sorry

**Comment by TyMeowBlackBelt** [comment]
does that work?

**Comment by LucasHT22** [comment]
> Oh that makes sense sorry

No worries:)

**Comment by LucasHT22** [comment]
What about add instructions to header?

**Comment by TyMeowBlackBelt** [comment]
This work?

**Comment by LucasHT22** [comment]
yes, but wdym by "ins. cont.;"?

**Comment by LucasHT22** [comment]
What are the functions of the arrows?

**Comment by TyMeowBlackBelt** [comment]
What are the arrows?

**Comment by TyMeowBlackBelt** [comment]
ijkl?

**Comment by LucasHT22** [comment]
Oh sorry! I meant signs:
image

**Comment by TyMeowBlackBelt** [comment]
Oh, That was a decorative piece i made for my ice themed area then moved it to the grassy area because I thought it might be fun to have just a little thing pointing out were the goblins in each level are, since they blend in very well with the background of my starting area.

**Comment by LucasHT22** [comment]
oh nice! how to solve this level? hard game haha
image

**Comment by TyMeowBlackBelt** [comment]
I have once before legitimately solved this level, but only once. I normaly skip it with the I button.

**Comment by LucasHT22** [comment]
> I have once before legitimately solved this level, but only once. I normaly skip it with the I button.

Sorry for the delay, I had some problems with eletricity. What about change a bit?

**Comment by TyMeowBlackBelt** [comment]
Of that level? Gladly

**Comment by LucasHT22** [comment]
Great! Is there a way to make a version without the obstacles that reset? It's very difficult to reach the end like this haha

**Comment by TyMeowBlackBelt** [comment]
obstacles that reset?

**Comment by LucasHT22** [comment]
> obstacles that reset?

I don't know how I lost your PR! Really sorry!! I meant the obstacles that when hit reset the game, but a gameplay would work too

**Comment by TyMeowBlackBelt** [comment]
There is no obstacles that do that...

**Comment by TyMeowBlackBelt** [comment]
j is the only thing that should reset it

**Comment by LucasHT22** [comment]
Hmmm weird, could you send a speed run/gameplay of your game?

**Comment by TyMeowBlackBelt** [comment]
sure I will get on that...

**Comment by TyMeowBlackBelt** [comment]
i have the video of the speedrun 11 minutes it wont send in github says the file is too large i would have to cut it into 12 or so peices.

**Comment by LucasHT22** [comment]
> i have the video of the speedrun 11 minutes it wont send in github says the file is too large i would have to cut it into 12 or so peices.

You can sent to me via email: lucas@hackclub.com :)

**Comment by TyMeowBlackBelt** [comment]
sent email

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
