### PR TITLE
Love_Lock

### PR DESCRIPTION
**Pull request by StuntStorm**
**_My Fourth New Game is now Released!_**

LOVE LOCK
------------

✔ It's a game about a lover who is handicapped but his loved one is locked away.
✔ Objective: Unlock your way to save your bae
✔ You need the key to unlock the teleport to your Lover

----------------------------------------------------------
Controls
------------

- Use w, a, s, d to move around.
- Press j to reset the level.
- Press k for Music.
- Press i for Credits.
- Press l for Controls.

----------------------------------------------------------

### The game is a modified version of tolls by leo

love_lock

### CODE REVIEW

**Comment by Omay238** [comment]
This is is a pretty good game, good art, good music. My only complaint would be that the reset button is pretty buggy. But again, overall it is a good game.

**Comment by StuntStorm** [comment]
> This is is a pretty good game, good art, good music. My only complaint would be that the reset button is pretty buggy. But again, overall it is a good game.

Thanks a lot for your feedback 💌
Wow! yes! I didn't notice that reset button issue..Fixed that now..Thank you again Omay! 🤗

**Comment by leomcelroy** [comment]
A major improvement over the original! Thanks for turning it into a real game.

**Comment by StuntStorm** [comment]
> A major improvement over the original! Thanks for turning it into a real game.

Thank youu ✨ 👍🏻 👍🏻

**Pull request merged**
