### PR TITLE
Street Racer game

### PR DESCRIPTION
**Pull request by Cdogo**
# Your checklist for this pull request

## About your game
A simple 90s street racer game where you race your car on a highway

What is your game about? 

How to play your game?

a and d to move
## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Comment by Arpan-206** [comment]
This game is looks very similar to [Cricket-Dodge](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/Cricket-Dodge.js).

You can still state the original author and modify the game moderately.
Feel free to ask for help in the #sprig channel.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
I disagree with Arpan, the code is very different, even though the proposal is similar. how about adding one more Player to keep the proposal different from others?

**Comment by Cdogo** [comment]
Will do!

**Comment by Cdogo** [comment]
added!

**Comment by Arpan-206** [comment]
Did you use some existing code, because I found some comments to be quite irrelevant? Also, only player one is set up as pushable, is there a particular reason for that?

**Comment by Cdogo** [comment]
Yes I did use the starter code.

**Review by LucasHT22 — APPROVED** [review]
Ok, good game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by rosea12345678910** [comment]
i hate you

**Pull request merged**
