### PR TITLE
pusher game

### PR DESCRIPTION
**Pull request by Lima014**
## About pusher game
A mind-game for those who have everything pretty much seen. A block game, move your character and move blocks so you can move to your goal.

## How to play your game?
Use W,A,S,D to move your character and push objects, use J to restart the level

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. (On the editor)
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for PR! 

- wdym with the tittle?
- How about adding more levels?
- Is the "you winl" with l at the end on purpose?

**Comment by yazidears** [comment]
I suggest changing the title to something that is more recognizable and easily understandable by players. The current title 'Black and White' is not very appealing, and a better alternative could be 'Pusher' for example, it's up to you btw :)))))

**Comment by yazidears** [comment]
LGTM!!! Maybe adding more maps would be better, as it extends the gameplay time

**Comment by yazidears** [comment]
Things to note:
There is no reset game button
Level 2 cannot be passed (maybe it's my sprig or something)

Good job btw :))

**Comment by Lima014** [comment]
I have changed the title of the game and made more levels, in addition to correcting the spelling mistake of "you win". Please let me know as soon as possible if there is anything else I need to correct.

**Comment by LucasHT22** [comment]
a restart function would be very good and maybe a level counter would be interesting

**Comment by LucasHT22** [comment]
I meant restart the level, sorry :)

**Comment by Lima014** [comment]
ok so i add the restart and more levels, i have to do something more?

**Comment by Lima014** [comment]
i add the funcion to restart the level with the j, somthing else that i have to do ?? :)

**Comment by yazidears** [comment]
LGTM :) great job! Maybe on a next update a score or sum would be awesome!

**Review by yazidears — APPROVED** [review]
Adding a score counter would be awesome! 
anyways, good job!
looks great :)

**Review by LucasHT22 — APPROVED** [review]
Perfect! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
