### PR TITLE
Mind Game

### PR DESCRIPTION
**Pull request by brunoblaise**
# Your checklist for this pull request

## Mudacumura Bruno Blaise

**Author:** @brunoblaise

## About your game

**What is your game about?**

Got Inspiration from @veritasium from one of his videos: What Game Theory Reveals About Life, The Universe, and Everything so basically it's a game known as Prisoner Dilmena but I chose the name "mind game"  because all you are doing is playing with the computer and learning its patterns and once you grasp the way it works you can play a mind game with it, you can trick and gain points  but be careful the computer sees your moves maybe it's playing with you one of it's mind game

That's all about the game; Mind game is tricking your opponent for you to gain points.

**How do you play your game?**

- Press 'j' to start the game
- Learn patterns the computer comes up with 
- Once you understand the patterns play a mind game with it
- Use the 'a' to cooperate with it and 'd' to deflect 
- Use the 'j' to start again and 'l' to restart the game
- Try beating the game and getting the highest score!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR!

**Comment by brunoblaise** [comment]
Welcome!

**Comment by savinajabbo** [comment]
Your game is so interesting! I love how creative it is

**Comment by brunoblaise** [comment]
hhh, Thanks! @savinajabbo

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
