### PR TITLE
Space War

### PR DESCRIPTION
**Pull request by EgoistD**
# Your checklist for this pull request

## Author name - Vineet Papnai

**Author:**

 Space War
## About your game

**What is your game about?**

Embark on an interstellar journey with our game. You command a spacecraft, navigating the cosmos, defending against enemies using your laser weapon. The game showcases unique bitmap graphics for the player’s spacecraft, the laser, enemies, and explosive crashes. The controls are intuitive, perfect for compact interfaces. With each defeated enemy, the challenge escalates, ensuring a dynamic gaming experience. Whether you’re a seasoned gamer seeking a new challenge or a casual player wanting some fun, our game offers an immersive experience. Get ready to defend your spacecraft against cosmic invaders!

**How do you play your game?**

Here’s a brief guide on how to play the Space War:

Navigation: Use the ‘A’ and ‘D’ buttons to move your spacecraft left and right respectively.
*Attack: Press the ‘I’ button to shoot lasers at the incoming enemies.
*Restart: If your spacecraft is hit, you can restart the game by pressing the ‘J’ button.
*Scoring: Points are earned for each enemy defeated. The game keeps track of your high score and displays it at the end of each game.
Remember, the goal is to defend your spacecraft and achieve the highest score possible. Good luck! 😊

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by EgoistD** [comment]
Hey,
I am author of Space War game,
I am in high school in India,
I built the game as I got to know about Sprig,
I have a query that, WILL I ALSO GET MY OWN SPRIG GAME CONSOLE as i meet
all the requirements.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by EgoistD** [comment]
> Thanks for your PR! Where did you hear about Sprig?

I heard about Sprig on hackclub last year, I thought it was hard to build a game but when one of my friend also got a sprig then I thought to give it a shot.

**Comment by EgoistD** [comment]
Hey, what is Plagairism-check and why it failed ?

**Comment by LucasHT22** [comment]
> Hey, what is Plagairism-check and why it failed ?

don't worry:)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Out of curiosity, did you use any game for inspiration?

**Comment by EgoistD** [comment]
> Out of curiosity, did you use any game for inspiration?

I just played my friend's game and bunch of tutorials to code

**Comment by LucasHT22** [comment]
I'm asking because there are somo similarities:
https://cloud-ohje45y66-hack-club-bot.vercel.app/020240105-1737-16.1476355.mp4
Please make your own game:)

**Comment by EgoistD** [comment]
> I'm asking because there are somo similarities: https://cloud-ohje45y66-hack-club-bot.vercel.app/020240105-1737-16.1476355.mp4 Please make your own game:)

actually he is my friend only 

> I'm asking because there are somo similarities: https://cloud-ohje45y66-hack-club-bot.vercel.app/020240105-1737-16.1476355.mp4 Please make your own game:)

Kindly wait 1 h and I will change it to a game that doesn't exist in Sprig gallery (Will you then accept ??)

**Comment by karamassie** [comment]
yes! as the rules state, your game must be mostly original. can you DM me in Slack please? @kara

**Comment by LucasHT22** [comment]
^ what Kara said:)

**Comment by Sheepy3** [comment]
Closing this PR due to inactivity. Please let me know if you'd like this reopened.

**Comment by EgoistD** [comment]
hey i made the game again but i cant create new pull request what should i do

**Pull request closed without merging**
