### PR TITLE
Desi Pong

### PR DESCRIPTION
**Pull request by arnob-das**
Hello,
I am Arnob Das, a teenage technology lover who has built a game by sprig game editor. The name of my game is "Desi Pong". It's a general pong game, but it has an extra feature. In this game, there are two players, and the two players can be controlled by different keys. There is one ball that always changes its position, and the players try to catch the ball. If one player is failed to catch the ball, the opposite player will get one score. In this game, "w" and "s" are for player-1, and "i" and "k" are for player-2 to change their position. That's all about my game.

While building this exciting game, I learned a lot of things. Before developing the game, I know the basics of JavaScript. But when I try to develop the game I face problems and difficulties. I search on google and many other forums to solve my coding problem. Finally, I got the solution. By doing these, I solved all the problems that arisen while building the game and enjoyed the whole moment very much.

### CODE REVIEW

**Comment by leomcelroy** [comment]
Thanks for the PR! It's nice to have a multiplayer version but I think this submission is still too similar to [this earlier game](https://github.com/hackclub/sprig/pull/313). Maybe try to add some twist to pong to make it more your own.

**Comment by arnob-das** [comment]
add pause, resume and reset game functionality. "l" for pause, "j" for resume and "d" for reset game.
now the game has high score limit and this is 10.
after reaching the score 10 by player 1 or player 2 the game will stop and display the player 1/ player 2 is win and game over text on the screen.
Thank You.

**Comment by arnob-das** [comment]
also updated the top score position.
please merge my pull request.
Thank You.

**Comment by leomcelroy** [comment]
Thanks for incorporating the feedback! I'll merge it in.

You can order your Sprig here: https://sprig-order.hackclub.dev/

**Comment by arnob-das** [comment]
Thank You.

**Pull request merged**
