### PR TITLE
adding maze game

### PR DESCRIPTION
**Pull request by DxrkzSerpent**
# Your checklist for this pull request

## Author name

**Author:** 

Eric

## About your game

**What is your game about?**

a simple maze game with a win screen at the end

**How do you play your game?**

WASD to move, reach the blue and purple box at the end of the maze to progress

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by DxrkzSerpent** [comment]
changed it

**Comment by grymmy** [comment]
Two things:

1. Your PR now deletes mazegame, which it shouldn't.  Please update the PR such that you do not delete one of the existing gallery entries.
2. To meet the bar and receive a Sprig device, I'd like you to add a little bit more logic (code) by adding a mechanic or two.  Right now the implementations is a bit too simple, we need a little bit more to give the award.

**Review by grymmy — CHANGES_REQUESTED** [review]
Please see my previous comment.

**Comment by grymmy** [comment]
Eeeeeek!  Now we have a PR with zero files changed - a new one, in my book.
Screenshot 2024-06-26 at 7 44 36 PM

Any chance we could get on a zoom and get this sorted out in a quick 15m or so?  More than willing to either find someone to help you directly, or help you myself w/ this problem.  U on HC slack?

**Comment by grymmy** [comment]
Looked at this today.  Still waiting changes from the author.

**Comment by grymmy** [comment]
Closing this as a result of inactivity.  If you feel that you want to reopen this and move forward towards landing this and acquiring a sprig device grant, please reopen the issue and ping me!

**Pull request closed without merging**
