### PR TITLE
add galloping game to repo :D

### PR DESCRIPTION
**Pull request by solunian**
# Your checklist for this pull request

## Author name

**Author:** Daniel Cui

## About your game

**What is your game about?**

A gallant horse is travelling at breakneck speeds! Only problem is that it might actually break its neck from crashing into trees... Avoid the trees for as long as you can until the time in the stage runs out!

**How do you play your game?**

Use WASD to move. When prompted to start or restart, use L.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! Out of curiosity, have you ever beaten the game?

**Comment by solunian** [comment]
Yes, I have beaten it. In the later levels, there are some instances that trees spawn and trap the horse, so you have to get an apple to clear the field or restart that section. 😁

**Comment by LucasHT22** [comment]
wow haha Do you have a screen recording? If not, no problem:)

**Comment by solunian** [comment]
Yeah, sorry I don’t… but you can tweak the level in the code to start at 5 instead of 0 and it’ll be easier.

**Review by LucasHT22 — APPROVED** [review]
Ok! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
