### PR TITLE
Escape_the_dungeon_demo

### PR DESCRIPTION
**Pull request by LuanderFarias**
## About the game

What is the game about? 
A game i made to have my first contact with spring. its just a single and simple puzzle, but for me it takes some time to get all the documentation and understand the logic so i really liked the experience :)

How to play your game?
Press WASD to move, Get the key and walk for the gate.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Comment by LucasHT22** [comment]
Good sprites! levels are not progressing for me

**Comment by LuanderFarias** [comment]
actually it's only one level... it's just a demo

**Comment by LucasHT22** [comment]
what about these other levels that are in the code?

**Comment by LuanderFarias** [comment]
i forgot to remove lol

**Comment by leomcelroy** [comment]
BTW I really like the art in this one.

**Comment by LuanderFarias** [comment]
tysm, i actually think i'm gonna abandon this project :( but maybe theres a new one with better art soon 👀

**Pull request closed without merging**
