### PR TITLE
the journey of the box[a sokoban saga]

### PR DESCRIPTION
**Pull request by TheLegendOfMario**
# Your checklist for this pull request

## Author name

**Author: Ethan Francis**

## About your game

**Pushing boxes to the goal, but on some levels, there is buttons that you have to hold down with boxes.**

**press WASD to move j to restart. get the boxes (blue) to the holes. the buttons make all walls disappear.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Your file is empty

**Comment by TheLegendOfMario** [comment]
ok. i'll fix that.

**Comment by TheLegendOfMario** [comment]
It should now appear as a file.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Just a detail: level 7 doesn't seem to be working

**Comment by TheLegendOfMario** [comment]
how is it not working?

**Comment by TheLegendOfMario** [comment]
I don't see a problem.

**Comment by LucasHT22** [comment]
so please send a screen recording showing how to solve level 7

**Comment by TheLegendOfMario** [comment]
Since I have a mediocre chromebook running lubuntu, without much disk
space, I took pictures and will send them to you in the following email. it
will be a link to a google doc with a walkthrough.

**Comment by TheLegendOfMario** [comment]
here is the link:
https://docs.google.com/document/d/1-si9w_EY0Vq_R8quhGTPckv6ouIDAkDTlagdv43H-Cc/edit?usp=sharing

**Review by LucasHT22 — APPROVED** [review]
oh sorry, i'm so dumb. Anyway, great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Out of curiosity, where did you hear about Sprig?

**Pull request merged**
