### PR TITLE
Pipes Puzzle

### PR DESCRIPTION
**Pull request by rayhanadev**
# Pipes Puzzle 🚿

Pipes Puzzle Thumbnail

This is the Pipes Puzzle :D. Not too original of a game I believe, yet I built a simple, highly un-optimized engine and ported it to Sprig and it plays really well! I'm quite proud of it as my first Sprig game :).

---

(Assuming by programming experience you mean my experience with Sprig?) I thought Sprig was rather interesting :). Its pretty "low-level" for a game development kit and I had to develop several tools in order to functionally create my sprites (five base pipe sprites, four rotations of each sprite, and active/inactive variants of all sprites resulting in 40 unique pipe sprites + one sprite for the cursor + three sprites for the end screen — totaling up to 44 sprites) and populate the legend with my sprites. It had a really nice learning curve and I was able to pick it up rather quickly because it is such a simple library!

I did face some compatibility errors when I used my engine with Sprig, for reasons I still don't know so I spent more time debugging than all else. The lack of stack traces and the need to use the console to (painstakingly) debug code wasn't too fun, but I was able to get there :).

I think the Sprig editor is nice, but still has some hurdles to jump :). Specifically it wasn't too user-friendly and the Sprig-specific extensions such as the pixel displays weren't too friendly with code such as:

```js
const baseSprite = '...'; // some proper sprite
const newSprite = bitmap`${rotate(baseSprite)}`;
```

The editor would parse raw the contents of the string in bitmap, starting at the `$` and it would throw errors instead of evaluating the string, which is understandable but maybe a future inclusion to the IDE!

One suggestion I have would be a way to use Sprig in other IDEs, such as a CDN url to the (unminified) script. That way I could use it in my favorite IDE, Replit, via the HTML, CSS, and JS template. For me personally that would improve my developer experience by leagues.

Besides this I enjoyed my experience with Sprig! The technical challenges and debugging were nice to keep me on my toes :), and I look forward to making more games and seeing the library grow! :D

### CODE REVIEW

**Comment by SamDev-7** [comment]
Thanks for the PR! Great game!!

I really love the art style! The game is challenging and interesting. 
I see that the maps are automatically generated, that is so cool!

Very well polished game!
If you're a teen congratulations on your Sprig. You can order it here: https://sprig-order.hackclub.dev/

**Comment by rayhanadev** [comment]
Sweet thanks :D.

**Review by LucasHT22 — COMMENTED** [review]
Great game! Congrats :)

**Comment by rayhanadev** [comment]
> Great game! Congrats :)

Thank you :D

**Comment by Omay238** [comment]
Nice, I was actually working on a similar game. Yours is better in every way though lol. Good job!

**Comment by rayhanadev** [comment]
> Nice, I was actually working on a similar game. Yours is better in every way though lol. Good job!

awwwh thank you, i'm sure yours would be just as good ❤️

**Pull request merged**
