### PR TITLE
Snake Game

### PR DESCRIPTION
**Pull request by JARVIS-124**
# Your checklist for this pull request

## Author name

**Dibya**

## About your game

**Snake Game **

**Press WASD to move the snake and enjoy the game**

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Please provide a clear "about" and a brief gameplay description ("How do you play your game?"), I only see an white screen when I run it

**Comment by JARVIS-124** [comment]
> Please provide a clear "about" and a brief gameplay description ("How do you play your game?"), I only see an white screen when I run it

done please check

**Comment by LucasHT22** [comment]
Where's the snake? I only see an white screen

**Comment by JARVIS-124** [comment]
> Where's the snake? I only see an white screen

There it's the black one you can't see?

**Comment by grymmy** [comment]
I also see only a white screen and no real functional gameplay for some reason.  Can you please paste this code from the PR into the sprig editor directly and try to reproduce it on your side?

**Comment by JARVIS-124** [comment]
> I also see only a white screen and no real functional gameplay for some reason. Can you please paste this code from the PR into the sprig editor directly and try to reproduce it on your side?

It's working from my side idk why not your

**Comment by JARVIS-124** [comment]
?

**Pull request closed without merging**
