### PR TITLE
add builder game

### PR DESCRIPTION
**Pull request by Omay238**

### CODE REVIEW

**Comment by LucasHT22** [comment]
I don't understand your game, could you explain it to me?

**Comment by Omay238** [comment]
WAD to move, IJKL to make boxes. Get a box into the goal.

**Comment by SamDev-7** [comment]
I love the ability to "modify" the level. Brings new challenges as you have to move both yourself and a box without trapping yourself. It might be beneficial to add some instructions? I was also confused before you explained the goal.

**Comment by Omay238** [comment]
This game is really buggy. I think I'm just going to close this one, and make a new PR later with an updated version

**Pull request closed without merging**
