### PR TITLE
Pizza Game

### PR DESCRIPTION
**Pull request by danieliscrazy**
## Author name

**Author:** Daniel Davidson

## About your game

**What is your game about?**

This is a pizza delivery game that the Hakkuun AI on the Arcade website gave me the idea for.

**How do you play your game?**
WASD to move, J to mute music
Collect the pizzas and deliver them to hungry people! Once you reach 76 pizzas delivered, it becomes infinitely generated.

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Review by alx-alexpark — DISMISSED** [review]
Hey there!

Great game, I liked playing it.

Just one more thing before I can merge your PR and send you your console, could you fix this error in your game?

https://github.com/hackclub/sprig/actions/runs/11655444869/job/32450159595?pr=2541

Lmk if you need any help, and you can always ask for help in #sprig on the slack.

**Comment by danieliscrazy** [comment]
Can I ask when/where this error showed up? I'm not seeing it anywhere in the game when I play through it normally.

**Comment by danieliscrazy** [comment]
Did a look through my code, the line it's showing to be the error is nowhere to be found in my code. I don't know what the issue is, but as far as I can tell it's not the result of my code.

**Comment by alx-alexpark** [comment]
Hold up, I'm checking with people who know this better than I do. But as of right now, there is nothing I can do, as this failing check blocks me from merging your PR.

**Review by alx-alexpark — APPROVED** [review]
Congrats on your game :) I had a fun time playing it!

If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
