### PR TITLE
Dodge The Rock

### PR DESCRIPTION
**Pull request by tomatoduck**
# Your checklist for this pull request

## About your game

What is your game about? 
You have to dodge the rocks coming your way. If you manage to dodge you get points. There are different difficulties that make the game more fun to play. Once you get hit by a rock the game ends. 

How to play your game?
You have to press "s" to go down and "w" to go up.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Just one question: did you use any inspiration games?

**Comment by tomatoduck** [comment]
> Great game! Just one question: did you use any inspiration games?

Well, I looked through a few of the other games in the gallery in https://sprig.hackclub.com/ to get an idea on how to use the editor but other than that not really.

**Review by LucasHT22 — APPROVED** [review]
Ok! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by LucasHT22** [comment]
> First of all, my face on the student ID isnt needed, right? If not, I would blur it. 

Yep! Just the informations we need

> Second of all, since Im new to github, under your given link it wants the link of the pull request. Is this pull request the one wanted? So the link of this specific site? 

This link: https://github.com/hackclub/sprig/pull/942

And lastly I want to know if I have to give my phone number (I live in Germany).

Carriers require, especially for those going through customs

**Comment by tomatoduck** [comment]
> > First of all, my face on the student ID isnt needed, right? If not, I would blur it.
> 
> Yep! Just the informations we need
> 
> > Second of all, since Im new to github, under your given link it wants the link of the pull request. Is this pull request the one wanted? So the link of this specific site?
> 
> This link: `https://github.com/hackclub/sprig/pull/942`
> 
> > And lastly I want to know if I have to give my phone number (I live in Germany).
> 
> Carriers require, especially for those going through customs

Thanks!

**Pull request merged**
