### PR TITLE
Sokoban_Hard!!!

### PR DESCRIPTION
**Pull request by P-Rama-Ganesh**
# Your checklist for this pull request

## About your game

What is your game about? 
> Example: Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))

How to play your game?
> Example  : Press WASD to move, J to restart and K to toggle trails, Get A boxes (cyan) to A goals (green), Get B boxes (magenta) to B goals (red), Get normal boxes (gray) to either goal. (from [Sokoban plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
sorry, but could you tell me how to solve the first and last level?

**Comment by P-Rama-Ganesh** [comment]
> 
lucas  text me on slack about game level

**Comment by LucasHT22** [comment]
what is your @?

**Comment by P-Rama-Ganesh** [comment]
this could be a challenging game

**Comment by SamDev-7** [comment]
The file here is conflicting with #693. 
It may be helpful to use branches and limit it to one game per branch to avoid confusion.

**Comment by P-Rama-Ganesh** [comment]
ramaganesh2024@gmail.com and palla.ramagaesh8@gmail.com

**Comment by agentblack6000** [comment]
is this PR ready to merge?

**Comment by grymmy** [comment]
@P-Rama-Ganesh I am closing this PR.  **You are free to reopen this PR yourself** (or reach out to me directly!) and continue advocating for this code landing, but it seems that it hasn't been acted upon for 3 months.

**Pull request closed without merging**
