### PR TITLE
Among_The_Stars

### PR DESCRIPTION
**Pull request by NikoHacker1337**
# Your checklist for this pull request

## Author name

**Author:**
VanGo

## About your game

**What is your game about?**
A game where the stars are more sinister than they seem. Look around at the shimmering lights. They hold secrets untold. You must fight as the lights blind you.

**How do you play your game?**
You move with WASD and use J to shoot a lazer in the direction you last traveled and press L to pause the game to open the shop and upgrade the lazer by pressing A.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

I usually program from scratch in c. I tried my best to emulate not being tile based. As I have never used js it was a little weird. This game is SUPER janky and unoptimized, though, it does run without errors (that I know of). I have no clue if the sprites will show up on the screen, but they should. I have been programing since 8.

### CODE REVIEW

**Comment by NikoHacker1337** [comment]
I forgot to write the title "Among_the_Stars" my bad

**Comment by LucasHT22** [comment]
no problem, you can change

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! But Score isn't working

**Comment by NikoHacker1337** [comment]
"Good game! But Score isn't working"
What did you mean by this

**Comment by NikoHacker1337** [comment]
The score is based on enemies shot, did you pres j to shoot them?

**Comment by LucasHT22** [comment]
oh right, sorry

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
