### PR TITLE
Racer

### PR DESCRIPTION
**Pull request by CoolCoderSJ**
A port of the classic game to sprig, where you switch lanes to avoid obstacles

Play it live: https://editor.sprig.hackclub.com/?id=32fb78b30f2eb269c39810e907b1178c

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR!

**Comment by LucasHT22** [comment]
it seems that it is possible to change the player's position before the timer starts, was it planned?

**Comment by CoolCoderSJ** [comment]
Yep, it's required for some of the levels when there's an obstacle right in front of you

**Comment by LucasHT22** [comment]
oh, ok!

**Comment by LucasHT22** [comment]
looks good to me, I'm learning a yarn test for sprig, but I don't know how to apply it yet, so I'll approve it and if errors appear in the yarn test I'll send you a DM in Slack, ok?

**Comment by LucasHT22** [comment]
Congrats!
you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by CoolCoderSJ** [comment]
Great, thank you!

**Pull request merged**
