### PR TITLE
Add collect 500 coins

### PR DESCRIPTION
**Pull request by oliverlinux**
Your checklist for this pull request
Author name
Author
oliverlinux

About your game
What is your game about?
Collecting coins, just to waste time and get highest score. But with a twist: You can fall after you jump and move.

How do you play your game?
Move with WASD, your score shows on top of screen.

Code
Check off the items that are true.

[x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
[x ] The game is placed in the in the [/games directory](https://github.com/hackclub/sprig/tree/main/games).
[x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
[ x] The game runs without errors.
[ x] The name of the file/game contains only alphanumeric characters, -s, or _s.
[ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
The game was mostly made in the sprig editor, I set the title author and tags with sublime text
Image (If an image is used)
No image

 The image is in the [/games/img directory](https://github.com/hackclub/sprig/tree/main/games/img).
 The name of the image matches the name of your file.
Thanks for your PR!

### CODE REVIEW

**Comment by grymmy** [comment]
Please make one more unique change to this game and I promise you will be rewarded with a Sprig.  I just need to see slightly more, something to make the game fun beyond monotony (I do appreciate the name of this game implies the wasting of time).

**Review by grymmy — CHANGES_REQUESTED** [review]
Please make one more meaningful addition to this game.

**Comment by oliverlinux** [comment]
> Please make one more meaningful addition to this game.

I added fake coins, which you lose when collecting, and I added a win screen

**Comment by grymmy** [comment]
Excellent work @oliverlinux, good perserverence!  If you haven't already gotten one, and if and only if you're a teenager, please fill in [this form](https://sprig-order.hackclub.dev/) to receive your very own Sprig device!  Also feel free to join us in Hack Club's Slack in the #sprig channel to show off your new game to others...

**Pull request merged**
