### PR TITLE
infinite-loop

### PR DESCRIPTION
**Pull request by mattsoh**
# Your checklist for this pull request

## Author name

**Author:** mattsoh

## About your game

**What is your game about?**

A Sprig Maze Game for arcade-jam (theme Loopholes) where you get through the two (yes, only two!) levels in the fastest time possible! 

**How do you play your game?**

Just use WASD for directional control, the other buttons are left for you to find out :) (Try not to look at the code).

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by mattsoh** [comment]
For the reviewer that really doesn't have patience, j is used to jump over special tiles (those labeled with slide/"s"), k is used to pick up coins (coins only show when you go over them). Some walls are fake (fake/"f" and coin/"c"). Coins decrease your total time. Slides are solids with the player.

**Comment by recursiveforte** [comment]
I love this game, but it's too short for me to accept (we have a minimum of five minutes of play time). The timer at the bottom was a helpful indicator of this, lol. I can approve it if you add a few more levels!

**Comment by mattsoh** [comment]
Hi,

It says "Your game [is required to have] a minimum of 1 min of gameplay"? Or is this outdated?

Anyway I will work on the project to make it ≥5 mins. 

Also does the player trying to find out what the hidden controls/items are count as runtime?

Thanks!

**Comment by mattsoh** [comment]
Also the coins reduce the time of the timer at the bottom :)

**Comment by mattsoh** [comment]
@recursiveforte

**Comment by recursiveforte** [comment]
Sorry, my bad! I'm approving this, and you should see it in the gallery this week.

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev).

**Comment by mattsoh** [comment]
Thanks for your help!

**Pull request merged**
