### PR TITLE
Add black_jack.js

### PR DESCRIPTION
**Pull request by xevaly**
# Your checklist for this pull request

## About your game

What is your game about? 
I made blackjack how its played in the casinos. You get a balance of 500 and can play the dealer and try to win as much as you can!

How to play your game?

Before the game starts, the player can adjust their bet size by pressing the "I" key to increase the bet size and the "K" key to decrease it.

When the player is ready to start the game, they can press the "J" key to begin.

The player and the dealer will be dealt one card.

The player can then choose to hit by pressing the "H" key, stand by pressing the "S" key, or double down by pressing the "D" key.

If the player chooses to hit, they will receive an additional card and their hand value will be recalculated. The player can continue to hit until they choose to stand, or until their hand exceeds a value of 21, at which point they lose the game (this is called "busting").

If the player chooses to stand, their turn is over and the dealer will start their turn.

The dealer's turn is automated according to the rules of the game (hit if their hand value is less than 17, stand if their hand value is 17 or higher).

If the dealer busts, the player wins the game. If the dealer does not bust, then the player's hand is compared to the dealer's hand, and whoever has the hand closest to a value of 21 without going over wins. If the player and dealer have the same hand value, the game is a tie, or "push."

To play another Round with the same bet size simply press "A" or get back to the main menu by pressing "L".

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
Great idea! 
Could you send a gameplay of your Sprig game? it's my first contact with this game, it would make the review faster

**Comment by xevaly** [comment]
How could I record it? Is there any native way built into the website?

**Comment by LucasHT22** [comment]
we don't have native, you can use any software that record the screen

**Comment by xevaly** [comment]
@LucasHT22

**Comment by LucasHT22** [comment]
??

**Comment by xevaly** [comment]
@LucasHT22 Github apparently didn't want to upload my video... The comment I tagged you in, should've had the video.

Here is a different platform you can view the video on. Hope this works.

**Comment by xevaly** [comment]
https://streamable.com/3jmif3

**Comment by LucasHT22** [comment]
Great!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
