### PR TITLE
TheMazeGame

### PR DESCRIPTION
**Pull request by NavritAngurana**
# Your checklist for this pull request

## Author name
Navrit Angurana
**Author:**

Potat
## About your game

**What is your game about?**
Navigate Mazes while being hunted by monsters, you have limited vison. your only tool is a flash that can stun them for a bit, can you beat all the levels? 

**How do you play your game?**
WASD to move, L to flash, get to the exit(white circle), avoid red(bad guys) 

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by NavritAngurana** [comment]
> Thanks for your PR! Where did you hear about Sprig?

I heard about it from the hack club at our school

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice:) Did you completed/won the game? it's hard haha

**Comment by NavritAngurana** [comment]
> Nice:) Did you completed/won the game? it's hard haha

Yea I just did it, this game is hard indeed (level 24 especially), way harder than I want it to be. If possible, could I just submit a new pr after tweaking the difficulty to not be nearly impossible game?

**Comment by LucasHT22** [comment]
> > Nice:) Did you completed/won the game? it's hard haha
> 
> Yea I just did it, this game is hard indeed (level 24 especially), way harder than I want it to be. If possible, could I just submit a new pr after tweaking the difficulty to not be nearly impossible game?

You can just update this PR:)

**Comment by NavritAngurana** [comment]
Hello I am back from my hiatus, I got distracted by my semester 1 finals :(,
I have the fixed up code ready BUT I sadly don't know how to edit the pull request to change PR, where do I input my changes?

**Comment by LucasHT22** [comment]
> Hello I am back from my hiatus, I got distracted by my semester 1 finals :(, I have the fixed up code ready BUT I sadly don't know how to edit the pull request to change PR, where do I input my changes?

Go to `Files changed` > `...` > `edit` :)

**Comment by NavritAngurana** [comment]
updates have been made

**Comment by LucasHT22** [comment]
Nice! Could you send a gameplay from level 21 to the end? it's hard haha

**Comment by NavritAngurana** [comment]
> Nice! Could you send a gameplay from level 21 to the end? it's hard haha

https://youtu.be/0GxJM375tO0?si=oiujvmGkJFrxOSfz

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
