### PR TITLE
Flamin_Fingers

### PR DESCRIPTION
**Pull request by RichieTran**
# Your checklist for this pull request

## About your game

What is your game about? 

Getting the pointer (what you control) to the white circles on each level.

How to play your game?

Press WASD to move.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! but the levels don't seem to be evolving (going from 1 to 2, 2 to 3...) and did you use any other game for inspiration?

**Comment by RichieTran** [comment]
Hello, I'm emailing incase the Github comment does not work. Should I
change the second and third levels, I have some ideas that would be easy to
add. Also I used the timer "Flurffy" by Lucas and edited it so it would
change depending on the level, but everything else I did myself. Should I
add that I used the timer from Flurffy? Thank you!

**Comment by LucasHT22** [comment]
> Hello, Should I change the second and third levels, I have some ideas that would be easy to add. 

Ok!
> Also I used the timer "Flurffy" by Lucas and edited it so it would change depending on the level, but everything else I did myself. Should I add that I used the timer from Flurffy? Thank you!

Yeah, it would be nice:) I asked because I'm the creator of Fluffy haha

**Comment by RichieTran** [comment]
> > Hello, Should I change the second and third levels, I have some ideas that would be easy to add.
> 
> Ok!
> 
> > Also I used the timer "Flurffy" by Lucas and edited it so it would change depending on the level, but everything else I did myself. Should I add that I used the timer from Flurffy? Thank you!
> 
> Yeah, it would be nice:) I asked because I'm the creator of Fluffy haha

Okay I changed it, do I have to close the pull request then change it then do another pull request? Thank you again!

**Comment by LucasHT22** [comment]
you can change it in your fork which will automatically appear here, or go to 
`Files changed` > `...` > `edit`

**Comment by RichieTran** [comment]
> you can change it in your fork which will automatically appear here, or go to `Files changed` > `...` > `edit`

Okay I updated it, let me know if I need to change anything else :).

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Our broader community would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by RichieTran** [comment]
> Great! Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> 
> Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Hello, on the sprig website when I click on the game it says "404: Not Found" and won't let me play, is it because I changed the file before? Is there any way to fix it, thank you!

**Comment by LucasHT22** [comment]
fixed! thanks for letting me know and sorry:)

**Comment by RichieTran** [comment]
> fixed! thanks for letting me know and sorry:)

Okay, thank you! :)

**Comment by RichieTran** [comment]
> fixed! thanks for letting me know and sorry:)

If I ever wanted to add an update or something, would I just submit another pull request?

**Comment by LucasHT22** [comment]
Yep!

**Pull request merged**
