### PR TITLE
flappy birdy

### PR DESCRIPTION
**Pull request by lolxdop**
# Your checklist for this pull request

## Author name

**lolxdop**

## About your game

**The player has to dodge the pipes by controlling the bird.**

**Use W to move upwards & use S to move downwards.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by lolxdop** [comment]
I have authorized to Vercel and approved the deployment still it is showing to authorize and deploy.Also am I going to get the Sprig console?

**Comment by LucasHT22** [comment]
> I have authorized to Vercel and approved the deployment still it is showing to authorize and deploy.

Just ignore it:)
> Also am I going to get the Sprig console?

Depends more on you than me:)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Out of curiosity, did you use any game for inspiration?

**Comment by lolxdop** [comment]
yes
it is flappy bird.

**Comment by lolxdop** [comment]
also i used a little bit of code from gallery coz i was not able to get custom background so i just got that code

**Comment by lolxdop** [comment]
srry for late reply i was sleeping

**Comment by lolxdop** [comment]
i was offline.

**Comment by lolxdop** [comment]
also this is my sisters laptop so she gives me for sometime srry.

**Comment by lolxdop** [comment]
ohh ur from brazil.I am from india.

**Comment by LucasHT22** [comment]
> also this is my sisters laptop so she gives me for sometime srry.

No worries, take your time:)

**Comment by LucasHT22** [comment]
> ohh ur from brazil.I am from india.

Nice!

**Comment by LucasHT22** [comment]
> also i used a little bit of code from gallery coz i was not able to get custom background so i just got that code

Which game?

**Comment by lolxdop** [comment]
The one named flappy bird but no gravity and worse.btw how will i know if i am going to get the sprig?

**Comment by lolxdop** [comment]
I want the console because i want to code my own pokemon game so i made a simple and easy game fast so ill get a console.and then make my pokemon game.

**Comment by LucasHT22** [comment]
> The one named flappy bird but no gravity and worse.

It's too similar... Please make an original game:)
> btw how will i know if i am going to get the sprig?

you'll get when this PR be merged

**Comment by lolxdop** [comment]
what is PR merge?

**Comment by LucasHT22** [comment]
> what is PR merge?

When this Pull Request is approved

**Comment by lolxdop** [comment]
how will its get approved?
also how will i get to know if its is approveed?
also how much time it will take?

**Comment by LucasHT22** [comment]
> how will its get approved? also how will i get to know if its is approveed? 

Will appear here a check mark
> also how much time it will take?

depends more on you

**Comment by Sheepy3** [comment]
Closing this PR due to inactivity. If you want it reopened, ping me here.

**Pull request closed without merging**
