### PR TITLE
Added ElfSokoban

### PR DESCRIPTION
**Pull request by markonije**
# Elf Sokoban
## About Elf Sokoban

ElfSokoban is a Christmas-themed Sokoban game where you, an elf, help Santa get presents to the right places for them to get picked up by Santa.
You play by using WASD to move around and push presents. If you get stuck on a level, press J to restart it. There are 17 levels to complete which get progressively harder as you progress. 
I had fun coding this game with my clubmates.

## Code
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! We're glad you enjoyed it :) What does the message at the end mean?

**Comment by markonije** [comment]
It means "You won" in Serbian! I put it that way so that the club members whose English is not the best could play it.

**Comment by LucasHT22** [comment]
Oh, cool! I understand, for a long time my games the message was "Você venceu!" which is "You won!" in Portuguese

**Review by LucasHT22 — APPROVED** [review]
Great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Review by LucasHT22 — COMMENTED** [review]
Sorry, I'm not good at puzzles, how to solve levels 3,4,5?

**Pull request merged**
