### PR TITLE
feat: updated game logic and added game info

### PR DESCRIPTION
**Pull request by kcoderhtml**
This is an update of the code I originally submitted. Once I got my sprig, I realized that the code wasn't properly optimized and made a bunch of tweaks.

Original PR: #1203

### CODE REVIEW

**Review by LucasHT22 — APPROVED** [review]
LGTM!

**Comment by LucasHT22** [comment]
Please update your branch, looks like I can't: 
image

**Comment by kcoderhtml** [comment]
I can't either. I wonder if there is a problem on GitHub's side.

**Comment by kcoderhtml** [comment]
Had to update from the fork.

**Comment by kcoderhtml** [comment]
Thank you!

**Pull request merged**
