### PR TITLE
The IMPOSSIBLE Puzzle

### PR DESCRIPTION
**Pull request by 0monish0**
The impossible puzzle

What is your game about? 
> Example: Pushing the pieces to the right place this is impossible bcz its really hard to do so

How to play your game?
> Example  : Press WASD to move and change the pieces you will get familiar with the controls as you play move the pieces the get the image as stated in the code

i tried to play the game and got it only once  correct so its named as the impossible game. this was a wonderful experience to code such an game  it was my first game i would continue to develop more games and have some very excellent plans in my mind 

The impossible puzzle

What is your game about? 
> Example: Pushing the pieces to the right place this is impossible bcz its really hard to do so

How to play your game?
> Example  : Press WASD to move and change the pieces you will get familiar with the controls as you play move the pieces the get the image as stated in the code

i tried to play the game and got it only once  correct so its named as the impossible game. this was a wonderful experience to code such an game  it was my first game i would continue to develop more games and have some very excellent plans in my mind 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
what's the picture of this puzzle?

**Comment by LucasHT22** [comment]
please complete the checks:

## Code
Check off the items that are true.
- [ ] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

**Comment by 0monish0** [comment]
> what's the picture of this puzzle?

in the code see the very first  the very first bitmap  with a comment telling  "the image will look like this" that is the pitcure

**Comment by LucasHT22** [comment]
> > what's the picture of this puzzle?
> 
> in the code see the very first  the very first bitmap  with a comment telling  "the image will look like this" that is the pitcure

Oh, my bad, sorry

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

out of curiosity, how did you meet sprig?

**Comment by 0monish0** [comment]
> Looks good to me! Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> 
> out of curiosity, how did you meet sprig?

first of all i wanna thank you so much i cannot wait to get my sprig and make more games i hope we connect to each other in future. 
i heard about sprig from hack club.
>Thanks ;)

**Comment by LucasHT22** [comment]
I thank you! I hope to see you more often here too:)

**Pull request merged**
