### PR TITLE
Amongus Flight

### PR DESCRIPTION
**Pull request by YashasSingh**
# Your checklist for this pull request

## About your game
This game is about maneuvering your among-us character in through the blockers set by the imposter. As the game progresses it gets harder, I took inspiration from subway surfer.

How to play your game?
Press the buttons "a" and "d" to move left or right to avoid hitting the blockers set by the imposter.
## Code
Check off the items that are true.
- [ x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by YashasSingh** [comment]
I mistakenly added two of the same file

**Review by LucasHT22 — APPROVED** [review]
Great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by YashasSingh** [comment]
@ LucasHT22 I wanted to know if I did everything correctly for signing up for the sprig is there any way to know?

**Comment by LucasHT22** [comment]
Holly contacted you :)

**Comment by YashasSingh** [comment]
What did she contact me with?

**Comment by LucasHT22** [comment]
> What did she contact me with?

Email!

**Pull request merged**
