### PR TITLE
Spraze

### PR DESCRIPTION
**Pull request by Peiprjs**
Made a maze game for Sprig. The third level was the hardest.

### CODE REVIEW

**Comment by Peiprjs** [comment]
The first club meeting we have we'll try to start coding a Sprig version of the Pico-8 version of Celeste

**Comment by Peiprjs** [comment]
It's still in slight WIP, I want to add some more levels and untouchable blocks.

**Comment by Peiprjs** [comment]
BTW something is broken because of some n.replace function that looks like it's a device uploading thing? I have spent about half an hour debugging but can't seem to fix it.

**Comment by Peiprjs** [comment]
I've added some sound effects as well.

**Comment by Peiprjs** [comment]
By the way, where does the name Sprig come from? The little pink frog?

**Comment by leomcelroy** [comment]
Nice work! Sprig is just a fun name we came up with. It invokes the green circuit board and this idea of new growth (in its cheesiest interpretation). This game is really complete with art and sounds. As you note some levels are definitely more engaging than others. The PR starts on level 10 so I'll change that to 0 and then merge it in!

**Comment by Peiprjs** [comment]
> Nice work! Sprig is just a fun name we came up with. It invokes the green circuit board and this idea of new growth (in its cheesiest interpretation). This game is really complete with art and sounds. As you note some levels are definitely more engaging than others. The PR starts on level 10 so I'll change that to 0 and then merge it in!

Yeah I forgot I had modified it to start at 10 because I tried to fix some bugs... guess I should've checked that one value lol

**Comment by Peiprjs** [comment]
How can I get the physical console, by the way?

**Comment by leomcelroy** [comment]
Good question! Here is the form to get on the Sprig waitlist. You're of the first to complete a game so we're still ironing out bugs.

https://airtable.com/appN9cSnDgORAM2bp/tblYLyzi8RySfkONg/viwMrglQ6x9pBSE0O?blocks=hide

**Pull request merged**
