### PR TITLE
bbbbbb

### PR DESCRIPTION
**Pull request by Hoggie5**
# Your checklist for this pull request

## About your game

What is your game about? 
bbbbbb is a simple platformer with a bit of a twist. Loosely based off of vvvvvv byTerry Cavanagh

How to play your game?
You use A & D for left and right movement. I & K and used to "change gravity."

## Code
Check off the items that are true.
- [ *] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ *] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [* ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ *] The game runs without errors. 
- [* ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [* ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [* ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [* ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
vvvvvv?

**Comment by Hoggie5** [comment]
> vvvvvv?

It's another platformer not made through sprig. I took some of the basic mechanics and turned it into something similar but distinctly different

**Comment by LucasHT22** [comment]
oh, ok!

**Review by LucasHT22 — APPROVED** [review]
Very good game! Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by Hoggie5** [comment]
Awesome! I had a blast working on it!

**Pull request merged**
