### PR TITLE
Rythym

### PR DESCRIPTION
**Pull request by Techno3d**
# Your checklist for this pull request

## Author name

**Author: Shadman**

## About your game

**What is your game about?**

Rythym is a 'rhythm' game where you try to not miss any arrows that are going down the screen.

**How do you play your game?**

Use the WASD keys to activate the corresponding pads (w for the 1st, a for the 2nd, s for the 3rd, and d for the 4th) before the arrow is on the pad (so right on top). Press I to start, stop, and reset the game. 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by Techno3d** [comment]
> Thanks for your PR! Where did you hear about Sprig?

I heard about it through my hack club at bronx science!

**Comment by Techno3d** [comment]
Is there anything else I have to do? I have never pull requested to a public repo before.
Or do I just have to wait a bit?

**Review by LucasHT22 — APPROVED** [review]
We're in holidays, that's why we're answering slow:) Merry Christmas! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by Techno3d** [comment]
> n holidays, that's why we're answering slow:) Merry Christmas! Congrats:)

Oh I just realized, there has been almost no Christmas cheer for me today I forgot it happened lol.
Thanks so much

**Pull request merged**
