### PR TITLE
Add tic tac toe

### PR DESCRIPTION
**Pull request by reesericci**
I created tic tac toe for sprig!

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
Cool game!

**Comment by leomcelroy** [comment]
Thanks for the PR Reese! I actually had a lot of fun figuring out how to position things, you could probably make a game with that mechanic somehow. Practically for the tic-tac-toe game it was a bit confusing. Maybe you could add a virtual cursor like in [matcher](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/matcher.js).

**Comment by reesericci** [comment]
I think it's part of the fun figuring out how to use it: it adds a twist to the standard tic-tac-toe.

**Comment by leomcelroy** [comment]
Fair enough haha. I guess plain tic tac toe can get a bit boring, maybe it is more fun this way. I'll plan to merge on Tuesday, when I'm back in the "office".

**Comment by leomcelroy** [comment]
Seems to play well. Congrats!

You can fill out this form to order a Sprig: http://sprig-order.hackclub.dev/

**Pull request merged**
