### PR TITLE
Dragon Fest

### PR DESCRIPTION
**Pull request by peyeyey**
# Your checklist for this pull request

## About your game

What is your game about? 
Survive for one minute by shooting down orbs with fireballs.

How to play your game?
WS to move, J to shoot, L to start, and K to reset. Make sure orbs don't reach the hedge. 

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

## Experience
This is my first time coding, my dad helped me with it, I groaned a bunch, and learned 2 things that are hard: remembering names, making functions, and off by one errors.

### CODE REVIEW

**Review by LucasHT22 — APPROVED** [review]
I had a lot of fun with your game! Looks good to me. Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by peyeyey** [comment]
I really want a sprig but I am only in 4th grade :( can I still get one please? or do I have to wait?

**Comment by LucasHT22** [comment]
4th grade??? 10 years??? I'm 13, WOW, so young haha, we say teen but it's teen or younger:)

join our Slack channel (hackclub.com/slack/), you will see other creators of all ages (#sprig)!

**Comment by peyeyey** [comment]
Haha I am 9!

**Comment by LucasHT22** [comment]
WOW congrats!

**Comment by peyeyey** [comment]
But in about 5 months 10:)

**Pull request merged**
