### PR TITLE
Update rescue_leo.js 

### PR DESCRIPTION
**Pull request by agentblack6000**
Add a main menu screen, clean up code, and add a new level for Rescue Leo

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
image
Good update! how to solve this level?

**Comment by agentblack6000** [comment]
Good catch, I forgot to copy paste the latest version from the sprig editor! That level is unsolvable, I pushed a patch to fix that

**Review by LucasHT22 — APPROVED** [review]
LGTM!

**Comment by LucasHT22** [comment]
Wait wait do you know what could be causing this? https://cloud-exdha5afe-hack-club-bot.vercel.app/0screenshot_20230304-234052.png

**Comment by agentblack6000** [comment]
Umm I'm not sure, for the main menu I basically added another level that works using `onInput("j", () => {...}`, and some more logic in the `afterInput()`

**Review by ni5arga — APPROVED** [review]

**Comment by agentblack6000** [comment]
so we can't merge the update until that test is successful?

**Comment by ni5arga** [comment]
i think we can

**Comment by LucasHT22** [comment]
@agentblack6000, i can help, just add `if(!getFirst(player)) return;`  in the player movments https://github.com/hackclub/sprig/commit/ba7e8b67ee47a12312c49ac6a5dee8573b61eeb3

**Comment by LucasHT22** [comment]
we cannot merge before that, to ensure your game will run on the console

**Comment by agentblack6000** [comment]
> @agentblack6000, i can help, just add `if(!getFirst(player)) return;` in the player movments [ba7e8b6](https://github.com/hackclub/sprig/commit/ba7e8b67ee47a12312c49ac6a5dee8573b61eeb3)

done, but that doesn't seem to fix the error :(

**Comment by agentblack6000** [comment]
> @agentblack6000, i can help, just add `if(!getFirst(player)) return;` in the player movments [ba7e8b6](https://github.com/hackclub/sprig/commit/ba7e8b67ee47a12312c49ac6a5dee8573b61eeb3)

Thanks, that fixed the error!

**Comment by agentblack6000** [comment]
ready to merge?

**Review by LucasHT22 — APPROVED** [review]
LGTM!

**Pull request merged**
