### PR TITLE
Galacticats

### PR DESCRIPTION
**Pull request by apzzd**
# Your checklist for this pull request

## About your game

In my game you have to keep from landing on the same squares as enemies that move based on how you move. You control a space cat who needs to get back to his spaceship.

Use W, A, S, and D to move.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

### CODE REVIEW

**Comment by LucasHT22** [comment]
great game! how to solve level 12?

**Comment by apzzd** [comment]
up, right, up, right, up, right, up, left, up, left, up

**Comment by LucasHT22** [comment]
this error is appearing for me: `Uncaught Error: Level must be rect. on line 1430 in column 51. Open the browser console for more information.`

**Comment by apzzd** [comment]
Hmm that's odd. What did you do to get that error?

**Comment by LucasHT22** [comment]
when you go to starship it appears

**Comment by apzzd** [comment]
ok, I'll check it out...

**Comment by apzzd** [comment]
Did that fix it?

**Comment by LucasHT22** [comment]
fixed!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

out of curiosity, how did you meet sprig?

**Comment by apzzd** [comment]
My dad told me about this challenge so I did it. :)

**Comment by apzzd** [comment]
The "Request a Sprig" form asks for a school photo ID. I'm homeschooled and don't have one, so what should I do?

**Comment by LucasHT22** [comment]
Oh, nice!

**Comment by LucasHT22** [comment]
> My dad told me about this challenge so I did it. :)

Oh, nice!

**Comment by LucasHT22** [comment]
> The "Request a Sprig" form asks for a school photo ID. I'm homeschooled and don't have one, so could I upload a passport photo and my homeschool registration form instead?

yeah, just prove your age and student status :)

**Comment by apzzd** [comment]
Ok, thanks :D

**Pull request merged**
