### PR TITLE
Fill the map

### PR DESCRIPTION
**Pull request by ansh3108**
##About Fill the Map

**The game is about to fill the map without overlaping or going back

**How to play

<!--- Press WASD to move, Press J to reset the level, fill the map with the green color without going back or overlaping the filled boxes --!>

##Code

- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game runs without errors.

### CODE REVIEW

**Comment by Arpan-206** [comment]
Which one is your game?

**Comment by ansh3108** [comment]
fill the map

**Comment by Arpan-206** [comment]
Screenshot 2023-03-11 at 6 57 50 PM

Can't go to these corner white edges

**Comment by ansh3108** [comment]
This is the glitch for the new homepage, It is working for many games from
gallery

**Comment by Arpan-206** [comment]
I suggest you report this to @kognise or raise an Issue.

**Comment by ansh3108** [comment]
Ok, will do that.

**Comment by ansh3108** [comment]
Btw are you a sprig reviewer?

**Comment by Arpan-206** [comment]
Not exactly, I just like to help out so that you can fix issues before an official reviewer comes along and not waste much time and not have to wait for a re-review.

**Comment by LucasHT22** [comment]
Hey @ansh3108 and @Arpan-206 ! 
this problem of multiple commits is being solved by HQ! Sorry for the inconvenience, but I think it's better to wait for this problem to be solved :) Keep an eye on #sprig-plataform in Slack for updates!

**Comment by ansh3108** [comment]
So can i get my pr approved or w8 for the problem to get fixed?

**Comment by LucasHT22** [comment]
I think it will be fast, approximately 72 hours maybe

**Comment by ansh3108** [comment]
Ok, thanks for the update.

**Comment by LucasHT22** [comment]
Hey @ansh3108 !  Please fill in this "form":

# Your checklist for this pull request

## About your game

**What is your game about?**



**How do you play your game?**



## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

**Comment by ansh3108** [comment]
Hey @LucasHT22 , How do fill this form?

**Comment by ansh3108** [comment]
> Hey @ansh3108 ! Please fill in this "form":
> 
> # Your checklist for this pull request
> ## About your game
> **What is your game about?**
> 
> **How do you play your game?**
> 
> ## Code
> Check off the items that are true.
> 
> * [x]  The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
> * []  The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
> * [x]  The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
> * [x]  The game runs without errors.
> * [ ]  The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
> * [x]  The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
> 
> ## Image (If an image is used)
> * [ ]  The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
> * [ ]  The name of the image matches the name of your file.
> 
> > Thanks for your PR!

**Comment by ansh3108** [comment]
> Hey @ansh3108 ! Please fill in this "form":
> 
> # Your checklist for this pull request
> ## About your game
> **What is your game about?**
> This game is about to like the player has to fill the whole map with only a single color without moving back or overlapping the filled tiles
> **How do you play your game?**
> use WASD controlls for movement and press J to reset the map.
> ## Code
> Check off the items that are true.
> 
> * [x]  The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
> * []  The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
> * [x]  The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
> * [x]  The game runs without errors.
> * [ ]  The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
> * [x]  The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
> 
> ## Image (If an image is used)
> * [ ]  The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
> * [ ]  The name of the image matches the name of your file.
> 
> > Thanks for your PR!

**Comment by LucasHT22** [comment]
Great! Hey! Close this PR and open a new one so I can merge:)

**Pull request closed without merging**
