### PR TITLE
Quantum Escape

### PR DESCRIPTION
**Pull request by realharshita**
# Your checklist for this pull request

## Author name

**Harshita**

## About your game

**What is your game about?**

The game "Quantum Escape" is about a scientist who gets trapped in a quantum computer simulation. Players must navigate through puzzle-solving and platforming elements in a visually abstract and ever-changing digital environment. The game combines challenging gameplay with strategic thinking to escape from the simulation.

**How do you play your game?**

In "Quantum Escape," players control a scientist navigating through a quantum computer simulation. The game involves using the WASD keys for directional control. The objective is to solve puzzles, avoid obstacles like black holes, and manipulate entangled boxes to progress through different levels. Players must strategize their movements to ensure both the player character and the entangled boxes navigate safely to the exit without colliding with hazards. The game challenges players to think critically and overcome obstacles to escape the digital environment.

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Hrm - I played this 3x and got into buggy scenarios that I couldn't escape from.  Can you add a little bit of safeguards for the player to avoid situations where you can't progress?

**Comment by realharshita** [comment]
Will work on it. thanks for letting me know.

**Comment by grymmy** [comment]
Looked at this today.  Still waiting on more changes from the author.

**Comment by GalaxyGamingBoy** [comment]
Hey! I’ll be closing the PR because of inactivity. Feel free to reopen the PR and ping me if you still want to move forward into acquiring a sprig device grant and publishing your game.

**Pull request closed without merging**
