### PR TITLE
feature: Add lint-sprig script and missing games.

### PR DESCRIPTION
**Pull request by shanecelis**
Re-adding games and lint-sprig script.

### CODE REVIEW

**Comment by grymmy** [comment]
@shanecelis I will review this today and also ensure your vercel privs get figured out.

**Comment by sampoder** [comment]
@grymmy can you fill me in, what are the Vercel issues?

**Comment by grymmy** [comment]
> @grymmy can you fill me in, what are the Vercel issues?

Heck you might have a better idea than I, but I figured the warnings above
Screenshot 2023-03-15 at 10 12 46 AM

could be resolved and vercel could auto-deploy if Shane had proper perms...?  To be honest, I'd like to really dig into how we stage deployments (see #970)

**Comment by sampoder** [comment]
@shanecelis can you DM your email? I'll add you to our Vercel account. Assuming that's linked to your GitHub account, that'll give you the correct perms.

**Comment by grymmy** [comment]
> @shanecelis can you DM your email? I'll add you to our Vercel account. Assuming that's linked to your GitHub account, that'll give you the correct perms.

Thanks for following up on this @sampoder.

**Review by grymmy — APPROVED** [review]
LGTM

**Comment by shanecelis** [comment]
DM’d you, @sampoder.

**Pull request merged**
