### PR TITLE
Adding Hungry Ninja Game

### PR DESCRIPTION
**Pull request by PrajvalRaval**
# Your checklist for this pull request

## Author name

**Prajval Raval**

## About your game

**What is your game about?**

🍎🥷 Get ready for the most explosive culinary adventure in "Hungry Ninja!" Join our stealthy, yet seriously snack-hungry ninja as they embark on a perilous quest to satisfy their insatiable apple cravings. Armed with nimble moves and a bottomless stomach, our ninja must navigate through orchards loaded with juicy apples and, of course, the occasional explosive surprise!

Dodge deadly bombs, unleash lightning-fast moves, and master the art of fruit-fueled acrobatics to become the ultimate apple-nabbing ninja. It's a race against time and danger as you strive to collect as many apples as possible while avoiding those bomb-erific booby traps.

🏆 Can you outsmart the orchard's explosive guardians and prove that you're the top ninja gastronome? Strap on your ninja gear, sharpen your appetite, and get ready for a deliciously dangerous journey in "Hungry Ninja!" It's a feast for the senses, but watch out for those bombshells – they're not part of the recipe! 🍏💣

**How do you play your game?**

Press WASD to move, J to restart.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

Screenshot 2023-12-17 at 12 10 45 AM

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! Loved your answer to what's your game about, what about adding this to header of the code?

**Comment by PrajvalRaval** [comment]
> Nice! Loved your answer to what's your game about, what about adding this to header of the code?

done!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right! Just re-check this:
- [ ]  The name of the file/game contains only alphanumeric characters, -s, or _s.

**Review by LucasHT22 — APPROVED** [review]
I'll merge when I have better internet but Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by LucasHT22** [comment]
You can also get a case for your Sprig here: https://airtable.com/appN9cSnDgORAM2bp/shrUfm6TWoA1VFKik !

**Pull request merged**
