### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by UtkarshDwivedi4**

### CODE REVIEW

**Comment by UtkarshDwivedi4** [comment]
Hello, I am high schooler i made this javascript game with mentorship . I loved it .

**Comment by UtkarshDwivedi4** [comment]
/*
@title: spaceship_lander
@author: UD UTKARSH
*/

**Comment by LucasHT22** [comment]
Was this game developed in the [Sprig editor](https://editor.sprig.hackclub.com/)?

**Comment by LucasHT22** [comment]
> Was this game developed in the [Sprig editor](https://editor.sprig.hackclub.com/)?

Apparently not,
If not, you can't ask for a Sprig console, see:
```
There are only a few requirements to get a Sprig console:

1. You must be in high school or younger (this will be checked before mailing)
**2. Your game must use the Sprig editor**
3. Your game has a minimum of 5 mins of gameplay
4. Your game is original
```

See the full text [here](https://github.com/hackclub/sprig/blob/main/docs/GET_A_SPRIG.md)

**Comment by leomcelroy** [comment]
Glad you had fun working on your game and thanks for sharing! These PRs are for Sprig games though, and I encourage you to take a crack at making one.

**Pull request closed without merging**
