### PR TITLE
Simple rendering

### PR DESCRIPTION
**Pull request by leomcelroy**
Reverting back to canvas rendering. Addresses some minor rendering issues such as limit of 4 sprites per tile. Also makes sprig engine more easily usable as a library.

### CODE REVIEW

**Comment by leomcelroy** [comment]
I would love help checking every game before we merge this in. @Omay238 @LucasHT22 @Neesh774 @SamDev-7

**Comment by LucasHT22** [comment]
I'll check now

**Comment by LucasHT22** [comment]
all games are playable, in yarn test only `Snake_4_2 ` returns error in properties `x ` and `y`, I've tried everything but I couldn't solve it

**Comment by Omay238** [comment]
@LucasHT22 Can you put a screenshot in the github thread? I have been unable to access Slack recently. I can try to debug it.

**Comment by LucasHT22** [comment]
ok! 
image

**Comment by Omay238** [comment]
I think I fixed it. I changed every time it looks for `something.x` to check that it exists. I also changed == -> === and != -> !== to just be correct JS syntax.

**Comment by LucasHT22** [comment]
Very good @Omay238 ! Thanks

**Comment by leomcelroy** [comment]
It's because there are random inputs so the test is not exhaustive or repeatable. But the test also looks at the map not the render. So really we have to manually check the games.

**Pull request merged**
