### PR TITLE
LockandKeySprigMazeGame

### PR DESCRIPTION
**Pull request by Abbby1007**
# Your checklist for this pull request

## Author name

Abigail Loken

## About your game

**What is your game about?**

About a yellow and blue player, who must work together, by unlocking locks with their color coded keys and pushing their color coded boxes. 

**How do you play your game?**

For player 1 you use WASD to move. for Player 2 you use IJKL to move. the goal is for each player to find their color-coded key, that will unlock their color-coded lock, while also pushing color-coded boxes, with the ultimate goal of reaching their color-coded checker flag

## Code
Check off the items that are true. 
- [ `x`] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ `x`] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [`x` ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [`x` ] The game runs without errors. 
- [ `x`] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ `x`] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ `x`] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [`x` ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please modify this to differentiate it more from @recursiveforte 's example.

**Comment by grymmy** [comment]
Looked at this today, still awaiting changes from the author.

**Comment by Abbby1007** [comment]
> Looked at this today, still awaiting changes from the author.

Sorry, I haven't updated my game I wont be able to make changes for a while. Thank you for reviewing it.

**Comment by grymmy** [comment]
Looked at this today.  Per author's instructions, will wait.

**Comment by grymmy** [comment]
I am closing this as it appears inactive.  Please feel free to re-open this PR if you want to continue to advocate for its merge.

**Pull request closed without merging**
