### PR TITLE
Burger_Maker_V1

### PR DESCRIPTION
**Pull request by AceGreenJay**
The first game in the Burger Maker series.

# Your checklist for this pull request

## About your game

What is your game about? 
> One must push burger ingredients into their proper points while playing as Mr. Chef.

How to play your game?
> Press WASD to move, J to restart a level, and i to continue upon starting.

## Code
Check off the items that are true.
- [Yes] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [Yes] The game is placed in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [Yes] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [Yes] The game runs without errors. 
- [Yes] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [Yes] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [Yes] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [Yes] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by AceGreenJay** [comment]
I am a high school student and made this game for the Hack Club Sprig console giveaway.

I am a novice programmer, having learned topics within HTML/CSS/JavaScript and Python. Furthermore, I also have Linux terminal and Vim experience.

**Comment by LucasHT22** [comment]
Great game! but it doesn't change level, it stays only on the 1st

**Comment by AceGreenJay** [comment]
> Great game! but it doesn't change level, it stays only on the 1st

Thank you! I fixed it! I just finished a play through.

**Comment by LucasHT22** [comment]
Sorry for the delay, but I'm not able to complete the last level, could you record the screen showing how to solve it?

**Comment by AceGreenJay** [comment]
> Sorry for the delay, but I'm not able to complete the last level, could you record the screen showing how to solve it?

No problem. Here is the tutorial:
https://user-images.githubusercontent.com/94772862/209858797-6c8a640e-9acb-4975-accf-734915e560e6.mp4

**Comment by AceGreenJay** [comment]
Also, which shipping carrier will the console be sent through (e.g. FedEx, UPS, DHL)?

**Comment by LucasHT22** [comment]
> > Sorry for the delay, but I'm not able to complete the last level, could you record the screen showing how to solve it?
> 
> No problem. Here is the tutorial: https://user-images.githubusercontent.com/94772862/209858797-6c8a640e-9acb-4975-accf-734915e560e6.mp4

Thanks!

**Comment by LucasHT22** [comment]
> Also, which shipping carrier will the console be sent through (e.g. FedEx, UPS, DHL)?

varies depending on your country

**Comment by LucasHT22** [comment]
Great game! Looks good to me. Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by AceGreenJay** [comment]
Great! Thank you for your diligence!

**Pull request merged**
