### PR TITLE
Cube Escape

### PR DESCRIPTION
**Pull request by GalaxyGamingBoy**
# Your checklist for this pull request

## About your game

What is your game about? 
My game is about a cube that was wrongfully sentenced by trying to escape cube prison.

How to play your game?
Press `WASD` to move.
Press `L` to shoot a bullet to the right.
Press `J` to shoot a bullet to the left.
Shooting brown box and enemies, removes them.
Navigate to the `gray` warp portal to change to the **next** level.
Navigate to the `red` warp portal to change tp the **previous** level.
Navigate to the `green` warp portal to **restart** the current level.
If you touch the enemy ( green cube officer ) on any side you will lose 1 hp.
If your hp reaches 0 you restart.
You can touch the key item to unlock locked walls, after losing 1 hp you will **lose** the key.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)
No Image

> Thanks for PR!

### CODE REVIEW

**Review by SamDev-7 — CHANGES_REQUESTED** [review]
Awesome game, thanks for the PR. Very interesting how the bullet can go through the wall. 
The puzzles were quite tricky.

Before we merge, one thing I noticed was that the health seems to disappear when you restart the level (with the green hole). 
While you're fixing that, try adding more levels!
Let us know how it goes, happy hacking!

**Comment by GalaxyGamingBoy** [comment]
Should be fixed now. For the sprig will someone contact me through slack?

**Review by SamDev-7 — APPROVED** [review]

**Comment by SamDev-7** [comment]
Congrats! 
Regarding the Sprig, you can order it here if you are a teen: https://sprig-order.hackclub.dev/
If you have any questions, don't hesitate to ask them here or message us in `#sprig` on [the Slack](https://hackclub.com/slack)!

**Comment by GalaxyGamingBoy** [comment]
Thanks! Super excited to add more levels and even a new game, soon™

**Pull request merged**
