### PR TITLE
New Game - Chuckman Go!

### PR DESCRIPTION
**Pull request by faisalsayed10**
## About your game

What is your game about? 
Avoid enemies throughout the path and reach the goal!

How to play your game?
Press WASD to move, J to restart, Get to the finishing position (yellow) by avoiding all the enemies.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Comment by faisalsayed10** [comment]
Here's the demo: https://editor.sprig.hackclub.com/?id=87b00c92c17948475462ccf97945a967

**Comment by LucasHT22** [comment]
Very good game! did you manage to complete all the levels? I couldn't pass the first one haha

**Comment by faisalsayed10** [comment]
Yeah I did test them out a lot of times! Be assured it's totally possible :p

**Comment by LucasHT22** [comment]
ok!

**Review by LucasHT22 — APPROVED** [review]
Looks good to me! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by faisalsayed10** [comment]
Yay tysm!

**Pull request merged**
