### PR TITLE
Random Maze Game using DFS Algorithm

### PR DESCRIPTION
**Pull request by HanzPo**
**Author:** Hanz Po

## About

Sprig is perfect for maze games and I wanted to learn more about graph theory, so I decided to combine them into this project. This project incorporates the iterative implementation of a randomized depth-first search (DFS) generation algorithm, as described in this Wikipedia article: https://en.wikipedia.org/wiki/Maze_generation_algorithm

I'm unfamiliar with JavaScript so I first implemented the algorithm in C++ then moved it to JavaScript afterwards. C++ implementation: https://github.com/HanzPo/dfs-maze-cpp

The objective of the game is to get the player (red square) to the target (green square).

**Controls:**
WASD to move
J to generate a maze

**Other settings:**
You can change the dimensions of the maze by chainging the dimensions of the placeholder level in the levels array, but the
dimensions must be odd numbers.

## Code
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! Thanks for PR:) Where did you hear about Sprig?

**Comment by HanzPo** [comment]
> Nice! Thanks for PR:) Where did you hear about Sprig?

Hi! Someone told me about Hack Club so I went on the website and saw the Sprig page

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right:) Out of curiosity, did you use any game for inspiration?

**Comment by HanzPo** [comment]
> Right:) Out of curiosity, did you use any game for inspiration?

Yeah there's another game with randomly generated maze levels using a similar algorithm but I wrote my game from scratch

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
