### PR TITLE
Mr.Man!

### PR DESCRIPTION
**Pull request by waitwhat653**
# Your checklist for this pull request

## Author name
Deoteet
**Author:**
Deoteet Ojasavee

waitwhat
## About your game
It's a game where you push a block onto goals.
**What is your game about?**
Pushing boxes to the goal.

**How do you play your game?**
Press IJKL to move, D to restart, Get boxes to goals.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by waitwhat653** [comment]
so is it approved?

**Comment by recursiveforte** [comment]
I can't approve this since it's too simple to the maze game example. You could differentiate it by adding another game mechanic- for help, you could check out the [tutorial](https://jams.hackclub.com/batch/sprig/part-3) on this.

**Comment by grymmy** [comment]
Closing this PR as it is quite old and hasn't moved in some time.  Feel free to reopen this if you want to advocate for its merge.

**Comment by waitwhat653** [comment]
yeah you should close it

**Pull request closed without merging**
