### PR TITLE
Birdy Girdy

### PR DESCRIPTION
**Pull request by jose4185**
# Your checklist for this pull request

## Author name 

**Author:** Jose Garza

## About your game 

**What is your game about?** A Bird that collects food throughout a maze.

**How do you play your game?** Navigate The Bird through the maze and collect its food.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Please check off the items that are true 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

**Comment by grymmy** [comment]
If you wish to move forward with landing this PR eventually, please modify the filename of your game to not include any space characters.

**Review by grymmy — CHANGES_REQUESTED** [review]
If you wish to move forward with landing this PR eventually, please modify the filename of your game to not include any space characters.

**Comment by grymmy** [comment]
I am closing this PR due to inactivity.  Please feel free to reopen this PR if you want to push it forward and get it merged.

**Pull request closed without merging**
