### PR TITLE
SquidsInTheStars

### PR DESCRIPTION
**Pull request by Lucas4680**
# Your checklist for this pull request

## Author name

**Author: Lucas**

## About your game

**What is your game about? Defeating evil squids in a galaxy setting**

**How do you play your game? Use WASD to move and I to shoot. It is an endless game that progressively gets harder, and the score is kept by how many squids you've defeated.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! Where did you hear about Sprig?

**Comment by Lucas4680** [comment]
> Thanks for your PR! Where did you hear about Sprig?

I'm one of the leaders of my own club with HC and found out about Sprig through the Slack and website. We're considering a kick-off event that might feature the Sprig as a project.

**Review by LucasHT22 — COMMENTED** [review]
How did I lost it? Really sorry about delay!!

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Did you use any game as inspiration?

**Comment by Lucas4680** [comment]
Hey! It's alright. Overall, I took heavy inspiration from the asteroid breaker games you would find in an arcade. I tried to add my own original elements as well, such as the game theme.

**Comment by LucasHT22** [comment]
Hey! The checks aren't running in this PR... Could you make another PR? I just need checks approved to merge:)

**Comment by LucasHT22** [comment]
> Sure! Should I close this PR? It doesn't let me make another because I already have this fork.

Yes, thanks:)

**Pull request closed without merging**
