### PR TITLE
Add pong-multiplayer game

### PR DESCRIPTION
**Pull request by devramsean0**
What is your game about? 
It is a version of pong that allows for 2 player multiplayer

How to play your game?
| Player  | Up  | Down  | Colour |
|---|---|---|---|
|  1 |  W | S  | Black |
|  2 |  I |  K | Red |
## Code
Check off the items that are true.
- [ x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)
Not used
- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR! 2 bugs, after the end the ball keeps moving and when it hits outside the player's space, it also scores a point

**Comment by devramsean0** [comment]
I fixed the ball moving after end of game bug, but the other one is gonna require a rewrite of the scoring system, groan

**Comment by devramsean0** [comment]
I think I have fixed both now

**Review by LucasHT22 — APPROVED** [review]
Great changes! Looks good to me. Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
