### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by aaronsfunstuff**
# Your checklist for this pull request

## Author name

**Author:Aaron lei**

Aaron
## About your game
This game is called: banana runner
**What is your game about?**
Making the player get to a portal without getting chopped by the moving knife, a separate goal is to get as many keys as possible too.(the last level is suppose to say u win with the trees)

**How do you play your game?**
 Press WASD to move. The trees will block your way to getting to the portal, so u will have to go around them, there will be a knife that moves when you move so you have to get to the portal strategically.

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please add a game mechanic or two to meet the criteria for a Sprig device grant.

**Comment by aaronsfunstuff** [comment]
@grymmy I am trying to resubmit a different commit so let me know if you saw the new file

**Comment by grymmy** [comment]
Okay I am satisfied after you've made this update.  Please fill in [this form](https://sprig-order.hackclub.dev/) to receive a Sprig device (if you're a teenager, and haven't received one, that is).  Also, join us in Hack Club's Slack and share your creation in the #sprig channel!

**Comment by aaronsfunstuff** [comment]
Thank you so mucb

**Pull request merged**
