### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by shazam2123**
# Your checklist for this pull request

## Author name

**Author: Shahzeb Wali**

## About your game

**What is your game about? My game is about a stick figure jumping to try and avoid obstacles and get the highest score possible.**

**How do you play your game? You play the game by pressing W to jump.**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Thanks for your PR! Where did you hear about Sprig?

**Comment by shazam2123** [comment]
I learned about it through my schools Hacking Club at Bronx Science.

**Comment by shazam2123** [comment]
> Hey! Thanks for your PR! Where did you hear about Sprig?
Through my schools Hack Club at bronx science.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! Out of curiosity, did you use any game for inspiration?

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right! What about adding "restart with w" below "you died"?

**Comment by shazam2123** [comment]
Sure

**Comment by shazam2123** [comment]
Done!

**Comment by shazam2123** [comment]
Done!

**Comment by LucasHT22** [comment]
Really sorry about the delay! No idea how I missed it! Just re-check this:
- [ ] The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by shazam2123** [comment]
All completed! @LucasHT22

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by shazam2123** [comment]
Awesome, thanks!

**Pull request merged**
