### PR TITLE
parachute_panic

### PR DESCRIPTION
**Pull request by ristonrodrigues723**
# Your checklist for this pull request

## Author name

**Author : Riston Rodrigues**

## About your game

**What is your game about?**

-obstacle dodging,
- collecting tockens which increase your score,
 - staying in the air for max amt of time, 
- landing on the boats to finish the game
- avoid landing in water(to avoid penalty)

**How do you play your game?**
-use WASD to move. 
-Press I to restart the game.
-Dodge the clouds, ufos and land on the boats.
-the longer u dodge the obstacles the more score u get. 
-collect the crane to recieve a score boost.
-landing in water ensures u still win the game but with imposed penalty where total score will be halved

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [X] The game runs without errors. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [X] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — APPROVED** [review]
Good game! I think there something wrong with "score"
image

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Good game! I think there something wrong with "score"
image

**Comment by ristonrodrigues723** [comment]
hey lucus its the penalty for landing in water , if u land on ships u get ur score as intact if u land in water score will be halved it increases the difficulty level

**Review by LucasHT22 — APPROVED** [review]
oh right right, sorry. Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by ristonrodrigues723** [comment]
k , thanks a lot bro

**Pull request merged**
