### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Benjamin-Rosenfeld**
# Your checklist for this pull request

## About your game

What is your game about? 
> Pushing the blue number boxes into the green boxes without getting them stuck

How to play your game?
> Example  : WASD to move, J to reset the level

## Code
Check off the items that are true.
- [ ✅] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [✅ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [✅ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [✅ ] The game runs without errors. 
- [ ✅] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ✅] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
very good game! I burned my neurons haha but I can't solve level 2 and 3, could you show me how to solve it? And what is the function of magnets?

**Comment by Benjamin-Rosenfeld** [comment]
Here is recording of solutions for levels 2 and 3
https://user-images.githubusercontent.com/86892462/210190237-0d714a5b-d1d8-494f-b8a6-8c83e30aee99.mov

Magnets are from before I revamped the game, I removed them and will edit the pull request accordingly

**Comment by LucasHT22** [comment]
Great! 
image
Is the duplicate 1 intentional?

**Comment by Benjamin-Rosenfeld** [comment]
Yes, the duplicate 1 block and players are designed to be confusing, only one of them actually works

**Comment by LucasHT22** [comment]
Good idea haha, could you show me how to solve this level?

**Comment by Benjamin-Rosenfeld** [comment]
Ah yes, level 4 is evil, even I usually can't solve it first try :)

https://user-images.githubusercontent.com/86892462/210282845-615e5cdc-6a62-4ce9-98ba-20bf9de42841.mov

**Review by LucasHT22 — APPROVED** [review]
Great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
