### PR TITLE
Feature lint sprig

### PR DESCRIPTION
**Pull request by shanecelis**
I wrote a tool to help ensure other sprig games present in the repository aren't missing from the gallery. It's called `lint-sprig`. It's a little bash shell script. It might be helpful for all the awesome work sprigsters are doing adding games to the repository and website. 

Here was the output I used to make changes for my prior pull request that found three games that hadn't been added to the `metadata.json` file.

```sh
$ ./bin/lint-sprig
error: Unexpected character in file name 'games/5-in-1-Carnival-Game-Pack!.js'.
warning: 'Alien_Attack' for games/Alien_Attack.js not present in games/metadata.json.
Suggested fix: add this record to games/metadata.json.
  {
    "filename": "Alien_Attack.js",
    "title": "Alien_Attack",
    "author": "whatware",
    "img": "games/img/Alien_Attack.png",
    "tags": [],
    "addedOn": "2023-03-01"
  },
error: Unexpected character in file name 'games/Cookie_Click!.js'.
warning: 'ElfSokoban' for games/ElfSokoban.js not present in games/metadata.json.
warning: no 'games/img/ElfSokoban.png' image found.
Suggested fix: add this record to games/metadata.json.
  {
    "filename": "ElfSokoban.js",
    "title": "ElfSokoban",
    "author": "Markonije",
    "img": "",
    "tags": [],
    "addedOn": "2023-03-01"
  },
error: Unexpected character in file name 'games/It_Is_Coming_Out!.js'.
warning: 'It_Is_Coming_Out!' for games/It_Is_Coming_Out!.js not present in games/metadata.json.
error: no @author in games/It_Is_Coming_Out!.js
Suggested fix: add this record to games/metadata.json.
  {
    "filename": "It_Is_Coming_Out!.js",
    "title": "It_Is_Coming_Out!",
    "author": "N/A",
    "img": "games/img/It_Is_Coming_Out!.png",
    "tags": [],
    "addedOn": "2023-03-01"
  },
error: Unexpected character in file name 'games/Music!.js'.
error: Unexpected character in file name 'games/sPaint!.js'.
error: Unexpected character in file name 'games/seven_ate_nine_(789).js'.
```

You can also provide it with one or more game files to check. Here is the usage.

```
$ ./bin/lint-sprig -h
Usage: ./bin/lint-sprig [games/<name>.js ...]

Perform sanity check on sprig games. Ensures js files in games directory are
represented in metadata file. Checks name for invalid characters. Suggests a
record to add to metadata if not present, pulling title and author from
javascript file. Checks for associated image file.

Does not read metadata to determine if it references files not present.
```

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Great feature! Very interesting! 
How about we make a Github Actions to run it periodically?


And also, a small warning: there are some changes that are also in your other PR (#883)

**Review by grymmy — CHANGES_REQUESTED** [review]
@shanecelis sorry - this PR needs rebasing due to the recent merge.  Can you please resubmit such that it can get a proper review and merge?

**Comment by grymmy** [comment]
@shanecelis I believe this PR is dead so I'm closing it, please reopen it if you want to advocate for its merge.

**Comment by shanecelis** [comment]
Its contents were resubmitted in this PR: https://github.com/hackclub/sprig/pull/971

**Pull request closed without merging**
