### PR TITLE
Added game killer_training

### PR DESCRIPTION
**Pull request by jakjakob**
# Your checklist for this pull request

## Author name

**Author:** jakjakob

## About your game

**What is your game about?**

shooting a puppet while trying to find the right way (sometimes through a maze) in a certain time

**How do you play your game?**

WASD to move, IJKL to shoot. IJKL determines the directions you shoot, bullet has 2 range. You can't touch the puppet or you'll restart the game. By missing the shot you have to restart the level (and you lose 5s)

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

No Image used
> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! Did you manage to finish all the levels? I'm not haha

**Comment by jakjakob** [comment]
> Great game! Did you manage to finish all the levels? I'm not haha

Yeah I did! I didn't wanted to make it too easy, (that's why I added the time limit). I have on average 2 min over, but also probably because I know in all of them the best route. Thx for the feedback! Btw how many levels have you done? Should I add more time? I'll make a no time limit mode for the next update.

**Comment by LucasHT22** [comment]
> > Great game! Did you manage to finish all the levels? I'm not haha
> 
> Yeah I did! I didn't wanted to make it too easy, (that's why I added the time limit). I have on average 2 min over, but also probably because I know in all of them the best route. Thx for the feedback! Btw how many levels have you done? Should I add more time? I'll make a no time limit mode for the next update.

WOW! I did 22 levels haha, I would add more 50 on time:)

**Comment by jakjakob** [comment]
Okay, I added more time. It is now 6 minutes instead of 5. (I did 6 so it was easier for the starting screen)

**Review by LucasHT22 — APPROVED** [review]
Great! Congrats:)

Note: You can make more updates making another PR:)

Where did you heard about Sprig?

If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
