### PR TITLE
Bolt Battle

### PR DESCRIPTION
**Pull request by clikbait295**
My game is a remix of Candy Rush - I've added more levels and changed the candy to lightning bolts and the mouth to a battery.

I've had some experience coding with the Raspberry Pi and Arduino.

### CODE REVIEW

**Comment by Omay238** [comment]
I do like the new levels, although the code is a direct copy of candy rush. It would be good if you added a new feature or mechanic, but other than that, it is a gallery-worthy game.

**Comment by clikbait295** [comment]
Gotcha, added a new feature just now. In this update, blue bolts must be moved onto blue batteries, and yellow bolts must be moved to yellow batteries.

**Comment by LucasHT22** [comment]
@clikbait295 , Could you put credits to @Tasbia (#438 ) and the game Cand Rush below the instructions?

**Comment by clikbait295** [comment]
Just added some credits!

**Comment by LucasHT22** [comment]
Is there a solution for this one? Or am I playing bad?
image

**Comment by clikbait295** [comment]
Whoops, my bad. All levels should be playable now.

**Comment by LucasHT22** [comment]
The game is good! Fix the duplication and we can merge :)

**Comment by clikbait295** [comment]
Sorry, I'm not sure what you mean. What should I fix?

**Comment by clikbait295** [comment]
Fixed! Don't know how that happened...

**Comment by LucasHT22** [comment]
image
Check this

**Comment by clikbait295** [comment]
Fixed!

**Comment by LucasHT22** [comment]
Congrats! Like other remixes, it's very good :)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by clikbait295** [comment]
Great thank you so much! Loved developing on this platform, it's the perfect mix of actual coding while still being accessible for those who have just started to program.

**Comment by LucasHT22** [comment]
> Great thank you so much! Loved developing on this platform, it's the perfect mix of actual coding while still being accessible for those who have just started to program.

Good to know you liked the Sprig, @clikbait295 ! Thanks for the feedback :)

**Pull request merged**
