### PR TITLE
Avoid the Tree

### PR DESCRIPTION
**Pull request by samarth641**
# Your checklist for this pull request

## About your game

What is your game about? 
Avoid a Three is a simple game where a bird must fly through a forest avoiding trees. The objective is to fly as far as possible without crashing into a tree. The game may have various features such as power-ups, different environments, and obstacles. The player controls the bird's movement by tilting their device or using on-screen buttons to navigate through the forest. The game may be set in a endless mode, where the player must try to get the highest score, or in a level-based mode, where the player must complete a certain number of levels to win the game.(from [Samarth Verulkar](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/samarth641/sprig/main/games/Avoid_The_Tree.js))

How to play your game?
Press W to go up and S to go down Avoid the tree log at all cost and make a high score  (from [Samarth Verulkar](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/samarth641/sprig/main/games/Avoid_The_Tree.js))

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by SamDev-7** [comment]
Cool art, but the code is really similar to [flappy_bird_but_no_gravity_and_worse](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/flappy_bird_but_no_gravity_and_worse.js). 

Can add something new to the game? 
Some ideas could be:
- Adding gravity
- Flying enemies 
- Maybe the trees can move up and down?

Be creative! I'm looking forward to see what you come up with.
Happy hacking!

**Review by samarth641 — COMMENTED** [review]
@SamDev-7  I have done the required changes

**Comment by LucasHT22** [comment]
I'm not Sam but I'll check

**Comment by LucasHT22** [comment]
I saw that you use 2 codes, the gravity demo and the game already mentioned by Sam, add these references at the top of the code:)

**Comment by samarth641** [comment]
@LucasHT22 Can you tell me what to add the reference in code

**Comment by LucasHT22** [comment]
Yep!
``` References:
Coding Demo 5: Gravity by Leonard (Omay)
flappy_bird_but_no_gravity_and_worse by sam liu```

**Review by samarth641 — COMMENTED** [review]
.

**Review by samarth641 — COMMENTED** [review]
done.

**Comment by samarth641** [comment]
@LucasHT22 can you tell me how to change it I am not able to shall I directly upload it to my fork or to spring fork

**Review by samarth641 — COMMENTED** [review]
Image uploaded ;)

**Comment by samarth641** [comment]
@LucasHT22  its telling me to add my pull request link so shall I add this one https://github.com/hackclub/sprig/pull/703

**Comment by LucasHT22** [comment]
> @LucasHT22 its telling me to add my pull request link so shall I add this one #703

add `https://github.com/hackclub/sprig/pull/703`

**Pull request merged**
