### PR TITLE
Highlight erroring line

### LINKED ISSUE #797: Highlight errors in editor

### PR DESCRIPTION
**Pull request by SamDev-7**
Uses a similar (janky) method to UI V1, finds and highlights the erroring line. 
Resolves #797.

## Examples: 
image

image

### CODE REVIEW

**Comment by grymmy** [comment]
My general thoughts on this are there could be a few comments added to explain the magic tricks being performed in this code.  That being said, this definitely attempts to solve a very real problem effecting users.  Would suggest the PR author to exercise the editor a bit w/ different error scenarios to see if this change reacts well to them.

Will merge when additional requested comments are added clarifying what some of these functions do.

**Comment by SamDev-7** [comment]
@grymmy I've tried adding more comments, most of the modified code is adapted from V1. I'm unsure how comments should be styled with Sprig, so please let me know if I did anything wrong. Thanks!

**Comment by SamDev-7** [comment]
Update: It seems to have issues with nesting anonymous functions. 
Sample: https://sprig.hackclub.com/share/JOU4JeHU2cGMrydlXCcD

**Comment by SamDev-7** [comment]
Apologies for the notification spam, I've attempted a fix. That error is normalized [here](https://github.com/hackclub/sprig/blob/aa446aeeefa8308cf447beee5936ce512153d970/src/lib/engine/3-editor/index.ts#L21) and not the usual location, so it was missed.

**Review by grymmy — APPROVED** [review]
LGTM

**Comment by grymmy** [comment]
@SamDev-7 Okay to merge after you resolve the remaining conflict in the PR.

**Comment by SamDev-7** [comment]
@grymmy I have attempted to elaborate regarding comments and the merge conflicts have been resolved. Let me know if issues still persist.

**Pull request merged**
