### PR TITLE
Add Bert Blaster Game

### PR DESCRIPTION
**Pull request by ungarmichael**
Hi, we created a game called bert blaster and it is about one of our teachers fighting against the austrian law system. You can start the game with W, then shoot bullets with L, stop the game with J and jump over obstacles using W.

### CODE REVIEW

**Comment by LucasHT22** [comment]
Thanks for PR!

**Comment by LucasHT22** [comment]
nice game, nice sprites :) i would merge it now! but before that, could you talk more about this analogy of the law system with the game?

**Comment by LucasHT22** [comment]
add .js at the end of the filename!

**Comment by ungarmichael** [comment]
thank you, just fixed it

**Comment by LucasHT22** [comment]
Congrats!
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by ungarmichael** [comment]
@LucasHT22 I am still in Highschool but already 19 years old, can I still get my hands on a sprig?

**Comment by LucasHT22** [comment]
Yeah! just attach a school document!

**Comment by LucasHT22** [comment]
image

**Pull request merged**
