### PR TITLE
Meteor shower

### PR DESCRIPTION
**Pull request by BronxMate**
# Your checklist for this pull request

## About your game

What is your game about? 
> The goal in the game is to get the rocket to the coin, without touching any meteors.

How to play your game?
> Press WASD to move, and K start the game. If you finished the game, press "run" to start again.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

### CODE REVIEW

**Comment by LucasHT22** [comment]
good game! could you add more levels?

**Comment by BronxMate** [comment]
I can try

**Comment by LucasHT22** [comment]
anything you can ask me :)

**Comment by BronxMate** [comment]
I am done, how can I edit the uploaded code?

**Comment by LucasHT22** [comment]
In this PR `Files changed` > `...` > `edit` :)

**Comment by LucasHT22** [comment]
2 more levels, the game is good but too short and also change the color of the "level done" messages to be better for the eyes:)

**Comment by BronxMate** [comment]
Done :D

**Comment by LucasHT22** [comment]
Very good changes!

**Comment by BronxMate** [comment]
Thanks!

**Pull request merged**
