### PR TITLE
gravity_box

### PR DESCRIPTION
**Pull request by JosiasAurel**
# Your checklist for this pull request

## Author name

**Author: Josias Aurel**

## About your game

It's about a box that responds to gravity. You get to rotate the world to make the box fall in the direction you want till you reach your goal.

You play the game by rotating the world at 90-degree angles using the <kbd>a</kbd> and <kbd>d</kbd> keys to turn the planet 90 degrees counterclockwise or clockwise, respectively.

## Code

- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Great game! What about more levels?

**Comment by Goldenpig12345** [comment]
ok yes i know about the wall and i have fixed it and sent another request.
sorry, i might be slow at this cuz github is hard.

**Comment by JosiasAurel** [comment]
oh lol @LucasHT22 this should be fixed now. ack @Goldenpig12345 saw another pr for your game

**Review by LucasHT22 — APPROVED** [review]
Great, @JosiasAurel ! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by JosiasAurel** [comment]
yay! Thank you @LucasHT22. Can't order a Sprig ig... graduated high-school already

**Pull request merged**
