### PR TITLE
Super_Mario

### PR DESCRIPTION
**Pull request by Cosmin-Mare**
# Your checklist for this pull request

## Author name

**Author: Cosmin**

## About your game

**What is your game about?**
My game is about Super Mario, you have to get to the pipes to go to the next level.

**How do you play your game?**
AD to move horizontally, W and J to jump, K to reset level after you die and L to reset game after you die. Get to the pipes and hit mystery boxes with your head to get mysteries.

## Code
Check off the items that are true. 
- [ X ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ X ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ X ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ X ] The game runs without errors. 
- [ X ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ X ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ X ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ X ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Did you manage to reach the end of your game?

**Comment by Cosmin-Mare** [comment]
yes! although it is challenging! you have to manage your lives rlly well in some levels

**Comment by Cosmin-Mare** [comment]
IMG_20240301_164551000
I tested it on a sprig and I can get to the end!

**Review by LucasHT22 — APPROVED** [review]
Right! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
