### PR TITLE
Box_Guy

### PR DESCRIPTION
**Pull request by ilyKcaj**
# Your checklist for this pull request

## Author name

**Author:** jli46

## About your game

**What is your game about?**
Box Guy is a very challenging and unforgiving puzzle game. You are Box Guy, and your mission is to complete all of the ten levels in the game. To beat each level you must reach the door, but this is not as easy since the door is not always in a convenient place. There are obstacles in the way such as walls that are non-moveable and boxes that are moveable, which you can use to your advantage.

**How do you play your game?**
Your goal is to get to the door on the map. Your character can fall any height but can only climb up one unit. You can pick up boxes with nothing on top of them and set them down in front of you or on top of a one-unit obstacle in front of you.

A: Move left and face left, D: Move right and face right, S: Pick up or drop box, W: Move upwards, J Key: Reset current level, L Key: Reset to very beginning start screen, K key: Begin game

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by savinajabbo** [comment]
Your game is so enjoyable! The sound effects are really cool, and I love the problem-solving aspect of the game!

**Review by LucasHT22 — APPROVED** [review]
Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by ilyKcaj** [comment]
Hi guys, I made a mistake on line 223. I would appreciate it if you could replace the "d" in the line with a "." Thanks, and sorry for the inconvenience.

**Comment by LucasHT22** [comment]
No worries! I can't find it tho 
image

**Comment by ilyKcaj** [comment]
Oops, in that screenshot its on line 224.

**Pull request merged**
