### PR TITLE
Draft Game by Ethan

### PR DESCRIPTION
**Pull request by EthanaelKk**

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for PR! Not knowing where you have to go makes the game interesting! Could you delete the DRAFT files? later we can merge

**Comment by EthanaelKk** [comment]
> Thanks for PR! Not knowing where you have to go makes the game interesting! Could you delete the DRAFT files? later we can merge

Yep! All Fixed 👍

**Comment by LucasHT22** [comment]
I removed the "das" lost for you :)

**Comment by LucasHT22** [comment]
The "luck" mechanism, you don't know which one you have to pass, sets it apart from other skoban and maze games, as simple as it is, a trick with the setSolids() function makes it original!
   I encourage you to keep improving your next games with more complex mechanics too :)

If you're a teenager, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
