### PR TITLE
Don't Get Caught

### PR DESCRIPTION
**Pull request by mariia-ty**
# Your checklist for this pull request

## Author name
Alexandra Miller, Mariia Tymoshenko, Elaine Liu, Shenelle Jayakody, Ariane Clarke

## About your game

**What is your game about?**
In this game, you are tasked with helping a piece of bread escape a scientist with an army of toasters. If the toasters were to catch the bread, it would get toasted and the game ends. 

**How do you play your game?**
Use WASD to move, and J to start the same after the story plays. 
## Code

- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Are you the same authors of Don't get burnt?

**Comment by fox-tech17** [comment]
Hey @LucasHT22! Yep, I'm one of them. I was told to make another pull request with a slightly different version of the game to get a sprig, and here it is.

**Comment by SamDev-7** [comment]
Hey there, Sam here! Thanks for the submission. I would love for you to get a Sprig, but following the rules, more needs to be done for this to be submitted as a remix. Really sorry about that. Try to change the story in a way that introduces new code and features to the game.
Best of luck with the game! Let us know if you run into any issues.

**Comment by grymmy** [comment]
Closing due to inactivity. Please re-open if you'd like to continue forward landing this game!

**Pull request closed without merging**
