### PR TITLE
Top_Hat_Turtles

### PR DESCRIPTION
**Pull request by PickleLikesPizza**
# Your checklist for this pull request

## Author name

**Author:**

PickleLikesPizza

## About your game

**What is your game about?**

A simple teamwork game where each turtle needs to reach their totem to ascend to the next level. There are a few levels, where they each get a little more challenging. Overall, mostly based off of teamwork.

**How do you play your game?**

WASD and IJKL to move; need two players. Each turtle (controlled by WASD and IJKL) needs to get to their respective totem, which is denoted by their top hat colors, to reach the next level.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
Please relocate the your game's javascript to the games directory per the PR instructions.  Right now you've located it in the root directory of the repository.

**Comment by PickleLikesPizza** [comment]
I should have put a push request for it in the directory.

**Comment by grymmy** [comment]
> I should have put a push request for it in the directory.

Sorry - i didn't understand that...  are you having an issue with updating this pull request?  If you're not familiar with how to, I can help you...

**Comment by PickleLikesPizza** [comment]
Sorry I haven't used Github a lot. I meant that I had attempted to place my game into the games directory, but it just told me it would send a push request so that it could get approved.

**Comment by grymmy** [comment]
> Sorry I haven't used Github a lot. I meant that I had attempted to place my game into the games directory, but it just told me it would send a push request so that it could get approved.

I understand.  I've modified the path and fixed the metadata on the game on my side.  Note that if you go to the "File changed" tab, and click 'edit' on a file, you can modify the path of the file at the top of the editor where the filename is displayed.

**Pull request merged**
