### PR TITLE
New Game

### PR DESCRIPTION
**Pull request by playfun24**
Author: Cindy (Wenxi Wang)

 playfun24

## About your game
**What is your game about?**
The player needs to push the rocks in order to get the treasure. 

**How do you play your game?**

Press WASD to move.  The goal is to move the rocks so the player reaches the treasure. Press k to restart the level. 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Thanks for the PR! Did you use any games for inspiration?

**Comment by playfun24** [comment]
I used the tutorial as inspiration for having the player push an item. I came up with the idea and made the maps independently.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Right, please re-check this:
- [ ] The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by playfun24** [comment]
I changed the file name. Is there anything else I need to do?

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
What about adding a bit more to your game? Another player, obstacles... Anything:)

**Comment by LucasHT22** [comment]
What about a bit more? :)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Sorry for the delay! What about a clearText() when restart? also, how to solve this level? 
image

**Comment by playfun24** [comment]
The "j" key removes the traps. I want the key to only work when the player is next to the trap tile. Is there code for that?

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Everthing is possible:) i think you can do with if. But i'm having some problems, see:
https://cloud-8m6zvv21o-hack-club-bot.vercel.app/020231221-2112-54.2294193.mp4

**Review by LucasHT22 — APPROVED** [review]
Looks alright now! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by playfun24** [comment]
I couldn't join any of the channels in slack.  What should I do?
Screenshot 2023-12-22 142512

**Comment by tregsthedev** [comment]
Hi Cindy!

I've promoted you to a full user, I'm really sorry about the error you had earlier. If you go back to #click-me-to-start and start the flow again, it should work :)

When you're on slack again, feel free to dm me @arav or you can dm @shawn if you need help! If you prefer the PR, that's also fine!

Happy Hoildays!

**Comment by LucasHT22** [comment]
bro @tregsthedev is really Omnipresence

**Comment by playfun24** [comment]
Hi, 
I just received my console but did not get the winter case. Do I need to make an additional video?

**Comment by LucasHT22** [comment]
> Hi, I just received my console but did not get the winter case. Do I need to make an additional video?

You probably will receive it soon! cc @Sheepy3

**Comment by playfun24** [comment]
The piece fell off the raspberry pi. Will it affect anything? The screen won't turn on. I found the drive before but when I plugged the wire in, I couldn't find it again. [Photo]

**Comment by playfun24** [comment]
Image_20231229220028

**Comment by LucasHT22** [comment]
WOW! I don't have much experience with hardware, please send a message in #sprig so I can ping the right person:)

**Pull request merged**
