### PR TITLE
Run 3 Maze

### PR DESCRIPTION
**Pull request by TCDATP**
Author name: Tej Patel

Description: Run 3 Maze" is a thrilling adventure game that challenges players to navigate through a series of intricate mazes while avoiding obstacles and pitfalls. The game is designed to test players' reflexes, spatial awareness, and problem-solving skills as they guide their character through increasingly complex levels.

Navigation: Use WASD to move your character through the maze. The objective is to reach the end of the level without falling into the void or colliding with obstacles.

> Thanks for your PR!

### CODE REVIEW

**Comment by TCDATP** [comment]
Hello,

I recently learned about Sprig from our computer science honors society
advisor.

Best regards, Tej Patel

**Comment by LucasHT22** [comment]
Nice! Could you check this? :)
## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file.

**Comment by TCDATP** [comment]
I believe I meet all the Code list items. There are other maze games from
what I have seen, but our codes and maze themes are different.

**Comment by LucasHT22** [comment]
Right, where's the end of the levels?

**Comment by TCDATP** [comment]
There is only 1 level. The start is on the top left and the end is on the
bottom right.

**Comment by LucasHT22** [comment]
Sorry for the delay! Hmm but that's not what the description says, what about more levels?

**Comment by TCDATP** [comment]
I initially planned on having more levels, but changed it since I thought
the deadline to submit the game was March 1st for sprig.

**Comment by LucasHT22** [comment]
> I initially planned on having more levels, but changed it since I thought the deadline to submit the game was March 1st for sprig.

There's no deadline:) Where did you hear about deadline?

**Comment by TCDATP** [comment]
Great! The advisor for my schools computer science honors society told me
that the deadline was March 1st or March 15th. So, is their no deadline at
all?

**Comment by LucasHT22** [comment]
> Great! The advisor for my schools computer science honors society told me that the deadline was March 1st or March 15th. So, is their no deadline at all?


Nope! Sprig is forever:)

**Comment by Sheepy3** [comment]
closing this pr due to inactivity. feel free to ping me to have this reopened and hopefully merged!

**Pull request closed without merging**
