### PR TITLE
Add Maths Speedrun Game

### PR DESCRIPTION
**Pull request by m-anshuman2166**
# Your checklist for this pull request

## Author name

**Anshuman M.**

## About your game

**What is your game about?**

Recognizing whether the calculation shown on the screen using addition or multiplication.

**How do you play your game?**

A : To indicate that the current equation is based on Addition.
D : To indicate that the current equation is based on Multiplication.
S : To reset the game

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice game! I noticed a bug: at the end the screen flashes and the score increases

**Comment by m-anshuman2166** [comment]
I'll check and fix it, thanks for letting me know

**Comment by m-anshuman2166** [comment]
@LucasHT22 I've fixed the bug.

**Review by LucasHT22 — APPROVED** [review]
Great changes! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
