### PR TITLE
Ethan's Game

### PR DESCRIPTION
**Pull request by ethanlanclos**
# Your checklist for this pull request

## Author name

**Author:** Ethan Lanclos

Ethan
## About your game

**What is your game about?**
This game is a simple but challenging basketball game. The objective is to put the basketball into the goal.

**How do you play your game?**
Press WASD to move; J to restart

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Did you use any game for inspiration?

**Comment by leomcelroy** [comment]
Can you adjust the metadata in the file to indicate you made this game your own and how?

**Review by grymmy — CHANGES_REQUESTED** [review]
Please move this game into the games folder.  It is currently situated in the root of the repo.

**Comment by grymmy** [comment]
I have corrected the position of the game itself but this flags as having too much similarity with the getting started tutorial.  As a result, and also due to inactivity, I am closing this PR.  Please feel free to reopen this PR once more development of the game has been completed.

**Pull request closed without merging**
