### PR TITLE
Astrovoid

### PR DESCRIPTION
**Pull request by Zutki**
# Your checklist for this pull request

## About your game

What is your game about? 
> The game is about moving a ship to avoid falling asteroids

How to play your game?
> Use WASD to move the ship around, press I to pause the game, avoid the asteroids

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

> Thanks for PR!

### CODE REVIEW

**Comment by LucasHT22** [comment]
Great game! How about adding the "j" as a restart?

**Comment by Zutki** [comment]
@LucasHT22 Sorry for the @, I added a restart key as you suggested

**Comment by LucasHT22** [comment]
No problem! can i review tomorrow? I'm out of office today

**Comment by Zutki** [comment]
You can review whenever works for you

**Review by LucasHT22 — APPROVED** [review]
Sorry for the delay! Great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by Zutki** [comment]
Wdym an error with .x?
I don't have any errors in my console while running the game

**Comment by LucasHT22** [comment]
I mean this: 
image
Probably .x in player movments

**Comment by Zutki** [comment]
I looked into the issue, turns out I was using my parameters wrong, I guess it was to where it didn't cause issue during my testing and the bot did it's job and found my mistake.

**Review by LucasHT22 — APPROVED** [review]
Interesting! Great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
