### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tigerflame777**
Time Puzzle: 
In this game you have to get all the boxes(grey squares) to the green square. You have 100 seconds to do so as well. Once your time is up, you must restart. 

This is my second game I made for the sprig and I have gotten better at coding ever since the first game I made.

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
I'm happy to see you again! your second game!
How should this level be resolved?
image

**Comment by tigerflame777** [comment]
> I'm happy to see you again! your second game! How should this level be resolved? image

First, you need to move the middle block to the furthest green square on the right side. Leave the green middle square last. Then move a block next to the block on the right side and do the same to the left side. 


image

**Comment by LucasHT22** [comment]
about time, don't you think 85 seconds is a short time to complete the game?

**Comment by tigerflame777** [comment]
> about time, don't you think 85 seconds is a short time to complete the game?

Yeah, I thought about that so now it's 100 seconds.

**Comment by LucasHT22** [comment]
Congrats for your second game!

**Pull request merged**
