### PR TITLE
Add Outbrick to sprig

### PR DESCRIPTION
**Pull request by Shrey-Mehra**
# Your checklist for this pull request

## About your game

What is your game about? 

How to play your game?

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Thanks for PR! 

What is your game about?

How to play your game?

**Comment by Shrey-Mehra** [comment]
Hey Lucas,
It's like a simple brickout game but with more interesting music and bg, etc.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
This game is extremely similar to https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/Breakout.js , I encourage you to make another game or make more changes

**Comment by Shrey-Mehra** [comment]
i have maded another game so i'm closing this pull

**Pull request closed without merging**
