### PR TITLE
Add my game! (UAV)

### PR DESCRIPTION
**Pull request by malted**
**Author:** malted

**What is your game about?**
UAVs

**How do you play your game?**
Press any button to move the ship & avoid UAVs.

## Code
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file.

> Thanks for your PR!
🚀

### CODE REVIEW

**Review by LucasHT22 — DISMISSED** [review]
Haha Don't you want to give credit to someone?

**Review by DevIos01 — APPROVED** [review]
LGTM!! <3

**Comment by LucasHT22** [comment]
Are you sure @malted ?? haha

**Review by LucasHT22 — APPROVED** [review]
Sorry for the delay, I forget haha. Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
