### PR TITLE
Box_Maze

### PR DESCRIPTION
**Pull request by BodenP-tech**
In my game you push boxes to get to the goal while a timer counts you down.
When I was younger I did code.org but now I am learning JavaScript through Codecademy.

### CODE REVIEW

**Comment by SamDev-7** [comment]
Awesome game! Thanks for the pr!
Fascinating as the goal differs from other push-box games. You have to get the player to the goal and not the box.

One thing though, as you know, you'll need to come up with a name! We'll merge it afterwords.
Let us know if you need any ideas.

**Comment by LucasHT22** [comment]
>The name doesn't show up because I forgot to name it 
what is the name?

**Comment by LucasHT22** [comment]
code.org at school?

**Comment by LucasHT22** [comment]
I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy

in English it would look like this:

var total = 10;
      var timer = setInterval(function(){
      total--;
      clearText();
      addText(""+total, { y: 1 , color: [255,0,0] });
        if(total <= 0){
          clearTile(getFirst(player).x,getFirst(player).y);
          clearInterval(timer);
          addText("Game over!")
      }
      },1000);

**Comment by BodenP-tech** [comment]
> code.org at school?

Mostly at home. My mother made me do code.org for 1 hour every weekend

**Comment by LucasHT22** [comment]
which of the 2 is the main one?

**Comment by BodenP-tech** [comment]
> Awesome game! Thanks for the pr! Fascinating as the goal differs from other push-box games. You have to get the player to the goal and not the box.
> 
> One thing though, as you know, you'll need to come up with a name! We'll merge it afterwords. Let us know if you need any ideas.

I think I commited the game with a name attached to it, I am wondering if there is anything else to do.

**Comment by BodenP-tech** [comment]
> which of the 2 is the main one?

The more recent one, I just added a name and tweaked my instructions.

**Comment by BodenP-tech** [comment]
> I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy
> 
> in English it would look like this:
> 
> var total = 10; var timer = setInterval(function(){ total--; clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <= 0){ clearTile(getFirst(player).x,getFirst(player).y); clearInterval(timer); addText("Game over!") } },1000);



> I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy
> 
> in English it would look like this:
> 
> var total = 10; var timer = setInterval(function(){ total--; clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <= 0){ clearTile(getFirst(player).x,getFirst(player).y); clearInterval(timer); addText("Game over!") } },1000);

I think its funny that you mentioned that you designed the code for this timer as I actually took this from one of my friends games who probably took it from you

**Comment by LucasHT22** [comment]
> > I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy
> > in English it would look like this:
> > var total = 10; var timer = setInterval(function(){ total--; clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <= 0){ clearTile(getFirst(player).x,getFirst(player).y); clearInterval(timer); addText("Game over!") } },1000);
> 
> > I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy
> > in English it would look like this:
> > var total = 10; var timer = setInterval(function(){ total--; clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <= 0){ clearTile(getFirst(player).x,getFirst(player).y); clearInterval(timer); addText("Game over!") } },1000);
> 
> I think its funny that you mentioned that you designed the code for this timer as I actually took this from one of my friends games who probably took it from you

cool, out of curiosity, what's your friend's game?

**Comment by LucasHT22** [comment]
> > which of the 2 is the main one?
> 
> The more recent one, I just added a name and tweaked my instructions.

Can I delete the previous version?

**Comment by BodenP-tech** [comment]
> > > which of the 2 is the main one?
> > 
> >
> > The more recent one, I just added a name and tweaked my instructions.
> 
> Can I delete the previous version?

I don't see why not

**Comment by BodenP-tech** [comment]
> > > I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy
> > > in English it would look like this:
> > > var total = 10; var timer = setInterval(function(){ total--; clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <= 0){ clearTile(getFirst(player).x,getFirst(player).y); clearInterval(timer); addText("Game over!") } },1000);
> > 
> > 
> > > I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy
> > > in English it would look like this:
> > > var total = 10; var timer = setInterval(function(){ total--; clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <= 0){ clearTile(getFirst(player).x,getFirst(player).y); clearInterval(timer); addText("Game over!") } },1000);
> > 
> > 
> > I think its funny that you mentioned that you designed the code for this timer as I actually took this from one of my friends games who probably took it from you
> 
> cool, out of curiosity, what's your friend's game?

His game is time_puzzle

**Comment by LucasHT22** [comment]
> > Awesome game! Thanks for the pr! Fascinating as the goal differs from other push-box games. You have to get the player to the goal and not the box.
> > One thing though, as you know, you'll need to come up with a name! We'll merge it afterwords. Let us know if you need any ideas.
> 
> I think I commited the game with a name attached to it, I am wondering if there is anything else to do.

It only fixes the failure of the timer not stopping when it reaches the last goal and the player also stops

**Comment by LucasHT22** [comment]
> > > > I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy
> > > > in English it would look like this:
> > > > var total = 10; var timer = setInterval(function(){ total--; clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <= 0){ clearTile(getFirst(player).x,getFirst(player).y); clearInterval(timer); addText("Game over!") } },1000);
> > > 
> > > 
> > > > I'm glad you used my timer :) I noticed that you used because the variables are in Portuguese (my native language! I'm from Brazil!), I used it in my game Flurffy
> > > > in English it would look like this:
> > > > var total = 10; var timer = setInterval(function(){ total--; clearText(); addText(""+total, { y: 1 , color: [255,0,0] }); if(total <= 0){ clearTile(getFirst(player).x,getFirst(player).y); clearInterval(timer); addText("Game over!") } },1000);
> > > 
> > > 
> > > I think its funny that you mentioned that you designed the code for this timer as I actually took this from one of my friends games who probably took it from you
> > 
> > 
> > cool, out of curiosity, what's your friend's game?
> 
> His game is time_puzzle

Oh Akeel, he already made 2 games!, I also noticed that in his

**Comment by LucasHT22** [comment]
why did you delete the game?

**Review by LucasHT22 — APPROVED** [review]
now yes!

**Comment by LucasHT22** [comment]
Congrats!
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Pull request merged**
