### PR TITLE
Slippy Slidey

### PR DESCRIPTION
**Pull request by averyinterestingusername**
A game where you slip and slide over ice in order to press some tiles and proceed to the next level!

# Your checklist for this pull request

## Author name

B0redChungus

## About your game

About slipping and sliding into the next level!

**How do you play your game?**

By pressing all of the unpressed tiles on the ground, marked by a red 'X', and then pushing a button. The button will lead you to the next level, but to get there, you will need to cross some ice. On the ice, you slide, and you can't change the direction you're moving in. Good luck!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by averyinterestingusername** [comment]
For some reason I can't create a vercel account to see what went wrong. I'll try again tomorrow.

**Comment by averyinterestingusername** [comment]
Sprig app not deploying, and vercel is throwing an error when I try to login.

**Comment by averyinterestingusername** [comment]
Somebody on slack told me all i had to do is wait.
so i guess i will

**Comment by recursiveforte** [comment]
Nice job with this game! I'm approving it, and you'll see it in the gallery soon.

If you're a teenager, you can request a free Sprig console at [this link](https://sprig-order.hackclub.dev) and join our [online Slack community](https://hackclub.com/slack) to chat with other people making Sprig games.

**Pull request merged**
