### PR TITLE
Candy Rush!

### PR DESCRIPTION
**Pull request by Tasbia**
Try to get the candies in the mouths.
-No pushing candies with other candies; there are ways to position your character to not have to do this to win -The black blocks are walls, which your character cannot pass through.

### CODE REVIEW

**Comment by Omay238** [comment]
It's fun, the art is good, but there is only one level. I feel like adding more would be really important if you want to get a sprig.

**Comment by Omay238** [comment]
Nice! I'll merge this now.
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

**Comment by LucasHT22** [comment]
I love the pun on the name of the game haha

**Comment by Tasbia** [comment]
Ah whoops, sorry! I had my starting level not set at 0.

**Comment by LucasHT22** [comment]
Sorry, but I don't understand what you mean, could you explain better?

**Comment by Omay238** [comment]
> Sorry, but I don't understand what you mean, could you explain better?

I had previously put a comment on, saying there was one level, but they had the level variable set to some number that wasn't 0, likely for testing purposes.

**Pull request merged**
