### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Kalo08**
By Kalo 

about the game-

This game is a puzzle based maze game where you push a box into an activator to open up a wall. the ultimate goal is to reach the teleporter. sounds simple, but when there are multiple boxes and activators. your brain will have to think deep and hard about your next move.

how to play
use WASD to control you player and push the boxes into there places to open a wall which will eventually lead to the teleporter to the next level.

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for your PR! 

Please complete this:

## Code
Check off the items that are true. 
- [ ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

**Comment by Kalo08** [comment]
> Thanks for your PR!
> 
> Please complete this:
> 
> ## Code
> Check off the items that are true.
> 
> * [ ]  The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
> * [ ]  The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
> * [ ]  The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
> * [ ]  The game runs without errors.
> * [ ]  The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
> * [ ]  The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

**Comment by Kalo08** [comment]
(I accidentally closed it. So I'm just re-commenting what you said)

Check off the items that are true.

 The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
 The game is placed in the in the [/games directory](https://github.com/hackclub/sprig/tree/main/games).
 The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
 The game runs without errors.
 The name of the file/game contains only alphanumeric characters, -s, or _s.
 The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

All items are true

**Comment by Kalo08** [comment]
> Thanks for your PR!
> 
> Please complete this:
> 
> ## Code
> Check off the items that are true.
> 
> * [ ]  The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
> * [ ]  The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
> * [ ]  The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
> * [ ]  The game runs without errors.
> * [ ]  The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
> * [ ]  The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

(I accidentally closed it, so I'm just recommending)

all items are true

**Comment by LucasHT22** [comment]
Sorry for the delay! Nice, where did you hear about Sprig?

**Comment by Kalo08** [comment]
My friend asked me if I wanted to start a hack club with him through the school. Naturally, because I'm interested in engineering and computer science I said of course. Through that friend, I learned about the sprig.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
oh cool! Out of curiosity, did you use any game for inspiration?

**Comment by Kalo08** [comment]
No, what I used for inspiration was a game I was developing on Unity. It was in 3D but the concept was you would have walls that would open if you put a box on a pad. But this is slightly different because in the Unity game, there were things like pistons, levers/buttons, fans, and other elements that would move the box, and there were different types of boxes. Some you could lift with the player others were too heavy and needed something like a piston to move it. Others had no gravity and needed a fan to blow it into place. However, I did not have enough time to finish the project seeing how midterms were starting. then after that, I forgot about the concept then remembered it after some brainstorming. It would have been cool if I added more of the original features from the original concept. However, due to my current skill as the sprig editor, I was limited in what I could add. I was also limited by time because we would like to have a sprig we can use by Thursday which is our next meet.

**Review by LucasHT22 — APPROVED** [review]
Right, you can update just by making other PR:) Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
