### PR TITLE
2 Player Maze Runner

### PR DESCRIPTION
**Pull request by Ninjadash54**
# Your checklist for this pull request

## Author name

**Author:**
Josh Deva: 14 Year old enrolled in Prosper High School

**Email:**
djoshandrew@gmail.com

## About your game

**What is your game about?**
You have to use 2 players to finish all the levels first. Winner gets something from the other player!

**How do you play your game?**
WASD to move player 1, IJKL to move player 2

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR!

**Comment by Ninjadash54** [comment]
Yeah, Of course! Just wanted to know if it would be eligible to receive a
sprig. I had a lot of fun making the game! Hope it becomes a hit!

**Comment by savinajabbo** [comment]
Love your game! The two-player aspect makes it delightful to play with friends! Quick question: Is the last level supposed to be unbeatable? Also, what about adding a final map to announce the winner of the game?

**Comment by Ninjadash54** [comment]
Yeah those are amazing ideas. I can make the changes. How would you want
the game to be resubmitted after i finish?

**Comment by savinajabbo** [comment]
Feel free to commit your changes here, and then comment when you're finished!

**Comment by LucasHT22** [comment]
To update PR you can go to `Files changed` > `...` > `edit` :)

**Comment by Ninjadash54** [comment]
I just committed my changes. I think that should be good now!

**Comment by savinajabbo** [comment]
Changes looking good! Amazing game! :))

**Comment by Ninjadash54** [comment]
Thanks! Just wondering, do I need to do anything else to get the sprig
console/device? Like a form I have to fill out or something like that? Or
do you need me to add anything to the game?

**Review by LucasHT22 — APPROVED** [review]
Here it goes!
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by Ninjadash54** [comment]
Hey, quick question. I accidentally spelled my name wrong on the file. It's
supposed to be Josh Deva instead of Josh Deba. Is there any way to fix this?

**Comment by LucasHT22** [comment]
Looks like it's correct:)
image

**Comment by Ninjadash54** [comment]
I was referring to my name that shows up in the gallery of the sprig
website. Sorry for the confusion.

**Comment by LucasHT22** [comment]
Oh sorry, fixing now

**Comment by LucasHT22** [comment]
fixed https://github.com/hackclub/sprig/commit/5ca84647606762c2045ee55a9604f2beaf15847a

**Pull request merged**
