### PR TITLE
Added Dodgy-Day Game

### PR DESCRIPTION
**Pull request by cyberneel**
# Your checklist for this pull request

## Author name

**Author:** Neelesh Chevuri

## About your game

**What is your game about?**

My game is about dodging obstacles for as long as you can.

**How do you play your game?**

Use the WASD controls to move around, you have 3 hearts and the difficulty increases with the survival time. Make sure to not let the blue circles turn red!! If they do, you instantly loose, so keep moving!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
I played for a long period of time but it didn't seem to increase game difficulty over time.  This seemed wrong given the game was an endless spray of bullets - but the bullets were of such a consistent rate that it was outright boring and couldn't really be described as a game.

I do believe some small tweaks - very small - could make this much more enjoyable.  Can you try to make a tweak or two to push it in that direction?

**Comment by cyberneel** [comment]
@grymmy I have made changes and added a new mechanic to incentivize player movement, what do you think about it now? Thanks!

**Comment by grymmy** [comment]
Looking now...

**Comment by grymmy** [comment]
I run into a game-breaking error consistently shortly after starting the game and moving around a bit.  Here is a screenshot.

Can you test this a bit more and fix this bug such that I can play for a small amount of time (1 minute?)

**Comment by cyberneel** [comment]
> I run into a game-breaking error consistently shortly after starting the game and moving around a bit. Here is a screenshot.
> 
> Can you test this a bit more and fix this bug such that I can play for a small amount of time (1 minute?)

I can’t see the screenshot, can you resend it? Thanks!

**Comment by grymmy** [comment]
> > I run into a game-breaking error consistently shortly after starting the game and moving around a bit. Here is a screenshot.
> > Can you test this a bit more and fix this bug such that I can play for a small amount of time (1 minute?)
> 
> I can’t see the screenshot, can you resend it? Thanks! @grymmy

Oh no!  Sorry, I forgot to add it!  Let me try playing again now...

**Comment by grymmy** [comment]
I guess I just don't fully understanding why I am dying.  Also, note the error that shows up in red.
Screenshot 2024-07-22 at 12 54 16 PM

**Comment by cyberneel** [comment]
I think I added it in the game description, part of the game is to got touch the blue circles before they turn fully red or you die. The red error I think is just a reference issue after the player dies. I can't fix that. Thanks! @grymmy

**Comment by grymmy** [comment]
> I think I added it in the game description, part of the game is to got touch the blue circles before they turn fully red or you die. The red error I think is just a reference issue after the player dies. I can't fix that. Thanks! @grymmy

Ah - I understand now.  I do believe the reference issue could definitely be fixed (by you!) - however, I do understand now the logic for the game, and I appreciate the effort you've put into this.

Congratz!  If you're a teenager, and you haven't already received one, please fill out [this form](https://sprig-order.hackclub.dev/) to receive a Sprig device of your very own!  Also, feel free to join Hack Club's slack and share your creation in the #sprig channel!

**Pull request merged**
