### PR TITLE
FOOT_CATCH 

### PR DESCRIPTION
**Pull request by jakob07ffm**
# Your checklist for this pull request

## Author name

**Author: Jakob**

## About your game

**Catch all the food falling from the sky. If you miss 3 the game is over!**

**Controll the player with a and d**

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Hey! Which one of the versions of the game is the latest?

**Comment by jakob07ffm** [comment]
Hi, the misspelled one (CAHTCH_FOOD) was an accident, I tried to delete it, but I am pretty new here and failed. The latest version is the CATCH FOOD one.

**Comment by LucasHT22** [comment]
You mean FOOT CATCH? if you need any help, I'm here

**Comment by jakob07ffm** [comment]
Thanks, yes FOOT_CATCH, what is the next step i should do?

**Comment by LucasHT22** [comment]
> Thanks, yes FOOT_CATCH, what is the next step i should do?

Right now, it's just talk with me and I'll approve your game:) Where did you heard about Sprig?

**Comment by jakob07ffm** [comment]
I look at the GitHub game jam(https://itch.io/jam/game-off-2023) and they suggested sprig if JavaScript is your main programming language, so I look it up and I liked it.

**Comment by LucasHT22** [comment]
Wow nice! Did you use some game of inspiration?

**Comment by jakob07ffm** [comment]
I looked at the GitHub game jam, and they suggested sprig for JavaScript programming.

**Comment by jakob07ffm** [comment]
That was the jam: https://itch.io/jam/game-off-2023

**Comment by jakob07ffm** [comment]
You mean to enter with a Sprig game? Of cause, but its a big jam. I saw you posted it in the sprig chanel :)

**Comment by LucasHT22** [comment]
> You mean to enter with a Sprig game? Of cause, but its a big jam.

I mean if you use any game of our gallery as inspiration:)

> I saw you posted it in the sprig chanel :)

Hehe, we post things like this that we didn't know

**Comment by jakob07ffm** [comment]
hi Lucas, is there anything if have to chnge in the code?

**Comment by jakob07ffm** [comment]
I changed it:)

**Comment by jakob07ffm** [comment]
Can you mabey help me because if i try it it doesnt work?

**Comment by jakob07ffm** [comment]
Can you delete the picture? I tryed renameing it but i faild.

**Comment by jakob07ffm** [comment]
I cant delet it :(

**Comment by LucasHT22** [comment]
Probably is some github bug, I can't delete too:( but add the new image then after merge I delete:)

**Comment by jakob07ffm** [comment]
i will cose this pull request and open a new one with every thing right. I hope thats okay with you :)

**Comment by jakob07ffm** [comment]
i made it. In the new pull request is everything right,i hopr :)

**Comment by LucasHT22** [comment]
Alright!

**Pull request closed without merging**
