### PR TITLE
timing

### PR DESCRIPTION
**Pull request by darshg321**
# Your checklist for this pull request

## Author name

**Author:** Darsh Gupta

## About your game

**What is your game about?**
A stickman shooting bosses while dodging the boss attacks.

**How do you play your game?**
WASD to move, J to shoot to the left, L to shoot to the right. The goal is to kill all the bosses without getting hit.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by grymmy — CHANGES_REQUESTED** [review]
This was a fun game but I did run into a game-breaking issue - when killing the last boss on what I believe was the 2nd or third level, I experienced an awkward error (see subsequent comment)

**Comment by grymmy** [comment]
Screenshot 2024-06-24 at 9 25 25 PM

**Comment by darshg321** [comment]
I've added clearing the active projectiles so this error doesn't happen.

**Comment by grymmy** [comment]
Congratz, neat game - if you're a teenager, and you haven't already received one, please fill out [this form](https://sprig-order.hackclub.dev/) to receive a Sprig device of your own!  Also, feel free to join Hack Club's Slack and share your creation in the #sprig channel!

**Pull request merged**
