### PR TITLE
10 Levels Maze Game By Yash

### PR DESCRIPTION
**Pull request by Yash00241**
# Your checklist for this pull request

## Author name

**Author: YashV. Niranjan**

## About your game

**What is your game about?**
Getting the Hackclub Trophy by going out through mazes.

**How do you play your game?**
WASD Keys only 

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by recursiveforte** [comment]
This game is too similar to the maze game example for me to accept- we require games to contain original work. You could differentiate this by adding 1-2 new game mechanics.

**Comment by Yash00241** [comment]
> This game is too similar to the maze game example for me to accept- we require games to contain original work. You could differentiate this by adding 1-2 new game mechanics.

Got it sir but cannot do right now then will surely do it afterwards. Due to Mid-Year Examinations and as being the topper of class for last 3 years still need to get the first rank so would do it afterwards.

**Comment by Yash00241** [comment]
Hey @recursiveforte is it necessary to have a game only? Like I made a screensaver for sprig, can I  use it to have a sprig of my own?

Uploading Editor _ Sprig and 2 more pages - Personal - Microsoft​ Edge 2024-09-30 13-37-54.mp4…

**Comment by Yash00241** [comment]
Hey @recursiveforte is it necessary to have a game only? Like I made a screensaver for sprig, can I use it to have a sprig of my own?

Uploading Editor _ Sprig and 2 more pages - Personal - Microsoft​ Edge 2024-09-30 13-37-54.mp4…

**Comment by Yash00241** [comment]
Hey @recursiveforte is it necessary to have a game only? Like I made a screensaver for sprig, can I use it to have a sprig of my own?
Screenshot_30-9-2024_13402_sprig hackclub com

**Pull request closed without merging**
