### PR TITLE
Inhale_the_marshmallows.

### PR DESCRIPTION
**Pull request by Ploewn**
# Your checklist for this pull request

## Author name

**Author:**
Ploewn

## About your game

**What is your game about?**

This elegantly crafted masterpiece puts the player in the place of a banana man who is in desperate need of marshmallows. Make it through the treacherous levels by inhaling the marshmallow found in the map.

**How do you play your game?**

WASD to move, k to reset, L to move onto the next level once you've obtained the marshmallow (unless if you've finished the game).

## Code
Check off the items that are true. 
- [x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The game runs without errors. 
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Comment by Ploewn** [comment]
> Thanks for the PR! Where did you hear about Sprig?

**Comment by Ploewn** [comment]
Hiya, I heard about sprig from my friends.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! Could you please re-check this? 
- [ ] The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by Ploewn** [comment]
Hey, I've changed the name of the pr and the name of the js file to comply, however, i cannot seem to find my thumbnail anywhere, it's titled 'sprite (1).png'. Shall i add it again?

**Comment by LucasHT22** [comment]
> Hey, I've changed the name of the pr and the name of the js file to comply, however, i cannot seem to find my thumbnail anywhere, it's titled 'sprite (1).png'. Shall i add it again?

Just re-add with new title:) Also it's Inhale_the_marshmallows or banana_man?

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Could you make the yes sprite easier to be identified? Also please put your game inside of /games :)

**Comment by Ploewn** [comment]
Hey sorry for the delay but I cannot access /games? Thanks

**Comment by LucasHT22** [comment]
> Hey sorry for the delay but I cannot access /games? Thanks

Just rename your file with games/[YOURGAME].js :)

**Comment by Sheepy3** [comment]
closing this PR due to inactivity. feel free to ping me and ask for this to be reopened and hopefully merged!

**Pull request closed without merging**
