### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Toxrook**
# Your checklist for this pull request

## Author name

**Author:**

## About your game

**What is your game about?**

**How do you play your game?**

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ ] The game runs without errors. 
- [ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ ] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by Toxrook** [comment]
look all i was trying to do is the instructions on sprig to Try to share my
project and i dint know what i was doing im sorry if im worrying you in
some sort of way

-Tox

**Comment by LucasHT22** [comment]
No worries!:)

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
First, What is your game about?

How do you play your game?

**Comment by LucasHT22** [comment]
Is there something in the tutorial that is confusing? let us know:)

**Comment by karamassie** [comment]
hi @Toxrook -- the best place to come find help on getting your game submitted is in our hack club slack. if you're not in yet,  join via https://hackclub.com/slack and then go to the #sprig channel.

**Comment by grymmy** [comment]
Closing due to inactivity. Please re-open if you'd like to continue forward landing this game!

**Pull request closed without merging**
