### PR TITLE
fold template literals after update has been propagated in editor

### LINKED ISSUE #2368: Bitmaps/maps unfold for everyone when someone edits them in one of the instances

### PR DESCRIPTION
**Pull request by JosiasAurel**
resolves #2368 

when a change is propagated to bitmaps/map/tune, their template literals get unfolded and the change applied. however, they're not closed back. this change forces the template literals to fold after these changes have been applied to the editor.

### CODE REVIEW

**Review by Cosmin-Mare — CHANGES_REQUESTED** [review]
I don't think we should collapse all template literals when someone edits one of them

**Comment by grymmy** [comment]
Do we plan on this PR surviving and moving forward, or do we kill it with 🔥 ?

**Comment by Cosmin-Mare** [comment]
Afaik @JosiasAurel is working on finding a way to only collapse the bitmap that has been edited, so no🔥yet

**Review by Cosmin-Mare — APPROVED** [review]
lgtm, tested and it works perfectly!

**Pull request merged**
