### PR TITLE
Bastion

### PR DESCRIPTION
**Pull request by De-y**
# Your checklist for this pull request

## Author name

**Author:**
de-y (Dheeraj Chintapalli)

## About your game

**What is your game about?**
My game is a 2d platformer like Fireboy & Watergirl (that I took inspiration from with the mechanics) and you try to reach the last level.  The game works with fake blocks, buttons, spikes, and more (even more to come)! It's a 2 player game (also 1 player if you can use both key sets) & requires cooperation.

Here is the image of the game:

image

**How do you play your game?**

For Fireboy, you would use the "JIL" keys to move, and for watergirl, you would use "WAD" (similar to the real game but fireboy is the arrow keys) & if you die, the game will automatically restart for you.

I & A keys are for jumping and AD, JL are for movement.

## Code
Check off the items that are true. 
- [X] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [X] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [X] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [] The game runs without errors.
^ The game does have a error but doesn't affect game playability and only appears once in a while. 
- [X] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [X] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [X] The name of the image matches the name of your file. 

> Thanks for your PR!

Just to note, this PR also contains the Basketball game from https://github.com/hackclub/sprig/pull/1175

### CODE REVIEW

**Comment by De-y** [comment]
Just for further clarification regarding the image, I took the sprites from the game & then edited them onto the image & then used a nice font for the text.

I have learned a lot more about Sprig in the past day than I ever had. Basketball game was the first game & this one should be somewhat more better than the Basketball Game. I'll update both later though with a nice content update.

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Nice! How to solve this level?
image

**Comment by LucasHT22** [comment]
BTW - I see that you're working hard in your games:)

**Comment by De-y** [comment]
Haha, thanks!

The way to solve the first level is to make the watergirl/blue character
fall, which you can then use to get her onto the other side onto the
blue-colored door.

**Comment by De-y** [comment]
Please do let me know when the game can be added, I'm currently busy with
other things so I won't be able to make any updates but this should be it.

More content will be added soon because I'm busy with school, the mechanics
are weird for jumping but do make all the levels completable( even though
im duping people with fake blocks.

**Comment by LucasHT22** [comment]
Alright, are you on Hack Club Slack?

**Comment by De-y** [comment]
Yes, I am as Dheeraj.

**Comment by LucasHT22** [comment]
I'll merge, because I know you're working hard, but before, send me a DM on Slack, I'm `@lucas`

**Comment by De-y** [comment]
I have sent a DM on slack.

**Review by LucasHT22 — APPROVED** [review]
I know you worked hard on these games, Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by De-y** [comment]
Found some issues, made a new PR to fix this as part of a content update & it introduces new blocks and a new level.

**Pull request merged**
