### PR TITLE
Add Cookie Clicker Game

### PR DESCRIPTION
**Pull request by knvi**
# Cookie Clicker

### What is your game about? 
The game is about earning money by clicking a cookie. Of course, you can not touch the screen, so you press the `J` button to click the cookie! You also have an Cookie Per Second, aswell as a Cookie Per Click upgrade, which increase your earnings with each second/click! The game's code also has a really neat-lookin' doc part where each game variable is explained!

### How to play your game?
The controls are really simple! You press the `J` key to click the cookie to earn money, press the `I` button to buy a Cookie Per Second upgrade, and press the 'K' button to buy a Cookie Per Click button! The game also has a visual representation of each key required to do a specified action.

### Game length
The game is nearly infinite in length haha, all until you run out of space for the numbers to show. Should take >5 minutes though.

## Code
Check off the items that are true.
- [x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. Example: `sokoban_plus.js` -> `sokoban_plus.png`.

( #633 was an issue, thought I forgot to add a label, just to find out I couldn't add it haha )

### CODE REVIEW

**Comment by LucasHT22** [comment]
Great game! How about making the cookie appearance change after a cash number?

**Comment by kunevi** [comment]
It would require a lot of sprites, wouldn't it? Keep in mind that I would require 2 sprites for each type, since I also have the big cookie sprite

**Comment by kunevi** [comment]
And I am also kinda bad at pixel art, so it would turn out... Not too good...

**Comment by knvi** [comment]
Added a second cookie type, gaven after 10000 money is reached, just like you suggested!

**Comment by LucasHT22** [comment]
I have a game (in development) with 55 Sprites haha

**Comment by knvi** [comment]
> > It would require a lot of sprites, wouldn't it? Keep in mind that I would require 2 sprites for each type, since I also have the big cookie sprite
> 
> I have a game (in development) with 55 Sprites haha

Oh wow, that's really impressive!

**Comment by knvi** [comment]
How many cookie types do you think I should get in the game?

**Comment by knvi** [comment]
Or the golden one + the default one is good enough?

**Comment by LucasHT22** [comment]
> How many cookie types do you think I should get in the game?

I think 3

**Comment by knvi** [comment]
> > How many cookie types do you think I should get in the game?
> 
> I think 3

Alright! Getting to work... should make a new commit soon

**Comment by knvi** [comment]
Updated! Added Gold, Diamond and Emerald cookies! Also updated the small doc at the start of the file, and added 3 variables so the requirement for each cookie will be tweakable.

**Review by LucasHT22 — APPROVED** [review]
Great game! Looks good to me, Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

out of curiosity, how did you meet sprig?

**Comment by knvi** [comment]
Hey! Thanks a lot, already filled up the form. I saw a mention about Sprig while signing up to the Hackclub's Winter Hardware Wonderland. I got curious, so I checked it out, and instantly went in making a game!

**Comment by LucasHT22** [comment]
Oh, nice!

**Pull request merged**
