### PR TITLE
trap_it

### PR DESCRIPTION
**Pull request by PRairigh**
# Your checklist for this pull request

## Author name

P. Rairigh

## About your game

The objective is to trap the robot. As you move, you can lay walls. You must find a way to trap the robot within your walls.

**How do you play your game?**

Press WASD to move. Use JKLI to place a wall piece in one of squares adjacent to you. When the robot is unable to move, he will loose health points. When he has lost all of his points, you win. (The "s" key will also show his health) But if he breaks out, his health regenerates!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by PRairigh** [comment]
I do not seem to have access to the Vercel messages, so I am not sure what failed. But hopefully when a maintainer looks at this they can let me know what I need to fix. Thank you. 
Patrick

**Comment by yednapg** [comment]
Hi @PRairigh! Please add metadata to your game file? Also, please keep the game file inside /game and remove it from /game/img.


Additionally please add one or two more unique mechanics to this game to meet the bar re: a Sprig device reward.

**Review by grymmy — CHANGES_REQUESTED** [review]
See @yednapg 's comments.

**Comment by PRairigh** [comment]
I have added the metadata and removed the image per your request.
Also regarding the extra mechanics, I made the robot movement more complex by alternating between random motion and moving towards the player. Then I added additional levels of play (more robots on each level and starting blocks randomly placed).
I am not familiar with the github workflow, but hopefully you can see my changes here.
Thank you.

**Comment by yednapg** [comment]
Love it. It took a moment to familiarize myself with the game, but in the end, it was fun. If you’re a teenager and haven’t already received one, please fill out [this form](https://sprig-order.hackclub.dev/) to receive one, and feel free to join Hack Club's Slack and share your creation in the #sprig channel!

**Pull request merged**
