### PR TITLE
minion-game

### PR DESCRIPTION
**Pull request by hazik-khalid**
# Your checklist for this pull request

## Author name

**hazik khalid:**

## About your game

**it is a game in which ur player is a minion and you have to help him find his coin**

**WASD to move j to restart and k to jump?**

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for PR! Where did you hear about Sprig?

**Comment by hazik-khalid** [comment]
I saw a video of spring on hackclub youTube

**Comment by LucasHT22** [comment]
Nice! What about more levels?

**Comment by hazik-khalid** [comment]
I am working on the new levels and making the game more fun to play

**Comment by Sheepy3** [comment]
closing this PR due to inactivity. feel free to ping me and ask for this to be reopened and hopefully merged!

**Pull request closed without merging**
