### PR TITLE
Push the Blocks

### PR DESCRIPTION
**Pull request by dwong828**
Added a new game called Push The Blocks.   This was really fun to make!

### CODE REVIEW

**Comment by dwong828** [comment]
Do you want me to add a background and outside walls before you approve this game?

**Comment by Omay238** [comment]
Yeah, that would be good.

**Comment by Omay238** [comment]
Nice. It looks good. If you're a teen congratulations on your Sprig. You can order it here: https://sprig-order.hackclub.dev/
I'll merge it now (:

**Comment by LucasHT22** [comment]
add right control!

**Pull request merged**
