### PR TITLE
beginner-test

### PR DESCRIPTION
**Pull request by diegoperac**
This is my first JavaScript code.

### CODE REVIEW

**Comment by LucasHT22** [comment]
> This is my first JavaScript code.

Your code? This is a copy of @leomcelroy 's [Skoban](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban.js)
Even the comments in the code are the same!

**Review by SamDev-7 — CHANGES_REQUESTED** [review]
Try to be more original! Feel free to remix off of a game that already exists, but try to add your own original twist. We'll be happy to help if you get stuck.

**Comment by LucasHT22** [comment]
Hey @diegoperac !
I see you're gone, don't give up, try an original game :)

**Comment by leomcelroy** [comment]
Thanks for the submission! I'm going to close this PR for now but please re-open when you've had a chance to modify your game more.

**Pull request closed without merging**
