### PR TITLE
The Legend Of Sprig

### PR DESCRIPTION
**Pull request by MedievalApple**
# Your checklist for this pull request

## Author name

**Author: Medieval Apple**

## About your game

**What is your game about?**

Long ago there was a treasure hunter named Sprig 
who built an enormous labyrinth to store their fabled treasure.
Inside this labyrinth, they built a maze of 68 rooms and 
created tons of enemys to protect them.

You take on the role of Marin who is an
adventure in search of Sprig's fabled treasure
with your trusty sword and shield in hand will you
be able to find the treasure?

**How do you play your game?**

Press W,A,S,D to move and K to swing your sword. Find keys to open locked doors, collect pumpkins, and fight enemies to make your way through the labyrinth to find the treasure.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [x] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [x] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
WOW! Awesome game, did you win the game? I don't haha

**Comment by MedievalApple** [comment]
Thank you 😊 I was able to win but it took me a while to complete lol

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Haha, where did you hear about Sprig?

**Comment by MedievalApple** [comment]
I heard about it from the hack club booth at the first robotics championship event

**Review by LucasHT22 — APPROVED** [review]
Alright, Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by MedievalApple** [comment]
Thank you! 😊

**Pull request merged**
