### PR TITLE
Treasure-Hunt-Adventure

### PR DESCRIPTION
**Pull request by evanss2025**
# Your checklist for this pull request

## Author name

**Author:**

Sophia E

## About your game

**What is your game about?**

In my game the player is a pirate who is trying to get a gem to their ship! They have to go through jungles and beaches while navigating and using boxes to transport their treasure.

**How do you play your game?**

Press WASD to move, j to restart. Push the gem using the player to the ship. Boxes can move boxes and the gem, the gem can't move boxes.

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — COMMENTED** [review]
Thanks for the PR!

**Comment by savinajabbo** [comment]
I love the creativity of the pirate theme in your game! It's so cute. What about adding more elements throughout the levels?

**Comment by evanss2025** [comment]
> I love the creativity of the pirate theme in your game! It's so cute. What about adding more elements throughout the levels?

I would but I was wondering how long Sprig takes to ship, it would be great if the game could arrive here for April 27th bc I'm representing hack club at a girl scout STEM Fest. I can add the details if I need to to get it shipped

**Comment by LucasHT22** [comment]
Hey @evanss2025 ! If you're in the USA it shouldn't take more than 2 weeks. But could you provide more context? You can DM me on Slack `@lucas` or send me an email: `lucas@hackclub.com`

**Review by LucasHT22 — APPROVED** [review]
I'm approving because it has a reasonable amount of levels and has very good sprites! I really suggest you add more elements as Savina suggested. Congrats:)
If you're a teen, you can get your sprig here! http://hack.af/sprig-order

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Pull request merged**
