### PR TITLE
Find the Clone

### PR DESCRIPTION
**Pull request by TheGoldenBlock2**
# Your checklist for this pull request

## Author name

**Author:**

TheGoldenBlock

## About your game

**What is your game about?**

My game is about differentiating very similar boxes to find the odd one out, and then pushing it to the goal. 

**How do you play your game?**

Use WASD to move, j to reset.

## Code
Check off the items that are true. 
- [ x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game runs without errors. 
- [ x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Sorry for my delay, Where did you hear about Sprig?

**Comment by TheGoldenBlock2** [comment]
No problem about your delayed response (I was in bed anyway). I heard about
Sprig from a classmate of mine, when he brought his Sprig console to school
and told me how I could win one. It looked really cool, so I decided to
code my game in order to get one.

**Review by LucasHT22 — APPROVED** [review]
Nice! Great game! Congrats:)
If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/

Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

**Comment by TheGoldenBlock2** [comment]
> Nice! Great game! Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> 
> Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)

Uh, [#ship] doesnt exist on the slack. as a matter of fact, nothing exists on the slack apart from this weird channel about caves.

**Comment by LucasHT22** [comment]
> > Nice! Great game! Congrats:) If you're a teen, you can get your sprig here! https://sprig-order.hackclub.dev/
> > Hack Clubbers would love to see this! Just post a link and 1-2 sentences talking about your game to our [#ship](https://hackclub.slack.com/archives/C0M8PUPU6) [channel](https://hackclub.com/slack/):)
> 
> Uh, [#ship] doesnt exist on the slack. as a matter of fact, nothing exists on the slack apart from this weird channel about caves.

weird! what's your user? so one of our admin can check it:)

**Comment by TheGoldenBlock2** [comment]
nevermind, i figured out the cave channel was verification. however, i had a question. i sent in the order form, with my student id, and i was wondering when i would get a tracking link for my order. thanks :)

**Comment by LucasHT22** [comment]
> nevermind, i figured out the cave channel was verification. however, i had a question. i sent in the order form, with my student id, and i was wondering when i would get a tracking link for my order. thanks :)

Did you order green or black?

**Comment by TheGoldenBlock2** [comment]
Sorry about the message, I recieved a USPS tracking link. However to answer your question, I ordered black :)

**Comment by LucasHT22** [comment]
> Sorry about the message, I recieved a USPS tracking link. However to answer your question, I ordered black :)

Great choice! If you need something, I'm here:)

**Comment by LucasHT22** [comment]
Hey @TheGoldenBlock2 ! Could you DM me on Slack? I'm `@lucas` there:)

**Pull request merged**
