### PR TITLE
Tag!

### PR DESCRIPTION
**Pull request by Dayytime**
# Your checklist for this pull request

## Author name

**Author:** Majd

## About your game

**What is your game about?**
Two player tag game with multiple maps and power ups!

**How do you play your game?**

WASD to move player one and IJKL to move player two. Whoever is red is the tagger and whoever is blue is the runner. The runner needs to survive a set amount of time and the tagger has to tag the other player before that time runs out!

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Comment by yednapg** [comment]
Hi. Please add more mechanics and features to this game to meet the bar re: a Sprig device reward.

**Comment by yednapg** [comment]
Waiting for the author to modify this to meet the bar for a Sprig device grant.

**Comment by Dayytime** [comment]
I will add moving walls and spike obstacles.

**Comment by grymmy** [comment]
I await walls and spikeys from the author.

**Comment by yednapg** [comment]
Waiting for the author to modify this to meet the bar for a Sprig device grant.

**Comment by grymmy** [comment]
Closing this due to inactivity.  Feel free to re-open this PR if you want to advocate for its merge.

**Pull request closed without merging**
