### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by feiderob**
# Your checklist for this pull request

## Author name

**Author:** feiderob

 

## About your game

**What is your game about?** Play as a farmer and help the escaped slimes get home!

**How do you play your game?** Use WASD to move, and J to restart. Get the cyan slimes into the fences. The barrels are able to be moved

## Code
Check off the items that are true. 
- [x] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [x] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x] The game runs without errors. 
- [x] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)

## Image (If an image is used)

- [ ] The image is in the [`/games/img` directory](https://github.com/hackclub/sprig/tree/main/games/img).
- [ ] The name of the image matches the name of your file. 

> Thanks for your PR!

### CODE REVIEW

**Review by LucasHT22 — CHANGES_REQUESTED** [review]
Thanks for the PR! Where did you hear about Sprig?

**Comment by feiderob** [comment]
> Thanks for the PR! Where did you hear about Sprig?

My computer science teacher informed my class!

**Comment by LucasHT22** [comment]
Nice! Could you re-check this?
- [ ]  The name of the file/game contains only alphanumeric characters, -s, or _s.

**Comment by feiderob** [comment]
Should be fixed, sorry about that!

**Comment by LucasHT22** [comment]
No worries but change the file name too:)

**Comment by feiderob** [comment]
This is my first time using Github, apologies! Should hopefully be fixed haha

**Comment by Sheepy3** [comment]
closing this PR due to inactivity. feel free to ping me and ask for this to be reopened and hopefully merged!

**Pull request closed without merging**
